### ISSUE TITLE
cmake extensionj 

### ISSUE THREAD

**Issue by MdKhushalwarsi** [microsoft/vsmarketplace#1000]
Type: <b>Bug</b>

thye cmake extrension is not working

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vsmarketplace/issues/999
- [ ] https://github.com/microsoft/vsmarketplace/issues/20
```

**Comment by madhurivadaligithub** [comment]
Thanks for reaching out to the VS Marketplace Team. Could you please share the error message, a screenshot, and the repro steps to help us investigate better.

Regards,
VS Marketplace Team

**Comment by SirsaPrasanjit** [comment]
![VS code error](https://github.com/user-attachments/assets/b9cccb4c-734d-429a-8b75-6fffbf4c685c)
Whenever i open VS code and go to extensions, i get the below error.

**Comment by madhurivadaligithub** [comment]
Thanks for the update, could you please submit a Fiddler trace recording to look further or share details by using MTR.

To capture MTR:
Download [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).

Enter marketplace.visualstudio.com as the hostname and click Start.


<img width="403" alt="mtr" src="https://github.com/user-attachments/assets/cb785840-daab-4d64-a6a6-3199caf7850b">

Wait until the Sent column is >= 100.

Copy text to clipboard, share with us.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
