### ISSUE TITLE
Python 2024.14.0 Bug - Multiline and if command

### ISSUE THREAD

**Issue by Sergio-Valera** [microsoft/vsmarketplace#1001]
Type: <b>Bug</b>

I encountered an issue with the Python extension for Visual Studio Code where my Python code was resulting in a SyntaxError: invalid syntax even though the code was syntactically correct. The problem persisted across various scripts and was not related to the content of the scripts themselves.
Code that doesn't work on 2024.14.0

query_inicial2 = """xd"""
log_directory = r'C:\\Users\\FU77326035\\Desktop\\Folder_Codigos\\LOGS'
rojo = False
if rojo == True:
    False
script_name = 'Proyecto1.py'
print('xd')
if rojo == True:
    False
print('hola')
It seems the issue might stem from the use of multi-line strings (""") combined with conditional statements. The extension may be misinterpreting the end of the conditional due to the multi-line string, which could be causing the syntax error.

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Support Team, this issue appears to be a support question specific to the extension which is best addressed by the extension owner.  I recommend visiting the extension page on https://marketplace.visualstudio.com/ and posting a question there. Let me know if we can help you with anything else.

Regards,
VS Marketplace Team
