### ISSUE TITLE
Fetching extension

### ISSUE THREAD

**Issue by malfidos** [microsoft/vsmarketplace#1002]
![Captura de pantalla 2024-09-10 170149](https://github.com/user-attachments/assets/9d2e2905-8f60-4744-9650-5fd1f7c6e40d)
Type: <b>Bug</b>

i cant see the marketplace for extension always when i try to find any extension give this error:

"Error while fetching extensions. Failed to fetch".

This is the first time i see this since i use VS Code and i dont understand why at this momento. I made a reinstallation of Windows 11 so my pc now is totally clean and this is the only one thing isnt working.

I was trying to search any result about this proble at StackOverflow and VSCode community andd every i saw is a problem who seems a bit equal but said:

"Error while fetching extension. XHR"

I mean thats not my problem but i dont really know.

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @malfidos ,

Thanks for reaching VS Marketplace Team, we are unable to repro the issue.
If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists please feel free to reopen or create a new issue.
