### ISSUE TITLE
Error Failed to fetch

### ISSUE THREAD

**Issue by GregSal** [microsoft/vsmarketplace#1004]
Type: <b>Performance Issue</b>

Getting "Error Failed to fetch" when attempring Extensions marketplace query or Extensions check for updates.  

I am not able to locate and further information in the Output, so I have no idea where to start troubleshooting.

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace Team, we are unable to repro the issue.
If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team

**Comment by GregSal** [comment]
Hello,
   The reason for contacting you about this is the lack of diagnostic
information.  I can replicate the issue on other PCs at work, but
everything is fine on my home PC.  The workplace sys admins insist that
they are not blocking access and that they have not made any recent changes.

The lack of diagnostic information makes it difficult to investigate.
I have three questions and one comment:
1. Is there some log file or output from VS Code somewhere that will give
me more information than "Failed to Connect"?
2. If not, is there a way to run VS Code in a Verbose or debug mode that
will generate this information?
3. This is being run on a windows 10 OS behind a company firewall.  Are
there any event or log files I can look for that might shed some light on
this problem?

Comment / Suggestion.
There is a lot of different output choices in the Output pane, but for
something like this it is not clear where to look.  I would appreciate it
if someone generated general "getting started with troubleshooting" with
guidance on where to look for diagnostic information for different kinds of
problems.

Greg Salomons

**Comment by madhurivadaligithub** [comment]
Thank you for sharing the details Sorry to hear you are experiencing the issue. It appears the queries looks specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues
