### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Truong-Quoc-Bao** [microsoft/vsmarketplace#1005]
Type: <b>Bug</b>

lỗi màu

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.4.0
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Truong-Quoc-Bao ,

Thanks for reaching VS Marketplace Team, could you please share the more details to investigate further.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
