### ISSUE TITLE
I remove the llm vscode extentsion but still getting the notifications of that

### ISSUE THREAD

**Issue by vinit1799** [microsoft/vsmarketplace#1008]
Type: <b>Bug</b>

I remove the llm vscode extentsion but still getting the notifications of that, api inference error, etc

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @vinit1799 

Thanks for reaching VS Marketplace Team, could you please share the publisher and extension details to look further.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

VS Marketplace Team
