### ISSUE TITLE
Object filter feature request for the MS SQL Extension on VSCode

### ISSUE THREAD

**Issue by fevzikartal** [microsoft/vsmarketplace#1009]
### Visual Studio Code 
We can use Visual Studio Code for SQL development after installing the MS SQL Extension. 
It has good features but as a developer and a DBA **We don't able to filter db objects**. 
![image](https://github.com/user-attachments/assets/1365e4a0-de0a-4b29-b490-d78fefd68ecc)

### SSMS Object Filter Feature
![image](https://github.com/user-attachments/assets/d1908525-d558-48fc-a294-5120715fbaa2)

### Azure Data Studio Filter Feature
![image](https://github.com/user-attachments/assets/aa57e2e2-5140-42dc-a873-1ad4427ecefc)

#### Azure Data Studio has similar behavior with VS Code with extension.
It is clear that Vs Code with extension needs object filter feature. Could you add to your plan for future releases.

Sincerly

**Comment by LarnuUK** [comment]
This appears to be about the extension [SQL Server (mssql)](https://github.com/Microsoft/vscode-mssql) not the VS Code Marketplace.

**Comment by LarnuUK** [comment]
There also already appears to be an [existing request](https://github.com/microsoft/vscode-mssql/issues/1445), dating back to October 2019, and is currently planned for the October 2024 release.

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing an issue with searching. It appears to be specific to VS Code editor and tools if I'm understanding correctly. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team

**Comment by fevzikartal** [comment]
Is closing the request as completed a solution?. When compared with the other editors (SSMS and ADS). There is absolute lack of feature to filter objects for Vs Code with extension. As a moderator - admin you would forward the request to correct header instead of closing as completed. There is no completion of request. Thanks for explanation but there would be forward mechanism.

**Comment by LarnuUK** [comment]
> Is closing the request as completed a solution?. When compared with the other editors (SSMS and ADS). There is absolute lack of feature to filter objects for Vs Code with extension. As a moderator - admin you would forward the request to correct header instead of closing as completed. There is no completion of request. Thanks for explanation but there would be forward mechanism.

It is when you have posted this in the wrong place; the developera here can't help you. They can't forward your request on, becauae that's an entirely project. GutHub isn't slowly used by VSCode.

See my responses above for where you would have needed to have asked, and that the request already exists.

**Comment by fevzikartal** [comment]
> > Is closing the request as completed a solution?. When compared with the other editors (SSMS and ADS). There is absolute lack of feature to filter objects for Vs Code with extension. As a moderator - admin you would forward the request to correct header instead of closing as completed. There is no completion of request. Thanks for explanation but there would be forward mechanism.
> 
> It is when you have posted this in the wrong place; the developera here can't help you. They can't forward your request on, becauae that's an entirely project. GutHub isn't slowly used by VSCode.
> 
> See my responses above for where you would have needed to have asked, and that the request already exists.

Thank you for your responses but closing as a completed situation is not correct. I opened the issue in the master - main product line and this is incorrect, wrong header. 
Closing with direction, Closing with suggestion would be used. Otherwise completion statistics of issues will be wrong.
