### ISSUE TITLE
ftp-simple

### ISSUE THREAD

**Issue by DanielMartinho81** [microsoft/vsmarketplace#1010]
Type: <b>Bug</b>

Faz cercar de uma semana que o ftp-simple não funciona mais. Alguma solução?

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @DanielMartinho81 ,

Thank you for contacting the VS Marketplace Team. Could you please elaborate on your concern and provide the publisher/extension details to help us investigate further

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

VS Marketplace Team
