### ISSUE TITLE
cannot fetch extensions 

### ISSUE THREAD

**Issue by Maingi01** [microsoft/vsmarketplace#1011]
Type: <b>Feature Request</b>

am having trouble when trying to fetch for extensions

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 6.0.6002
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Maingi01 ,

Thanks for reaching VS Marketplace Team, we are unable to repo the issue, could you please submit a recording and Fiddler trace to investigate further.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Could you please share details by using MTR.

**To capture MTR:**
Download  [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).

Enter marketplace.visualstudio.com as the hostname and click Start.

Wait until the Sent column is >= 100.

Capturing MTR
<img width="403" alt="mtr" src="https://github.com/user-attachments/assets/748f005c-a5b6-4375-8149-8c68af93964b">


Copy text to clipboard, share with us.

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
