### ISSUE TITLE
ERROR WHILE FETCHING EXTENSIONS

### ISSUE THREAD

**Issue by Hephzibah24** [microsoft/vsmarketplace#1013]
Type: <b>Performance Issue</b>

When I try to search for any extensions, It shows me"Error while fetching extensions". I have tried to change from 'overide' to 'on', 'fallback', and the rest in my settings but it doesn't seem to work at all. What else can I do please?

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Hephzibah24 ,

Thanks for reaching VS Marketplace Team, we are unable to repro the issue, could you please share the extension and screenshot details to look further

Regards,
VS Marketplace Team.

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
