### ISSUE TITLE
not recognising the path 

### ISSUE THREAD

**Issue by Kanchan-spxce** [microsoft/vsmarketplace#1015]
Type: <b>Performance Issue</b>

i was corrently typing a random code but i'm unable to use it to execute it as when i'm giving the command of .\a.exe  it is showing not recognising the path

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Kanchan-spxce ,

Thank you for contacting the VS Marketplace Team. Could you please elaborate on your concern and provide the publisher/extension details to help us investigate further

Regards,
VS Marketplace Team

**Comment by Kanchan-spxce** [comment]
Thank you for your response. I have already found the solution for the
problem
