### ISSUE TITLE
i can't able to install python extension

### ISSUE THREAD

**Issue by KaranBodkhe599** [microsoft/vsmarketplace#1016]
Type: <b>Bug</b>

i want python language but it couldn't download in the vs code

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @KaranBodkhe599 ,

Thank you for contacting the VS Marketplace Team. To help us investigate further, could you please provide more details about your concern, including any screenshots or error messages? Also, please include the publisher/extension details.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
