### ISSUE TITLE
action pack subscription

### ISSUE THREAD

**Issue by TomCallen** [microsoft/vsmarketplace#1017]
i cannot login to Visual studio 2022 Professional, it wants a subscription, however i have purchased on 1/10/24 action pack subscription for $495 for one year.
my login is tcallen@computrakorg.onmicrosoft.com
credit card ref number 2443099401700494886770 7  dated 1/10/24
phone 970-222-7924
Please Help, I use visual studio every day and it says the Trial period has expired,
Tom Callen
Microsoft Partner ID# 617763

**Comment by madhurivadaligithub** [comment]
Hi @TomCallen ,

Thank you for reaching out to the VS Marketplace Team. Please remove all personal data from your request and avoid including personal information in the future. For Marketplace-related queries, contact our VS Marketplace Support alias at VSMarketplace@microsoft.com.

Regards,
VS Marketplace Team
