### ISSUE TITLE
Snippets are deprecated

### ISSUE THREAD

**Issue by MdKhushalwarsi** [microsoft/vsmarketplace#1018]
Type: <b>Performance Issue</b>

Resolve this problem of snippets.

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by MdKhushalwarsi** [comment]
![Screenshot 2024-09-30 133251](https://github.com/user-attachments/assets/39d0b8e2-c516-4b44-93bb-e255945126b4)

**Comment by madhurivadaligithub** [comment]
Thank you for reaching VS Marketplace Support Team. We are following up to determine how best to address it.

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Could you please share more details about your concern?

 It appears to be specific to VS Code editor and tools if we understand correctly. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.


Regards,
VS Marketplace Team
