### ISSUE TITLE
Showing error fetch failed

### ISSUE THREAD

**Issue by sumanBiswas2024** [microsoft/vsmarketplace#1019]
Type: <b>Bug</b>

Showing error fetch failed

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @sumanBiswas2024 ,

Thank you for contacting the VS Marketplace Support Team. Could you please provide more details and share any relevant screenshots or logs so we can investigate further.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
