### ISSUE TITLE
Microsoft Developer Product Decision

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vsmarketplace#1022]
Type: <b>Feature Request</b>

May I know what is Microsoft's Developer Product Direction?

VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for contacting the VS Marketplace Support Team. Could you please provide more details about your requirement to look further.

VS Marketplace Team
