### ISSUE TITLE
Unable to Recover VS Marketplace Publisher Account

### ISSUE THREAD

**Issue by jribbink** [microsoft/vsmarketplace#1023]
I apologize as this is probably not the correct forum to be posting this discussion on, however, I have exhausted other channels and am unsure how to proceed.

I had initiated a correspondance with support (vsmarketplace@microsoft.com) on September 24th (ticket number 80c2ec86), attempting to recover my organization's account.  I received a reply on September 25th outlining instructions to prove ownership.

I followed these, sending ownership proof of https://github.com/onflow/vscode-cadence and I made this commit https://github.com/onflow/vscode-cadence/blob/master/OWNERSHIP_PROOF.md

However, I received a follow up email on September 26th indicating that in 3 business days my ticket would be closed, despite having sent this proof.  3 business days have now passed, and I have sent multiple follow up emails which have received no response.

We are urgently trying to recover this access in order to release necessary updates to the VSCode Cadence extension.  Please let me know if there are any other recovery paths which I can explore or anything else I can do.

**Comment by madhurivadaligithub** [comment]
Hi @jribbink ,

Thank you for contacting the VS Marketplace Team. As mentioned in our follow-up emails on September 25th and September 27th, we need proof to process your request.

We will review the commit and proof you sent through this GitHub issue and process the request accordingly.

We are closing this issue as we are actively updating through the support alias.

If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
