### ISSUE TITLE
Error GET Failed to fetch

### ISSUE THREAD

**Issue by Quqin917** [microsoft/vsmarketplace#1024]
Type: <b>Performance Issue</b>

The issues started right after the installation process when I'm trying to access and downloads extensions.

When I'm checking my extension by pressing  ctrl+shift+x. The icon for extension and the pages doesn't load. and when I try to install it's say Failed to Fetch

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for contacting the VS Marketplace Support Team. Could you please provide more details and share any relevant screenshots or logs so we can investigate further.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

**Comment by Quqin917** [comment]
i'm sorry for the late respons. This is screenshot of the logs 

![Image](https://github.com/user-attachments/assets/c338e7a5-7377-4391-abe5-66a879d200c9)
