### ISSUE TITLE
not working shortcuts and not working also live server,

### ISSUE THREAD

**Issue by Rajusrk** [microsoft/vsmarketplace#1025]
Type: <b>Bug</b>

shortcuts are not working and live server

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
This issue appears to be a support question specific to the extension which is best addressed by the extension owner. we recommend visiting the extension page on https://marketplace.visualstudio.com/ and posting a question there. Let us know if we can help you with anything else.

Regards,
VS Marketplace Team
