### ISSUE TITLE
error in marketplace

### ISSUE THREAD

**Issue by karanrajsurya** [microsoft/vsmarketplace#1026]
Type: <b>Performance Issue</b>

While typing a extension's name, it says "Error while fetching extensions. Failed to fetch". Even when i have my internet on and everything. Also searched on chatgpt and tried almost all its commands and still its not fetching extensions.

VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for the update, could you please submit a Fiddler trace recording to look further or share details by using MTR.

To capture MTR:
Download [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).

Enter marketplace.visualstudio.com as the hostname and click Start.
<img width="403" alt="mtr" src="https://github.com/user-attachments/assets/f24ee5a6-a75a-49d9-9de2-0d70d1f4e045">


Wait until the Sent column is >= 100.

Copy text to clipboard, share with us.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
