### ISSUE TITLE
TTS Not longer able to load scripts

### ISSUE THREAD

**Issue by akurtz9** [microsoft/vsmarketplace#1027]
Type: <b>Bug</b>

Using the Tabletop Simulator Lua extension. I get this error since the September upgrade.

command 'ttslua.getScripts' not found

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @akurtz9 ,

This issue appears to be a support question specific to the extension which is best addressed by the extension owner.  we recommend visiting the extension page on https://marketplace.visualstudio.com/ and posting a question there. Let us know if we can help you with anything else.

Regards,
VS Marketplace Team
