### ISSUE TITLE
Remote - SSH v0.115.0

### ISSUE THREAD

**Issue by sm1lexops** [microsoft/vsmarketplace#1028]
can't connect to remote hosts, after update  v0.115.0
Same error tested  on macos and linux ubuntu 24.04
Failed to connect to the remote extension host server (Error: ExtensionInstallFailed(ExtensionInstallFailed("file:///home/aleksey.smirnov/.vscode-server/cli/servers/Stable-d78a74bcdfad14d5d3b1b782f87255d802b57511/server/out/vs/server/node/server.main.js:33\n\t| KEY ('==' | '!=' | '<' | '<=' | '>' | '>=' | 'in' | 'not' 'in') value`,this.D())}}u(){const t=this.D();switch(t.type){case 17:case 18:return this.z(),t.lexeme;case 11:return this.z(),\"true\";case 12:return this.z(),\"false\";case 13:return this.z(),\"in\";default:return\"\"}}w(t){return t.replaceAll(this.v,\"\")}x(){return this.f[this.g-1]}y(t){return this.C(t)?(this.z(),!0):!1}z(){return this.E()||this.g++,this.x()}A(t,s){if(this.C(t))return this.z();throw this.B(s,this.D())}B(t,s,i){const r=m(1692,null,t,wo.getLexeme(s)),n=s.offset,o=wo.getLexeme(s);return this.h.push({message:r,offset:n,lexeme:o,additionalInfo:i}),Sa.c}C(t){return this.D().type===t}D(){return this.f[this.g]}E(){return this.D().type===20}},xt=class{static fal...

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing an issue with remote hosts. It appears to be specific to VS Code editor and tools if we understanding correctly. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
