### ISSUE TITLE
ftp-simple

### ISSUE THREAD

**Issue by dashingwebtech** [microsoft/vsmarketplace#1029]
Type: <b>Bug</b>

Getting error with this update

VS Code version: Code 1.94.0 (d78a74bcdfad14d5d3b1b782f87255d802b57511, 2024-10-02T13:08:12.626Z)
OS version: Windows_NT x64 10.0.22635
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for contacting the VS Marketplace Support Team. Could you please provide more details about your requirement to look further.

VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
