### ISSUE TITLE
Show a message if an extension has not enough reviews, instead of showing a rating of 0.0 out of 5

### ISSUE THREAD

**Issue by hediet** [microsoft/vsmarketplace#103]
Extensions that don't have enough reviews simply get a rating of 0.0 out of 5 stars. Since the number of reviews is shown next to the rating, this could give the impression that the extension got very bad reviews.

While it is not possible to actually give 0 star ratings, this could still be quite confusing.

![image](https://user-images.githubusercontent.com/2931520/122226036-dc93ac80-ceb5-11eb-9f97-740147f65e41.png)

I suggest to show a different hover message (e.g. "This extension needs more reviews to show a rating") and maybe render some question mark on top of the grayed out stars.

This is what the macOS app store says:

<img width="566" alt="2021-06-16_14-12-57" src="https://user-images.githubusercontent.com/2931520/122231030-6f364a80-ceba-11eb-8fdc-8c28f3444bc2.png">

**Comment by usernamehw** [comment]
It usually shows rating even with 1 review. This is just broken since Saturday for some extensions.

**Comment by usernamehw** [comment]
Seems to be fixed now.

**Comment by hediet** [comment]
Seems like they restored the old behavior. I'm actually in favor of showing the rating only after a certain amount of reviews - but this should be visually communicated, so that users clearly see that the extension does not have enough reviews yet.

**Comment by usernamehw** [comment]
Does anyone know if this was a bug or a feature?

If that was a feature I'm fully against it. People VERY rarely add reviews to extensions: as you can see even on the this random screenshot: `27,000` installs and 4 reviews: that's ridiculous.

**Comment by hediet** [comment]
> as you can see even on the this random screenshot: 27,000 installs and 4 reviews: that's ridiculous.

Yes, but I also once published an extension and got a random 1/5 review as first review. It took quite some time until other people added a bunch of 5/5 reviews - until then I had an average rating of 1/5 which super sucked, as the rating is displayed very prominently.

**Comment by prashantvc** [comment]
We have fixed it, could you check it again

**Comment by hediet** [comment]
Confirmed!
