### ISSUE TITLE
Modern extensions that do not support older VS versions do not appear on the home page

### ISSUE THREAD

**Issue by VisualMicro** [microsoft/vsmarketplace#1030]
**Describe the bug**
The gallery home is missing extensions that do not support older versions of Visual Studio.

An extension vsix that specifies VS 2022 but does NOT specify (VS2019 or below) does not appear on the home page (see image below)

**To Reproduce**
1. Go to 'https://marketplace.visualstudio.com/'
2. Ensure **Visual Studio** is selected
3. Scroll through the **Most Popular** and **Highest Rated** extensions and notice that VS2022 extensions only appear if they are also for older versions of VS

**Expected behavior**
The lists on this page should include modern extensions that do not support older vs versions. It currently does not.

**Screenshots**
These lists are wrong:-
![Image](https://github.com/user-attachments/assets/841ffe1b-a430-4b0c-aa49-ca62451e3ea5)

**Additional context**
Recently this problem was fixed for the Featured List on the same page via this ticket
https://github.com/microsoft/vsmarketplace/issues/375

**Comment by madhurivadaligithub** [comment]
Racking here https://github.com/microsoft/vsmarketplace/issues/375
