### ISSUE TITLE
I cannot access the extensions.

### ISSUE THREAD

**Issue by Joychepchumba** [microsoft/vsmarketplace#1031]
Type: <b>Feature Request</b>

I keep on getting Ërror while fetching extensions. Failed to fetch."

I have done everything, changed proxy settings, changed dns server and uninstalled the application but I still have the same problem. Kindly help. Thank you

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Joychepchumba ,

Are you still facing the issues? if yes, could you please share the below details to look further.

Thanks for the update, could you please submit a Fiddler trace recording to look further or share details by using MTR.

To capture MTR:
Download [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).

Enter marketplace.visualstudio.com as the hostname and click Start.

![Image](https://github.com/user-attachments/assets/6e17e489-f211-476e-9162-ffd029dec475)

Wait until the Sent column is >= 100.

Copy text to clipboard, share with us.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
