### ISSUE TITLE
Syntax highlighting broken

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vsmarketplace#1032]
**Describe the bug**
Syntax highlighting no longer works inside Markdown code blocks

**To Reproduce**
1. Go to [amodio.tsl-problem-matcher](https://marketplace.visualstudio.com/items?itemName=amodio.tsl-problem-matcher) or [RedCMD.tmlanguage-syntax-highlighter](https://marketplace.visualstudio.com/items?itemName=RedCMD.tmlanguage-syntax-highlighter)
3. Scroll down to any of the code blocks
4. See no syntax highlighting within the code blocks

**Expected behavior**
Syntax highlighting

**Screenshots**
![Image](https://github.com/user-attachments/assets/6394a93e-b004-4118-8273-9e058bc5f6a2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 129

**Comment by madhurivadaligithub** [comment]
Hi @RedCMD ,

Thank you for reaching VS Marketplace Support Team. We are following up to determine how best to address it.

-VS Marketplace Team

**Comment by RedCMD** [comment]
still not resolved
