### ISSUE TITLE
Images not showing when using Go Live

### ISSUE THREAD

**Issue by chelseaangeles** [microsoft/vsmarketplace#1033]
Type: <b>Bug</b>

The images are not showing when using Go Live. 

 The path is:
/project
   /body
      /index.html
      /about.html
   /assets
      /logo
         /logo1.png

<img src="../assets/logo/logo1-red.png">

VS Code version: Code 1.94.2 (Universal) (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Darwin x64 24.0.0
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you forThanks for reaching VS Marketplace, please share error message or screenshot to investigate better.

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Since we haven't received a response, we're assuming the issue has been resolved. If the problem persists, please reopen this request or submit a new one. Thank you!

Regards,
VS Marketplace Team
