### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by Coo-NA-l-7025** [microsoft/vsmarketplace#1034]
Type: <b>Bug</b>

Error while fetching extensions. Failed to fetch

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace Team, could you please submit a Fiddler trace recording to look further or share details by using MTR.

To capture MTR:
Download [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).

Enter marketplace.visualstudio.com as the hostname and click Start.
![Image](https://github.com/user-attachments/assets/744c72ee-6df9-4bbf-bd9e-e69762dc65fc)


Wait until the Sent column is >= 100.

Copy text to clipboard, share with us.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Since we haven't received a response, we're assuming the issue has been resolved. If the problem persists, please reopen this request or submit a new one. Thank you!

Regards,
VS Marketplace Team
