### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by mohamedjavith820** [microsoft/vsmarketplace#1035]
Issue Type: <b>Bug</b>

XHR failed

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T17:05:44.765Z)
OS version: Windows_NT ia32 6.1.7601
Restricted Mode: No

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace, please share error message or screenshot to investigate better.

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
