### ISSUE TITLE
cannot search and install extension

### ISSUE THREAD

**Issue by blaze0928** [microsoft/vsmarketplace#1037]
Type: <b>Bug</b>

the extension market are failed in loading the extension list and I can't download

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace, please share error message or screenshot to investigate better.

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
