### ISSUE TITLE
Unable to download extensions

### ISSUE THREAD

**Issue by mkgrove66** [microsoft/vsmarketplace#1038]
Type: <b>Bug</b>

I have installed VS CODE on my laptop, and I am unable to download and/or see any extensions

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Dulicate to this https://github.com/microsoft/vsmarketplace/issues/1039 hence close.
