### ISSUE TITLE
Unable to download extensions

### ISSUE THREAD

**Issue by mkgrove66** [microsoft/vsmarketplace#1039]
Type: <b>Bug</b>

I have installed VS Cdoe on my laptop, and I ma unbel to download and/or see any extensions

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for the update, could you please submit a Fiddler trace recording to look further or share details by using MTR.

To capture MTR:
Download [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).

Enter marketplace.visualstudio.com as the hostname and click Start.
![Image](https://github.com/user-attachments/assets/f961cbe2-e262-4225-81f8-2f572c561764)

Wait until the Sent column is >= 100.

Copy text to clipboard, share with us.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
