### ISSUE TITLE
Cannot access Extensions Marketplace in Brazil

### ISSUE THREAD

**Issue by PedroHercules** [microsoft/vsmarketplace#1041]
Type: <b>Bug</b>

Steps to Reproduce:

Open Visual Studio Code.
Ensure that the VPN is disabled.
Attempt to access the Extensions Marketplace.
Observe the error messages in the console log indicating failed network requests (e.g., "Failed to fetch" errors).
Actual Result: When the VPN is disabled, I am unable to access the Extensions Marketplace. The following error messages are displayed in the console:

Error messages indicating failed GET requests, such as:
https://az764295.vo.msecnd.net/extensions/chat.json - error GET Failed to fetch
Failed to fetch chat participant registry
Expected Result: I should be able to access the Extensions Marketplace without needing to connect to a VPN.

Additional Information:

This issue occurs on the latest version of Visual Studio Code.
The problem does not occur when connected to a VPN, which suggests it may be related to network settings or restrictions when the VPN is not active.
My operating system is Windows 11.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.26100
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace Team, could you please submit a Fiddler trace recording to look further or share details by using MTR.

To capture MTR:
Download [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).

Enter marketplace.visualstudio.com as the hostname and click Start.
![Image](https://github.com/user-attachments/assets/214289b4-6f1c-41d2-8064-7baeea6c0063)


Wait until the Sent column is >= 100.

Copy text to clipboard, share with us.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
