### ISSUE TITLE
error fetching extentions

### ISSUE THREAD

**Issue by ghost** [microsoft/vsmarketplace#1042]
Type: <b>Bug</b>

error fetching the extention 

please help beacuse of this problem distracting me in my graduation project and i want to setup some extention

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace Support Team, could you please share more details like error message, screenshot to look further.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
