### ISSUE TITLE
I can't install extensions

### ISSUE THREAD

**Issue by MuhammadArifRizki** [microsoft/vsmarketplace#1043]
Type: <b>Feature Request</b>

Error while installing 'Python' extension. Please check the log for more details.

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace Support Team, could you please share more details like error message, screenshot to look further.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
