### ISSUE TITLE
showing vs code  error

### ISSUE THREAD

**Issue by prxkhxr-02** [microsoft/vsmarketplace#1045]
Type: <b>Bug</b>

error in fetching the extension plese help me to resolve the issue

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.26100
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for the update, could you please submit a Fiddler trace recording to look further or share details by using MTR.

To capture MTR:
Download [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).
![Image](https://github.com/user-attachments/assets/056e6435-6d3b-4508-bd4f-b5f1d5526740)
![Image](https://github.com/user-attachments/assets/5d844f5e-8b09-4aa2-a8ec-f90f040521fb)


Enter marketplace.visualstudio.com as the hostname and click Start.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
