### ISSUE TITLE
Please unlock my VSIX ID - cannot reupload my extension anymore

### ISSUE THREAD

**Issue by xiaomi7732** [microsoft/vsmarketplace#1046]
I didn't not know that the VSIX id can't be reused once deleted:

![Image](https://github.com/user-attachments/assets/823b7c94-5e96-46d2-b8ad-3d6173d2ef2b)

Could you please **unlock the VSIX id** for us so that I can upload another version:
Microsoft.VisualStudio.Extensions.CodeOptimize.VSExt.28c71906-d891-4eac-8b83-64effc23888b

**Comment by madhurivadaligithub** [comment]
Hi @xiaomi7732 ,

Thanks for reaching VS Marketplace Team, could you please reach out to our support team VSMarketplace@microsoft.com with these details for quick assistance.

Regards,
VS Marketplace Team
