### ISSUE TITLE
blackbox.ai workspace context isn't working

### ISSUE THREAD

**Issue by johnroed** [microsoft/vsmarketplace#1047]
Type: <b>Bug</b>

when i shared my files to blackbox.ai in the workspace context it just processing non stop and when my wifi it good though

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing the issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
