### ISSUE TITLE
I am unable to publish an extension I spent months on.

### ISSUE THREAD

**Issue by juanxaiodev** [microsoft/vsmarketplace#1050]
While attempting to upload my extension "Solidity for Ethereum Chain" (Which would allow the user to audit smart contracts, deploy them, etc whilst running the code through a specially-trained AI to detect possible vulnerabilities (such as re-entrancy.) I get the following error:

![Image](https://github.com/user-attachments/assets/80b238bf-d08b-4d5c-a1ad-30b1f3a1787f)

How to replicate this:

Create any extension (even a blank one) and add the name "Solidity" or "Ethereum" to the display name / item name, and it flags it as malicious despite there being hundreds of other extensions with alike names????????????

Yes, I have also done my due-diligence by asking an AI what could be wrong, clearing ALL of my code and leaving just a blank extension (which proves that it is the names that are causing this). As well as I have emailed the staff team **4 times** now. I am kindly requesting that these harmless words get unblocked, as I don't know why they were blocked in the first place.

**Comment by juanxaiodev** [comment]
Just trying to understand why the name of an entire language is not allowed on the store all of the sudden, when I see hundreds of them readily available?

**Comment by madhurivadaligithub** [comment]
Hi @juanxaiodev ,

Thank you for reaching out to the VS Marketplace Support Team. We are tracking this issue through the support alias VSMarketplace@microsoft.com. This entry will be closed as a duplicate.


please feel free to reopen or create new for any further issues.

Regards,
VS Marketplace Team

**Comment by juanxaiodev** [comment]
Hey there.

According to the e-mail it is marked as "Spam" but there are plenty of other extensions with the same name??? Lol.

Also - I would like it to be unblocked for me if possible:)
