### ISSUE TITLE
I'd like to be able to get an Enbed Code for my calculator

### ISSUE THREAD

**Issue by REtonyortega** [microsoft/vsmarketplace#1052]
Type: <b>Feature Request</b>

I'd like to be able to get an Enbed Code for my calculator, how can I do this?

REtonyortega@gmail.com

Thank you,

Tony Ortega

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @REtonyortega ,

Thank you for opening the issue. We're sorry to hear you're experiencing problems. It appears to be specific to the VS Code editor and tools, if we understand correctly. It's best to reach out to the VS Code team at https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
