### ISSUE TITLE
Change ownership of VS Code extension on VS Code marketplace

### ISSUE THREAD

**Issue by SebastienAndre** [microsoft/vsmarketplace#1053]
The vscode extension has been published by a former employee. 
Now we have to publish new version the vscode extension.
How to transfer the ownership of vscode extension to other employee?
Thank you.

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace Team, could you please reach out to us with your extension VSIX through our support alias ([VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com)) to address this issue promptly.

Regards,
VS Marketplace Team
