### ISSUE TITLE
Perplexity AI  dont work 

### ISSUE THREAD

**Issue by damadorPL** [microsoft/vsmarketplace#1054]
Type: <b>Bug</b>

using @perplexityi show 
---
Authorize agent

Please authorize usage of @perplexityai on github.com and resend your question. Learn more.
---

clicking authorize button open browser and return 

---
This GitHub App must be configured with a callback URL
---

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.26100
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. We're sorry to hear you're experiencing problems. It appears to be specific to the VS Code editor and tools, if we understand correctly. It's best to reach out to the VS Code team at https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
