### ISSUE TITLE
Cannot create extension with the name "Solidity" or "Ethereum"

### ISSUE THREAD

**Issue by juanxaiodev** [microsoft/vsmarketplace#1055]
I can't create an extension with the name "Solidity" or "Ethereum", it says it's "Malicious" when it's a coding language???????????

https://soliditylang.org/

I can't even have the word in the description or README either.

Get this fixed please.

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace Team, could you please reach out to us with your extension VSIX through our support alias (VSMarketplace@microsoft.com) to address this issue promptly.
