### ISSUE TITLE
error problem

### ISSUE THREAD

**Issue by SahilMangate** [microsoft/vsmarketplace#1056]
Type: <b>Bug</b>

if i write a wrong code so it is not showing error

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace, please share error message or screenshot to investigate better.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
