### ISSUE TITLE
Extension keep loading and cant install

### ISSUE THREAD

**Issue by sebastiangavinn** [microsoft/vsmarketplace#1057]
Type: <b>Bug</b>

Im updating my vs code to the latest version, and when im installing extension, it keep loading

VS Code version: Code 1.95.0 (912bb683695358a54ae0c670461738984cbb5b95, 2024-10-28T20:16:24.561Z)
OS version: Linux x64 6.8.0-47-generic
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing an issue with searching. It appears to be specific to VS Code editor and tools if we understand correctly. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

If you need any further assistance, please reopen or create a new issue.

Regards,
VS Marketplace Support Team
