### ISSUE TITLE
Error install extension from file .vsix

### ISSUE THREAD

**Issue by TRINHHOANGANH** [microsoft/vsmarketplace#1059]
**Describe the bug**

When I install the Continue by Extension and the .vsix file. In my IDE it shows two items: "New Session", "History"; "Toggle Full Screen".

**To Reproduce**
1. Go to tab " Extension"
2. Install Continue extension
3. Download Continue extension in VS martketplace
4. Install Continue extension with file ".vsix"

**Screenshots**
![Image](https://github.com/user-attachments/assets/be269eb9-a55b-425b-b30e-f9d0e23a2542)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20

**Comment by madhurivadaligithub** [comment]
Thank you for reporting your concern. We are unable to repro the issue and following up to determine how best to address it. 
 
-VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
