### ISSUE TITLE
Marketplace API: ability to get latest version of extension that's compatible with a certain vscode (engine)

### ISSUE THREAD

**Issue by amtadev** [microsoft/vsmarketplace#106]
Hello,

I Install VSIX files through its web API rather than from inside VS Code since offline installation is a must in the environment I work in.
To get the latest version of a particular, I put the word "latest" instead of the version number in the download link.
Example:
`https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-toolsai/vsextensions/jupyter/latest/vspackage`
This will download for me the latest available version of Jupyter extension.
The problems here is as follows:
1- The latest version could be an insider version (rather than a stable one), which has been the case for (at least) Jupyter extension in its last 5 versions. Downloading an extension which is only compatible with insider vscode (engine) renders it useless if my vscode version is the stable one.
2- even if the latest version of an extension required a stable vscode (engine) version, I may not have the latest vscode version, which again, will make it incompatible.

The suggestion here is to have the ability to pass the version of the vscode engine I have in the marketplace API link and get the latest version of an extension for a particular vscode engine. 
JetBrains have something similar which can be found here: 
`https://plugins.jetbrains.com/docs/marketplace/plugin-update-download.html`

Or, at least, avoid marking insider versions of the extensions as 'latest' which will fix problem 1 above.

Thank you

**Comment by Neelima10735584** [comment]
Since latest version of extension compatible with a certain vscode, we are closing this issue.

Regards,
VS Marketplace Team
