### ISSUE TITLE
In the Query Result, unable to select multiple cells

### ISSUE THREAD

**Issue by kartik1581** [microsoft/vsmarketplace#1060]
Type: <b>Feature Request</b>

When i run the Oracle SQL query, results are displayed in the grid (Query Result grid). I want to select multiple cells in the column but unable to do so. Same feature is available in many grids (e.g. oracle SQL Developer).

Currently i have to export the data in the CSV and from then i need to select required cells.

VS Code version: Code 1.95.1 (Universal) (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @kartik1581,

This issue appears to be a support question specific to the extension which is best addressed by the extension owner.  We recommend visiting the extension page on https://marketplace.visualstudio.com/ and posting a question there. Let us know if we can help you with anything else.

Regards,
VS Marketplace Team
