### ISSUE TITLE
MatplotlibDeprecationWarning running pytest with PythonDebugger 

### ISSUE THREAD

**Issue by StefanieSenger** [microsoft/vsmarketplace#1062]
Type: <b>Bug</b>

I am getting `MatplotlibDeprecationWarning` when I run this with the `PythonDebugger` in the `Testing` extension:

```python
import warnings
import pytest

def f():
    warnings.warn("Test", UserWarning)

def test_warn():
    with pytest.warns(UserWarning, match="Test"):
        f()
```
Here's the traceback:
```
/home/stefanie/code/scikit-learn_dev/scikit-learn/sklearn/test_warn.py::test_warn failed: def test_warn():
>       with pytest.warns(UserWarning, match="Test"):
E       matplotlib._api.deprecation.MatplotlibDeprecationWarning: The interactive_bk attribute was deprecated in Matplotlib 3.9 and will be removed in 3.11. Use ``matplotlib.backends.backend_registry.list_builtin(matplotlib.backends.BackendFilter.INTERACTIVE)`` instead.
```

I would have expected not to see this warning and to continue with the debugging. Just running the test with Testing in VSCode or running pytest on the terminal works just fine.

sklearn/test_warn.py:8: MatplotlibDeprecationWarning

VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Linux x64 6.11.5-arch1-1
Modes:

versions:
pytest==8.3.1
matplotlib==3.9.2

**Comment by Neelima10735584** [comment]
Hi @StefanieSenger ,

Thank you for reaching VS Marketplace Support Team, this issue is specific to VS Code editor and tools, if we understand correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

Please feel free to reach out to us if you still require any help.

**Comment by StefanieSenger** [comment]
> this issue is specific to VS Code editor and tools, if we understand correctly.

Yes it is. Sorry, I have then misplaced this issue. I will raise it in the correct project.
