### ISSUE TITLE
failed to fetch extensions

### ISSUE THREAD

**Issue by julbroa** [microsoft/vsmarketplace#1067]
Type: <b>Bug</b>

if i search extensions, only appear: error while fetching extensions, XHR failed

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 6.1.7601![Image](https://github.com/user-attachments/assets/d26b0d34-499f-41e5-8283-c05f313704a6)

Modes:

**Comment by Neelima10735584** [comment]
Thanks for the update, could you please submit a Fiddler trace recording to look further or share details by using MTR.

To capture MTR:
Download [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).

Enter marketplace.visualstudio.com as the hostname and click Start.
Image

Wait until the Sent column is >= 100.

Copy text to clipboard, share with us.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team

**Comment by julbroa** [comment]
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                           192.168.100.1 -    0 |  204 |  204 |    1 |    2 |   33 |    5 |
|                             10.62.128.1 -    0 |  204 |  204 |    2 |    5 |   47 |    6 |
|                             10.180.49.9 -   94 |   43 |    3 |    8 |    9 |   13 |    8 |
|                             10.180.49.6 -   98 |   41 |    1 |    0 |    5 |    5 |    5 |
|                          10.180.200.218 -    0 |  204 |  204 |    6 |   10 |   43 |   10 |
|      ae67-0.mex30-96cbe-1a.ntwk.msn.net -    0 |  204 |  204 |    6 |   10 |   47 |    8 |
|                           13.104.187.83 -    0 |  204 |  204 |    6 |    9 |   41 |    7 |
|                   No response from host -  100 |   40 |    0 |    0 |    0 |    0 |    0 |
|                            13.107.42.18 -    0 |  204 |  204 |    6 |    9 |   48 |   11 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider
