### ISSUE TITLE
Shouldn't there be a restriction on displayName length and other fields in the extension manifest? 

### ISSUE THREAD

**Issue by sandy081** [microsoft/vsmarketplace#107]
_Initially filed by @aravindvnair99 here - https://github.com/microsoft/vscode/issues/126771_

Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.57.1
- OS Version: Windows 10 21H1 19043.1052

Steps to Reproduce:

1. Install [Tabnine AI Code Completion for all major programming languages, autocomplete JavaScript, Python, TypeScript, PHP, Go, Java, Ruby, C/C++, HTML/CSS, C#, Rust, SQL, Bash, Kotlin, React, Swift, Scala, Sass, Perl, Objective C, Node JS, Matlab, Haskell, Dart, Angular](https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode) extension.
2. Open `Running Extensions` or `Extension panel` to end up with these:

- Unable to see activation time in Visual Studio Code - Running Extensions:
![image](https://user-images.githubusercontent.com/22199259/122211744-b1648980-cec4-11eb-988e-a9b3b3d63d1e.png)

- Name not completely visible in Visual Studio Code - Extension panel
![image](https://user-images.githubusercontent.com/22199259/122211958-ebce2680-cec4-11eb-8a6e-69f8fe3c7859.png)

I did report to the authors at https://github.com/codota/tabnine-vscode/issues/535 and also gave them a PR for the same at https://github.com/codota/tabnine-vscode/pull/536 which they have [closed](https://github.com/codota/tabnine-vscode/pull/536#issuecomment-864506999) by saying:

>we use longer names to make it easier for people to find Tabnine in the search results.

I understand that, but shouldn't there be a restriction on `displayName` length from Visual Studio Code itself to prevent authors from using whatever length they feel like? As then I would not end up with the scenario as shown in the screenshot, especially I not being able to view the activation time.

On a side note, I also feel not imposing length or quantity restrictions for items in the [extension manifest](https://code.visualstudio.com/api/references/extension-manifest) leads to abuse and unfair competition. I strongly feel this should be regulated so that all extensions have equal visibility and opportunity to grow their user base and not based on who adds more things in the fields. Right now, I see only the following two restrictions:

Name | Type | Details
-- | -- | --
description | string | A short description of what your extension is and does.
keywords | array | An array of&nbsp;keywords&nbsp;to make it easier to find the extension. These are included with other extension&nbsp;Tags&nbsp;on the Marketplace. This list is currently limited to 5 keywords.

But `short` is subjective. Short to you is different from short to me. I feel there should be a well-defined maximum number. And likewise, for keywords, I see many extensions using more than 5 keywords including the one I mentioned which is using [34 keywords](https://github.com/codota/tabnine-vscode/blob/8f8f1c19b94bc71224bed5d444040030d94ea4d7/package.json#L54-L89).

Other fields don't have restrictions at all.

**Comment by sandy081** [comment]
It seems authors are adding such long titles for better discoverability. I do not think we shall encourage authors to come up with such hacks for discoverability. Is it possible to place some restrictions for such usages?

**Comment by RandomFractals** [comment]
I disagree on the keywords part. Please don't do that. Search in marketplace is broken as is.

Please fix that first!

Thanks

**Comment by eamodio** [comment]
💯 Agree -- Marketplace search needs to be fixed before anything here should be changed imo.

**Comment by aravindvnair99** [comment]
@sandy081 @prashantvc any updates?

**Comment by prashantvc** [comment]
like everyone mentioned it is an issue with search, and people optimising their extension to show up on the top.
As we improve the search, we hope extension authors will stop doing this. 

We will evaluate this later, while we deploy search improvements. I am closing this issue for now
