### ISSUE TITLE
Remote save and delete too slow

### ISSUE THREAD

**Issue by daixd5520** [microsoft/vsmarketplace#1071]
Type: <b>Bug</b>

when I save or delete files through ssh window, it shows "xxx save workers"

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 5.15.0-107-generic

**Comment by Neelima10735584** [comment]
Thank you for contacting the VS Marketplace Support Team. We will review it and follow up to determine the best way to address it.

VS Marketplace Team

**Comment by Neelima10735584** [comment]
As this issue is specific to VS Code editor and tools, if we understand correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
