### ISSUE TITLE
Can't create publisher or extension, issue with spam filter

### ISSUE THREAD

**Issue by techaddict993** [microsoft/vsmarketplace#1072]
Any of the words related to crypto in any capacity are flagged by the spam filter, this seems to be an issue reported a lot

Examples:

Solidity
Ethereum
Blockchain
DeFi

ETC

I have already reported this issue via email to no avail, as well as sent my VSIX. But I still cannot sign up or create extension. Please fix this, Visual studio Code.

**Comment by Neelima10735584** [comment]
Thanks for reaching VS Marketplace Team, Could you please out to us through our VS Marketplace Support ([VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com)) alias for further clarifications.

Regards,
VS Marketplace Team

**Comment by techaddict993** [comment]
It's been a week, I opened a ticket with this ticket here. Your support team simply ignores it.
