### ISSUE TITLE
can not use extension

### ISSUE THREAD

**Issue by Harshitsaxena14** [microsoft/vsmarketplace#1073]
Type: <b>Bug</b>

.
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by Neelima10735584** [comment]
Thanks for reaching VS Marketplace, please share error message or screenshot to investigate better.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
