### ISSUE TITLE
Can't create publisher or extension, issue with spam filter

### ISSUE THREAD

**Issue by techaddict993** [microsoft/vsmarketplace#1075]
Any of the words related to crypto in any capacity are flagged by the spam filter, this seems to be an issue reported a lot

Examples:

Solidity
Ethereum
Blockchain
DeFi

ETC

I have already reported this issue via email to no avail, as well as sent my VSIX. But I still cannot sign up or create extension. Please fix this, Visual studio Code.

EDIT: My email has been unanswered for a week ONCE AGAIN, this is the fourth email.

**Comment by Slikk42** [comment]
Hello @techaddict993  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by Neelima10735584** [comment]
Thanks for reaching VS Marketplace Team, Could you please out to us through our VS Marketplace Support ([VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com)) alias for further clarifications.

Regards,
VS Marketplace Team
