### ISSUE TITLE
pati

### ISSUE THREAD

**Issue by Vyta309** [microsoft/vsmarketplace#1076]
Type: <b>Feature Request</b>

dvylika  sss

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by Neelima10735584** [comment]
Thanks for reaching VS Marketplace Support Team, could you please share more details like error message, screenshot to look further.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
