### ISSUE TITLE
Python Debugger doesnt work

### ISSUE THREAD

**Issue by Semkem** [microsoft/vsmarketplace#1078]
Type: <b>Bug</b>

I'm trying to complete course vs code with fastapi on vs code site and when I try to start the fastapi debug its tsart the debug console with command and then showig pop up with text "timeout for waiting debuge" and its stopped/ I cant find how i can resolve this by myself

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.26100
Modes:

**Comment by Neelima10735584** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing this issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
