### ISSUE TITLE
Live preview not working

### ISSUE THREAD

**Issue by Abhyudai-lpu** [microsoft/vsmarketplace#1079]
Type: <b>Feature Request</b>

Live preview stopped working properly, I have to right click and click on show preview

VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Abhyudai-lpu 

Thanks for reaching VS Marketplace Support Team, could you please share repro steps and extension details to investigate further.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
