### ISSUE TITLE
failed to fetch extensions

### ISSUE THREAD

**Issue by julbroa** [microsoft/vsmarketplace#1084]
Type: Bug

if i search extensions, only appear: error while fetching extensions, XHR failed

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 6.1.7601Image

Modes:
![Image](https://github.com/user-attachments/assets/9b0e7124-4dc1-46cd-a306-77ac1c5dbf50)

**Comment by Neelima10735584** [comment]
Thanks for the update, could you please submit a Fiddler trace recording to look further or share details by using MTR.

To capture MTR:
Download [WinMTR](https://sourceforge.net/projects/winmtr/files/WinMTR-v092.zip/download).

Enter marketplace.visualstudio.com as the hostname and click Start.
I

![Image](https://github.com/user-attachments/assets/1f363a1f-8a28-4dfe-84f0-00a739ffab40)


Wait until the Sent column is >= 100.

Copy text to clipboard, share with us.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
