### ISSUE TITLE
Copy button is not working

### ISSUE THREAD

**Issue by im-ansam** [microsoft/vsmarketplace#1087]
The copy button in the extension installation command is not working.

**To Reproduce**
1. Go to any extension and try to copy the installation command using the copy button
2. Try to paste it somewhere

 - OS: [ linux ]
 - Browser [ Chrome ]
![Image](https://github.com/user-attachments/assets/5c8e4423-3590-4890-beee-2f570467e502)

**Comment by Neelima10735584** [comment]
Hi,

Thank you for opening the issue. Sorry to hear you are experiencing this issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
