### ISSUE TITLE
Cannot add new member to extension publisher

### ISSUE THREAD

**Issue by TalkIsCheap0** [microsoft/vsmarketplace#109]
https://marketplace.visualstudio.com/manage/publishers

i want to add a new member to the publisher which i created,
but i got the error like this: Invalid domain.
i am sure that the email address is correct and effective
![image](https://user-images.githubusercontent.com/49405187/123117154-793ce800-d47c-11eb-9f9c-2c026c7108a5.png)

**Comment by ssbarnea** [comment]
There is also a long thread on https://stackoverflow.com/questions/56032912/vs-marketplace-add-member-displayes-invalid-domain-error on this issue alone but the reality is that functionality is fully broken and the only option so far is to use email support form from the top of the web page.

I guess they address these doing an SQL insert or update on production database ;)

**Comment by iChenLei** [comment]
+1, please fix it !!!   @prashantvc @isidorn

**Comment by isidorn** [comment]
No plans to fix for now. This is also captured in other issues in this repo.
The flow for the time being is to email marketplace support.
No actions planned, thus closing

**Comment by ki39** [comment]
> No plans to fix for now. This is also captured in other issues in this repo. The flow for the time being is to email marketplace support. No actions planned, thus closing

Why not fix it .It cant work.

**Comment by anupkmr03** [comment]
As an alternate solution, please try adding member using `User Id`. 
Steps for the same. 
1. Ask member to login their account on [Marketplace](https://marketplace.visualstudio.com/)
2. `User Id` will be visible by hovering over email. As shown in the image. 
![image](https://user-images.githubusercontent.com/16070906/146738216-6b44fc70-3a63-4534-b2c1-1985d6f407ab.png)
3. Member can copy the `User Id` by clicking `copy-to-clipboard` button and share to the publisher (You).
4. Now, the publisher (You) can add member via `User Id` from members portal. As shown in the image. 
![image](https://user-images.githubusercontent.com/16070906/146739219-6aaa43f0-e1c1-454e-a702-beed388954b5.png)

**Comment by PhilippeFerreiraDeSousa** [comment]
> No plans to fix for now. This is also captured in other issues in this repo. The flow for the time being is to email marketplace support. No actions planned, thus closing

Any update? We managed to use the userId method, but I would assume that this is a very trivial thing to fix?
