### ISSUE TITLE
lost access to a publisher, ghosted by vsmarketplace@microsoft.com after sending my verification data

### ISSUE THREAD

**Issue by janw4ld** [microsoft/vsmarketplace#1095]
my issue is the same as https://github.com/microsoft/vsmarketplace/issues/356
- my extension is [lambda-black](https://github.com/janw4ld/lambda-black)
- [here](https://github.com/janw4ld/lambda-black/tree/vscode-repo-ownership-verification) is the repo ownership commit i was asked to make
- the email address i'm trying to verify is linked to the repo is janw4ld@tutanota.com, which is this github account's public email address visible on [my profile](github.com/janw4ld) as well as every commit in the lambda-black repo  
![Image](https://github.com/user-attachments/assets/8304a641-a600-49dc-82c3-304ee900a9b9)

**Comment by Neelima10735584** [comment]
Thanks for reaching VS Marketplace Team, Could you please out to us through our VS Marketplace Support ([VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com)) alias for further clarifications.

Regards,
VS Marketplace Team

**Comment by janw4ld** [comment]
My issue is that I haven't got a response from vsmarketplace@microsoft.com in more than 20 days, despite following up on my last email multiple times, so I don't think following up on my emails can help here.

**Comment by Neelima10735584** [comment]
We have verified your ownership and will provide the required access as soon as possible. We will track your issue there.
Closing this issue.
