### ISSUE TITLE
Extension cannot be installed for several minutes after publishing a new version

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vsmarketplace#11]
**Describe the bug**

When I publish a new version of [Luna Paint](https://marketplace.visualstudio.com/items?itemName=Tyriar.luna-paint) I see this for several minutes:

![image](https://user-images.githubusercontent.com/2193314/109656889-bc63fb80-7b19-11eb-9f5f-2f43474cb1b1.png)

While it's possible this could be a client issue, it seems much more likely that the marketplace is exposing the package in an invalid state while publish happens in the background. The old version should be exposed until the new one is actually ready to go.

cc @sandy081 

**To Reproduce**
1. Publish an extension
2. Try install it in stable or insiders

**Expected behavior**
No error should occur for users due to publishing.

**Desktop (please complete the following information):**

Version: 1.54.0-insider (user setup)
Commit: e7989863202eac0ec4e66ca82733d968bca7527a
Date: 2021-03-01T21:11:33.783Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by sandy081** [comment]
Yes, VS Code excludes invalid versions

**Comment by SaiKanth007** [comment]
@sandy081 Thanks for the confirmation
@Tyriar This issue should have been resolved. Feel free to create a new ticket if you are seeing any other issues.
