### ISSUE TITLE
An Abusive Titled Extension

### ISSUE THREAD

**Issue by LordBars** [microsoft/vsmarketplace#110]
Issue Type: <b>Bug</b>

### Abusive Statement 

I found an extension which includes abusive statements in it's description, the extension id is: mithatguner.ext-skm
The abusive statement is: "Yapacağın İşi Sikeyim Extension"

It is written in Turkish Language and when we translate it to English, it means: "I f*ck your job extension". I don't want to see this type of extension in marketplace. Please fix this.

![Image](https://user-images.githubusercontent.com/75415283/123446574-b1aa0680-d5e1-11eb-99d7-fa293289a753.png)

VS Code version: Code 1.57.1 (Universal) (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 19.6.0
Restricted Mode: Yes

**Comment by isidorn** [comment]
I have reported this extension and have verified that the description is offensive.
We will remove it. No other action planned, thus closing this item
