### ISSUE TITLE
platformio installing issue

### ISSUE THREAD

**Issue by mahdifarajiii** [microsoft/vsmarketplace#1101]
![Image](https://github.com/user-attachments/assets/fcfc118b-a3a5-43be-a43e-6ccaa23c38c6)

Type: <b>Bug</b>

i wnat to add platformio to my vscode but it's not install. i stay for two hours on platformio IDE extention page and nothing happens, even any error doesn't shown

VS Code version: Code 1.96.2 (fabdb6a30b49f79a7aba0f2ad9df9b399473380f, 2024-12-19T10:22:47.216Z)
OS version: Windows_NT x64 10.0.26100
Modes:

**Comment by Neelima10735584** [comment]
Hi,

Thank you for opening the issue. Sorry to hear you are experiencing this issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
