### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by ThuraLinn** [microsoft/vsmarketplace#112]
Issue Type: <b>Bug</b>

We cannot connet to Extensions Marketplace at this time,please try again later.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:07.755Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

**Comment by prashantvc** [comment]
Can you share more details? What region you live in? Do you still see this issue?

Can you load marketplace.visualstudio.com in the browser?
