### ISSUE TITLE
Bicep errors are miss leading when using module

### ISSUE THREAD

**Issue by tigerdeccan** [microsoft/vsmarketplace#116]
Issue Type: <b>Bug</b>

When you create a module you see all these errors complaing syntax is incorrect .  this is related to Bicep extension.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No
![Uploading Screenshot 2021-07-04 at 02.21.08.png…]()

**Comment by isidorn** [comment]
No related to marketplace, closing
