### ISSUE TITLE
Marketplace not working.

### ISSUE THREAD

**Issue by wraient** [microsoft/vsmarketplace#117]
Issue Type: <b>Bug</b>

5/7/2021
I have a fairly high internet connection (60Mbps) but still I can't connect to vscode marketplace from yesterday and even I can't browse vscode website on web. Please fix this problem ASAP.
Thanks & Regard,
Wraient
wraient.911@gmail.com

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.10.0-kali7-amd64
Restricted Mode: No

**Comment by prashantvc** [comment]
Can you share more details? What region you live in? Do you still see this issue?

Can you load marketplace.visualstudio.com in the browser?

**Comment by wraient** [comment]
no, I can't load marketplace.vscode or any microsoft website by then but now the issue is sorted out. Once I got an pop-up on vs code saying "do you trust this autor of this directory?" I clicked on yes and from then it started working. I live in India and about the browser I guess it was because of release of windows 11 and everyone downloading it and server getting trafficed. so that's it. Thanks for your kind words.
