### ISSUE TITLE
Extension host terminated unexpectedly & User not signed in errors on VS Code

### ISSUE THREAD

**Issue by SamanthaPeterson** [microsoft/vsmarketplace#119]
Issue Type: <b>Bug</b>

"Extension host terminated unexpectedly" and "user not signed in" errors occurring in vs code. 
Any tips or suggestions appreciated. I am running into issues frequently when i try to install new extensions (on vs code). I am not sure what i am doing wrong, pretty new to coding. 
Thank you in advance for any suggestions. 
<img width="594" alt="Screen Shot 2021-07-08 at 4 34 09 PM" src="https://user-images.githubusercontent.com/85209802/124998833-5547dd80-e00a-11eb-831f-6f7b00059162.png">

VS Code version: Code 1.58.0 (Universal) (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:17.694Z)
OS version: Darwin x64 20.5.0
Restricted Mode: No

**Comment by SamanthaPeterson** [comment]
I can't see where to sign in at. I have restarted my computer several times and vs. code. I have tried to disable some of the extensions I installed to see if that would help.

**Comment by isidorn** [comment]
This is a VS Code issue. Thus closing and I suggest you ask this on StackOverflow.
Closing as not Marketplace
