### ISSUE TITLE
Error while installing extensions

### ISSUE THREAD

**Issue by Milayo** [microsoft/vsmarketplace#120]
Issue Type: <b>Performance Issue</b>

I keep getting this error whenever I try to install an extension.

"Error while installing 'Path Autocomplete' extension. Please check the log for more details."

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by isidorn** [comment]
I can not reproduce this. If this is only happening for the Path Autocomplete extension I suggest you file an issue with them
If you see for all extensions please let us know and we will reopen this
