### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by almaskhanwazir** [microsoft/vsmarketplace#121]
Issue Type: <b>Bug</b>

Click on extensions icon, it says 'we cannnot connect  to the extensions marketplace at this time, please try again later.
when i go to marketplace and search extension and click on install it says XHR request failed

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

**Comment by isidorn** [comment]
I can not reproduce this, closing this. And if you have reproducable steps @almaskhanwazir let us know and we can reopen
