### ISSUE TITLE
live serve跳转问题

### ISSUE THREAD

**Issue by Ang-ahao** [microsoft/vsmarketplace#122]
Issue Type: <b>Bug</b>

live server   跳转浏览器 纸条一个页面

VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by isidorn** [comment]
We only support issues in English
