### ISSUE TITLE
Degugging feature cannot open a new browser

### ISSUE THREAD

**Issue by Mathias02** [microsoft/vsmarketplace#126]
Issue Type: <b>Performance Issue</b>

Good day,

I am reporting the debugging option that cannot run a new chrome browser, when trying to reload it gives me this message in the termina; box: crbug/1173575, non-JS module files deprecated.
chromewebdata/(index)꞉7157:22:7146 
please assist

VS Code version: Code 1.58.1 (2aeda6b18e13c4f4f9edf6667158a6b8d408874b, 2021-07-13T06:58:28.115Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by isidorn** [comment]
Not related to the Marketplace, please ask this on StackOverflow. Thus closing
