### ISSUE TITLE
incorrect sort function

### ISSUE THREAD

**Issue by gtumanyan** [microsoft/vsmarketplace#128]
Issue Type: <b>Bug</b>

Open EXTENSIONS: MARKETPLACE, enter a search string, then press Filter Extensions... and select Recently Published
The command entered will be @sort:publishedDate and the message "We cannot connect to the Extensions Marketplace at this time, please try again later." appears.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

![image](https://user-images.githubusercontent.com/24494814/126076432-82c6580f-7f72-401a-8735-b6eb55435851.png)

**Comment by isidorn** [comment]
This should be fixed now
