### ISSUE TITLE
Can't change publisher owner to Google Domain Email(But I've registered it as a Microsoft Account)

### ISSUE THREAD

**Issue by huacat1017** [microsoft/vsmarketplace#129]
**Describe the bug**
I registered a Microsoft Account(using Gmail Domain) and I went to [Marketplace Manage Page](https://marketplace.visualstudio.com/manage) to change Publisher owner to my new account. But when I typed my Email, I got Invalid domain error.

**Screenshots**
![126034073-c13f489e-2f18-49f4-ac5d-9f09f0badcc4](https://user-images.githubusercontent.com/57604590/126253116-f7c28023-4eb6-4dce-873c-76e4b77dd9e6.png)

**Comment by madhurivadaligithub** [comment]
This issue was fixed now with identity, could you please reactive or open new issue if the issue still persists.

Regards,
VS Marketplace team
