### ISSUE TITLE
Create Publisher form broken in Firefox

### ISSUE THREAD

**Issue by mattrossman** [microsoft/vsmarketplace#130]
**Describe the bug**
I cannot publish an extension because the form to create a publisher [from the instructions](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) doesn't work in Firefox

**To Reproduce**

1. In Firefox, visit https://marketplace.visualstudio.com/manage/createpublisher
2. Fill out name and id
3. Click "Create" at bottom

Nothing happens and no errors appear in the console

**Expected behavior**
The form should submit

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 90.0

**Additional context**
The same steps work properly in Microsoft Edge

**Comment by justindbaur** [comment]
Just had the same issue with the following configuration:

* OS: MacOS 12.0 Beta (21A5304g)
* Browser: Firefox
* Version: 92.0 (64 bit)

Switching to Google Chrome worked fine.

**Comment by Neelima10735584** [comment]
Hi @mattrossman,

Thanks for reaching VS Marketplace Team, are you still facing the issue?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
