### ISSUE TITLE
color not found in emmet

### ISSUE THREAD

**Issue by Joshualosasa** [microsoft/vsmarketplace#136]
Issue Type: <b>Feature Request</b>

Hello, today I was planning to start doing some coding for my website, everything started well, however. I encouter an issue. which was the following emmet does  not have color option within it. I was trying to get some colour on my page. but that option does not appear to exist on here. please would fix the issue.

I would highly appreciated it, 

Thank you.

VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by isidorn** [comment]
Not related to marketplace, thus closing
