### ISSUE TITLE
If an extension defines a submenu, it shows up as "undefined" in the Commands section

### ISSUE THREAD

**Issue by ADTC** [microsoft/vsmarketplace#138]
Issue Type: <b>Bug</b>

As an example, view the [Java Code Generators extension (sohibe.java-generate-setters-getters)](https://marketplace.visualstudio.com/items?itemName=sohibe.java-generate-setters-getters) in the Marketplace.

Go to the _Feature Contributions_ tab.

![image](https://user-images.githubusercontent.com/6047296/128415656-5ebc1736-915b-460b-976a-ac22e4af30f8.png)

See that the Commands section has an `undefined` entry. This corresponds to [the "submenu" entry of the package.json file](https://github.com/sohibegit/vscode-java-code-generator/blob/0d00c1e4c1f29e6af1082ef6cdd6035adeaeb606/package.json#L72) in the extension repository.

It will be better displayed as "**Submenu:** `generators/editor/annotations`" with the Description showing the submenu label **"Java Code Generators"**. This will also make it visible that the menu context of several other commands match this submenu entry.

![image](https://user-images.githubusercontent.com/6047296/128415926-589a8787-00c5-4fd6-b59f-d6d6fabfe25e.png)

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by isidorn** [comment]
This is actually a vscode issue.
I suggest to ask a question on StackOverflow since this should just work. 
Closing as this is not a Marketplace issue

**Comment by ADTC** [comment]
> This is actually a vscode issue.
> Closing as this is not a Marketplace issue

@isidorn Kindly update the `README.md` file here to define what qualifies as Marketplace issue and what doesn't. I thought that since this repo is for the Marketplace, it is also the right repo to report bugs with the Marketplace module inside VS Code application. It seems I am wrong.

> I suggest to ask a question on StackOverflow since this should just work.

This doesn't seem like something I'd ask on SO, as it looks like a bug in VS Code that prevents it from displaying **correctly**, rather than a question of how to configure VS Code to display it _as I want it_. Perhaps reporting it to the VS Code repo as a bug is the right course of action?

Thank you anyway 🙂
