### ISSUE TITLE
can't connect to the extensions marketplace

### ISSUE THREAD

**Issue by mr-narendro** [microsoft/vsmarketplace#139]
Issue Type: <b>Bug</b>

how to fix we can't connect to the extensions marketplace at this time, please try again later in visual studio code???

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by amit-kulkarni-in** [comment]
Please reopen the issue if you are still facing connectivity issues to extension marketplace.
