### ISSUE TITLE
VSIX - CLR assembly versioning not working

### ISSUE THREAD

**Issue by tonyhallett** [microsoft/vsmarketplace#149]
**Describe the bug**

Using a [github action](https://github.com/FortuneN/FineCodeCoverage/runs/3360074992?check_suite_focus=true) I have set the version of the vsix according to https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference?view=vs-2019

> Version - Defines the version of this package and its contents. This attribute follows the CLR assembly versioning format: Major.Minor.Build.Revision (1.2.40308.00). A package with a higher version number is considered updates to the package, and can be installed over the existing installed version.

```
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011">
  <Metadata>
    <Identity Id="fcc-f339fe606-9d51-4fca-895c-d50375137b62" Version="1.1.8.143" Language="en-US" Publisher="Fortune Ngwenya" />
```

The VSIX has been published https://marketplace.visualstudio.com/items?itemName=FortuneNgwenya.FineCodeCoverage
But the version showing is the version from the last publish that did not provide a build number.

![image](https://user-images.githubusercontent.com/11292998/129889022-c0e15201-0938-4216-a2cd-8a1541aacb9b.png)

As a result visual studio is not installing the update.

**Expected behavior**
That the version provided is displayed and being used.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 92.0.4515.131

**Comment by tonyhallett** [comment]
@prashantvc

Please can you clarify the marketplace logic that applies.

**Comment by prashantvc** [comment]
On the marketplace we use three part version numbers. We will work with VS extensibility team to address this
For now I am closing the issue
