### ISSUE TITLE
Extension not showing

### ISSUE THREAD

**Issue by ram-digimonk** [microsoft/vsmarketplace#155]
Issue Type: <b>Bug</b>

desplaying message: 'We cannot connet to the extensions Marketplate at this time, please try again later'

and on deveplor console showing error: 
'DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/3866c35…/node_modules/xterm-addon-webgl/lib/xterm-addon-webgl.js.map: Connection error: net::ERR_PROXY_CONNECTION_FAILED'

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by isidorn** [comment]
This is a connection issue. I suggest to try some of the VS Code proxy settings. 
Nothing Marketplace can do here, thus closing
