### ISSUE TITLE
Path suggetion

### ISSUE THREAD

**Issue by navdeep1998** [microsoft/vsmarketplace#157]
Issue Type: <b>Feature Request</b>

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
OS version: Linux x64 5.4.0-80-generic
Restricted Mode: Yes

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
