### ISSUE TITLE
Issue accessing Extention marketplace

### ISSUE THREAD

**Issue by Echelon98** [microsoft/vsmarketplace#158]
Issue Type: <b>Performance Issue</b>

My Extention marketplace is showing we can not connect at the Extention marketplace at the this tme. please try again later

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by amit-kulkarni-in** [comment]
Please reopen the issue if you still observe that you are not able to connect to extension marketplace.
