### ISSUE TITLE
Encourage Posting Issues instead of Reviews

### ISSUE THREAD

**Issue by ntotten** [microsoft/vsmarketplace#16]
Many reviews on the Marketplace for extensions end up being feature requests, issues, or general requests for help. It would be great if the Marketplace encouraged users to post issues or use the correct forums by showing something like the following on the review screen.

![image](https://user-images.githubusercontent.com/282782/108080988-76e5ff80-703e-11eb-94e6-41ed60d07dc8.png)

The Issue URL would be the `bugs.url` property, while the Support URL would be a new `support.url` property.
```
  "bugs": {
    "url": "https://github.com/prettier/prettier-vscode/issues"
  },
  "support": {
    "url": "https://stackoverflow.com/questions/tagged/prettier"
  },
```

**Comment by isidorn** [comment]
This makes sense. Assigning to Backlog.
We plan to do this,
