### ISSUE TITLE
Clicking Support > FAQ in footer takes me to a Azure DevOps extension specific page

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vsmarketplace#162]
**To Reproduce**
1. Go to https://marketplace.visualstudio.com/vscode
2. Click FAQ, it sends you to https://docs.microsoft.com/en-us/azure/devops/marketplace/faq-extensions?view=azure-devops

**Expected behavior**
It shouldn't be there the FAQ isn't relevant to VS Code

**Comment by prashantvc** [comment]
This is something we are working on. Marketplace was (still) part of AzDO, and lot of the documentation links back to AzDO.
This will change gradually :)

**Comment by madhurivadaligithub** [comment]
Hi @Tyriar 

Now the FAQ in footer https://marketplace.visualstudio.com/vscode takes to VS Code extensions related page.

Redirecting page: https://code.visualstudio.com/docs/editor/extension-marketplace

Regards,
VS Marketplace Team
