### ISSUE TITLE
Allow extensions to publish beta releases and users to opt-in to them

### ISSUE THREAD

**Issue by isidorn** [microsoft/vsmarketplace#165]
Originally by @dantup in https://github.com/microsoft/vscode/issues/15756

"Apologies if this has come up before; I'm unable to find any related issues.

It would be cool to be able to publish extensions in a beta form (similar to Code Insiders) so that they can be run "in production" with real users that have opted-in. This would reduce the disk in publishing an extension because you can push it to a smaller number of users for testing (I probably don't need to sell this to you, I guess you have Insiders for very similar reasons).

I know we can package and distribute extensions ourselves for now, but it's not as easy (eg. updating is not automatic).

I originally thought the "Preview" flag might've provided this functionality but unless I've overlooked something, it does not seem to."

---
From @isidorn

Due to the lack of this feature a lot of extensions are publishing two versions: a regular one and a beta one and this is very confusing to the user because:
* These beta extensions do not have consistent naming: `beta`, `nightly`, `insiders`
* The beta extensions have special settings flags that need to be turned on in order for this to work
* Running extensions side by side is a problem

We need a consistent experience.

fyi @alexr00 @connor4312 @eamodio @jrieken as some team members that I know have these insiders extensions and probably know a lot more issues about this.

**Comment by isidorn** [comment]
This is now supported by VS Code. Marketplace still has to support full SemVer for which I believe there is another issue (if not I know @prashantvc has this on the backlog)

**Comment by DanTup** [comment]
I think the relevant issue (for those that want to subscribe) is https://github.com/microsoft/vsmarketplace/issues/50
