### ISSUE TITLE
Cannot install Python extension

### ISSUE THREAD

**Issue by mokari** [microsoft/vsmarketplace#166]
Issue Type: <b>Bug</b>

[error] XHR failed: Error: XHR failed
    at XMLHttpRequest.v.onerror (vscode-file://vscode-app/c:/.../AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:21:11471)

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested.

Thanks,
VS Marketplace Team
