### ISSUE TITLE
Private marketplace support

### ISSUE THREAD

**Issue by isidorn** [microsoft/vsmarketplace#167]
VS Code customers have a need for a private marketplace. Motives:
* They have extensions which they do not want to share publicly (they only make sense for their setup)
* Strict security requirements: want more control over what is available
* Still want all the benefits of a marketplace (nice integration with VS Code, auto update)

**Comment by GitMensch** [comment]
Interesting, I wasn't aware of that, so were on 3 possible vsix providers already.
