### ISSUE TITLE
visual code  crashed on running a leap year program

### ISSUE THREAD

**Issue by domthefam** [microsoft/vsmarketplace#168]
This was my first program("to check weather the year is leap year or not") on visual code after installing it i downloaded its all  necessary extensions but after running  the program it was throwing an error stating "YOU DONT HAVE DOWNOADED THE PLAIN TEXT.EXE EXTENSION"  after the suggestion  to download two new extensions from marketplace it was of no use the same error was showing in my screen.

 

![Screenshot (3)](https://user-images.githubusercontent.com/88775168/131143417-663570de-9eff-4d4f-a3a9-ec9996dde5cf.png)
![Screenshot (4)](https://user-images.githubusercontent.com/88775168/131143431-783d72a9-54a8-4cc6-a896-9f5ff3e6e564.png)
![Screenshot (5)](https://user-images.githubusercontent.com/88775168/131143434-eb22e02c-90ee-4bb0-b66c-cf4c7083ff4c.png)

**Comment by gjsjohnmurray** [comment]
/question

It's now "crashing", but telling you what the problem is. You have written your C program in a file named "leap year.txt" and VS Code thinks it is a "Plain Text" file.

![image](https://user-images.githubusercontent.com/6726799/131486649-4a9706b3-e8c6-4527-a9d4-a996104d7540.png)

**Comment by domthefam** [comment]
thank you sir

**Comment by domthefam** [comment]
> /question
> 
> It's now "crashing", but telling you what the problem is. You have written your C program in a file named "leap year.txt" and VS Code thinks it is a "Plain Text" file.
> 
> ![image](https://user-images.githubusercontent.com/6726799/131486649-4a9706b3-e8c6-4527-a9d4-a996104d7540.png)

thank you sir
