### ISSUE TITLE
New Token not working for vsce publish

### ISSUE THREAD

**Issue by hugos** [microsoft/vsmarketplace#169]
I've created a new PAT to update my vscode theme but when it comes to publish it using `vsce publish` this error follows:

`{"$id":"1","customProperties":{"Descriptor":null,"IdentityDisplayName":null,"Token":null,"RequestedPermissions":0,"NamespaceId":"00000000-0000-0000-0000-000000000000"},"innerException":null,"message":"Access Denied: The Personal Access Token used has expired.","typeName":"Microsoft.VisualStudio.Services.Security.AccessCheckException, Microsoft.VisualStudio.Services.WebApi","typeKey":"AccessCheckException","errorCode":0,"eventId":3000}`

I've really tried a lot of things, but I'm out of ideas and in need of some help.

(The Token has MarketPlace manage and all accessible organisations)

**Comment by GrayJack** [comment]
I'm having the same issue

**Comment by rtlayzell** [comment]
Any update on this?

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
