### ISSUE TITLE
vscode://vscode.github-authentication/did-authenticate?windowid=1&code=3548347a8afb08e7d4ad&state=2e8ca57d-744b-425c-bd06-dc2c2a29e998

### ISSUE THREAD

**Issue by ShenLong03** [microsoft/vsmarketplace#172]
Issue Type: <b>Bug</b>

vscode://vscode.github-authentication/did-authenticate?windowid=1&code=3548347a8afb08e7d4ad&state=2e8ca57d-744b-425c-bd06-dc2c2a29e998

VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, please share a screenshot or any error message to investigate further.

Regards,
VS Marketplace Team
