### ISSUE TITLE
IBM namespace in VSCode Marketplace

### ISSUE THREAD

**Issue by jjasghar** [microsoft/vsmarketplace#176]
Hi! I'm a Developer Advocate for @IBM cloud. 

I work with @stevemar and @christo4ferris to help run the GitHub IBM public org.

It seems there's an intersection between GitHub and the VSMarketplace and we are attempting to organize our internal workflows.

Can we get in contact with who owns the plugins from IBM's namespace? We would like to standardize on things and have no idea who to reach out to.

If you'd like to email me, please don't hesitate to email me at <jja@ibm.com>.

**Comment by prashantvc** [comment]
Hey there,
I am a PM on the VS Marketplace team.
Could you email me the details at prchol@microsoft.com
