### ISSUE TITLE
ES7

### ISSUE THREAD

**Issue by keke524** [microsoft/vsmarketplace#178]
Issue Type: <b>Bug</b>

搜索ES7显示无法连接！！

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by amit-kulkarni-in** [comment]
Please re-open the issue if you are still facing challenges to connect to VS Marketplace.
