### ISSUE TITLE
扩展市场提示无法连接

### ISSUE THREAD

**Issue by Wangsd823** [microsoft/vsmarketplace#179]
Issue Type: <b>Bug</b>

正常使用，每一天突然间不好用，这段时间没有做任何配置的修改

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by amit-kulkarni-in** [comment]
Please re-open the issue if you are still facing the bug in the latest version.
