### ISSUE TITLE
Add Extensions Extended Info

### ISSUE THREAD

**Issue by dasaveliev** [microsoft/vsmarketplace#18]
**### THE PROBLEM**
Not a rare situation when for an extension has lots of installs, 5 stars, BUT it is outdated and rated by a small percent of users. To find this out we have to do an additional manual research which can easily be eliminated and make extensions info more representative.

**### PROPOSED SOLUTION**
When browsing Extensions, add the following info:
1. Deinstallations count
    To understand the level of real usability
2. Rated by users (qty of users rated an Extension) - add text info
    The hover popup is not enough, need to have this info in the list and in the Extension details page
3. The date of the last update
    Please add this info next to the build state.

**Comment by isidorn** [comment]
Closing as there are other issues that cover this.
