### ISSUE TITLE
无法连接到扩展商店, 请稍后重试

### ISSUE THREAD

**Issue by keyasu** [microsoft/vsmarketplace#180]
Issue Type: <b>Bug</b>

正在用的好好的 , 显示  无法连接到扩展商店, 请稍后重试  网络没有问题,  已经安装的可以查看详情

正在用的好好的 , 显示  无法连接到扩展商店, 请稍后重试  网络没有问题,  已经安装的可以查看详情

正在用的好好的 , 显示  无法连接到扩展商店, 请稍后重试  网络没有问题,  已经安装的可以查看详情

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

**Comment by amit-kulkarni-in** [comment]
Please re-open the issue if you are still facing connectivity challenges to VS Marketplace.
