### ISSUE TITLE
扩展市场没办法搜索

### ISSUE THREAD

**Issue by Eiffelyk** [microsoft/vsmarketplace#181]
Issue Type: <b>Bug</b>

扩展市场不能搜索

VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by amit-kulkarni-in** [comment]
Please re-open the issue if you are still facing challenges to connecting and searching on VS Marketplace extension store.
