### ISSUE TITLE
连接不上扩展商店

### ISSUE THREAD

**Issue by tpxiang** [microsoft/vsmarketplace#183]
Issue Type: <b>Bug</b>

在扩展商店搜索插件，提示连接不上应用商店

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by amit-kulkarni-in** [comment]
Please re-open the issue if you are still having connectivity issues with the search for VS marketplace .
