### ISSUE TITLE
Not Updating Or Installing!

### ISSUE THREAD

**Issue by G00Dway** [microsoft/vsmarketplace#184]
Issue Type: <b>Performance Issue</b>

Hello! i Saw a Bug Here! This MarketPlace is Not Updating Or Installing The "Jupyter" Extension! Please Fix That! 

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by amit-kulkarni-in** [comment]
Please re-open the issue if you still facing any performance issue in updating or installing the extension.
