### ISSUE TITLE
Issues connecting to Marketplace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vsmarketplace#185]
Users are getting CORS issues connecting to Marketplace.

https://github.com/microsoft/vscode/issues/132634
https://github.com/microsoft/vscode/issues/132716
https://github.com/microsoft/vscode/issues/132661

**Comment by prashantvc** [comment]
Apologies for the issue. We have rolled back our changes. You should be able to access the marketplace now. We are currently investigating the root cause

**Comment by sandy081** [comment]
Closing this as the original vs code issue is moved here - https://github.com/microsoft/vsmarketplace/issues/186
