### ISSUE TITLE
Search extension is broken, cannot find the extension!!

### ISSUE THREAD

**Issue by acfuns** [microsoft/vsmarketplace#186]
- VS Code Version: 1.6.0
- OS Version: window11

Problem description:
On the afternoon of September 8, 2021, when I was downloading the plugin for work, I was informed by the search: I cannot connect to the extension mall now, please try again later.

**Comment by ruon1804** [comment]
I have same issue today. Please re-check it. Thanks.

```
Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631
```

![image](https://github.com/user-attachments/assets/eb1507c6-bd3a-4957-a715-6a76bdacc692)
