### ISSUE TITLE
Remote SSH stopped working in VS Code Insiders

### ISSUE THREAD

**Issue by lucasthim** [microsoft/vsmarketplace#187]
Issue Type: <b>Bug</b>

Hi, 

the Remote SSH connection stopped working yesterday. I haven't done any update or installed anything from the market place. I try to connect and it says "Could not establish connection to "xx.xx.xx.xxx": Connecting with SSH timed out". 

I tried downgrading the Remote  - SSH extension version from 0.65.7 to 0.65.6 and it did not work. Also, I can confirm I am able to connect to the remote server from my computer, for I am using a regular windows cmd terminal. Also, I tried connecting with regular VS Code with the same 0.65.7 Remote - SSH version, and it worked.

Thanks.

VS Code version: Code - Insiders 1.61.0-insider (aa93eefe550167de3ca29aaa3d06f721a47594a3, 2021-09-09T05:15:19.597Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Fetching remote diagnostics for 'SSH' failed: Connecting with SSH timed out

**Comment by Neelima10735584** [comment]
Hi,

Thank you for reaching out to the VS Marketplace Team. Please note that remote connections have certain time limits within network connections. If you encounter any further issues, do not hesitate to contact us.

Regards,
VS Marketplace Team
