### ISSUE TITLE
live server extension

### ISSUE THREAD

**Issue by BadKarma187** [microsoft/vsmarketplace#189]
Issue Type: <b>Bug</b>

I have installed an live serer extension but it is not being active

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching out to the VS Marketplace Team. This issue has been resolved, and the mentioned extension is now active in the VS Marketplace. Please let us know if you encounter any further issues.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
