### ISSUE TITLE
remote-ssh can't make project

### ISSUE THREAD

**Issue by gigss** [microsoft/vsmarketplace#190]
Issue Type: <b>Bug</b>

host: ubuntu16.04
build linux-4.9,terminal will hang.  debug info as below:
make[5]: Entering directory `/my path/linux-4.9'
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/bounds.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CHK     scripts/mod/devicetable-offsets.h
then terminal hang here, normally, next step is Building modules by make)
but in other terminal, for example, xshell or finalshell, it can work.
  

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No
Remote OS version: Linux x64 4.15.0-112-generic

**Comment by Neelima10735584** [comment]
Hi @gigss ,

Thank you for opening the issue. Sorry to hear you are experiencing an issue with searching. It appears to be specific to VS Code editor and tools we understand correctly. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
