### ISSUE TITLE
Finishing VS Live share installation

### ISSUE THREAD

**Issue by rushikamod28** [microsoft/vsmarketplace#191]
Issue Type: <b>Bug</b>

I want to run c++ code on VS code but the code can't run
insted my antivirus said that any virus detected in it.
I have downloaded all required applications and extentions on my pc to run c++ code 
plz solve my issue as soon as possible

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi @rushikamod28,

Thanks for reaching VS Marketplace Team, If the error is still persisting, please share any error message or screenshot to investigate better.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
