### ISSUE TITLE
I can't save my feedback in Azure DevOps marketplace, why?

### ISSUE THREAD

**Issue by DevOps-zhuang** [microsoft/vsmarketplace#192]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by madhurivadaligithub** [comment]
Hi @DevOps-zhuang 

Thanks for providing details, are you still facing the issue?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
