### ISSUE TITLE
Cannot connect to marketplace

### ISSUE THREAD

**Issue by diksha0492** [microsoft/vsmarketplace#194]
Issue Type: <b>Performance Issue</b>

1. Open VS code.
2. Go to Extensions tab and type 'Salesforce extension' on the search box.
3. Click on enter. Error gets generated  - 'Cannot connect to the marketplace at this time.'
<img width="770" alt="VSCode error" src="https://user-images.githubusercontent.com/59659185/134472190-b706b254-2eec-4501-9b65-7b8308867f3f.PNG">

VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:07:10.714Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by amit-kulkarni-in** [comment]
Please re-open the case if you are still seeing the issue in your VS Code client.
