### ISSUE TITLE
C# Compiling

### ISSUE THREAD

**Issue by jfouryeah12** [microsoft/vsmarketplace#195]
Issue Type: <b>Bug</b>

Cannot compile cscs.runtimeconfig.json' was not found.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi @jfouryeah12,

Thanks for reaching VS Marketplace Team, If the error is still persisting, please feel free to reach out to us.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
