### ISSUE TITLE
Advanced extension search (for example excluding certain words)

### ISSUE THREAD

**Issue by hex13** [microsoft/vsmarketplace#20]
Having option to search for an extension in Marketplace is nice, but it would be nicer if I could make some more sophisticated search, e.g. excluding something words from results.

For example, I'm looking for `redux` related extension

![image](https://user-images.githubusercontent.com/3883359/39709215-970c5070-5219-11e8-9ca7-3c3bc47b5b03.png)

Most of these extensions are snippets, so I would like to filter them out (I don't need snippets), I tried something like this:

`redux -snippets` (extensions containing `redux`, but not `snippets`)

but this apparently does not work.

Is there a possibility to add such feature to VSCode in future versions?

**Comment by MostHated** [comment]
I am interested in this as well.

**Comment by rafasoares** [comment]
I'd like to add, since now we have support for `@category` filters, being able to exclude categories would be awesome!

Something like `foo -@category:themes`.

Thanks!

**Comment by anangaur** [comment]
Can we dupe this to #154? Is this issue represented in the list on that issue? /cc: @prashantvc @isidorn

**Comment by isidorn** [comment]
I would prefer if we leave this open, since #154 points to this issue for more details.
However I know that @SaiKanth007 and Karan Jain have done improvements to the extension search and one of the improvements was support for excluding words. Once that ships we can go ahead and close this issue.

**Comment by codedChaos** [comment]
> I would prefer if we leave this open, since #154 points to this issue for more details.
> However I know that @SaiKanth007 and @kj0171 have done improvements to the extension search and one of the improvements was support for excluding words. Once that ships we can go ahead and close this issue.

don't suppose we have access to compile those patches and test them on our own?

**Comment by isidorn** [comment]
@codedChaos unfortunately not right now. However I expect VS Code insiders to have these changes some time in September.

**Comment by FractalHQ** [comment]
@isidorn What is the pattern for this?  I'm trying to show installed extensions, excluding themes.  However, in the latest vscode-insiders:

`@installed -@category:"themes"` -> only shows (installed) themes
`@installed -@themes` -> `No extensions found.`
`-@category:"themes"` -> `No extensions found.`

**Comment by kj0171** [comment]
@installed filter is managed by vscode editor because marketplace has no information about installed extensions on any vscode editor. Hence, any filter applied along with @installed doesnot reach marketplace search service. @sandy081, please correct me if i am wrong.

Term Inclusion/Exclusion introduced as part of relevancy improvements are only part of search text and not filter.

eg: js snippet -theme (Exclude the results having theme in their meta data).
Please refer to this for details about the enhancements. (https://github.com/microsoft/vsmarketplace/issues/154#issuecomment-1285224069)

**Comment by xmaxrayx** [comment]
is this been supported or not yet? if yes can someone tell me how to exclude ?

**Comment by rafasoares** [comment]
> is this been supported or not yet? if yes can someone tell me how to exclude ?

Currently (`v1.92.2`), it works for keywords (e.g. `github -copilot`), but not for advanced filters like `@category:*` or `@installed`.

**Comment by gerroon** [comment]
This is really sad, we still don't have a way to exclude the themes from the extensions tab.
