### ISSUE TITLE
Cannto Connect to the Extension Marrketplace

### ISSUE THREAD

**Issue by afqAhmed** [microsoft/vsmarketplace#201]
Issue Type: <b>Feature Request</b>

Cannot install any extensions at all

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, If the error is still persisting, please share a screenshot or any error message to investigate further.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
