### ISSUE TITLE
Não consigo instalar extensões

### ISSUE THREAD

**Issue by RobsonPMoraes** [microsoft/vsmarketplace#202]
Issue Type: <b>Bug</b>

Bom dia, me chamo Robson.

Sou estudante de Análise e Desenvolvimento de Sistemas, mas não tenho muito conhecimento sobre informática.
Utilizo o VSCode como programa para programar, mas hoje, notei que não consigo instalar mais nenhuma extensão. Não sei se foi alguma coisa que alterei e não consigo reverter.

Desinstalei o aplicativo e o instalei novamente, mas veio com as mesmas configurações anteriores.

Como dou um reset nas configurações que alterei? É possível isso?

Desde já agradeço a atenção.

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
