### ISSUE TITLE
not connect to internet

### ISSUE THREAD

**Issue by niki1312** [microsoft/vsmarketplace#203]
Issue Type: <b>Bug</b>

i am trying to install extentions from marketplace but there is error like " we cannot connect to marketplace at this time, please try again later"

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace, please share error message or screenshot to investigate better.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
