### ISSUE TITLE
bug in live installer

### ISSUE THREAD

**Issue by JeeshaanBakshi** [microsoft/vsmarketplace#204]
Issue Type: <b>Bug</b>

pls help me i having a lot of problem in live installer pls revert back to me asap 
i have to reload my page again and again to see the changes i have done in my html and css code 

VS Code version: Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e, 2021-09-22T12:00:31.514Z)
OS version: Windows_NT x64 10.0.22468
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. now we are unable to see the extension in vscode. If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
