### ISSUE TITLE
Attempting to update extensions, getting error about rate limit

### ISSUE THREAD

**Issue by bbarry** [microsoft/vsmarketplace#208]
Issue Type: <b>Bug</b>

2 extensions have update in VS Code and are failing to update.

Attempting to update them manually brings me to a page that returns the following json:

{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}

This error is unhelpful because it doesn't give me direction on how to fix the issue.

VS Code version: Code 1.61.0 (ee8c7def80afc00dd6e593ef12f37756d8f504ea, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by k8rina** [comment]
+1 I am attempting to downlaod some externsion and I keep getting the error log

{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}

I am running a linux redhat

**Comment by KB3HNS** [comment]
+1 I have been getting this for several days trying to update Extension Pack for Java 0.25.1.  This seems to only affect certain plugins.
Clarification on the experience:  Attempt to update directly fails with a dialog box stating "Error while updating <package name> extension.  Please check log for more details."  With a button "Try Downloading Manually...".  Clicking the button launches the system web browser and the page is th
[VS Code Java Extension Update Failed.txt](https://github.com/microsoft/vsmarketplace/files/9462195/VS.Code.Java.Extension.Update.Failed.txt)
at down in issue report.

I am attaching the log file referenced with identifying information redacted.

**Comment by DualityStudios** [comment]
+1 I have encountered this error only on *some* extensions. I have the exact same experience as @KB3HNS. When I click "Try Downloading Manually..." I get the following error (at the webpage):
```
{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}
```

**Comment by Neelima10735584** [comment]
Hi,

Thank you for contacting the VS Marketplace Team. The issue has been resolved, and we have updated the error messages on VS Marketplace. If the error persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
