### ISSUE TITLE
I can't publish my extension on site

### ISSUE THREAD

**Issue by BruceQiu1996** [microsoft/vsmarketplace#209]
i wanna publish my extensions ,but get this error refuse my submit.
![image](https://user-images.githubusercontent.com/28331315/137586232-a33f0548-93ca-461d-9244-d037ebbc7890.png)

**Comment by Neelima10735584** [comment]
Hi @BruceQiu1996,

Thanks for reaching VS Marketplace Team, are you still facing the issue?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @BruceQiu1996 ,

Apologies for the delay, we haven’t seen your publisher created on the Marketplace yet. Could you please create the publisher now and let us know if you encounter any issues?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
