### ISSUE TITLE
Marketplace:  "Manage Extension" is broken for golang.go

### ISSUE THREAD

**Issue by hyangah** [microsoft/vsmarketplace#215]
I cannot see acquisition nor user reviews from the https://marketplace.visualstudio.com/manage/publishers/... pages.  I can see the extension publishing history page though. `golang.go-nightly` works, so I suspect it is related to the extension renaming as seen in  https://github.com/microsoft/vscode/issues/76253.

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
