### ISSUE TITLE
Error while publishing an extension to vscode marketplace

### ISSUE THREAD

**Issue by homeboy445** [microsoft/vsmarketplace#216]
I'm getting an error while publishing my extension on vscode marketplace and it goes like `ERROR: Specified part does not exist in the package`.

Steps I followed which led to this error:
1.) I generated my extension using yo code.
2.) Made my changes.
3.) Then I provided my PAT to the vsce login and it succeeded.
4.) Afterwards that, I went with the command `vsce publish` which resulted in `ERROR: Specified part does not exist in the package.`
I tried changing several options in my package.json but got no luck with that.

**Info**
 - OS: Ubuntu 20.04 LTS
 - VS code version: 1.61.0

Here's the link to my extension's repository: https://github.com/homeboy445/auto-Include

Edit: I managed to get it to work by packaging it & then uploading it to the marketplace directly. Although I'm still unable to even package my extension in Ubuntu, however, I packaged my extension on windows 10 & it worked.

**Comment by Neelima10735584** [comment]
Hi @homeboy445,

Apologies for the delay, If the issue still persists, could you please reach out to us via [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com)

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
