### ISSUE TITLE
CoffeeScript Language Support

### ISSUE THREAD

**Issue by n-are-n** [microsoft/vsmarketplace#218]
Issue Type: <b>Bug</b>

There is no support for CoffeScript Language. Provide an extension for the CoffeeScript.

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.22478
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. now we are able to see Coffee script extensions in Marketplace. If you are still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
