### ISSUE TITLE
Support `generic` platform for extensions

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vsmarketplace#219]
While the `vsce` allows publishing to [many platforms at one-shot](https://github.com/microsoft/vscode-vsce/issues/625), this would still require the extension authors to keep their list of platforms in sync (i.e. updated). If any new platform is added, their extension would not be available for download in there unless they add this platform to the publish list, even though the extension itself would actually work as the code is platform-agnostic.

The support for a platform named `generic` would solve this issue, and this is how I believe the VS Marketplace should handle its presence:

1. If an extension for the same platform is published, use it.
2. Otherwise, fallback to `generic` platform

Refs https://github.com/microsoft/vscode-vsce/issues/625#issuecomment-949607554
Refs https://github.com/microsoft/vscode/issues/23251#issuecomment-941063232
Refs https://github.com/microsoft/vscode/issues/23251#issuecomment-920032324

**Comment by felipecrs** [comment]
@joaomoreno any chance this should go to vsce repo instead?

**Comment by joaomoreno** [comment]
No, support must come from the Marketplace. VSCE is just a tool which operates against it.

**Comment by felipecrs** [comment]
Right. Thank you!

**Comment by SaiKanth007** [comment]
@felipecrs Yes and I think VSCode Client is already doing it. @sandy081 correct me if my understanding is wrong.
