### ISSUE TITLE
i cant install any extension

### ISSUE THREAD

**Issue by sylvie-codes** [microsoft/vsmarketplace#228]
Issue Type: <b>Performance Issue</b>

I can't install any vs code extensions

VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 6.3.9600
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
