### ISSUE TITLE
In WIN10, My ICON is LOST when I Scroll

### ISSUE THREAD

**Issue by YangsonHung** [microsoft/vsmarketplace#233]
- VS Code Version:
- OS Version:
![image](https://user-images.githubusercontent.com/32238889/138555583-ffc374d3-d1dc-450a-83ff-9d096f68ab39.png)

Steps to Reproduce:

1. install a new vscode
2. open vscode's extensions shop
3. search a name and scroll
4. open extensions side bar, icon will also disappear  
![image](https://user-images.githubusercontent.com/32238889/138555551-d847ea17-1646-472a-a38b-203ef873133d.png)

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
