### ISSUE TITLE
Cannot reply comment for years

### ISSUE THREAD

**Issue by heku** [microsoft/vsmarketplace#236]
Hi,

I cannot reply to any comment in vs marketplace for years, seems it's caused by some resources cannot be loaded successfully. 
I understand this maybe cause by our country's network limitations, it's still very appreciated if you could make it works.

![issue](https://user-images.githubusercontent.com/3367199/140597451-ca55aa1a-563c-481c-9979-436128a68a6d.png)

**Comment by madhurivadaligithub** [comment]
Hi @heku ,

Thanks for reaching VS Marketplace Team, are you still facing the issues?

Regards,
VS Marketplace Team

**Comment by heku** [comment]
Tks, the issue is gone, let me close this.
