### ISSUE TITLE
VALIDATION IS STUCKED

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/vsmarketplace#24]
My extension Patch is still being verified. It has been in this state for around 14 hours!
Also, the number of downloads Spicked from 18k to 108k, which indicates the validation bot is in an infinite loop.

https://marketplace.visualstudio.com/items?itemName=allanoricil.salesforce-soql-editor

![image](https://user-images.githubusercontent.com/55927613/100748179-ebfc4e00-33da-11eb-9612-2620cbd4a5be.png)

**Comment by isidorn** [comment]
Closing as outdated

**Comment by AllanOricil** [comment]
and it never happened again. So I think you guys are good.
