### ISSUE TITLE
Error in installing extensions  

### ISSUE THREAD

**Issue by niki1312** [microsoft/vsmarketplace#240]
Issue Type: <b>Bug</b>

my vs code give an error like " Error while fetching extensions.XHR failed
currently I uninstall vs code completely on my system and again reinstall it but it still there what should i do..
please help me in this

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

**Comment by mirzaghalib4726** [comment]
Yes!!!
C/C++ Extension Pack is not installing on Ubuntu Distro
Error: connect ECONNREFUSED 72.21.80.5:443

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested.

Thanks,
VS Marketplace Team
