### ISSUE TITLE
Error upgrading to VSCode 1.62, solved by disabling extensions

### ISSUE THREAD

**Issue by GurinIAstate** [microsoft/vsmarketplace#241]
Issue Type: <b>Bug</b>

While updating to Visual Studio Code 1.62 my install repeatedly ended up bricked, needing me to run the uninstaller and reinstall VSCode. Using the new installer wouldn't allow installation, I had to use a previous version, which only worked AFTER I deleted the VSCode folder in Program Files (Where I have it installed). Repeated attempts to update would spit out undescriptive errors and stop VSCode from working at all. There would also somtimes be issues that prevented installation as well, but I don't know what- typically they say that the installation is not allowed due to preexisting files, and the problem tends to go away when restarting the PC. Disabling all my extensions allowed me to safely update, but none of them should have been running something while VSCode was updating, aside from my cosmetic extensions.

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi @GurinIAstate,

Thank you for opening the issue. Sorry to hear you are experiencing an issue with searching. It appears to be specific to VS Code editor and tools we understand correctly. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
