### ISSUE TITLE
Extensions Error

### ISSUE THREAD

**Issue by mirzaghalib4726** [microsoft/vsmarketplace#242]
Issue Type: <b>Bug</b>

It is not allowing my to install extension
C/C++ Extension Pack in the Ubuntu System.
connect ECONNREFUSED 72.21.80.5:443

VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

**Comment by Neelima10735584** [comment]
Hi 

Thank you for opening the issue. Sorry to hear you are experiencing an issue with searching. It appears to be specific to VS Code editor and tools we understand correctly. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
