### ISSUE TITLE
INSTALLED label over the extension name

### ISSUE THREAD

**Issue by shizlie** [microsoft/vsmarketplace#244]
Issue Type: <b>Bug</b>

Go to Extensions tab
Under INSTALLED label, there is extension name behind

<img width="335" alt="Screen Shot 2021-11-11 at 18 03 45" src="https://user-images.githubusercontent.com/32748490/141287420-ac073b8d-12b2-4561-8d64-0fb5e489157d.png">

VS Code version: Code 1.62.1 (Universal) (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T09:23:14.144Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
