### ISSUE TITLE
Live Server

### ISSUE THREAD

**Issue by AJ-Coder11** [microsoft/vsmarketplace#245]
Issue Type: <b>Bug</b>

Live Server is not showing up as an option on VS Code anymore. I don't know how to fix it, but just please fix it fast.

VS Code version: Code 1.61.2 (Universal) (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T15:49:28.381Z)
OS version: Darwin x64 17.7.0
Restricted Mode: No

**Comment by prashantvc** [comment]
This looks like vscode issue. You may want to file it at https://github.com/microsoft/vscode/issues
