### ISSUE TITLE
Vs2022 extensions not accessible to users from the main gallery page

### ISSUE THREAD

**Issue by VisualMicro** [microsoft/vsmarketplace#250]
Can we please either switch over to vs2022 or provide link for users to click that shows the extensions for vs2022.

Currently the visual studio extensions are the 2017/2019 extensions.

https://marketplace.visualstudio.com/

Labelled as a bug but it's more of an oversight since vs2022 is now the official IDE.

Thanks

**Comment by amit-kulkarni-in** [comment]
Thanks for sharing the feedback. We have fixed the "See More" to provide the search access to VS 2022 extension in home page.  https://marketplace.visualstudio.com/search?sortBy=Installs&category=All%20categories&target=VS&vsVersion=vs2022

Please let us know if there are any other concerns.
