### ISSUE TITLE
Adding verified domain with `.com.br` returns error `Url should not contain subdomains including "www"`

### ISSUE THREAD

**Issue by microhobby** [microsoft/vsmarketplace#251]
**Describe the bug**

I'm trying to add my domain https://microhobby.com.br/ to verify my extensions ownership but the platform seems to be detecting `.br` as a subdomain. So, I'm getting the error `Url should not contain subdomains including "www"` when I hit the save button.

**To Reproduce**
1. Go to Manage Publishers & Extensions
2. Click on Publisher details
3. Set the Verified Domain field to any ".com.br" domain
4. Save
5. See error

**Expected behavior**

Be able to use ".com.br" domains to verify ownership.

**Desktop (please complete the following information):**
 - OS: Windows 11 Dev Channel
 - Browser Microsoft Edge
 - Version 95.0.1020.53 (Official build) (64-bit)

**Comment by microhobby** [comment]
@roblourens @prashantvc I still don't know if this is something wrong on my side or on your side. In my opinion ".com.br" domains should also be valid and your verification is wrong, thinking that .br is a subdomain instead of a country code.

**Comment by prashantvc** [comment]
This sounds like a bug to me; we are going to pick it up for next sprint. Thanks for reporting :)

**Comment by rheajain** [comment]
@prashantvc As per this RFC https://datatracker.ietf.org/doc/html/rfc1034#:~:text=A%20domain%20is,D%2C%20D%2C%20and%20%22%20%22.
 
In this url:
br is the Top level domain
com is the primary domain
microhobby is the subdomain

So this error is expected. Please correct me if I'm wrong.

**Comment by ChrisBibby** [comment]
Having the same issue with a .co.uk domain.

**Comment by microhobby** [comment]
> @prashantvc As per this RFC https://datatracker.ietf.org/doc/html/rfc1034#:~:text=A%20domain%20is,D%2C%20D%2C%20and%20%22%20%22.
> 
> In this url: br is the Top level domain com is the primary domain microhobby is the subdomain
> 
> So this error is expected. Please correct me if I'm wrong.

No, this error is not expected. "com.br" as "co.uk" are the Top level domain (TLD) in this case. Look this RFC https://datatracker.ietf.org/doc/html/rfc1591#section-2

**Comment by melMass** [comment]
I have the same issue with a .com ...
![image](https://user-images.githubusercontent.com/7041726/149797130-7ef1c78a-a0af-4b0e-bbd7-23ecadccf0df.png)

**Comment by microhobby** [comment]
I'm closing this because it's now working. I was able to verify my `.com.br` domain.
