### ISSUE TITLE
Unable to view extension acquisition

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vsmarketplace#252]
**Describe the bug**
When I try to view the acquisition trend for my extension (https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql) I just get this error 

![image](https://user-images.githubusercontent.com/28519865/142468921-b775b7e9-3497-4066-8c4d-af46fb1656b6.png)

(I've waited at least 15min and it's still showing)

**To Reproduce**
1. Go to https://marketplace.visualstudio.com/manage/publishers/ms-mssql/extensions/mssql/hub?_a=acquisition
2. Error is shown instead of acquisition graph

**Additional context**

And when I try to export I see this error 

`{"$id":"1","innerException":null,"message":"Version string portion was too short or too long.","typeName":"System.InvalidOperationException, mscorlib","typeKey":"InvalidOperationException","errorCode":0,"eventId":0}`

The extension

**Comment by SaiKanth007** [comment]
This is fixed now. Hence closing it.
