### ISSUE TITLE
Published a version, unpublished it, then made a code change and republished it with the same version number.  VSCode Extension install is not picking up the newer published version.

### ISSUE THREAD

**Issue by davidkjackson54** [microsoft/vsmarketplace#253]
I published n Extension version 1.0.2 with a specific Publisher value in the package.json. Then I unpublished it 5 minutes later, made a code change to alter the publisher to our company standard,  rebuilt the VSIX and republished with the same version number. 

I then attempted to install this new published version from within VSCode  but VSCode appears to be caching the older version and installed that instead.   
I went to the Marketplace website for the extension - where you have the option to Install the Extension or 'Download Extension"  
I chose now to download the Extension and a new VSIX File was downloaded to my desktop. 
I then proceeded to install that VSIX and it works fine and it has the correct publisher value.

After 4 hours, I tried to install the Extension via VSCode again and it still fails by picking up some older cached version.

It does appear that publishing, then unpublishing and republishing with the same version number does cause VSCode some grief but it should still permit it having unpublished the original.  I can find no documentation on this issue. 
 
Having installed the extension from within VSCode , I  went to the .vscode directory on my laptop  and looked at the code that was installed and sure enough it was the code prior to my code change. 

**Desktop (please complete the following information):**
 - OS:  Windows 10 
 - Browser Edge
VSCode version : 1.62.3

**Comment by madhurivadaligithub** [comment]
Hi @davidkjackson54 ,

Thanks for reaching VS Marketplace Team, are you still facing the issue?

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Hi @davidkjackson54,

Since we have not received any response from you, we are closing the issue. If the issue still persists, please reopen or create a new request.

Regards,
VS Marketplace Team
