### ISSUE TITLE
Verify publisher fails - The domain url provided could not be reached

### ISSUE THREAD

**Issue by antonbabenko** [microsoft/vsmarketplace#254]
Trying to [verify publisher](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher), typing various "Domain names" in "Verified domains" (e.g. `https://modules.tf`) I constantly get the same error:
```
The domain url provided could not be reached
```
Full response:
```
{"$id":"1","innerException":null,"message":"The domain url provided could not be reached","typeName":"System.ArgumentException, mscorlib","typeKey":"ArgumentException","errorCode":0,"eventId":0}
```

I tried with other `.com` domains I own and always got the same error.

Looks like a bug. Please help.

**Comment by isidorn** [comment]
@roblourens I have moved the issue to the `vsmarketplace` repo.
@rheajain and @chgill-MSFT can investigate more.
Thanks!

**Comment by antonbabenko** [comment]
Thanks @roblourens for the information. I will see what I can do to change this on my hosting provider.

**Comment by antonbabenko** [comment]
The problem has been fixed by my hosting provider.

**Comment by BartNetJS** [comment]
I have a domain that gives a 200 on a head request, but still give the error message ''The domain url provided could not be reached"
What else can be wrong?

**Comment by isidorn** [comment]
@BartNetJS I think it would be best if you simply open a new issue. Thank you

**Comment by david-sandy** [comment]
> @antonbabenko you are getting this error because as part of validating a genuine domain URL, we are making a HEAD request and validating that we get an OK response. I see that on making that HEAD request we get 405 response from the URL.

Do we have the ability to modify where it looks for the validation?  I don't know much about how this works.

**Comment by bobmagicii** [comment]
greetings from 2026 ffs.

first i had to use edge just to get the save button to work.

i have tried 3 domains on 2 different hosts. it does not work.

<img width="546" height="555" alt="Image" src="https://github.com/user-attachments/assets/9850e5f0-f99e-4a61-bfb4-9e4603ce9928" />

**Comment by mariaghiondea** [comment]
Please reach out to Visual Studio Marketplace Support <VSMarketplace@microsoft.com> if you are having issues. These need to be individually worked through since each case is different.
