### ISSUE TITLE
developer

### ISSUE THREAD

**Issue by Shaikh-Aman-github** [microsoft/vsmarketplace#255]
Issue Type: <b>Feature Request</b>

I am facing isuess with my marketplace. it is not working 

VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 6.3.9600

**Comment by rheajain** [comment]
@Shaikh-Aman-github are you not able to view extensions on VS Code?
Can you share a screenshot if possible?

**Comment by Shaikh-Aman-github** [comment]
yes of course - Rhea Jain,

below attaching...

[image: image.png]

-I had also tried to re-install it.
-Also checked my internet connection

it is always showing "try again later"


Thanks, *Rhea Jain*, for your response to my issues.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Shaikh-Aman-github** [comment]
I have created the ticket around 2 years ago,

At that time the issue was not resolved but I changed the laptop :-)
working fine now 😀

thanks for your instant/quick replay, appreciated

**Comment by Neelima10735584** [comment]
Apologies for the delay and thanks for the update. Please feel free to contact us if you are facing any issues.

Regards,
VS Marketplace Team
