### ISSUE TITLE
Unable to verify publisher via marketplace

### ISSUE THREAD

**Issue by AlencarGabriel** [microsoft/vsmarketplace#256]
Does this issue occur when all extensions are disabled?: -

- VS Code Version: - 
- OS Version: - 

I followed the procedures outlined in the publisher's verification documentation (https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher), but marketplace is unable to verify my domain's DNS.

Note: It has been more than 72 hours since the addition of the TXT record in DNS.

![image](https://user-images.githubusercontent.com/10109480/142913089-a84a69ca-3ab2-4de4-9867-aaf1f2e0d6f1.png)

![image](https://user-images.githubusercontent.com/10109480/142912976-6a89b3a9-2704-4d5b-b8f6-f86c82ed280d.png)

**Comment by rheajain** [comment]
@AlencarGabriel what is your publisher name?

**Comment by AlencarGabriel** [comment]
My publisher name is **AlencarGabriel** (https://marketplace.visualstudio.com/publishers/AlencarGabriel)

**Comment by rheajain** [comment]
@AlencarGabriel I see that your TXT record has the wrong Key.
The Key is supposed to be- `_visual-studio-marketplace-alencargabriel.gabrielalencar.dev` and you have stored it as- `_visual-studio-marketplace-alencargabriel.gabrielalencar.dev.gabrielalencar.dev`
There is an extra `.gabrielalencar.dev` in the record's Key.

**Comment by AlencarGabriel** [comment]
How strange, where did you get this information?

In my DNS zone the host registered is exactly as expected: `_visual-studio-marketplace-alencargabriel.gabrielalencar.dev`

**Comment by antonbabenko** [comment]
@AlencarGabriel Here you can verify that it is set for the wrong domain - https://www.whatsmydns.net/#TXT/_visual-studio-marketplace-alencargabriel.gabrielalencar.dev.gabrielalencar.dev

DNS providers often add domain names to the record, so you need to edit it and it should be visible here - https://www.whatsmydns.net/#TXT/_visual-studio-marketplace-alencargabriel.gabrielalencar.dev

**Comment by AlencarGabriel** [comment]
I managed to perform the domain verification.

I don't know if this behavior is just Godaddy's behavior, but it looks like they themselves add the `.gabrielalencar.dev` to the end of the host, causing duplication.

I changed the TXT record in DNS to `_visual-studio-marketplace-alencargabriel` and it worked.

Thanks for the tip @antonbabenko and @rheajain for support.

**Comment by manifestinteractive** [comment]
It looks like this is actually an issue with the instructions in VS Code.  They should probably give you different instructions based on domain registrar.  The instructions you can copy and paste, as well as the instructions in the modal that pops up had the same instructions that included the domain suffix at the end.  Removing that from my domain verification hostname solved my problem of not being able to validate even though the DNS was correct ( according to instructions ).

**Comment by DetachHead** [comment]
this happens with namecheap too. it's especially annoying that it tells you to wait 72 hours when in my experience dns record updates don't usually take longer than 30 minutes max. after i waited a few days i realized the hostname was being duplicated and fixed it, it worked instantly.

perhaps it could detect this mistake and show a more helpful error message?
