### ISSUE TITLE
Reports/Acquisition page does not work

### ISSUE THREAD

**Issue by mangh** [microsoft/vsmarketplace#257]
**Describe the bug**
Reports/Acquisition page is not working for a last few weeks. It displays *"Sorry, we are unable to process your request. Give it a few minutes and then please try again."* instead of the acquisition graph.

**To Reproduce**
1. Go to [UnitsOfMeasurement](https://marketplace.visualstudio.com/items?itemName=MarekAniola.UnitsOfMeasurement-20210510)
2. Go to 'Reports'
3. Acquisition graph is missing. Instead it displays *"Sorry, we are unable to process your request. Give it a few minutes and then please try again."* but the graph will not appear no matter how long  I wait.

**Expected behavior**
Acquisition Trend displayed in a graph.

**Screenshots**
![image](https://user-images.githubusercontent.com/11795323/143199614-b86b1a7f-017f-4e25-876b-5ce90fe9b14d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, Version 21H1, OS Build 19043.1348
 - Browser: Microsoft Edge
 - Version 96.0.1054.29 (Official build) (64-bit)

**Comment by nikhgup** [comment]
@mangh This has been fixed. hence closing it. Feel free to reopen if you are still facing it.
