### ISSUE TITLE
Getting TF400898: An Internal Error Occurred. while publishing an extension

### ISSUE THREAD

**Issue by odockal** [microsoft/vsmarketplace#258]
Hello, we have an issue while trying to publish an extension using vsce:
```
$ vsce --version
2.5.0
$ node --version
v14.18.0
$ vsce publish -p xxx --packagePath tekton-pipelines-1.0.0-72159.vsix
 INFO  Publishing 'redhat.vscode-tekton-pipelines v1.0.0'...
 ERROR  TF400898: An Internal Error Occurred. Activity Id: c69fa9bd-5a8c-4543-9cb9-aa38f81a3cf1.
```

**Comment by fbricon** [comment]
It'd be nice if server-side errors were propagated to the client side, so if the issue is caused by a malformed vsix, we'd be able to see and fix it. TF400898 code is not helpful.

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
