### ISSUE TITLE
Marketplace publisher isn't aligned

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vsmarketplace#261]
The publisher isn't aligned which is very obvious with the new checkbox.

![image](https://user-images.githubusercontent.com/2193314/144223452-712ad986-190f-4a4a-9a88-3e82d1df77f5.png)

Probably need to set line-height on the element.

**Comment by isidorn** [comment]
fyi @prashantvc

**Comment by prashantvc** [comment]
Thanks, we are aware of alignment issue :) 
We will fix this issue in Dec iteration

**Comment by prashantvc** [comment]
Another one main page and search results
![image](https://user-images.githubusercontent.com/328076/144393258-d9f9bc10-acbb-47a3-9c48-ca63f287edaf.png)

**Comment by anupkmr03** [comment]
@prashantvc verified icon alignment issue on search results has been pushed. 
Also, as discussed for publisher profile alignment issues leaving for UI revamp.

**Comment by isidorn** [comment]
@anupkmr03 then let's go ahead and close this issue if the fix has been pushed for search?

**Comment by anupkmr03** [comment]
Thanks @isidorn  for the confirmation closing this.
