### ISSUE TITLE
Pre-release versions are not flagged in the Marketplace version history

### ISSUE THREAD

**Issue by weinand** [microsoft/vsmarketplace#262]
Testing microsoft/vscode#138068

Pre-release versions are not flagged in the Marketplace version history and the "odd version number==pre-release" convention might not be obvious to users.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/1898161/144259565-08679777-ec89-43aa-a60c-6549ab573d8a.png">

**Comment by isidorn** [comment]
@weinand this has to be supported by the Marketplace and for now we decided this is not P1. We would prefer if the MP focuses on supporting full semver versioning. Once we have that this will no longer be an issue.
Apart from this the Markteplace is working on not showing the pre-release extension version by default.

**Comment by Neelima10735584** [comment]
closing this issue as we are tracking in [Pre-release extensions decorations in the UI #264](https://github.com/microsoft/vsmarketplace/issues/264)
