### ISSUE TITLE
Cannot verify domain when managing publisher

### ISSUE THREAD

**Issue by sgranade** [microsoft/vsmarketplace#263]
I received email notice that I could verify my publisher on the marketplace. I have a valid domain and can add a TXT record to its DNS. However, even after adding the domain (https://granades.com) in the `Verified domain` entry on the `Manage Publishers & Extensions` page, the Verify button remains grayed out and I can't select it, preventing me from verifying myself.

**Comment by rheajain** [comment]
@sgranade The Verify button is greyed out till the time that you haven't added and saved a Domain. Have you saved the domain?

**Comment by sgranade** [comment]
I thought I had, but it turns out uBlock Origin wasn't playing nicely with the Save button on the publisher page. Once I tracked that down, I was able to save and then continue verification.

**Comment by SeyyedKhandon** [comment]
> Same issue here - how does one save a domain name?

By disabling the ublock origin, my problem has been fixed.

**Comment by AlexPapageorge-Poly** [comment]
I am having the same issue and have disabled blockers 
![image](https://github.com/microsoft/vsmarketplace/assets/128623315/9558fdbd-2538-4146-9978-9eeaefe042fb)
