### ISSUE TITLE
Duplicated extensions in extension view on vscode.dev

### ISSUE THREAD

**Issue by aeschli** [microsoft/vsmarketplace#265]
- open https://vscode.dev/
- open the extensions view, enter `azure reposit` and scroll down
- you can see that there are duplicated extensions

![image](https://user-images.githubusercontent.com/6461412/144467602-379c44d5-80f4-42d8-923a-59bec3970a55.png)

(Also Azure DevOps WebDev)

**Comment by sandy081** [comment]
@aeschli Thanks for sharing the query results from network requests. Seems Marketplace is sending duplicates. Hence moved to Marketplace.

@SaiKanth007 FYI

**Comment by SaiKanth007** [comment]
Assigning to our on call engineer @nikhgup

**Comment by rheajain** [comment]
> From the dev tools, network page (again slightly different duplicates)
> 
> * first call:
>   ![image](https://user-images.githubusercontent.com/6461412/144562946-1df62a9e-3ea9-4e75-b48a-096d427289d1.png)
> * second call:
>   ![image](https://user-images.githubusercontent.com/6461412/144563197-09b491f9-766a-4654-80d2-25cb63e4f7e0.png)
> 
> ![image](https://user-images.githubusercontent.com/6461412/144563397-3d6bbcec-e51c-4e5a-88da-fd15aab9b53e.png)
@aeschli If I search for `Azure blueprints generato` I only see unique results. What was your search term here?
Also, in the network calls you shared, which is the duplicate extension?

**Comment by aeschli** [comment]
@rheajain My search term was`azure reposit` (See the steps in the description)
I tried it again today, and can reproduce it. This time its `Azure Shades`
![image](https://user-images.githubusercontent.com/6461412/147769114-a15487b9-1538-4b6a-b082-b3a369eb66e8.png)

**Comment by aeschli** [comment]
>Also, in the network calls you shared, which is the duplicate extension?
- first call:
![image](https://user-images.githubusercontent.com/6461412/144562946-1df62a9e-3ea9-4e75-b48a-096d427289d1.png)
- second call:
![image](https://user-images.githubusercontent.com/6461412/144563197-09b491f9-766a-4654-80d2-25cb63e4f7e0.png)

It's index 48 and index 0

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
