### ISSUE TITLE
GitHub Website Suggestion

### ISSUE THREAD

**Issue by BillyAlbornoz1** [microsoft/vsmarketplace#266]
You all need to make sure that you are able to post up photos, videos as well as any other forms of media in general that would actually be able to explain as specifically as possible about the reasons for why it is always as important as ever nowadays, today in general that any forms of media are posted on up that would actually be able to explain the ways of actually being able to learn how to navigate through this type of site, GitHub, in as short and simple of a process as possible right alongside with making sure that there are also any forms of media that could actually ever be posted on up in general that would actually be able to explain as specifically a possible about the reasons for why it is always as important as ever nowadays, today in general that all of these forms of media always make sure to talk about the complete history of this type of website, the complete history of the type of company that had actually created it right alongside with the ways that they both have been working nowadays, today in general in comparison to the ways that they all were working way back then during the times of when they all had first originated and so on and so forth. Lastly, all of the forms of media mentioned way earlier in the beginning should always be translated into as many different worldwide foreign languages as possible.

**Comment by chgill-MSFT** [comment]
Hi there!

Unfortunately, I had a hard time reading through this paragraph to understand your request. Additionally, the issue title is fairly vague.

Please consider editing the issue title and clarifying your feedback in a follow up comment - otherwise we will close this issue in a few days.

Thanks!

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
