### ISSUE TITLE
Align verified publisher indicators in extension cards and extension details page with VS Code UI

### ISSUE THREAD

**Issue by chrisraygill** [microsoft/vsmarketplace#270]
Our current UI for verified publisher indicators is misaligned with VS Code and redundant for many publishers whose display name is very similar to their domain. 

Let's adopt the VS Code verified publisher indicator design on both the extension cards and the extension details page:

## Reference

**VS Code design**

![image](https://user-images.githubusercontent.com/15097183/145494928-e6a57ad1-d614-43b3-a136-0cebadc5048d.png)

## Target Marketplace design

**Extension cards**

![image](https://user-images.githubusercontent.com/15097183/145491973-2ca3d8aa-d299-4661-b0e4-e31b0f6282f5.png)

**Extension details**

![image](https://user-images.githubusercontent.com/15097183/145494009-721a9e69-789e-489d-b980-2169a576c307.png)

**Comment by Neelima10735584** [comment]
Since the verified publisher indicators have aligned correctly in VS Code, we are closing this issue.

Regards,
VS Marketplace Team
