### ISSUE TITLE
Latest icons for verified publishers and top publishers are not reflected on the publisher details page

### ISSUE THREAD

**Issue by chrisraygill** [microsoft/vsmarketplace#272]
When I go to the publisher details page for a verified publisher, none of the extension cards have a verified icon on them. Similarly, extension cards for top publishers show the old icon.

![image](https://user-images.githubusercontent.com/15097183/145518483-b5e885e5-84cf-465d-b872-d8e5bc1c2927.png)

![image](https://user-images.githubusercontent.com/15097183/145518511-05d0b728-0184-4b66-a2ea-2bda2dc5bf0b.png)

**To Reproduce**
Go to https://marketplace.visualstudio.com/publishers/Microsoft or https://marketplace.visualstudio.com/publishers/agile-extensions to see that the latest icons are not reflected on the extension cards

**Expected behavior**
I expect the extension cards to look the same as they do on the search page with the latest icons for verified and top publishers.

**Desktop (please complete the following information):**
 - Browser: Edge Beta

**Comment by madhurivadaligithub** [comment]
Hi @chrisraygill 

Thanks for reaching VS Marketplace Team, are you still facing the issues?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists please feel free to reopen or create a new issue.
