### ISSUE TITLE
Simplify the domain verification process by making the "Verify" button implicitly Save + Verify

### ISSUE THREAD

**Issue by chrisraygill** [microsoft/vsmarketplace#273]
Today to verify a domain when managing my publisher I have to:

1. Enter a valid domain.
2. Save my domain.
3. Click **Verify.**

However, some users don't find it intuitive that they have to save the domain before the **Verify** button is enabled. 

One option to solve this and reduce steps is to light up the **Verify** button when a valid domain is entered and make it implicitly Save + begin verification process when clicked. 

Alternatively, we should show the following tooltip on the disabled "Verify" button:

"Enter a valid domain and select Save to enable domain verification."

**Comment by Neelima10735584** [comment]
Since we have simplified the domain verification process, we are closing this issue.

Regards,
VS Marketplace Team
