### ISSUE TITLE
live sharing is always disabled

### ISSUE THREAD

**Issue by niyamath7010** [microsoft/vsmarketplace#275]
Issue Type: <b>Bug</b>

facing issue with live server

VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T06:26:56.179Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by isidorn** [comment]
Please file this against the live server extensions, this issue should not be in the marketplace repository. Thank you
