### ISSUE TITLE
Submit button on new publisher page not working

### ISSUE THREAD

**Issue by TeamDman** [microsoft/vsmarketplace#277]
**Describe the bug**
Can't create a new publisher 

**To Reproduce**
1. Go to https://marketplace.visualstudio.com/manage/createpublisher?managePageRedirect=true
2. Add name and ID
3. Scroll down to 'Submit'
4. Click, nothing happens

**Expected behavior**
Submit button works.

**Screenshots**

```
Uncaught TypeError: can't access property "addEventListener", document.getElementById(...) is null
    onload https://marketplace.visualstudio.com/manage/createpublisher?managePageRedirect=true:157
cre
```
![image](https://user-images.githubusercontent.com/9356891/145933403-a88851ea-9233-456b-b433-014c9db347e4.png)

![image](https://user-images.githubusercontent.com/9356891/145933463-d7373fbc-ce37-4444-be73-b0e257cce81a.png)

Presumably the button is loaded async or something? Pasting
```
document.getElementById("submitbutton").addEventListener("click", function(e) {
                                    validate(e);
                                    });
``` 
into my console then clicking submit worked.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
![image](https://user-images.githubusercontent.com/9356891/145933331-efd815eb-7319-457e-b8c1-a80958d85c1c.png)
 - extensions 
```
Auto Tab Discard
I don't care about cookies
JetBrains Toolbox Extension
LastPass: Free Password Manager
Reddit Enhancement Suite
Reddit on Youtube
Refined GitHub
SponsorBlock for YouTube - Skip Sponsorships
uBlock Origin
Video Speed Controller
View Image
YouTube NonStop
```

**Comment by rheajain** [comment]
@TeamDman can you please refresh the page and try again. This is an intermittent issue that we have observed earlier.

**Comment by TeamDman** [comment]
Still having the issue after loading page without cache

**Comment by TeamDman** [comment]
Update: 
Huh, Ctrl+F5 didn't work but checking "Disable Cache" in network tools actually worked.

**Comment by TeamDman** [comment]
Is there a way to delete a publisher? The management page doesn't have any options to do so

**Comment by Neelima10735584** [comment]
Hi @TeamDman,

are you still facing the issue? 

Regards,
VS Marketplace Team

**Comment by TeamDman** [comment]
Worked today trying with Edge

**Comment by TeamDman** [comment]
still don't know how to delete a publisher tho lol
