### ISSUE TITLE
Ability to download older extension version from Marketplace

### ISSUE THREAD

**Issue by SetTrend** [microsoft/vsmarketplace#28]
At my current client I'm forced to develop on a Citrix VM that's blocked from Internet access.

So I need to download Visual Studio Code and all extensions on my local machine, copy them to the VM and install them from there.

Currently, the latest German Language Pack extension (v1.34.0) doesn't match the latest VS Code version (1.33.1), so I cannot install:

![image](https://user-images.githubusercontent.com/9283914/57142561-1c25da00-6dbd-11e9-93f6-a006518ee163.png)

So, please add an option to Marketplace to allow for downloads of older extension versions.

**Comment by chrisdias** [comment]
It's possible to download a previous version of an extension from within VS Code once the extension is installed (click on the gear icon), but not from the marketplace UI or before installing on the desktop.

**Comment by SetTrend** [comment]
Thank you for mentioning it. Yet, that wouldn't solve the problem of downloading an older extension from marketplace (i.e. install offline), would it?

**Comment by prashantvc** [comment]
@SetTrend we recently enabled ability to download old versions of an extensions in the Marketplace. Look for Version History in the Extension Details page.

And we are in the process to enable it for VS IDE extensions too

**Comment by isidorn** [comment]
So this seems to be supported now. Closing and @SetTrend let me know if this does not work and we can reopen

**Comment by cyberluke** [comment]
It is not there:https://marketplace.visualstudio.com/items?itemName=vs-publisher-306627.ANTSProfilerVisualStudioAdd-in&ssr=false#overview

**Comment by failwyn** [comment]
I can't find this feature either.

**Comment by 5CoVK** [comment]
Me neither

**Comment by jpmorris** [comment]
This is not complete and I'm not sure @SetTrend 's was properly addressed.  I have the same issue:
- AWS Sagemaker Code Editor
- Marketplace blocked by firewall
- running on an old version of VSCode with no ability to upgrade

I want to download an updated python extension (indeed the IDE asks to upgrade):
- pressing 'upgrade' gives an error because it's blocked by firewall
- there are only 5 previous versions for downloading they are all too new, I need to get '2024.2.1'
- python extension versions are so specific I an unable to guess a url and download via wget or browser. 

This is incredibly annoying.

**Comment by DiskCrasher** [comment]
> @SetTrend we recently enabled ability to download old versions of an extensions in the Marketplace. Look for Version History in the Extension Details page.

The marketplace website only lists the last 5 releases.

**Comment by jpmorris** [comment]
as a stopgap get your vsix from open-vsx.org. They did it right from the beginning.

**Comment by DiskCrasher** [comment]
A better solution without downloading from an unofficial website:
https://github.com/microsoft/vscode-python/discussions/20184

**Comment by jpmorris** [comment]
@DiskCrasher  how do you determine the version to fill into the template for something besides vscode-python?  (Even vscode-python is a ton of work to find the version, just go to open-vs.org)

**Comment by DiskCrasher** [comment]
@jpmorris Combination of looking it up in the marketplace and GitHub release notes. There are also scripts out there that will do a data dump of all the marketplace extensions/versions.

**Comment by jpmorris** [comment]
Yep looks like that works.  Or you can just download from open-vsx.org.

**Comment by DiskCrasher** [comment]
I'd prefer to download from an official site.
