### ISSUE TITLE
Unable to Verify the Domain

### ISSUE THREAD

**Issue by pavan2004it** [microsoft/vsmarketplace#280]
I am trying to verify the domain in the market place but i am getting the error the domain url provided couldn't be reached.

I have already created a text record by the name of _visual-studio-marketplace-nubewired.nubewired.com but still i am getting the attached error.

<img width="1792" alt="Screenshot 2021-12-20 at 9 13 24 AM" src="https://user-images.githubusercontent.com/13082762/146708934-72605c64-b626-45a6-b847-ab9f09402c6a.png">

**Comment by rheajain** [comment]
@pavan2004it  As a validation we check that the URL you provide give a 200 OK response to the HEAD request call. 
The URL you provided is giving a 301 response. Please make sure that we get the expected response.
