### ISSUE TITLE
err faild xhr

### ISSUE THREAD

**Issue by azadsha** [microsoft/vsmarketplace#282]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by azadsha** [comment]
i can't update vscode
and 
i can't install extensions

**Comment by isidorn** [comment]
Closing as this is not reproducable.
If you find nice reproducable steps please open a new issue in the VS Code repository. Thank you
