### ISSUE TITLE
us

### ISSUE THREAD

**Issue by rbn2357** [microsoft/vsmarketplace#283]
Issue Type: <b>Bug</b>

softwear

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

**Comment by rheajain** [comment]
What exactly is the bug that you are trying to report here?

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists please feel free to reopen or create a new issue
