### ISSUE TITLE
unhide source control

### ISSUE THREAD

**Issue by gopal7123** [microsoft/vsmarketplace#284]
Issue Type: <b>Feature Request</b>

in my visual studio source control is hidden 
so, how can i unhide this 

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by isidorn** [comment]
F1 > View: Show Source Control
