### ISSUE TITLE
Togusa09.tmlanguage is abandoned

### ISSUE THREAD

**Issue by schierlm** [microsoft/vsmarketplace#285]
The extension https://marketplace.visualstudio.com/items?itemName=Togusa09.tmlanguage is abandoned, breaks JSON functionality in VS Code, trying to file a bug report results in a 404 link. A fork with fixed bugs is available at https://marketplace.visualstudio.com/items?itemName=pedro-w.tmlanguage

Yet the former has more downloads and better rating.

Is there a policy to remove abandoned extensions that harm VS Code and are not maintained?

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by prashantvc** [comment]
Unfortunately, we do not have a policy to remove the unmaintained extensions. We actively working on new set of guidelines to deal with the issues like this
