### ISSUE TITLE
Verify publisher fails - The domain url provided could not be reached with gennard.net

### ISSUE THREAD

**Issue by spgennard** [microsoft/vsmarketplace#286]
**Describe the bug**
Verify publisher fails - The domain url provided could not be reached

**To Reproduce**
try to verify *https://gennard.net* as a valid domain

**Expected behavior**
To be able to verify *https://gennard.net* and get the instructions to add the TXT dns record

** Screenshot**
![image](https://user-images.githubusercontent.com/5991192/147853809-55e54d04-a7f0-4fc7-8964-d4e18d7a9d0e.png)

**Additional context**
Using curl, I get a good response:

> $ curl -I https://gennard.net
> HTTP/2 200 
> date: Sat, 01 Jan 2022 15:09:48 GMT
> content-type: text/html
> content-length: 309
> content-security-policy: upgrade-insecure-requests;
> last-modified: Tue, 20 Mar 2018 22:55:39 GMT
> strict-transport-security: max-age=15768000
> accept-ranges: bytes

**Comment by rheajain** [comment]
![image](https://user-images.githubusercontent.com/11938462/148482893-4165853e-19be-4d2e-bdff-beebaa2866d9.png)

**Comment by spgennard** [comment]
@rheajain - Looks good to me

```shell
#  curl -I --max-redirs 0 https://gennard.net
HTTP/2 200 
date: Fri, 07 Jan 2022 11:57:51 GMT
content-type: text/html
content-length: 309
content-security-policy: upgrade-insecure-requests;
last-modified: Tue, 20 Mar 2018 22:55:39 GMT
strict-transport-security: max-age=15768000
accept-ranges: bytes
```

```shell
#  curl -L --max-redirs 0 https://gennard.net
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>   
</title><meta http-equiv="refresh" content="0;url= Welcome.html" /></head><body></body></html>
```

**Comment by spgennard** [comment]
Using developer mode on the browser, I can see this error:

```json
{$id: "1", innerException: null, message: "The domain url provided could not be reached",…}
$id: "1"
errorCode: 0
eventId: 0
innerException: null
message: "The domain url provided could not be reached"
typeKey: "ArgumentException"
typeName: "System.ArgumentException, mscorlib"
}
```

**Comment by spgennard** [comment]
@rheajain - Any idea what is going wrong?

**Comment by pratikgawali-msft** [comment]
Hi @spgennard, it seems the HEAD calls to your domain URL without the `User-Agent` header returns a 403 forbidden error. Please refer the screenshot below:
![image](https://user-images.githubusercontent.com/79199166/153557347-7e7a8657-603f-4744-afea-abbcf9854f5b.png)

Could you please ensure it returns 200 OK to get unblocked? Otherwise, we are working on it to take care of it from our end.

**Comment by spgennard** [comment]
@pratikgawali-msft - Thanks for doing the analysis.

The hosting service says a valid user-agent is expected, so I am not sure if I will be able to convince them to change it.
