### ISSUE TITLE
related to extension problem

### ISSUE THREAD

**Issue by mihirxtc** [microsoft/vsmarketplace#287]
Issue Type: <b>Bug</b>

i have dell latitude E6430 and i download visual studio code on this but i dont able to use any extension like runner python. 
so please solve this problem as soon as possible.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by chgill-MSFT** [comment]
Hi there 👋

Can you please provide further details such as screenshots of error messages. Does the issue happen when you're searching, installing, or trying to use the extensions?

**Comment by madhurivadaligithub** [comment]
Hi @mihirxtc 

Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
