### ISSUE TITLE
Extension marketplace teams should not be allowed to call themselves "VSCode"

### ISSUE THREAD

**Issue by NickHeiner** [microsoft/vsmarketplace#29]
Issue Type: <b>Bug</b>

The `vscode-icons` extension is listed as being authored by the "VSCode Icons Team". I am not sure if this means that it's a first-party extension, from the authors of VSCode, or an unrelated group that decided to take the same name.

Just like Apple does not permit apps in the App Store to masquerade as being from Apple when they're not, it should be clearer in the app store if extensions are authored by the VSCode core team.

VS Code version: Code 1.41.0 (9579eda04fdb3a9bba2750f15193e5fafe16b959, 2019-12-11T17:58:38.338Z)
OS version: Darwin x64 18.7.0

**Comment by isidorn** [comment]
IMHO I would not do anything here. This should be covered via verified publishers https://github.com/microsoft/vsmarketplace/issues/39
