### ISSUE TITLE
Erro ao carregar modo de exibição da web

### ISSUE THREAD

**Issue by Tommattih** [microsoft/vsmarketplace#290]
Issue Type: <b>Performance Issue</b>

A mensagem "erro ao carregar modo de exibição da web: error: could not register service workers: invalidstateerror: failed to register a serviceworker: the document is in an invalid state.." aparece para todas as tentativas de ver a descrição/preview das extensões (estejam instaladas ou não), busquei na web e no youtube e não encontrei nenhum relato ou explicação de como concertar... já faz dias que está assim, o que fazer?

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Tommattih** [comment]
Ainda não sei o que ocorreu, mas hoje normalizou a exibição.
Caso alguém saiba explicar o ocorrido, agradeço desde já

**Comment by Neelima10735584** [comment]
Hi @Tommattih,

Thank you for opening the issue. Sorry to hear you are experiencing an issue with searching. It appears to be specific to VS Code editor and tools we understand correctly. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
