### ISSUE TITLE
The domain url provided could not be reached

### ISSUE THREAD

**Issue by BartNetJS** [microsoft/vsmarketplace#291]
I have the same issue mentioned here https://github.com/microsoft/vsmarketplace/issues/254
''The domain url provided could not be reached"
But my root domain is giving a 200 on a HEAD request

What else could be wrong?

**Comment by aslakhellesoy** [comment]
I'm getting the same error. The domains I have tried are `https://smartbear.com` and `https://cucumber.io`. They both respond with 200 with a `HEAD` request.

**Comment by pratikgawali-msft** [comment]
Hi @BartNetJS and @aslakhellesoy, it seems the issue is that the HEAD call to your domain URL without the User-Agent header is not returning the 200 OK response code.

![image](https://user-images.githubusercontent.com/79199166/152933914-9d273677-14e8-4980-b812-62b96d0219f7.png)

**Comment by aslakhellesoy** [comment]
Thanks for the explanation @pratikgawali-msft.

Is there any particular reason you’re not sending `User-Agent` header? It’s not strictly required, but [strongly recommended](https://stackoverflow.com/questions/24274789/is-lack-of-user-agent-in-http-request-valid#24274846) and many servers are configured to reject requests that do not have it.

**Comment by sathaker** [comment]
Hi @BartNetJS and @aslakhellesoy 

We have updated our HEAD request. Can you please try again and confirm here?

**Comment by aslakhellesoy** [comment]
Hi - I have just tried again and it's still not working. Nothing goes through on https://marketplace.visualstudio.com/manage/createpublisher

**Comment by open-human** [comment]
I have the same problem.
Microsoft always have issues!

**Comment by open-human** [comment]
Today, I still have issues with create vscode extension

**Comment by equinusocio** [comment]
Same issue, can't verify my publisher account

**Comment by sanderjson** [comment]
This might be an example of bad UX. Consider the quote:

> To become verified, a publisher must have one or more extensions on the VS Marketplace for a minimum of 6 months, and the registration of the domain must also be at least 6 months old.

1. Try filling out the same form *without* the domain (creates publisher). (DONE)
2. Publish your extension. (WIP)
3. Then in six months return to the same form and _verify_ with your domain? (TBD)
