### ISSUE TITLE
Visual Studio "Featured" extensions are all for VS 2019 - should filter to VS 2022 compatible extensions

### ISSUE THREAD

**Issue by chgill-MSFT** [microsoft/vsmarketplace#294]
**Describe the bug**

Extensions shown on the Marketplace website landing page in the **Featured** section are all VS 2019 extensions, most of which are not compatible with VS 2022.

![image](https://user-images.githubusercontent.com/15097183/148613638-c887bcfe-106b-4361-a012-960060a9b357.png)

![image](https://user-images.githubusercontent.com/15097183/148613742-97794fe3-d2d5-4173-92b1-81e4261af9e0.png)

**Expected behavior**

**Featured** extensions should be compatible with VS 2022.

**Comment by pratikgawali-msft** [comment]
Thanks @chgill-MSFT for the feedback. Now, the extensions shown on the Marketplace website landing page in the Featured section are all compatible with VS 2022.

**Comment by madskristensen** [comment]
Awesome. Thank you!!
/cc @leslierichardson95
