### ISSUE TITLE
Extension tag links with spaces are not quoted on extension pages

### ISSUE THREAD

**Issue by ghost** [microsoft/vsmarketplace#295]
**Describe the bug**

**To Reproduce**
1. Go to [`bierner.markdown-preview-github-styles`](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles)
2. Click on the `github markdown` tag (in the "Tags" list on the right rail).
3. The results are wrong because it's interpreted as `tag:github markdown`/`markdown tag:github`, NOT `tag:"github markdown"`

**Expected behavior**

![correct search for extensions with quoted tag: 'github markdown'](https://user-images.githubusercontent.com/82655227/148643250-7175dd46-f5f2-4208-a253-3351b3bd0eb4.png)

**Screenshots**

![extension page tagged with 'github markdown'](https://user-images.githubusercontent.com/82655227/148643258-575c5a39-bb68-48aa-971a-b3a56a52cf41.png)

Actual tag search result:

![erroneous search for extensions tagged 'github' and matching the text 'markdown'](https://user-images.githubusercontent.com/82655227/148643501-95d43af7-ee3e-461e-8c7b-d54372ce5de5.png)

**Desktop**

 - OS: Windows 10 20H2
 - Browser: Edge
 - Version: 96

**Additional context**
Not sure if there are other bugs in general related to searching extension tags.

**Comment by prashantvc** [comment]
This is an issue with search, we are rolling out few improvements to address the issue like this.
You could see some improvements in coming weeks

**Comment by prashantvc** [comment]
This is fixed. Please reopen the issue if you still experience it
