### ISSUE TITLE
extensions

### ISSUE THREAD

**Issue by rohindhkishore** [microsoft/vsmarketplace#296]
Issue Type: <b>Bug</b>

it always shows xhr failed whenever i try to install extensions

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by pratikgawali-msft** [comment]
Could you share more information along with screenshots, if possible?

**Comment by madhurivadaligithub** [comment]
Hi @rohindhkishore ,

Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
