### ISSUE TITLE
Unable to publish extension

### ISSUE THREAD

**Issue by FrankSAURET** [microsoft/vsmarketplace#299]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.63.2
- OS Version:Windows 11 - Last update

Steps to Reproduce:

From 2 days i have this error when i use "vsce publish" to update my extension :

{"$id":"1","innerException":null,"message":"TF400733: The request has been canceled: The request has exceeded request timeout, please try again.","typeName"::"Microsoft.TeamFoundation.Framework.Server.RequestCanceledException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestCanceledException","errorCode":0,"eventId":3000}

**Comment by FrankSAURET** [comment]
Hey, always unable to publish. So, what news doc ?

**Comment by joaomoreno** [comment]
cc @prashantvc

**Comment by FrankSAURET** [comment]
Hi,
today i got this error. Can you help me. 
Thank you.

```
Sorry! Our services aren't available right now.
We're working to restore all services as quickly as possible. Please check back soon.

To see the latest status on our services, please visit our support page.

Ref A: 15A41A43F8B14187ACA3E0B77E22564D Ref B: PRAEDGE0817 Ref C: 2022-01-23T14:30:38Z
```

**Comment by anupkmr03** [comment]
Hi @FrankSAURET, 

Sorry for the delay. Could you help me with your publisher name and the extension on which you are facing this error? Also, please share screenshots where you are getting these errors?

**Comment by FrankSAURET** [comment]
Hello,
I just succeed to post from my workplace and with a new azure token.
I will try again tomorrow from home to send you the errors.

**Comment by FrankSAURET** [comment]
![erreur](https://user-images.githubusercontent.com/1547522/151159364-b2b9303f-1e3b-45d1-be59-a3f233131394.png)

Hello Anup,
From home it still doesn't work. Here is a screenshot, the error page is the same as the one I sent you earlier (3 days ago).

Ref A: DB3D3B5226584FCCA3B1175D4AA15F2C Ref B: PRAEDGE1415 Ref C: 2022-01-26T11:40:46Z

**Comment by FrankSAURET** [comment]
No news ?

**Comment by FrankSAURET** [comment]
Hi,
I always have this erreur at home :
`{"$id":"1","innerException":null,"message":"TF400733: The request has been canceled: The request has exceeded request timeout, please try again.","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestCanceledException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestCanceledException","errorCode":0,"eventId":3000}`

and publishing is ok at my workplace.

From home i publish some other extension without problem.

**Comment by pagnkelly** [comment]
same with you

**Comment by SaiKanth007** [comment]
Hi FrankSAURET,

I suspect the issue might be because of the _abriand-sin_ extension size which is 47 MB. I took a look at your other [extensions](https://marketplace.visualstudio.com/publishers/electropol-fr) that you were able to upload successfully from home, all of their size is less than 4 MB. That might be the reason.

What my hunch is that the stream might not be reaching the marketplace endpoint. Since the extension size is big the upload time might be exceeding the actual request time out limits. Can you also check your upload speed at home once?

**Comment by FrankSAURET** [comment]
Hi SaiKanth007,
It's possible, my home is in the middle of nowere. My upload speed is about 100kb/s.

Is there a solution ?

**Comment by seaniyer** [comment]
Closing as the issue appears to have been related to upload speed / external to VS Marketplace.
