### ISSUE TITLE
Markdown Marketplace: no link, [foo](bar.com), inside literal text, single and triple back tick

### ISSUE THREAD

**Issue by rioj7** [microsoft/vsmarketplace#30]
The file `README.md` from the extension is used by the Marketplace website. If you use `[foo]` followed by `(bar)` inside literal text, single and triple back tick, it is recognized as a Markdown link.

This construct happens easily in regular expressions.
```
\s*[^!@#](.*)
```
The `.*` is expanded to the full directory of the `README.md` file.

The Markdown syntax highlighting in VSC has a similar problem, it marks the text between `()` as a clickable link.

The Markdown Preview shows the literal text correct.

**Comment by rioj7** [comment]
Markdown files allow the use of [HTML Entities](https://html.spec.whatwg.org/multipage/named-characters.html)

By replacing `[abcd]` with `&lsqb;abcd&rsqb;` the link is no longer detected. for this to work you have to place the content of the single and triple back tick between HTML tags `<code></code>` and `<pre><code></code></pre>` and you need to translate `&`, `<` and `>` to the HTML Entities `&amp;`,  `&lt;` and `&gt;`

The example of the question needs to be written in Markdown file as:

```
<pre><code>\s*&lsqb;^!@#&rsqb;(.*)</code></pre>
```

**Comment by Neelima10735584** [comment]
Hi,

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
