### ISSUE TITLE
(elided 3 frames from dart:async)

### ISSUE THREAD

**Issue by D-scientist** [microsoft/vsmarketplace#305]
**(elided 3 frames from dart:async)**
Please help me how to remove this Error!!
Apparently there in no error in my code;

`import 'package:animation_wrappers/animation_wrappers.dart';
import 'package:flutter/material.dart';
import 'package:lawapp/Locale/locales.dart';
import 'package:lawapp/Theme/colors.dart';`

`
class Appointments extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var locale = AppLocalizations.of(context)!;

    final List<Widget> tabs = <Widget>[
      Tab(text: locale.upcoming),
      Tab(text: locale.past),
    ];
    return DefaultTabController(
      length: tabs.length,
      child: Scaffold(
        appBar: AppBar(
          title: Text(locale.myAppointments!,
              style: Theme.of(context)
                  .textTheme
                  .bodyText1!
                  .copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
          leading: IconButton(
            icon: Icon(Icons.chevron_left, color: Colors.white),
            onPressed: () {
              Navigator.pop(context);
            },
          ),
          bottom: PreferredSize(
              child: Container(
                alignment: Alignment.topLeft,
                child: TabBar(
                    indicatorWeight: 4.0,
                    indicatorSize: TabBarIndicatorSize.label,
                    tabs: tabs,
                    isScrollable: true,
                    labelStyle: Theme.of(context)
                        .textTheme
                        .bodyText1!
                        .copyWith(fontSize: 18, fontWeight: FontWeight.bold),
                    labelColor: primaryColor,
                    indicatorColor: primaryColor,
                    unselectedLabelColor: Colors.white),
              ),
              preferredSize: Size.fromHeight(40)),
        ),
        body: TabBarView(children: [Upcoming(), Upcoming()]),
      ),
    );
  }
}

class Upcoming extends StatelessWidget {
  final List title = [
    "Jack Williamson",
    "Peter Davis",
    "Jon Snow",
    "Emilia Clarke",
    "Tommy Shelby"
  ];
  final List imgs = [
    "assets/Layer 556.png",
    "assets/Layer 4 copy.png",
    "assets/Layer 558.png",
    "assets/Layer 557.png",
    "assets/Layer 558.png",
  ];
  @override
  Widget build(BuildContext context) {
    var locale = AppLocalizations.of(context)!;
    List subtitle = [
      locale.criminalLawyer!,
      locale.corporateLawyer!,
      locale.criminalLawyer!,
      locale.corporateLawyer!,
      locale.criminalLawyer!,
    ];
    return FadedSlideAnimation(
      ListView.builder(
        padding: EdgeInsets.symmetric(horizontal: 10),
        scrollDirection: Axis.horizontal,
        shrinkWrap: true,
        itemCount: 5,
        itemBuilder: (BuildContext context, int index) {
          return Stack(
            children: [
              Container(
                width: MediaQuery.of(context).size.width * 0.85,
                margin: EdgeInsets.symmetric(horizontal: 10, vertical: 40),
                padding: EdgeInsets.symmetric(horizontal: 15, vertical: 20),
                decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(10)),
                child: ListView(
                  children: [
                    Row(
                      children: [
                        Row(
                          children: [
                            Text(
                              locale.inDays!,
                              style: Theme.of(context)
                                  .textTheme
                                  .bodyText1!
                                  .copyWith(color: Colors.black, fontSize: 18),
                            )
                          ],
                        ),
                        Spacer(),
                        IconButton(
                            icon: Icon(
                              Icons.delete,
                              color: greyColor,
                            ),
                            onPressed: () {})
                      ],
                    ),
                    SizedBox(
                      height: 20,
                    ),
                    ListTile(
                      leading: FadedScaleAnimation(
                        Container(
                          child: Image.asset(imgs[index]),
                        ),
                      ),
                      title: Text(
                        title[index],
                      ),
                      subtitle: Text(
                        subtitle[index],
                        style: Theme.of(context).textTheme.bodyText1!.copyWith(
                              color: greyColor,
                            ),
                      ),
                    ),
                    SizedBox(
                      height: 20,
                    ),
                    ListTile(
                      leading: CircleAvatar(
                        backgroundColor: Colors.grey[300],
                        child: Icon(
                          Icons.account_balance,
                          color: primaryColor,
                          size: 20,
                        ),
                      ),
                      title: Text(
                        locale.appointmentFor!,
                        style: Theme.of(context).textTheme.bodyText1!.copyWith(
                              color: greyColor,
                            ),
                      ),
                      subtitle: Text(
                        locale.bankAndFinance!,
                        style: Theme.of(context).textTheme.bodyText1!.copyWith(
                            fontSize: 18,
                            color: Colors.black,
                            fontWeight: FontWeight.bold),
                      ),
                    ),
                    ListTile(
                      leading: CircleAvatar(
                        backgroundColor: Colors.grey[300],
                        child: Icon(
                          Icons.calendar_today,
                          color: primaryColor,
                          size: 20,
                        ),
                      ),
                      title: Text(
                        locale.appointmentDate!,
                        style: Theme.of(context).textTheme.bodyText1!.copyWith(
                              color: greyColor,
                            ),
                      ),
                      subtitle: Text(
                        "12 June, 2021 (Wed)",
                        style: Theme.of(context).textTheme.bodyText1!.copyWith(
                            fontSize: 18,
                            color: Colors.black,
                            fontWeight: FontWeight.bold),
                      ),
                    ),
                    ListTile(
                      leading: CircleAvatar(
                        backgroundColor: Colors.grey[300],
                        child: Icon(
                          Icons.schedule,
                          color: primaryColor,
                          size: 20,
                        ),
                      ),
                      title: Text(
                        locale.appointmentTime!,
                        style: Theme.of(context).textTheme.bodyText1!.copyWith(
                              color: greyColor,
                            ),
                      ),
                      subtitle: Text(
                        "11:00 am",
                        style: Theme.of(context).textTheme.bodyText1!.copyWith(
                            fontSize: 18,
                            color: Colors.black,
                            fontWeight: FontWeight.bold),
                      ),
                    ),
                    SizedBox(
                      height: 20,
                    ),
                  ],
                ),
              ),
              PositionedDirectional(
                bottom: 60,
                start: 20,
                end: 20,
                child: FadedScaleAnimation(
                  Container(
                    height: 55,
                    width: 180,
                    decoration: BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(10),
                        border: Border.all(color: primaryColor)),
                    child: Center(
                        child: Text(
                      locale.reschedule!,
                      style: Theme.of(context).textTheme.bodyText1!.copyWith(
                          fontSize: 17,
                          color: primaryColor,
                          fontWeight: FontWeight.bold),
                    )),
                  ),
                ),
              )
            ],
          );
        },
      ),
      beginOffset: Offset(0.4, 0),
      endOffset: Offset(0, 0),
      slideCurve: Curves.linearToEaseOut,
    );
  }
}`

![error1](https://user-images.githubusercontent.com/59016453/149678369-8807249f-91a8-4d79-b14e-c4ace2db8012.PNG)

`D/DynamitePackage( 9545): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     ( 9545): This request is sent from a test device.
I/Ads     ( 9545): Ad failed to load : 1
I/flutter ( 9545): BannerAd failedToLoad: LoadAdError(code: 1, domain: com.google.android.gms.ads, message: Error building request URL., responseInfo: ResponseInfo(responseId: null, mediationAdapterClassName: , adapterResponses: []))

════════ Exception caught by widgets library ═══════════════════════════════════
Null check operator used on a null value
════════════════════════════════════════════════════════════════════════════════
`

chain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\SAMIU\AppData\Local\Android\sdk
    • Platform android-31, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java  
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.63.2)
    • VS Code at C:\Users\SAMIU\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 97.0.4692.71
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 97.0.1072.55

• No issues found!

**Comment by pratikgawali-msft** [comment]
Hi @D-scientist, VS Marketplace takes care of hosting extensions for VS Code. This seems to be an application error.
