### ISSUE TITLE
error discoverring unittest tests 

### ISSUE THREAD

**Issue by nrbnlulu** [microsoft/vsmarketplace#307]
Issue Type: <b>Bug</b>

module with unittest classes not found in test explorer

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:39:46.686Z)
OS version: Linux x64 5.15.12-1-MANJARO snap
Restricted Mode: No

**Comment by nrbnlulu** [comment]
![Screenshot_2022-01-17_21-47-24](https://user-images.githubusercontent.com/88795475/149829661-6827d988-bb7d-4c47-b6d3-7a8b39b4265d.png)
![Screenshot_2022-01-17_21-46-06](https://user-images.githubusercontent.com/88795475/149829670-51bcd9e0-ecd9-47f2-b2bd-5ce74db0ec42.png)

**Comment by nrbnlulu** [comment]
![Screenshot_2022-01-17_21-53-20](https://user-images.githubusercontent.com/88795475/149830019-6c457c7b-af9f-451c-8b22-df5d4eaec72c.png)
![Screenshot_2022-01-17_21-47-24](https://user-images.githubusercontent.com/88795475/149830021-43df2600-6b36-4bc3-b648-52b4a89882bf.png)
![Screenshot_2022-01-17_21-46-06](https://user-images.githubusercontent.com/88795475/149830022-37d6cd78-ce39-4ed4-af42-6b89477409c5.png)

**Comment by prashantvc** [comment]
@isidorn could it be a VS Code issue?

**Comment by isidorn** [comment]
@nrbnlulu please file against Python extension https://github.com/microsoft/vscode-python
