### ISSUE TITLE
Repository link not rendered even though extension provides repository information

### ISSUE THREAD

**Issue by isidorn** [microsoft/vsmarketplace#311]
https://marketplace.visualstudio.com/items?itemName=xdebug.php-debug

Notice how the repository link is not rendered in the resources even though the extension defines it here
https://github.com/xdebug/vscode-php-debug/blob/7c8529a97cd4487953afb12377d9a91c3d2283ca/package.json#L35-L41

fyi @tyriar @zobo @prashantvc

**Comment by zobo** [comment]
Hi! I've released a new version. The first after migration. It looks OK now.

**Comment by isidorn** [comment]
Yeah looks good. @zobo thanks a lot 👏
