### ISSUE TITLE
my azure subscription is not showing in the editor

### ISSUE THREAD

**Issue by chayan0619** [microsoft/vsmarketplace#312]
Issue Type: <b>Feature Request</b>

my azure free student subscrition is not showing in the editor (visual studio code).

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by prashantvc** [comment]
Could you share more information? It looks like a particular extension issue

**Comment by SaiKanth007** [comment]
@chayan0619 This issue seems to be related to the VSCode editor. Can you please create a ticket with the VSCode repo.
