### ISSUE TITLE
Getting error when writing `vsce publish`

### ISSUE THREAD

**Issue by nikeedev** [microsoft/vsmarketplace#313]
Hello i wanted to publish my extension to Visual Studio Code. I used as the docs said `vsce publish`, but i always get this error: 
<img width="478" alt="image" src="https://user-images.githubusercontent.com/69197950/150650962-97bfb315-bb51-4d92-af81-b82e8d287021.png">
That `The Extension Id already exist in the Marketplace. Please use the different Id`. What "id"?

Specs:

I use windows 11, but that happend on the 10th too.

Vscode: 1.63.2

Anything else? just ask, cause theres is probably going to be a list if i write all self.....
.

Steps to reproduce
 
1. Make a extension.
2. Write `vsce publish`
3. You get the error.

I dont know why it is happening, i logged vsce in, but still does nothing.......

**Comment by munishgoyal1** [comment]
@nikhgup can you please look into this

**Comment by nikeedev** [comment]
It also happened at me even at new year, so bug is pretty old.

**Comment by nikhgup** [comment]
@nikeedev Id (canvas-snippets) you are using for publishing the extension is already exists in marketplace. Can you please try publishing the extension with different Id. We are not accepting extension with Id which already exists in Marketplace.
You can update the 'Id' in extension.vsixmanifest file as shown in attached image. 
![image](https://user-images.githubusercontent.com/52026487/151107187-234ac5df-079d-4b35-ac46-64579741bc20.png)

**Comment by nikeedev** [comment]
i have only these files: 
<img width="171" alt="image" src="https://user-images.githubusercontent.com/69197950/151116965-de4cbebe-a1bb-4c8b-82be-8c944cc779b5.png">
no `extension.vsixmanifest`

**Comment by nikeedev** [comment]
@nikhgup

**Comment by nikeedev** [comment]
Also, im making snippets for Visual Studio Code, so...

**Comment by nikeedev** [comment]
> i have only these files: <img alt="image" width="171" src="https://user-images.githubusercontent.com/69197950/151116965-de4cbebe-a1bb-4c8b-82be-8c944cc779b5.png"> no `extension.vsixmanifest`

here is proof: https://github.com/nikeedev/canvas-api-snippets

**Comment by nikhgup** [comment]
@nikeedev Apologies for confusion. extension.vsixmanifest file is inside vsix package you generated. As an alternate solution you can try changing 'name' in https://github.com/nikeedev/canvas-api-snippets/blob/main/package.json file and as 'canvas-snippets' name already exists in Marketplace.

**Comment by nikeedev** [comment]
Thank you very much @nikhgup ! I did change the name on `package.json` and it works :D! thx!
