### ISSUE TITLE
Marketplace error on VS extension upload

### ISSUE THREAD

**Issue by madskristensen** [microsoft/vsmarketplace#316]
**Describe the bug**
When uploaded on the website or from the CLI, I get this error message: _The package contains an invalid VSIX manifest file. This VSIX does not apply to any product installed on this machine. The problem could be that the VSIX manifest's format is not recognized, or that the manifest has been corrupted_.

I've tried with two of my extensions that worked fine just a few days ago when I last updated them.

**To Reproduce**
1. Upload any extension extension

**Comment by prashantvc** [comment]
@pratikgawali-msft Could you take a look at this please?

**Comment by pratikgawali-msft** [comment]
Yes, we are working to resolve the issue as quickly as we could.

**Comment by pratikgawali-msft** [comment]
The issue is resolved. Now the VS extension upload should work fine.
Thanks for reporting the issue so quickly.

**Comment by anangaur** [comment]
What was the issue?

**Comment by prashantvc** [comment]
This is an issue in the backend, I will talk to Munish and send out analysis over email
