### ISSUE TITLE
All Sass Products won't work for me

### ISSUE THREAD

**Issue by Jeskalana** [microsoft/vsmarketplace#318]
Issue Type: <b>Bug</b>

All the Sass compilers and watchers are hacked and won't work for me.  I don't know if it's just me or it's a universal problem.  Live Compilers won't watch or compile scss into css for me.  I've tried just about everyone.  Some won't install at all.  The instructions they give won't work.  The watch button doesn't even show up for me.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by pratikgawali-msft** [comment]
Hi @Jeskalana, VS Marketplace hosts extensions for VS Code. Could you provide more information if you are facing issues downloading/installing extensions from the VS Marketplace? Or you are facing issues with the working of certain extensions?

**Comment by SaiKanth007** [comment]
@Jeskalana Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
