### ISSUE TITLE
extenstion installing error

### ISSUE THREAD

**Issue by rajbhagwat** [microsoft/vsmarketplace#324]
Error while installing 'Material Icon Theme' extension. Please check the [log](command:workbench.action.showWindowLog) for more details.

**Comment by pratikgawali-msft** [comment]
Hi @rajbhagwat, I assume you are trying to install [this](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme) extension. Could you please share more information about the error you are facing? Error logs and error screenshots would be useful.

PS: I am able to install the extension on my VS Code.

![image](https://user-images.githubusercontent.com/79199166/152796246-eab6c9ee-5c32-49b3-8bf3-ef0884287815.png)

**Comment by SaiKanth007** [comment]
@rajbhagwat Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you are facing any other issues.
