### ISSUE TITLE
Can't install PlatformIO IDE

### ISSUE THREAD

**Issue by cfrank01** [microsoft/vsmarketplace#326]
Issue Type: <b>Bug</b>

Tried multiple times to install this extension and keep getting the same error about  certificate missing.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by pratikgawali-msft** [comment]
Hi @cfrank01, could you please share more information about the error you are facing along with screenshots.
PS: I am able to install the [extension](https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide) on my VS Code.

![image](https://user-images.githubusercontent.com/79199166/152792212-20c37e28-ac8d-4627-b38d-cec41b28a288.png)

**Comment by cfrank01** [comment]
After several more attempts, I was finally able to get this to install.  Not exactly sure what fixed has I had tried multiple times and all the suggested fixes to get this to work.
