### ISSUE TITLE
Unable to publish extension with vsixpublisher

### ISSUE THREAD

**Issue by timheuer** [microsoft/vsmarketplace#331]
**Describe the bug**
Trying to publish my extension and the vsixpublisher generates exception:

```
An error occurred while communicating with the marketplace: categories: Extension type cannot be multiple.
```
See https://github.com/timheuer/AddActionsWorkflow/runs/5194535197?check_suite_focus=true#step:6:16

repo has manifest being used also

**Comment by nikhgup** [comment]
@timheuer Categories mentioned here https://github.com/timheuer/AddActionsWorkflow/blob/main/vs-publish.json are not valid. we allow only one root category. root category can be "Controls", "templates", "tools".
category mentioned by you "build" and "source control" come under 'Tools' while "workflow" comes under 'Templates'. please remove "workflow" from category and you will be able to publish the extension.

**Comment by timheuer** [comment]
@nikhgup I removed the category (by the way this is not documented and
schemastore.org manifest is invalid then)

But still fails now with no helpful error message:
https://github.com/timheuer/AddActionsWorkflow/runs/5202694162?check_suite_focus=true#step:6:17

**Comment by timheuer** [comment]
Hmm, this issue now looks like: https://github.com/microsoft/VSExtensibility/issues/70

**Comment by nikhgup** [comment]
@timheuer I can see from logs your extension is published successfully. https://marketplace.visualstudio.com/items?itemName=TimHeuer.AddActionsWorkflow&ssr=false#overview.
Currently i don't see any other error except the earlier one with categories. Please let me know if we can close this issue?

**Comment by timheuer** [comment]
I think we can close this as the new bug appears to be related to VS2022 and the vsixpublisher.
