### ISSUE TITLE
Cannot verify domain even though valid

### ISSUE THREAD

**Issue by timheuer** [microsoft/vsmarketplace#332]
**Describe the bug**
trying to verify domain and it gives an error it is unreachable when it isn’t. 
![E46E8925-39DE-4116-A5C5-DDE5DE098AEA](https://user-images.githubusercontent.com/4821/153991985-bc88c7af-198a-40ef-8a84-c3194c08018d.png)

**Comment by nikhgup** [comment]
@timheuer we make HEAD call to verify the domain url and above URL returning 405 as response for HEAD call. Can you please allow HEAD call to return 200.

**Comment by timheuer** [comment]
Thank you I got this working now.  Please update the documentation to
reflect this requirement -- it is not listed in the "eligible domain"
requirements.

**Comment by timheuer** [comment]
@chgill-MSFT it's actually a 405 response, so it's not really checking for content, just likely control of the domain 'for real' -- I was fine to know that but it just wasn't documented clearly.
