### ISSUE TITLE
Add "file an issue" button to the "Rating and Review" section

### ISSUE THREAD

**Issue by minsa110** [microsoft/vsmarketplace#335]
Sometimes, issues are filed as VS Marketplace reviews that are supposed to be GH issues, which lowers the extension ratings. Even though the "Issues" link exists in the righthand column of the extension page, it doesn't seem as discoverable. Would it be possible to make filing an issue more prominent in the "Rating and Review" section by adding it as a button? Something like:

![image](https://user-images.githubusercontent.com/10833267/154720585-dbcf0542-2437-4dab-882b-ede3a63d0d4a.png)

Related: https://github.com/microsoft/vscode-jupyter-internal/issues/262

**Comment by misolori** [comment]
Similarly, other app stores have links for support/filing issues near where users write a review:

## Apple App Store
![CleanShot 2022-02-18 at 09 46 19@2x](https://user-images.githubusercontent.com/35271042/154735205-cc606f8b-f12f-409f-9c13-f43e50521355.png)

## Chrome
![CleanShot 2022-02-18 at 09 48 42@2x](https://user-images.githubusercontent.com/35271042/154735588-23f010e3-bb97-4f25-b72b-eb4c85aec0b6.png)

## Steam
In some cases if you write a negative review, some apps asks the user if they'd like to contact support first:

<img width="799" alt="CleanShot 2022-02-18 at 09 55 08@2x" src="https://user-images.githubusercontent.com/35271042/154736479-6143290b-8ad6-4256-a36c-853a77829f23.png">

**Comment by prashantvc** [comment]
This is something we have on our backlog; it will be a while we get to it :)

**Comment by amit-kulkarni-in** [comment]
We have implemented the minor enhancements on marketplace for more details refer to the discussion thread, https://github.com/microsoft/vscode-discussions/discussions/329.
