### ISSUE TITLE
xhr Failed

### ISSUE THREAD

**Issue by cgl712** [microsoft/vsmarketplace#337]
Issue Type: <b>Feature Request</b>

Trying to add Live Server extension. When trying to search extensions I receive "Error while fetching extensions. XHR failed".

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by NOTUJJWAL420** [comment]
Trying to add Live Server extension. When trying to search extensions I receive "Error while fetching extensions. XHR failed".

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Hi,
 
Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).
 
Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested.

Thanks,
VS Marketplace Team
