### ISSUE TITLE
Frontend doesn't support raw input

### ISSUE THREAD

**Issue by Enthusiast-007** [microsoft/vsmarketplace#341]
Issue Type: <b>Feature Request</b>

input() request doesn't work in jupyter notebook cells in VS CODE, while on execution with any input() code it keeps on loading infinitely.

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by prashantvc** [comment]
Not marketplace related, you may want file it on VS Code or Jupyter extension repo
