### ISSUE TITLE
Cleanup Store and Prevent Spammers and Scammers

### ISSUE THREAD

**Issue by hl2guide** [microsoft/vsmarketplace#342]
Please quickly clean up and prevent spam in the marketplace. Please protect your users.

Recent Extensions URL: https://marketplace.visualstudio.com/search?target=VSCode&category=All%20categories&sortBy=PublishedDate

It's being spammed with these extensions:
* robux
* Google Play Gift Card
* Amazon Gift Cards

e.g:

![1](https://user-images.githubusercontent.com/17044982/156949609-ab8044c4-5fcf-4639-9396-394896ed43d4.png)

Please consider automatically blocking with rules like:
* Minimum extension size > X
* Icon has been set
* Author is not spamming
* Set a maximum number of times a user can upload an extension per day
* etc..

**Comment by prashantvc** [comment]
Thanks for reporting the issue, we are actively working on preventing these spam extensions.
Meantime you may experience service degradation

We appreciate your patience ❤️

**Comment by prashantvc** [comment]
Please use this https://github.com/microsoft/vsmarketplace/discussions/343 for further discussion
