### ISSUE TITLE
The group vsmarketplace-core only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vsmarketplace#347]
**To Reproduce**
1. Click `Report Abuse`  of an extension on the marketplace.
2. Send e-mail from one's GMail account.
3. Received a message from `postmaster@microsoft.com`

> The group vsmarketplace-core only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

E-mails from GMail accounts should be accepted.

**Comment by SaiKanth007** [comment]
This issue has now been fixed.

**Comment by tamuratak** [comment]
I have confirmed.
