### ISSUE TITLE
It appears the marketplace rejects certain "reserved" keywords as extension name

### ISSUE THREAD

**Issue by sourishkrout** [microsoft/vsmarketplace#354]
I wasn't able to publish under `<publisher>.ext` or `<publisher>.extension`. Marketplace Manage as well as the APIs returned (slightly edited):

```
Done in 22.60s.
 WARNING  LICENSE.md, LICENSE.txt or LICENSE not found
 INFO  Publishing '<publisher>.extension v0.4.0'...
 ERROR  The Extension Id already exist in the Marketplace. Please use the different Id
 ```

It'd be great to detect earlier in the process and upgrade docs to list all reserved keywords if there are more. There's also a chance I could be wrong.

Version used:

```
vsce@2.5.3
```

**Comment by joaomoreno** [comment]
Unfortunately, the Marketplace started restricting extension names and makign them unique despite the publisher.

> ERROR  The Extension Id already exist in the Marketplace. Please use the different Id

A better error message should be sent from the service, clarifying what is meant by `Extension Id`.

cc @isidorn @sandy081

---

@holazz I suggest picking a different extension name, since `open-in-browser` is taken.

**Comment by isidorn** [comment]
We should also communicate this change clearly to extension authors. @prashantvc can you please take the lead here?

**Comment by holazz** [comment]
> Unfortunately, the Marketplace started restricting extension names and makign them unique despite the publisher.
> 
> > ERROR  The Extension Id already exist in the Marketplace. Please use the different Id
> 
> A better error message should be sent from the service, clarifying what is meant by `Extension Id`.
> 
> cc @isidorn @sandy081
> 
> @holazz I suggest picking a different extension name, since `open-in-browser` is taken.

I noticed that both `igordvlpr.open-in-browser` and `techer.open-in-browser` exist in the Marketplace. Isn't `${publisher}.${name}` as  Extension Id ?

**Comment by holazz** [comment]
> Unfortunately, the Marketplace started restricting extension names and makign them unique despite the publisher.
> 
> > ERROR  The Extension Id already exist in the Marketplace. Please use the different Id
> 
> A better error message should be sent from the service, clarifying what is meant by `Extension Id`.
> 
> cc @isidorn @sandy081
> 
> @holazz I suggest picking a different extension name, since `open-in-browser` is taken.

I noticed that both `igordvlpr.open-in-browser` and `techer.open-in-browser` exist in the Marketplace. Isn't `${publisher}.${name}` as  Extension Id ? @joaomoreno

**Comment by isidorn** [comment]
@holazz marketplace is moving to the new model. @prashantvc can provide more details what happens with the existing name conflicts.

**Comment by prashantvc** [comment]
We are working new extension model where extension names must be unique. As @holazz suggested could you pick different name instead of `open-in-browser`

We will update the error message to be more descriptive

**Comment by prashantvc** [comment]
We have changed the error message for better clarity and call for action to fix the issue

**Comment by prashantvc** [comment]
Keeping it opened until the fix goes live :)

**Comment by radeksimko** [comment]
> @prashantvc can provide more details what happens with the existing name conflicts

@prashantvc Can you explain what will happen to the _existing_ name conflicts? Will they be forced to change IDs - if so, how do you decide which ones stay and which ones will be renamed?

**Comment by prashantvc** [comment]
When we migrate to new system extension identifier will just be `name` from the `package.json`.

In case there is a conflict, for example `ms.python` and `google.python`, we will use the current convention of `{publisher}.{name}`.

**Comment by thegecko** [comment]
I am seeing this error when publishing a new version of an existing extension. The publisher and ID haven't changed AFAICT and there is only one extension with this ID in the marketplace.

<img width="537" alt="Screenshot 2022-07-04 at 13 27 51" src="https://user-images.githubusercontent.com/61341/177154866-5b10b340-64ac-4c6d-83dc-6d3fb1de119b.png">

**Comment by ssbarnea** [comment]
Any chance to address this? I wasted more than hour trying to debug blindly why marketplace rejected the upload with a defective error message.

I had to rename my extension `"name"` to make it unique to the entire marketplace (yep, all publishers), despite the fact that this requirements was never specified.

**Comment by prashantvc** [comment]
@ssbarnea I am extremely sorry about it. We have added a better error message and steps to resolve it.
You should see it soon in the production
