### ISSUE TITLE
failed to install extensions from marketplace

### ISSUE THREAD

**Issue by Zayar-Shane** [microsoft/vsmarketplace#355]
Issue Type: <b>Bug</b>

xhr failed when I try to install extensions from marketplace

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.13.0-37-generic
Restricted Mode: No

**Comment by RIyu200272** [comment]
I had the same issue too tried lots of tutorials but it still doesnt work for me

**Comment by Neelima10735584** [comment]
Hi,
 
Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).
 
Regards,
VS Marketplace Team
