### ISSUE TITLE
VS2022 specific extensions are still not easily visible to users - It's been many months since VS2022 was released

### ISSUE THREAD

**Issue by VisualMicro** [microsoft/vsmarketplace#357]
As you know it is not possible for most extensions to sit in the gallery as both VS2019 and VS2022. 

The gallery is showing 2019 extensions but Microsoft are recommending users install VS2022.

Around the time that VS2022 was in preview there was a thin yellow horizontal strip near the top of the main gallery page that, ineffect, said "Click here to see Visual Studio 2022 extensions". That message disappeared soon after the release of Visual Studio 2022. 

**This means that it is not obvious to users how to find Visual Studio 2022 extensions.** 

**Describe the bug**

It is not obvious to users how to find Visual Studio 2022 extensions from the main gallery page.

**To Reproduce**
1. Go to '[Visual Studio Gallery Main Page](https://marketplace.visualstudio.com/)'

Thank you for looking into this.

**Comment by anupkmr03** [comment]
We have updated the **see more link** on home page that redirects to vs2022 extensions page.
