### ISSUE TITLE
Web version of Marketplace doesn't match text for extension inside VS Code

### ISSUE THREAD

**Issue by pgrivachev** [microsoft/vsmarketplace#358]
Issue Type: <b>Bug</b>

The web version of Marketplace contains text from the previous release. After each release the text of web version of Marketplace is updated but it is always one release behind.

Actual text: https://marketplace.visualstudio.com/items?itemName=Fivetran.dbt-language-server
![image](https://user-images.githubusercontent.com/3650304/160825223-9cc8b4dc-dcbe-4aee-bd17-b415afea3b39.png)

Expected text: 
![image](https://user-images.githubusercontent.com/3650304/160782924-729b2a39-a1b3-4ead-9fed-3bc6a8924d81.png)

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

**Comment by nikhgup** [comment]
@pgrivachev There might be some delay due to cache refresh. Please reopen if issue is constantly reproducible.
