### ISSUE TITLE
Most Popular and Highest Rated show VS 2019 extensions instead of VS 2022

### ISSUE THREAD

**Issue by madskristensen** [microsoft/vsmarketplace#359]
![image](https://user-images.githubusercontent.com/1258877/161085978-3d2f9cae-419e-4f52-ba64-10b8285fa861.png)

**Comment by chgill-MSFT** [comment]
@prashantvc this seems like a quick fix that may be impactful for VS 2022 extension discovery 🙂

**Comment by prashantvc** [comment]
Yeah, I agree. We need to change the query to surface VS 2022 extensions.
VS '19 and '20 being two different entries; '19 entries do come out on top

**Comment by anupkmr03** [comment]
The fix for this issue has been pushed. I will update once the fix has been deployed to production. Thanks
