### ISSUE TITLE
扩展市场图标提示有一个插件可更新，但实则无插件更新

### ISSUE THREAD

**Issue by PCoeur** [microsoft/vsmarketplace#364]
Issue Type: <b>Bug</b>

扩展市场图标右小角显示数字1，人工查看已安装的插件并未有插件需要更新

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by MahalingamVR** [comment]
Please provide more details, with reproducible steps, in English for us to explore further. You could reopen the issue with the detailed steps. 
Thank you.
