### ISSUE TITLE
Unable to complete `vsce login` or `vsce publish`, hangs after "Personal Access Token verification succeeded"

### ISSUE THREAD

**Issue by azaslavsky** [microsoft/vsmarketplace#365]
Whenever I try either of `vsce login [MY_PUBLICATION_GROUP]` or `vsce publish`, the process seems to hang after "The Personal Access Token verification succeeded for publisher [MY_PUBLICATION_GROUP]" prints to my terminal's `stdout`.  I left it on overnight to see if this was due to something just being very slow, but it didn't seem to move, and the version number on my package still has not updated (I'm trying to bump [this extension](https://marketplace.visualstudio.com/items?itemName=fuchsia-authors.language-fidl) from `0.4.0` to `0.4.1`).  Is there something I'm doing wrong, or perhaps there's a bug on the backend?

For reference, I'm on a linux x64 machine, using node version `16.14.2`, npm version `8.5.0`, and vsce version `2.7.0`.

**Comment by joaomoreno** [comment]
@prashantvc Any chance we can get traceability here?

**Comment by prashantvc** [comment]
@azaslavsky

I believe, this is due to policy restricting Global PATs in the AzDO. More [here](https://devblogs.microsoft.com/devops/issue-with-extension-publishing/), please try the suggested workaround in the blog.

In mean time I will ask one of the engineers to take a look at the issue

**Comment by azaslavsky** [comment]
I didn't realize that it was possible to update the extension through the UI as well.   I've gone ahead and used that route - thank you!

**Comment by prashantvc** [comment]
Glad to hear that, but did the workaround helped in any way?

**Comment by azaslavsky** [comment]
I didn't do any of those things - I just went directly to the web UI, and
uploaded it there.  I'm sorry if that's not very helpful!

**Comment by SaiKanth007** [comment]
@azaslavsky closing this issue since you are able to upload the package. Feel free to create a new ticket if you are facing any other issue.
