### ISSUE TITLE
service not available

### ISSUE THREAD

**Issue by pansito** [microsoft/vsmarketplace#367]
Issue Type: <b>Bug</b>

Stops working the session for the ussers

VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by nikhgup** [comment]
@pansito Are you still facing the issue. please feel free to reopen the issue and share more details.
