### ISSUE TITLE
themes not responding

### ISSUE THREAD

**Issue by shrey0258** [microsoft/vsmarketplace#369]
Issue Type: <b>Performance Issue</b>

themes are not getting downloaded always showing error message

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by nikhgup** [comment]
@shrey0258 Please feel free to reopen if you are still facing the issue.
