### ISSUE TITLE
Cant connect to marketplace

### ISSUE THREAD

**Issue by jedidrew50** [microsoft/vsmarketplace#370]
Issue Type: <b>Bug</b>

I clicked the extensions icon. Then I get a message that says unable to search marketplace offline.

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by nikhgup** [comment]
@jedidrew50 Please feel free to open it again if you are still facing the issue.
