### ISSUE TITLE
extensions

### ISSUE THREAD

**Issue by RIyu200272** [microsoft/vsmarketplace#376]
Issue Type: <b>Performance Issue</b>

i tried to download extensions from the market place in VS code , but it appeared fail to do that and the error messages were XHR failed ,I've tried countless of tutorials but it still doesnt work for me 

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by nikhgup** [comment]
@RIyu200272 Please reopen issue if you are still facing it.
