### ISSUE TITLE
unable to create publisher account

### ISSUE THREAD

**Issue by dodu2014** [microsoft/vsmarketplace#379]
**Describe the bug**
unable to create publisher account

**To Reproduce**
1. Go to '[...](https://marketplace.visualstudio.com/)'
2. Click on 'Publish extensions'
3. After completing the basic information, click Create
4. See error, can't go next

**Expected behavior**

**Screenshots**
<img width="666" alt="image" src="https://user-images.githubusercontent.com/15245544/163895996-745785cb-7575-4eb9-b600-e4ce43fb16fb.png">

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser Edge
 - Version 100.0.1185.44 (64 位)

**Comment by ccalfje** [comment]
![image](https://user-images.githubusercontent.com/28975297/172042528-3a58e681-b406-4ff4-a943-3752ad46839d.png)
I encountered the same problem

**Comment by Nitrrine** [comment]
I had same issue, disabling ad blocker resolved that issue

**Comment by madhurivadaligithub** [comment]
Hi @dodu2014 

Thanks for reaching out to us, are you still experiencing the issue?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
