### ISSUE TITLE
  Build tool crashed.  Please contact owner for support. 

### ISSUE THREAD

**Issue by afifahli** [microsoft/vsmarketplace#381]
Issue Type: <b>Bug</b>

  Build tool crashed.  Please contact owner for support.
    Error message: failed to open clipboard

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:13:54.292Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

**Comment by nikhgup** [comment]
Can you please share more details with screenshots.
