### ISSUE TITLE
`code --install-extension Prisma.prisma-insider@[version]` returns `Server returned 503`

### ISSUE THREAD

**Issue by Jolg42** [microsoft/vsmarketplace#382]
We are seeing many `Server returned 503` errors from this command in our CI (GitHub Actions):
```
/workspaces/language-tools/.vscode-test/vscode-linux-x64-1.66.2/VSCode-linux-x64/bin/code --install-extension Prisma.prisma-insider@31.0.852
```
This command is called for each new version (with the corresponding version)

The full source code is located at https://github.com/prisma/language-tools/blob/main/scripts/e2eTestsOnVsix/install_extension.js

The GitHub Action workflow runs:
https://github.com/prisma/language-tools/actions/workflows/e2e_published_vsix.yml
Error log example: https://github.com/prisma/language-tools/runs/6075977680?check_suite_focus=true#step:5:31
```
{
  status: 1,
  signal: null,
  output: [ null, 'Installing extensions...\n', 'Server returned 503\n' ],
  pid: 1875,
  stdout: 'Installing extensions...\n',
  stderr: 'Server returned 503\n'
}
```
<img width="948" alt="Screen Shot 2022-04-19 at 12 40 45" src="https://user-images.githubusercontent.com/1328733/163986731-38f18e53-585a-401c-ac4f-8075eded17ab.png">

Originally reported in https://github.com/microsoft/vscode-test/issues/142 and got the following answer:
>Marketplace service is facing service issues the last couple of days. We are aware of this and we are looking into it.
Soon there should be an issue with more details in the [microsoft/vsmarketplace](https://github.com/microsoft/vsmarketplace) repository

I found the status page at [vsstatus.visualstudio.com](https://vsstatus.visualstudio.com/) and everything is green there 🤔

**Comment by Jolg42** [comment]
Isidor pointed me to this status event on a different URL (https://github.com/microsoft/vscode-test/issues/142#issuecomment-1102878873):
https://status.dev.azure.com/_event/302592133

So it seems that the https://vsstatus.visualstudio.com/ page is out of sync here.

**Comment by prashantvc** [comment]
Are you still facing this issue? Could you let us know if it is resolved

**Comment by Jolg42** [comment]
Looks all good now! 
Thanks 💚
