### ISSUE TITLE
New versions of VS Code extensions published with `vsce publish` are not yet available for download

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vsmarketplace#383]
Yesterday I published a total of 3 versions of 2 different extensions under a single publisher. Fifteen hours later they are still not being offered to VS Code users when checking for updates.

The "Updated" column of the Marketplace management page shows the expected times, but the new versions don't show in the "Manage" tab of the "Reports" page.

![image](https://user-images.githubusercontent.com/6726799/164419548-6f3ad178-13b3-4810-a8c3-5f0c8050ed0d.png)

![image](https://user-images.githubusercontent.com/6726799/164420819-afcd4cdc-cb7c-45ff-b67c-03bcbb4c35e5.png)

![image](https://user-images.githubusercontent.com/6726799/164421130-33da6283-0c8f-42b1-9cb2-53b059931f78.png)

When I first observed the problem yesterday I emailed full details to vsmarketplace@microsoft.com but so far have had no response.

Mysteriously, when I checked the "Manage" tab of the "Reports" page a couple of hours after emailing, the missing versions of one of the extensions had appeared. I checked the report for the other extension, then went back to the report for the first one and the new entries had vanished again.

**Comment by prashantvc** [comment]
Hey, we are investigating this issue, we are experiencing the service disruption.
CC #384

**Comment by gjsjohnmurray** [comment]
Missing entries appeared:
![image](https://user-images.githubusercontent.com/6726799/164560638-01ce0e0f-8b0b-4d31-8c06-f3962a137f2a.png)

![image](https://user-images.githubusercontent.com/6726799/164560724-fbc8e7b0-352d-4c64-9f00-12029d7d2611.png)

But still not showing up as available from VS Code's Extensions view.

And when I go back to the management pages in my screenshots above, the entries are missing again!

**Comment by PEZ** [comment]
We experienced the same with our extension: https://github.com/BetterThanTomorrow/calva/issues/1689

What was extra strange, but also offers a workaround for our users, is that if they:

1. uninstall the extension
2. reload the window
3. install the extension again

the latest version is installed.

**Comment by gjsjohnmurray** [comment]
The missing versions showed up a couple of hours ago, and this time they didn't vanish again. Extensions view from VS Code was able to update to these versions, and I was able to publish another version of one of them without problem.
