### ISSUE TITLE
Disruption in extension update flow

### ISSUE THREAD

**Issue by prashantvc** [microsoft/vsmarketplace#384]
Latest version for some of the extensions (extensions created recently) are not being available on the Extension download page and in the VS Code auto update flow.

The team is investigating the issue and we will keep you posted

**Comment by prashantvc** [comment]
Related issue https://github.com/microsoft/vscode/issues/147801

**Comment by PEZ** [comment]
Hello, just so I understand this correctly. https://github.com/microsoft/vscode/issues/147801 is about an extension that _is_ available on the Extension download page, but that then isn't found during a search for extensions updates. Is this still related given that context?

Also, exactly at 13:37 (CET), I managed to find it with the extension update check. Dunno if you fixed something, but anyway, pretty leet!

**Comment by gjsjohnmurray** [comment]
@prashantvc please provide a status update on this issue. Our inability to get extension updates published (see #383) is becoming a bigger problem with each passing day.

**Comment by gjsjohnmurray** [comment]
Seems to have been resolved now, at least for the two extensions I had problems with (#383).

**Comment by prashantvc** [comment]
We are currently dealing issue with cache refresh in VS Marketplace, it's causing problem with updates and new extension publishing. The team is still working to fix the issue, it's our only priority right now. I will have more details to share soon.

We really appreciate your patience

**Comment by munishgoyal1** [comment]
With the fix in place, the issue has subsided and we are seeing the cache refreshes coming back to normal. We are continuing to monitor actively.
Thank you for your patience.
