### ISSUE TITLE
Request translation plug-in

### ISSUE THREAD

**Issue by wdy2580** [microsoft/vsmarketplace#385]
Issue Type: <b>Feature Request</b>

The translation plug-ins in the plug-in market are difficult to use. Can Microsoft create a plug-in like the translation on the Liesi idea, which can display a translation box in the UI.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
