### ISSUE TITLE
 Sorry, we are unable to load the change quantity experience. Give it few mins and then try again.

### ISSUE THREAD

**Issue by nmgsa** [microsoft/vsmarketplace#386]
I'm getting the following error message when trying to purchase a Visual Studio license from the Visual Studio Marketplace.

_Sorry, we are unable to load the change quantity experience. Give it few mins and then try again._

I've tried in Edge and Chrome.

**Comment by derek-rlb** [comment]
Having the same issue.  Tried Google, Edge, incognito window, from home etc.  Looks to be server-side.  I am trying to add a Visual Studio Professional - monthly subscription to an Azure PAYG subscription.

The following stack trace is shown:

`Sorry, we are unable to load the change quantity experience. Give it few mins and then try again. Error: [{"errorMessage":"An undefined error occurred while attempting to connect to the server. Status code 0: error.","errorMethod":"BuyCustomizationSource.VSSCommerce.getItemPrice","errorType":"SystemError","errorTrace":"{\"stack\":\"TFS.WebApi.Exception: An undefined error occurred while attempting to connect to the server. Status code 0: error.\\n    at g (https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:820:735)\\n    at https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:820:3919\\n    at https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:820:984\\n    at n._func (https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:818:217)\\n    at n._invoke (https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:818:5287)\\n    at https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=:818:4088\",\"message\":\"An undefined error occurred while attempting to connect to the server. Status code 0: error.\",\"name\":\"TFS.WebApi.Exception\",\"status\":0,\"jqXHR\":{\"readyState\":0,\"status\":0,\"statusText\":\"error\"}}"}].`

**Comment by cgremmel** [comment]
Hi. Same here!

Reference #230 .

**Comment by nmgsa** [comment]
Any update on this? I need to purchase a new license by next week and I don't want to go through a reseller. Apparently this has happened before?

**Comment by derek-rlb** [comment]
This has worked for me today.

**Comment by cgremmel** [comment]
Finally I had success using Firefox. Chrome doesn't work.

**Comment by nmgsa** [comment]
Still very much an issue for me. Failed in Chrome, Edge, and a newly installed Firefox.

`Sorry, we are unable to load the change quantity experience. Give it few mins and then try again. Error: [{"errorMessage":"An undefined error occurred while attempting to connect to the server. Status code 0: error.","errorMethod":"BuyCustomizationSource.VSSCommerce.getItemPrice","errorType":"SystemError","errorTrace":"{\"fileName\":\"https://cdn.vsassets.io/bundles/vss-bundle-common-vWJDoSfx5H_lfbFAM0gFByXcK8TRJw4P135wLC-Xzy8w=\",\"lineNumber\":820,\"columnNumber\":735,\"message\":\"An undefined error occurred while attempting to connect to the server. Status code 0: error.\",\"name\":\"TFS.WebApi.Exception\",\"status\":0,\"jqXHR\":{\"readyState\":0,\"status\":0,\"statusText\":\"error\"}}"}].`

**Comment by nmgsa** [comment]
Looks like it's been fixed.
