### ISSUE TITLE
I need to remove or hide some of my old VS extensions. 

### ISSUE THREAD

**Issue by RoryBecker** [microsoft/vsmarketplace#387]
I need to remove or hide some of my old VS extensions. 

The extensions are those placed here -> https://marketplace.visualstudio.com/publishers/CodeRushCommunityContributors

I would gladly log in and do this myself, but I do not know the associated email to do so with.
Can someone tell me the associated email so that  I might attempt a password reset?

If necessary I am happy to cooperate in proving who I am.

Many thanks in advance.

**Comment by nikhgup** [comment]
@RoryBecker Can you please contact us at our support mail VSMarketplace@microsoft.com.
