### ISSUE TITLE
Error loading webview

### ISSUE THREAD

**Issue by EB-CMS** [microsoft/vsmarketplace#388]
Issue Type: <b>Bug</b>

details does't apeare!

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by tyeth** [comment]
Getting this. My only noticible contribution is I had the normal version of microsoft python extension and pylance. I went to install Circuitpython extension and it had an issue (pylance crashed and couldn't be restarted reliably after 5 attempts). I then had a broken install of the circuitpython extensions (it had registered commands in the command palette but they said command not found when executed).
I tried disabling and reenabling and reinstalling circuitpython extension and upgrading ms python extension to preview, not fixed.
![image](https://user-images.githubusercontent.com/6692083/170150140-0f0da2b4-4d75-4aae-8e6a-9060bb1d252b.png)
Version: 1.68.0-insider (system setup)
Commit: 27ea5e48aef2a62b76ab170026ade228ded8abdf
Date: 2022-05-24T10:08:28.490Z
Electron: 17.4.4
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22621
