### ISSUE TITLE
la marketplace ne fonctionne pas

### ISSUE THREAD

**Issue by samuelriboulet** [microsoft/vsmarketplace#389]
Issue Type: <b>Performance Issue</b>

Bonjour. Depuis une semaine, j'essaie d'installer une extension pour fortran.
Malheureusement, quand je lance une quelconque recherche dans la marketplace, il apparaît: "erreur lors de la récupération des extensions. XHR failed". Comment faire pour arranger ça?

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by prashantvc** [comment]
Does it happen with all the extensions? Could you provide steps to reproduce please

**Comment by nikhgup** [comment]
@samuelriboulet Are you still facing the issue.? Please reopen f issue is still present.
