### ISSUE TITLE
Most bizarre: I have my axios calls data printed in the terminal of vsc

### ISSUE THREAD

**Issue by lulalila** [microsoft/vsmarketplace#391]
Issue Type: <b>Performance Issue</b>

I don't know how to explain it better: I'm using Visual Studio Code, Nuxt and Axios, and whenever I refresh my web page I get all the content of my axios call printed in the vsc terminal.

I think I may have made some changes in the google inspector  with vue devtools but I'm not sure. Please help and forgive me for my broken english.

Thanks in advance. 

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by isidorn** [comment]
Please file this question on StackOverflow. This is not an actual reproducible issue, so I will have to go ahead and close it. Thank you
