### ISSUE TITLE
异常退出

### ISSUE THREAD

**Issue by billhuang6277** [microsoft/vsmarketplace#392]
Issue Type: <b>Bug</b>

图形界面无法启动。

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by isidorn** [comment]
Please file a proper issue with reproducible steps in English. 
Once more data is provided we can look into reopening this issue.
Thank you
