### ISSUE TITLE
TABNINE

### ISSUE THREAD

**Issue by jruiz601** [microsoft/vsmarketplace#393]
Issue Type: <b>Bug</b>

TABNINE KEEPS STARTING AND ITS NOT AVAIBLE TO USE IT

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by nikhgup** [comment]
Can you please share more details with screenshots?
