### ISSUE TITLE
Cannot verify publisher

### ISSUE THREAD

**Issue by aslakhellesoy** [microsoft/vsmarketplace#394]
**Describe the bug**

**To Reproduce**
1. Go to https://marketplace.visualstudio.com/manage/createpublisher
2. Fill in a valid URL in `Domain name` (e.g. `https://microsoft.com`)

**Expected behavior**

The `Verify` button is enabled

**Screenshots**

But it's not:

<img width="1196" alt="Screenshot 2022-05-10 at 15 38 28" src="https://user-images.githubusercontent.com/1000/167655312-f4637366-9d69-42dd-a294-d4f3ede3c142.png">

**Desktop (please complete the following information):**
- OS: MacOS
- Browsers: 
   - Firefox version 100.0
   - Chrome version 101.0.4951.54
   - Safari version 15.4

**Additional context**

See #291 and #254

**Comment by nikhgup** [comment]
@aslakhellesoy Verify button will be enabled once you save button is clicked. Please refer https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

**Comment by juancampa** [comment]
What fixed this for me was using the `www.mydomain.tld` version instead of just `mydomain.tld`. I'm guessing the redirect was the issue
