### ISSUE TITLE
coderunner

### ISSUE THREAD

**Issue by HiBEAU** [microsoft/vsmarketplace#395]
Issue Type: <b>Bug</b>

设置使用内置终端，但还运行时使用了内置和外连终端

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:14.619Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

**Comment by isidorn** [comment]
Please file an issue with reproducible steps in English and then we can consider to reopen this. Thanks
