### ISSUE TITLE
feature request: Longer historical view for acquisition trend graph

### ISSUE THREAD

**Issue by Almenon** [microsoft/vsmarketplace#396]
I'd like a longer historical view as the options only let me select the past 90 days. I know that a year ago I had less daily activations of my extension, so I'd love to compare this with my acquisition trend to see what my acquisitions looked like at the time.

**Comment by Almenon** [comment]
Relevant: https://github.com/microsoft/vsmarketplace/issues/353

**Comment by Neelima10735584** [comment]
Closing this issue as we are tracking at https://github.com/microsoft/vsmarketplace/issues/353
