### ISSUE TITLE
Render sponsor button in extension header

### ISSUE THREAD

**Issue by isidorn** [microsoft/vsmarketplace#398]
VS Code is adding sponsor support in the May milestone. More details here https://github.com/microsoft/vscode/issues/107482

For this we will add a new `sponsor` field in the package.json of an extension.
It would be great if the marketplace could render a sponsor button in the marketplace header when the sponsor field is present in the package.json

For example it could look like this. But it should not be called "Github Sponsor", just "Sponsor".

![image](https://user-images.githubusercontent.com/1926584/168780501-1c633ea1-152d-48d9-806c-8e5a9a8313df.png)

![image](https://user-images.githubusercontent.com/1926584/168780592-5f027d1f-07dc-47d1-a8ed-1e5ef9ae1780.png)

fyi @anangaur @sandy081

**Comment by anupkmr03** [comment]
Changes are done and deployed to PPE.

**Comment by isidorn** [comment]
@anupkmr03 awesome thank you!
