### ISSUE TITLE
Publisher verification docs are misleading or incomplete

### ISSUE THREAD

**Issue by mohitsinghs** [microsoft/vsmarketplace#403]
**Describe the bug**

Publisher verification docs are misleading or incomplete in their current state.

**To Reproduce**

Ensure that you are new to marketplace.

1. Go to `https://marketplace.visualstudio.com/manage/publishers/<your-publisher>`
2. Enter domain name in Verified domain and click save 
3. Update DNS records and click on verify.
4. See your verification denied for reasons not listed in docs.
5. Follow up on provided email to be ghosted.

**Expected behavior**
A clear and concise description of the process to verify publisher in the marketplace docs.
![domains](https://user-images.githubusercontent.com/4941333/169922377-3a3d246f-1a38-4909-a5cf-66a5476d7c96.png)

**Current Behaviour**

![email](https://user-images.githubusercontent.com/4941333/169923365-15e95027-9bf4-457e-9ab0-9ce73ef826ab.png)

**Additional Context**

The domain in the question does not serve any ads or malicious content and is open source.

**Comment by nikhgup** [comment]
@mohitsinghs We will verify your domain. Apologies for the issue, it got rejected because of human error.
