### ISSUE TITLE
omnisharp server

### ISSUE THREAD

**Issue by Wasco123** [microsoft/vsmarketplace#405]
Issue Type: <b>Bug</b>

whenever i type p on vscode is showing omnisharp server is not running

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by isidorn** [comment]
Please file a proper issue with reproducible steps. Thank you
