### ISSUE TITLE
Extension update doesn't show up in VS Code if a dependent extension is installed

### ISSUE THREAD

**Issue by DanTup** [microsoft/vsmarketplace#407]
Edit: See second comment - this seems to be related to the dependent extension.

I published v3.42.1 of the Dart extension just over 1hr 30min ago. I got the email saying it had passed the automated checks and the version number on the marketplace page updated almost immediately. Over an hour later, the extension still doesn't show up in VS Code (I've tried running **Check for Extension Updates** and reviewing the web request it makes, and the response from the server still includes the previous version, v3.42.0 that was published around 3 hours ago).

It does normally take ~10 mins for the extension to show up in VS Code, but it's never taken this long before, so I'm unsure whether something has gone wrong. I found https://github.com/microsoft/vscode/issues/147801 which describes a similar problem, but it seems like that issue was resolved.

<img width="867" alt="Screenshot 2022-06-01 at 20 36 00" src="https://user-images.githubusercontent.com/1078012/171487427-b6b83b3d-de13-4e86-8086-f2bef6ca6bde.png">

![Screenshot 2022-06-01 at 20 36 30](https://user-images.githubusercontent.com/1078012/171487475-01da370c-c7e9-45af-b401-def3c68bbd2d.png)

**Comment by DanTup** [comment]
This morning the issues seems to be resolved for me, so wherever the old version was cached may have expired. It definitely feels like there's still a bug here though, a dependent extension shouldn't result in different results (nor should the cache last so long).

**Comment by nikhgup** [comment]
@DanTup There was some intermittent cache issue from our side and because of that latest version was not appearing for some users.

**Comment by isidorn** [comment]
Let me assign to @SaiKanth007 for caching issue so he or his team mates can investigate on the Marketplace side when time allows. Thanks
