### ISSUE TITLE
host de extenciones

### ISSUE THREAD

**Issue by fabianvillera** [microsoft/vsmarketplace#409]
Issue Type: <b>Performance Issue</b>

despues de una actualizacion  
cuando se realiza una serie de pasos en el programa se para el host de extenciones

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
![image](https://user-images.githubusercontent.com/85636327/171616623-2fe0640e-4ebb-4f34-9792-a743ba711039.png)

**Comment by isidorn** [comment]
Please open an issue against VS Code in English. Thanks!
