### ISSUE TITLE
关于Remote-WSL

### ISSUE THREAD

**Issue by Frather233** [microsoft/vsmarketplace#41]
Issue Type: <b>Bug</b>

remote-WSL拓展包删除后，窗口左下角让就显示链接远程窗口的图标并且提示用github登录。

VS Code version: Code - Insiders 1.55.0-insider (d06d2f1d6245ce00b1c36a9cd81a9087d225173e, 2021-03-26T14:01:14.867Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
We only support issues in english
