### ISSUE TITLE
List pre-releases and stable releases separately in the Version History tab

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vsmarketplace#414]
If you look at https://marketplace.visualstudio.com/items?itemName=ms-python.python , you will see the last five releases which can be the last 5 pre-releases thanks to a daily pre-releases. This unfortunately makes it hard to download the latest stable release or older stable releases as they are drowned out within a week a of release.

Having at least the last stable release available to download would be great. Having more than one stable release to download is a bonus. Having a paginated listing of all releases would also cover this.

**Comment by isidorn** [comment]
@brettcannon this makes sense. My feeling is that this will only be done as part of the Marketplace redesign which should hopefully come some time next year.
Assigning to @prashantvc since he has more details. Thanks

**Comment by Neelima10735584** [comment]
closing this issue as we are tracking in https://github.com/microsoft/vsmarketplace/issues/264
