### ISSUE TITLE
"Extensions for the Visual Studio family of products" banner text should be VS Code specific

### ISSUE THREAD

**Issue by isidorn** [microsoft/vsmarketplace#417]
1. Go to https://marketplace.visualstudio.com/vscode
2. Notice banner

![Screenshot 2022-06-14 at 19 24 16](https://user-images.githubusercontent.com/1926584/173639141-baeea4e6-63e3-4aa8-89c1-2ac1de9cc30c.png)

This banner should say something like "Extensions for Visual Studio Code" instead.

fyi @anupkmr03

**Comment by anupkmr03** [comment]
adding @prashantvc to take decision on it. As we are using same banner for Vs Code and VS IDE, If we are changing it for VS code then we should change it for VSIDE as well.

**Comment by isidorn** [comment]
I suggest it says "Extensions for Visual Studio".
Plain and simple. Aligns with https://marketplace.visualstudio.com/azuredevops

**Comment by amit-kulkarni-in** [comment]
I agree with @isidorn , this would avoid confusion when user clicks and enters the Visual Studio Code or Visual Studio search page . This also provides consistency with Azure devops page.

**Comment by isidorn** [comment]
Great. Just to check if there have been any updates here?

**Comment by prashantvc** [comment]
Nothing yet! We will take it up next sprint (Aug)

**Comment by anupkmr03** [comment]
Changes are completed and live on PPE environment.
