### ISSUE TITLE
asdasd

### ISSUE THREAD

**Issue by m-aziz-kurt** [microsoft/vsmarketplace#418]
Issue Type: <b>Bug</b>

adsasdasd

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:37.209Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

**Comment by anupkmr03** [comment]
@m-aziz-kurt  Can you please explain what issue you are facing?

**Comment by amit-kulkarni-in** [comment]
Please provide more information on the issue with reproducible steps.
Once more data is provided we will reopen this issue.
Thank you
