### ISSUE TITLE
The installed extensions need to be grouped

### ISSUE THREAD

**Issue by 522247020** [microsoft/vsmarketplace#421]
Issue Type: <b>Feature Request</b>

Source translation software:

Multiple voice plugins can cause conflicts, and I want to disable other extensions in a single voice development environment.At present, you can only click one by one. Can you add the grouping function and perform batch operation on the expansion of the grouping?

多个语音的插件可能会造成冲突，我想在单个语音的开发环境禁用其他的扩展。目前只能一个一个的点击，是否能添加分组功能，对分组的扩展进行批量操作？
哪位好心人帮忙看看翻译的有没问题？

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by isidorn** [comment]
Hmm the translation is not really correct. Can you please file a new issue in VS Code and try to provide reproducable steps. Thank you!
