### ISSUE TITLE
problema no caractere &nbsp;

### ISSUE THREAD

**Issue by HarielAlmeida** [microsoft/vsmarketplace#423]
Issue Type: <b>Bug</b>

ao colocar o caracter &nbsp; pra obter a função espaço, ele não cumpre a função.
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by pratikgawali-msft** [comment]
Could you share more information along with screenshots?

**Comment by amit-kulkarni-in** [comment]
Please provide more information on the issue with screenshots.
Once more data is provided we will reopen this issue.
Thank you
