### ISSUE TITLE
Unable to update extension with new version

### ISSUE THREAD

**Issue by thegecko** [microsoft/vsmarketplace#425]
**Describe the bug**

It's no longer possible to upload a new version of a VS Code extension via the Web UI

**To Reproduce**

1. Upload a new extension
2. Update the version of the extension and rebuild
3. Upload new version of extension
4. This error is shown:

<img width="537" alt="Screenshot 2022-07-04 at 13 27 51" src="https://user-images.githubusercontent.com/61341/177156972-43253f29-e8c9-45db-807e-886761a9cf60.png">

**Expected behavior**
New version uploaded

**Screenshots**

<img width="537" alt="Screenshot 2022-07-04 at 13 27 51" src="https://user-images.githubusercontent.com/61341/177156972-43253f29-e8c9-45db-807e-886761a9cf60.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Additional context**
Workaround is to delete current extension entirely.

Split from here:

https://github.com/microsoft/vsmarketplace/issues/354#issuecomment-1173762802

**Comment by pratikgawali-msft** [comment]
Hi @thegecko, usually this extension id check is during the creation of new VS Code extension to ensure the extension id used is unique. We could not reproduce this issue. Could you please confirm that you are using `update` option and not the `New extension`?
![image](https://user-images.githubusercontent.com/79199166/177252284-fd21e728-0332-4e38-8755-321709f79cda.png)

**Comment by thegecko** [comment]
Well this is embarrassing, you are absolutely right.

I knew this ability was there, but just couldn't see the ellipses menu because the extension name also has ellipses and they blend together:

<img width="306" alt="Screenshot 2022-07-05 at 09 46 43" src="https://user-images.githubusercontent.com/61341/177288844-41c2c69c-9c48-4402-9d13-86cf2580ecbc.png">

I'll get my coat...
