### ISSUE TITLE
unable to search marketplace when offline 

### ISSUE THREAD

**Issue by aakarshitveersatech** [microsoft/vsmarketplace#427]
Issue Type: <b>Bug</b>

type something in search box

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by edith-ca** [comment]
no funciona css

**Comment by isidorn** [comment]
Yeah, you need internet for this. Closing as by design
