### ISSUE TITLE
Unable to view details of any extension in the Marketplace

### ISSUE THREAD

**Issue by TGiles** [microsoft/vsmarketplace#428]
Issue Type: <b>Bug</b>

When trying to view the details/changelog of any extension in the marketplace, the following error appears in the notifications:

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by kj0171** [comment]
Sorry for the response. Hopefully, this issue was resolved. Closing this ticket.
In case this is unsolved, and you are still facing it, this issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues

Thanks
