### ISSUE TITLE
emmet abbriviation

### ISSUE THREAD

**Issue by Deepak9633** [microsoft/vsmarketplace#429]
Issue Type: <b>Feature Request</b>

I tried to setup my emmet abbriviation setting but it did'nt done.
Please help me to reset it

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by madhurivadaligithub** [comment]
can you please share more details about this issue, if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by madhurivadaligithub** [comment]
@Deepak9633 Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
