### ISSUE TITLE
jules

### ISSUE THREAD

**Issue by julesML** [microsoft/vsmarketplace#432]
Issue Type: <b>Feature Request</b>

probleme d'extennsionss

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by madhurivadaligithub** [comment]
Hi @julesML Can you please share more details about this issue, if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by madhurivadaligithub** [comment]
@julesML Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
