### ISSUE TITLE
Themes displayed with some defects 

### ISSUE THREAD

**Issue by markoseekingalpha** [microsoft/vsmarketplace#433]
Issue Type: <b>Bug</b>

Steps to reproduce
1. Set any theme from  @id:Equinusocio.vsc-community-material-theme
2. Select any line of code in any file

**Actual result:** 
Block for code include strange squares on the right side of the screen 

**Expected result:** 
Block for code should be one color without defects

VS Code version: Code 1.69.1 (Universal) (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:51.333Z)
OS version: Darwin arm64 21.5.0

![image](https://user-images.githubusercontent.com/106514904/179243315-afcff567-534d-48db-9a60-0f0b88356fd8.png)

**Comment by madhurivadaligithub** [comment]
Hi @markoseekingalpha It seems you are facing issue with extension, can you please post under Q & A section of the respective extension for the required solution.
If it is related to VS Code, please create your issue here https://github.com/microsoft/vscode/issues

**Comment by madhurivadaligithub** [comment]
@markoseekingalpha  Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
