### ISSUE TITLE
very slow remote wsl extension

### ISSUE THREAD

**Issue by devmaicon85** [microsoft/vsmarketplace#438]
Issue Type: <b>Performance Issue</b>
sorry for the english. using google translator

I'm using WINDOWS 10 - with WSL 2 ubuntu - I have 16gb of ram. currently using NEXT project with TYPESCRIPT

using the REMOTE WSL extension works fine for a few minutes and is very slow when saving projects. It sometimes takes more than 1min to save or recognize intelisense. Without the remote wsl extension it works fine, much faster even. But when creating new files it does not recognize the syntax having to restart vscode, but much less bother than the crash of Remote WSL. I honestly don't know why this happens.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

**Comment by madhurivadaligithub** [comment]
Hi @devmaicon85  It seems you are facing issue with extension, can you please post under Q & A section of the respective extension for the required solution.

**Comment by madhurivadaligithub** [comment]
Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
