### ISSUE TITLE
help

### ISSUE THREAD

**Issue by carterworkinc06** [microsoft/vsmarketplace#439]
Type: <b>Bug</b>

feedback 

VS Code version: Code - Insiders 1.70.0-insider (9925e5d4d3d355758cd09d26868f0c12a0006828, 2022-07-11T12:20:21.684Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
@carterworkinc06 Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
