### ISSUE TITLE
In Manage Publishers & Extensions page, allow to open reports in a new tab.

### ISSUE THREAD

**Issue by a5hk** [microsoft/vsmarketplace#44]
Currently it is not possible to use middle-click or right-click on this menu item. 

![image](https://user-images.githubusercontent.com/5412540/113193412-2dabe100-9275-11eb-9145-b0719beb146e.png)

**Comment by Neelima10735584** [comment]
Thank you for contacting the VS Marketplace Team. We have implemented this feature in the marketplace. If you still experiencing any issues, please feel free to reach out to us.

Regards,
VS Marketplace Team
