### ISSUE TITLE
Is that possible to transfer an extension to another publisher org?

### ISSUE THREAD

**Issue by JounQin** [microsoft/vsmarketplace#440]
### Clear title 

I have an extension https://marketplace.visualstudio.com/items?itemName=JounQin.vscode-mdx, and want to transfer it to `unifiedjs` scope, I tried to just publish a new extension but failed with

```log
Error: The Extension Id already exist in the Marketplace. Please use the different Id
```

### Review existing feedback

N/A

### Separate Ideas

transfer `JounQin.vscode-mdx` to `unifiedjs.vscode-mdx`

**Comment by ssbarnea** [comment]
no, tried that, the answer was not, and that was for major publisher!

**Comment by JounQin** [comment]
> no, tried that, the answer was not, and that was for major publisher!

That’s sad.

**Comment by madhurivadaligithub** [comment]
Hi @JounQin, if it is related to VS Code, please create your issue here https://github.com/microsoft/vscode/issues

**Comment by JounQin** [comment]
> Hi @JounQin, if it is related to VS Code, please create your issue here [microsoft/vscode/issues](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

I don't think it's related to VSCode directly, we want to transfer VSCode extension's publisher.

**Comment by madhurivadaligithub** [comment]
Hi @JounQin 
Usually, we do not allow transfer of VSCode extensions since it has following consequences: 
1.	Users will not be able to install the older versions of your extensions that got published before the extension transfer from the VSCode.
2.	If this extension is used as a dependency in other extensions by using publisherName.ExtensionName, that would not work.
3.	You need to update all references to this extension with the new publisherName.
 
Please confirm if you are okay with the above consequences, then we can go ahead with the transfer extension request.

**Comment by JounQin** [comment]
> Please confirm if you are okay with the above consequences, then we can go ahead with the transfer extension request.

Thanks, I do confirm them.

**Comment by madhurivadaligithub** [comment]
Thank you, We need your VSID to process this request, please follow below steps to share VSID.
1.       Login to the Marketplace (https://marketplace.visualstudio.com ) with your email address, **which have an owner access to the publisher "unifiedjs"**
2.       After getting logged in, from the same browser window, open https://marketplace.visualstudio.com/_apis/connectiondata 
3.       You should see some JSON data in the window.
4.       Copy paste the output of the page that you see. We are interested in the "id" field of the "authenticated" user.

**Comment by JounQin** [comment]
cc @wooorm who has the owner access to the publisher "unifiedjs"

**Comment by wooorm** [comment]
```json
{"authenticatedUser":{"id":"ccb650b3-241b-6d93-b0c6-bc7b7568509a",...}
```

I believe this is the field you want. Let me know if I need to paste the rest too.

**Comment by madhurivadaligithub** [comment]
@JounQin  @wooorm Thanks for the details, completed the extension transfer to new publisher.

**Comment by JounQin** [comment]
> @JounQin @wooorm Thanks for the details, completed the extension transfer to new publisher.

Thanks for transferring and https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx just works!

**Comment by wooorm** [comment]
Thanks @madhurivadaligithub!

@JounQin Can you update the links in the readme etc? Thanks!

**Comment by JounQin** [comment]
> Thanks @madhurivadaligithub!
> 
> @JounQin Can you update the links in the readme etc? Thanks!

I'm just going to do this.

**Comment by JounQin** [comment]
https://marketplace.visualstudio.com/items?itemName=unifiedjs.vscode-mdx v1.0.1 is finally been released!
