### ISSUE TITLE
I can't install any extension

### ISSUE THREAD

**Issue by JoseLuisUicab** [microsoft/vsmarketplace#441]
Issue Type: <b>Bug</b>

when installing an extension I get the error
Error installing extension. See the [log] (command:workbench.action.showWindowLog) for more details.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: Yes

**Comment by madhurivadaligithub** [comment]
Hi @JoseLuisUicab can you please share more details about this issue, if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by madhurivadaligithub** [comment]
Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
