### ISSUE TITLE
i cant install live server

### ISSUE THREAD

**Issue by nitishdhiman706** [microsoft/vsmarketplace#442]
Issue Type: <b>Feature Request</b>

cant install live server extension

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by madhurivadaligithub** [comment]
Hi @nitishdhiman706 can you please share more details about this issue, if it is related to VS Code 
Please create your issue here https://github.com/microsoft/vscode/issues
