### ISSUE TITLE
VSCode Marketplace shows the latest version of pre-release instead of released version

### ISSUE THREAD

**Issue by mohitsuman** [microsoft/vsmarketplace#445]
Does this issue occur when all extensions are disabled?: Yes/No

### **Steps to Reproduce:**

1. Open Visual Studio Code Marketplace and Browse to the [VSCode Java extension](https://marketplace.visualstudio.com/items?itemName=redhat.java)
2. The download version (under More Info) shows the pre-release version of the extension

<img width="245" alt="Screenshot 2022-07-25 at 5 16 32 PM" src="https://user-images.githubusercontent.com/3133356/180771226-45c92a19-c1cb-4928-b0a9-9ede1870d2eb.png">

The VSCode Java extension supports pre-release versions. But on the Marketplace UI it should be showing the released version, so that users are able to understand what is the working release and do not get confused with pre-release versions.

This pre-release version is also used when we need to use the version badge in the readme using [imgshields](https://img.shields.io/visual-studio-marketplace/v/redhat.java?style=for-the-badge&label=VS%20Marketplace&logo=visual-studio-code) or [vsmarketplace](https://img.shields.io/visual-studio-marketplace/v/redhat.java?style=for-the-badge&label=VS%20Marketplace&logo=visual-studio-code). (These are for references)

_Note_: This will be true for any extension supporting pre-release.

### **Resolution:**

The VSCode Marketplace UI should display the version information pointing to the released version and display the same on the marketplace UI, under More Info.

**Comment by isidorn** [comment]
@mohitsuman this request makes sense and something we have already discussed with the Marketplace team.
Assigning to @prashantvc for now

**Comment by mohitsuman** [comment]
Hi @prashantvc , is there any update on getting this fixed in the marketplace UI?

**Comment by amey2688** [comment]
@prashantvc any update on this issue? this is something which can help many other users as well

**Comment by isidorn** [comment]
@anupkmr03 this would be great to have if it is not a huge investment.

**Comment by amey2688** [comment]
any update? this change will be very usefull for us as well

**Comment by isidorn** [comment]
Currently no updates. But I know this is something that the Marketplace team is aware of. Thanks for reaching out.

**Comment by prashantvc** [comment]
@amey2688, we know what's causing the issue, we will be picking this up in the next sprint`

**Comment by Neelima10735584** [comment]
Hi, 

Thank you for contacting the VS Marketplace Team. The issue has been resolved, and we able to see latest version of extension on VS Marketplace. If the error persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
