### ISSUE TITLE
make extension (plugins) cleo script for VSC  (sanny builder)

### ISSUE THREAD

**Issue by Samthapa76** [microsoft/vsmarketplace#447]
i wonder if you can make extension for VSC 
its a Sanny builder which is cleo editor it don't sound much interested here but as you can say just 10 to 15 million user using this days you can see your self and yea it will be great if it support full functions to edit and create script from VSC to .cs scripts

**Comment by madhurivadaligithub** [comment]
Hi @Samthapa76 can you please share more details about this issue, if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by madhurivadaligithub** [comment]
Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
