### ISSUE TITLE
Cannot install any extensions

### ISSUE THREAD

**Issue by StephenGhool** [microsoft/vsmarketplace#449]
Issue Type: <b>Feature Request</b>

Good day, recently my vscode extensions were randomly uninstalled and now I have an error installing all extensions. Some of the errors are as follows:
- Error while installing 'Python' extension. Please check the log for more details
- Unable to install the extension. Please Exit and Start VS Code before reinstalling.
- "Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'

 Things I have tried so far
- I have tried logining in with a different account
- restarting vscode and my laptop
- reinstalling vs code

If anyone has adivce on how to proceed, please let me know. thank you 

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by isidorn** [comment]
I can not reproduce this issue. If you can reproduce please file a new issue in the vscode repository with exact steps and a gif demonstrating your issue
