### ISSUE TITLE
Maybe "bitHound" should be removed from Approved Badges

### ISSUE THREAD

**Issue by liyuhang1997** [microsoft/vsmarketplace#45]
bitHound is dead. https://github.com/commitizen/cz-cli/issues/529

https://code.visualstudio.com/api/references/extension-manifest#approved-badges

**Comment by madhurivadaligithub** [comment]
Hi @liyuhang1997 ,

Thanks for contacting the VS Marketplace Support Team. Can you please confirm if you're still experiencing the issue? If so, could you provide more details so we can investigate further

Regards,
VS Marketplace Team
