### ISSUE TITLE
改了css 页面样式不变

### ISSUE THREAD

**Issue by xiaowenwei0622** [microsoft/vsmarketplace#450]
Type: <b>Bug</b>

每次需要重新运行一遍

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.19042
Modes:

**Comment by madhurivadaligithub** [comment]
can you please share more details about this issue, if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by madhurivadaligithub** [comment]
Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
