### ISSUE TITLE
I cant download any extensions/ the extensions I have are not working.

### ISSUE THREAD

**Issue by andrewstephen74** [microsoft/vsmarketplace#451]
Type: <b>Bug</b>

I tried to download python extensions and I am not able to.

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @andrewstephen74 can you please share more details about this issue (any error messages/screenshots), if it is related to VS Code extensions
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by madhurivadaligithub** [comment]
@andrewstephen74  Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
