### ISSUE TITLE
Cannot edit the overview of a Visual Studio extension without uploading a new version

### ISSUE THREAD

**Issue by reduckted** [microsoft/vsmarketplace#452]
**Describe the bug**
I want to edit the overview of a Visual Studio extension to say that it's now deprecated. When trying to save changes to the overview, I am told that an extension with the same version already exists.

**To Reproduce**
1. Publish a Visual Studio extension.
2. Go to _Manage Extensions_.
3. Find the extension you published and select _Edit_.
4. Edit the _Overview_.
5. Click _Save & Upload_.
6. You receive the error: "Upload failed: The extension with version <version> already exists."

**Expected behavior**
The extension's overview is updated without needing to upload a new version of the extension.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 103.0.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by nikhgup** [comment]
@reduckted This is expected behavior as per recent changes. There is no change allowed for extension without updating version of extension.

**Comment by prashantvc** [comment]
This change guarantees end users that the extension is immutable, description, license and any other metadata is mapped to an extension version. 
It's a minor inconvenience to publishers like you, but it's a first step in many trust and security features coming to the marketplace

**Comment by reduckted** [comment]
Thanks @prashantvc, that's understandable. Is there any way to deprecate an extension? #292 seems to be pretty close to that, so I might add a comment over there explaining my situation.

**Comment by christianshay** [comment]
Hi there,
What about situations where a typo is made when the vsix is published? 
In the case of VS Code, the metadata is included inside the VSIX and can be rigorously tested by a testing team etc.

But in the case of Visual Studio, this information is entered onto a web page and the person has one shot to get it right.

It seems heavy handed to require a whole new release if a typo is made. Perhaps this restriction should have waited until Visual Studio Marketplace accepted  this information as part of the VSIX.

**Comment by abpiskunov** [comment]
+1 to this. Metadata that is in VSIX indeed should be immutable and it is. However edit markdown, images or other easily editable parts of the extension should be done without rebuilding whole vsix. I would ask you to re-consider this.

**Comment by dzsquared** [comment]
the statements about the new version number being required contradict the UI, which makes mistakes even more inevitable.

<img width="520" height="318" alt="Image" src="https://github.com/user-attachments/assets/f3d46f83-56bf-4660-9631-b4b451cb86b5" />

**Comment by snehara99** [comment]
@prashantvc This is a major blocking issue for our team. We are planning to remove an extension and do not have a new vsix to publish. We simply need to update the overview to say that this extension is going to be removed on a certain date.
