### ISSUE TITLE
vs code marketplace is showing offline and not connecting to internet.

### ISSUE THREAD

**Issue by vivekm33na** [microsoft/vsmarketplace#453]
Type: <b>Bug</b>

I am connected to internet but vs code marketplace shows i am offline. please help me

actual result : unable to search the marketplace when offline, please check your network connection

expected result : i should be able to search for extensions

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22622
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @vivekm33na can you please share more details about this issue, if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by madhurivadaligithub** [comment]
Hi @vivekm33na  if you still facing the issue 
Please create your issue here https://github.com/microsoft/vscode/issues
