### ISSUE TITLE
There are marketplace entries for linking to copyright streaming media

### ISSUE THREAD

**Issue by michealespinola** [microsoft/vsmarketplace#454]
Type: <b>Bug</b>

An example marketplace search of, "one piece red", will return multple entries specific to viewing this anime online. I recommend using quotes in the search.

Entries such as these are starting to pollute normal search results when there are matching terms.

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @michealespinola can you please share more details about this issue, if it is related to VS Code extensions
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by michealespinola** [comment]
There are multiple bogus extensions. Just search the marketplace for "one piece red" and you will see them. There are currently about ~13 of them that match that particular search. Here is an example marketplace URL:

https://marketplace.visualstudio.com/items?itemName=OnePieceRedDeutsch.One-Piece-Red-hd-stream-Deutsch

**Comment by madhurivadaligithub** [comment]
@michealespinola Thanks for taking time to report this. We took these extensions down from the Marketplace.
