### ISSUE TITLE
Reformulate text as question

### ISSUE THREAD

**Issue by diegoandresalvarez** [microsoft/vsmarketplace#456]
Type: <b>Bug</b>

There is a message that says in the PYTHON extension that says

**We noticed you're using a conda environment. If you are experiencing issues with this environment in the integrated terminal, we recommend that you let the Python extension change "terminal.integrated.inheritEnv" to false in your user settings.**

And then the options YES or NO

Could you please ask a question? There is not a question here involved. I do not know what to answer.

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:15.055Z)
OS version: Linux x64 5.15.0-46-generic
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @diegoandresalvarez can you please share more details about this issue, if it is related to VS Code extensions
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by madhurivadaligithub** [comment]
Hi @diegoandresalvarez, since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
