### ISSUE TITLE
problem espace de travail

### ISSUE THREAD

**Issue by kamalouchah** [microsoft/vsmarketplace#457]
Type: <b>Feature Request</b>

ispace de travail

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:06.872Z)
OS version: Windows_NT ia32 6.1.7601
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @kamalouchah can you please share more details about this issue, if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by madhurivadaligithub** [comment]
Hi @kamalouchah, since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
