### ISSUE TITLE
Unable to find java executable

### ISSUE THREAD

**Issue by BeardedDaddy** [microsoft/vsmarketplace#458]
Type: <b>Performance Issue</b>

Good morning I am getting a java runtime notification. I have already clicked on the "Get Java Runtime" and downloaded the lasted version of java, restarted my computer and get the same message. I am using VS Code version 1.70.1. Is this a known issue. Also VS Code keeps asking me to pick an interpreter. It is set up to use Python but periodically I get this message. Please help.

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by isidorn** [comment]
Please ask this question on StackOverflow. This is not a VS Code marketplace issue.
