### ISSUE TITLE
Can't respond to Question, because Captcha is required that is not displayed

### ISSUE THREAD

**Issue by SabotageAndi** [microsoft/vsmarketplace#460]
**Describe the bug**
When I want to responde to a question, I only get the response  that there was an error loading data.

![image](https://user-images.githubusercontent.com/859801/185407082-f4246683-25ea-4ba9-aa4a-f4038a056085.png)

The error in the dev tools console says that a ReCaptcha token is invalid. But I don't get a captcha displayed at all.
![image](https://user-images.githubusercontent.com/859801/185407232-a0517951-d96e-4d2e-864f-f39686df2719.png)

Also there is an error from Javascript that is loaded via Google Tag Manager.
![image](https://user-images.githubusercontent.com/859801/185407769-6c46f3f9-c66e-401f-b588-938caf58d570.png)

**To Reproduce**
1. Go to Q&A 
2. Press on Reply 
3. Enter an Reply into the popup
4. Press Submit
5. See Error message

**Expected behavior**
Response is posted.

Also this should work if you are running ad-blocker. Google TagManager is blocked in this case.

**Screenshots**
![image](https://user-images.githubusercontent.com/859801/185407605-4ec57f9d-c9ad-41dc-bc9a-0b1c8a3bb72a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 104.0.1293.54

**Additional context**
Used AdBlocker:
- uBlock Origin
- pi Hole

**Comment by SaiKanth007** [comment]
@SabotageAndi Can you please try now. We have temporarily disabled the reCapthca on our Q&A, Ratings page for maintenace work. So, you should be able to reply now

**Comment by SaiKanth007** [comment]
Closing this as fixed. Please feel free to create a new issue if you see this issue again
