### ISSUE TITLE
git解决冲突变的不方便

### ISSUE THREAD

**Issue by xiangxinfei** [microsoft/vsmarketplace#462]
Type: <b>Feature Request</b>

以前合并文件冲突的时候  可以直接点击保留当前更改 或者  保留传入的更改这样的选项按钮 .  现在没有了  变得很不方便

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.17763
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @xiangxinfei  can you please share more details about this issue, if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues
