### ISSUE TITLE
java

### ISSUE THREAD

**Issue by Okan-ucan** [microsoft/vsmarketplace#463]
Type: <b>Bug</b>

java programı nasıl çalıştırılıyor

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:37:58.957Z)
OS version: Windows_NT ia32 6.1.7601
Modes:

**Comment by Ankit-Pani** [comment]
Java programlarını çalıştırmak için VSCode kullanmayın, bu hatayı başlangıçta ben de yaptım. Bunun yerine IntelliJIDea'yı kullanın. Bana Daha Sonra Teşekkür Edeceksiniz!

**Comment by isidorn** [comment]
Closing since this issue does not have reproducable steps
