### ISSUE TITLE
Can't add people to the VS Code extension acquisition page

### ISSUE THREAD

**Issue by yitao-mutable** [microsoft/vsmarketplace#464]
**Describe the bug**
Can't add people to the VS Code extension acquisition page

**To Reproduce**
1. Go to dev.azure.com
2. Add the new user
3. New user go to acquisition page
4. No permission to see

**Expected behavior**
The acquisition page showing how many install everyday

**Screenshots**
User not seeing this: 
<img width="241" alt="image" src="https://user-images.githubusercontent.com/106548387/187274050-3c930b7a-fce9-47b4-af51-4255c2d4c8f9.png">

**Additional context**
Tried adding the new user to every permission menu I can find in the Azure dev page and extension management page

**Comment by yitao-mutable** [comment]
any updates?

**Comment by madhurivadaligithub** [comment]
Hi @yitao-mutable If you still facing issue, please visit publisher manage page
https://marketplace.visualstudio.com/manage/publishers/<your publisherid>, under "members" tab add required people with **reader** access

**Comment by yitao-mutable** [comment]
worked, thanks
