### ISSUE TITLE
Trending, Most Popular, and Highest Rated is wrongly filtered to VS 2019 instead of 2022

### ISSUE THREAD

**Issue by madskristensen** [microsoft/vsmarketplace#465]
**Describe the bug**
The list of extensions shown in the 3 swim lanes target VS 2019 instead of VS 2022.

**To Reproduce**
1. Go to https://marketplace.visualstudio.com/vs
2. Look at the swim lanes

**Expected behavior**
VS 2022 was released in November of 2021. We need to show VS 2022 related extensions on the front page of the Marketplace.

![image](https://user-images.githubusercontent.com/1258877/187500784-b20a5e91-b90b-4df3-8734-f514d7619114.png)

**Comment by SaiKanth007** [comment]
@madskristensen Currently the Trending carousel doesn't differentiate the extensions based on the VS version. Infact all of the carousels on the home page are all VS Version agnostic.

**Comment by madskristensen** [comment]
Interesting. Well, both the `See more` links for both **Most Popular** and **Highest Rated** shows a VS 2019 filtered page. In that case, it should not add a version filter at all

**Comment by SaiKanth007** [comment]
Yes, See more ticket link should ideally a 'any' version filter and no 'VS2019'. We will create an issue on our backlog for this.

**Comment by anupkmr03** [comment]
I am working on this will update once the fix will be live.

**Comment by anupkmr03** [comment]
The fix for this issue has been pushed. I will update once the fix has been deployed to production. Thanks!

**Comment by ErikEJ** [comment]
This has NOT been fixed, and should be re-opened and given high priority - see #547

**Comment by Giorgi** [comment]
This is definitely not fixed.

**Comment by ErikEJ** [comment]
@Giorgi #547 is still open. Please add a comment there thanks 
/cc @madskristensen

**Comment by Giorgi** [comment]
@ErikEJ I thought that issue was about popular extensions only.

**Comment by ErikEJ** [comment]
@Giorgi it is about the "Highest rated" Lane- are the other lanes also broken?

**Comment by Giorgi** [comment]
Trending is still broken.

**Comment by ErikEJ** [comment]
@Giorgi how can you tell??

**Comment by Giorgi** [comment]
@ErikEJ There are several extensions that have been published for over a year, have no rating/review, very few installs but are still trending. For example this one:

![image](https://github.com/microsoft/vsmarketplace/assets/580749/dee78980-fb5d-41d9-ac15-d919818800fe)
