### ISSUE TITLE
Marketplace page is always outdated

### ISSUE THREAD

**Issue by pgrivachev** [microsoft/vsmarketplace#468]
Type: <b>Bug</b>

Marketplace page is always outdated. 

See https://marketplace.visualstudio.com/items?itemName=Fivetran.dbt-language-server
And the same in VS Code extension page.
Last gif is missing in marketplace.

![image](https://user-images.githubusercontent.com/3650304/187755014-dc991b5c-d674-458c-ba63-70fede2040b0.png)

Also [changelog](https://marketplace.visualstudio.com/items/Fivetran.dbt-language-server/changelog) in marketplace always contains only previous version, not current. While in VS Code I can see the latest changelog.

![image](https://user-images.githubusercontent.com/3650304/187757301-7498b544-3f1a-4e65-a7dd-ba86e6d79834.png)

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin x64 21.6.0
Modes:

**Comment by ssbarnea** [comment]
Just to add some more heat to it, while prereleases were made available more than an year ago, the web interface does not display them in any distinguishable way. The list is truncated at something like 6 entries and there is no way to check older releases. If you happened to implement continuous delivery... the entire page becomes useless.

But the root of the issues around here is that if nobody works on them, they will not get fixed.

I have being watching the tracker and only support issues were fixed, none that involved code change was fixed.

**Comment by pgrivachev** [comment]
Thank you @JatinSanghvi, the issue is resolved.
