### ISSUE TITLE
Extensions Installation

### ISSUE THREAD

**Issue by sahwala** [microsoft/vsmarketplace#469]
Type: <b>Bug</b>

When i trying to install PlatformIO IDE the installation process take so long, i have tried to restart the application, reset the connection, flush the dns, reinstall the App. But nothing changed. But if i install other extension like, notepad++ keymap, Remote - WSL, it can install without any problem. Any sugestion to me ?

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @sahwala 
the issue related to vscode, please create your issue here https://github.com/microsoft/vscode/issues

**Comment by isidorn** [comment]
I can not reproduce. Thus closing this, as @madhurivadaligithub suggests if you can reproduce please create a new issue in VS Code with steps.
