### ISSUE TITLE
Unable to add Extension

### ISSUE THREAD

**Issue by Shubham01dev** [microsoft/vsmarketplace#471]
Type: <b>Bug</b>

while searching extension for redux a Error comes with a statement that(Error while fetching xention. XHR failed ) 

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
@Shubham01dev  This issue related to vs code, please create your issue here https://github.com/microsoft/vscode/issues

**Comment by isidorn** [comment]
I can not reproduce. Thus closing this, as @madhurivadaligithub suggests if you can reproduce please create a new issue in VS Code with steps.
