### ISSUE TITLE
Please unlock my VSIX ID - cannot reupload my extension anymore

### ISSUE THREAD

**Issue by PiotrKarczmarz** [microsoft/vsmarketplace#472]
**Describe the bug**
I cannot reupload my extension [ContextKeeper](https://marketplace.visualstudio.com/items?itemName=ContextKeeper.ContextKeeper ) after deleting it (I had weird download issue when it was uploaded the first time). **My VSIX ID to unlock: 9694e3b5-4ef8-48f9-b44c-86dc26bd3a68**

**To Reproduce**
1. Go to [Publish New VS Extension](https://marketplace.visualstudio.com/manage/publishers/contextkeeper/newvsextension)
2. Click on "Upload extension->Drag and Drop a file here or **click** to upload."
4. See error: "The VSIX ID in the provided file is already in use. Every extension needs to have an unique ID. Provide a file with an unique ID"

**Expected behavior**
Successfully reuploading the extension with **VSIX ID: 9694e3b5-4ef8-48f9-b44c-86dc26bd3a68**

**Screenshots**
![image](https://user-images.githubusercontent.com/8102322/188831311-f1214293-4e6c-4a85-bc08-5fbed708339a.png)

**Additional context**
Currently changing VSIX ID to a new one will impact a lof of Beta users and will complicate update process on the Visual Studio side. I want to avoid that. This is the main reason I want to use the same ID.

**Comment by madhurivadaligithub** [comment]
@PiotrKarczmarz  We fixed this issue, can you please retry now?

**Comment by ucheNkadiCode** [comment]
@madhurivadaligithub We are having this issue right now for our Visual Studio extension. What can we do? Is there a workaround?

**Comment by PiotrKarczmarz** [comment]
> @PiotrKarczmarz We fixed this issue, can you please retry now?

Yes! It's working now 😀 Thank you @madhurivadaligithub!
