### ISSUE TITLE
Extention not install

### ISSUE THREAD

**Issue by shayan7109** [microsoft/vsmarketplace#475]
Type: <b>Bug</b>

"Error While installing'*'extention.please check the log for more detalis."i recive it from vs code and after click try downloading manually VS say:"once downloaded,please manually install the downloaded VSIX of'myextention'"
what is problem?

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by isidorn** [comment]
I can not reproduce this. Sounds like a VS Code issue. I suggest you open an issue in the VS Code repo with exact reproducable steps.
