### ISSUE TITLE
What do the acquisition metrics mean exactly?

### ISSUE THREAD

**Issue by symmb** [microsoft/vsmarketplace#477]
Hi! I have some questions about the metrics shown on the "Acquisition" tab of the reports page and I couldn't find any documentation on this.

  - Does the "Install from VS Code" count include every download initiated from VS Code (`ext install ...`, "Install" button)? What about installs from extension packs and updates? Also, does that include web versions of VS Code like GitHub Codespaces?
  - Does "Download from Marketplace" only include the direct download links on the extension page on the website?
  - Does "Page views" only count page views on the website or also in VS Code? If it includes VS Code, does it also extensions that were not installed from the Marketplace?

**Comment by SaiKanth007** [comment]
- Does the "Install from VS Code" count include every download initiated from VS Code (ext install ..., "Install" button)? What about installs from extension packs and updates? Also, does that include web versions of VS Code like GitHub Codespaces? _1. Yes, the install count is for every download from VSCode
2. Yes, it includes the web version download as well
3. The install count for the extension packs are incremented as well._
  
- Does "Download from Marketplace" only include the direct download links on the extension page on the website?  _Yes_

- Does "Page views" only count page views on the website or also in VS Code? If it includes VS Code, does it also extensions that were not installed from the Marketplace? - _It includes only from the Marketplace portal_

**Comment by symmb** [comment]
Cool, thanks for the clarification!
