### ISSUE TITLE
Unable to update / install some extensions

### ISSUE THREAD

**Issue by ssdishere** [microsoft/vsmarketplace#480]
Type: <b>Bug</b>

I'm unable to update extensions such as intelliji, excel viewer, pylance. But im able to install other extensions such as docker and firefox debugger. I'm able to uninstall excel viewer but now i'm not able to install it again. It shows: "Error while installing 'Excel Viewer' extension. Please check the [log](command:workbench.action.showWindowLog) for more details."

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by ssdishere** [comment]
i also tried changing the dns but it's not working

**Comment by ssdishere** [comment]
also i tried to install it via the marketplace using the .visx file. But it shows installation failed.

**Comment by madhurivadaligithub** [comment]
Hi @ssdishere Its related to vs code, please create your issue here https://github.com/microsoft/vscode/issues
