### ISSUE TITLE
Сan't publish the extension

### ISSUE THREAD

**Issue by dsbasko** [microsoft/vsmarketplace#481]
When trying to publish an extension, it gives an error: `An item with the same key has already been added`.
However, the extension is packaged and works fine with manual installation via vsix.

I tried:
- Change the name
- Change the version
- Change the publisher

**Comment by Neelima10735584** [comment]
Hi,

Thank you for contacting the VS Marketplace Team. The issue has been resolved, and we can now see your extension on VS Marketplace. If the error persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
