### ISSUE TITLE
unable to lose the software

### ISSUE THREAD

**Issue by Krishnapatel0127** [microsoft/vsmarketplace#482]
Type: <b>Bug</b>

its showing two unsaved files.i am unable to close the software.

VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin arm64 21.3.0
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
@Krishnapatel0127 , Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by isidorn** [comment]
I can not reproduce. Thus closing this, as @madhurivadaligithub suggests if you can reproduce please create a new issue in VS Code with steps.
