### ISSUE TITLE
Download/Install progress

### ISSUE THREAD

**Issue by JonFromMech** [microsoft/vsmarketplace#483]
Type: <b>Feature Request</b>

Please integrate progress monitoring during installs.

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Please create your issue here https://github.com/microsoft/vscode/issues
