### ISSUE TITLE
FatBug

### ISSUE THREAD

**Issue by Jesuis33** [microsoft/vsmarketplace#484]
Type: <b>Bug</b>

HAHAHHA

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @Jesuis33  Can you please share more details about this issue, if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues
