### ISSUE TITLE
extension issue

### ISSUE THREAD

**Issue by MURTAZAJAN1122** [microsoft/vsmarketplace#485]
Type: <b>Bug</b>

hi sir , 
i hope everyone will be fine my problem is that the extension of python is not installing in my vs studio please solve my problem.
thanks

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 6.3.9600
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
@MURTAZAJAN1122 Can you please share more details about this issue (any error messages)

**Comment by madhurivadaligithub** [comment]
Hi @MURTAZAJAN1122  Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.

**Comment by MURTAZAJAN1122** [comment]
Error in Installation of python extension

**Comment by SaiKanth007** [comment]
Can you share more details about the error you are getting?
A screenshot of the error or recording of your issue would help us better understand the issue.

**Comment by MURTAZAJAN1122** [comment]
I an already shared.

**Comment by MURTAZAJAN1122** [comment]
No response.

**Comment by isidorn** [comment]
Closing until issue has reproducable steps.
