### ISSUE TITLE
Marketplace won't allow me to verify my domain ownership

### ISSUE THREAD

**Issue by PrismaPixelStudios** [microsoft/vsmarketplace#487]
When configuring my organization as a publisher on Visual Studio Marketplace, I keep receiving an error that reads "The domain url provided could not be reached" when I hit save on the Details tab after entering my domain (https://prismapixel.studio) into the Domain name input box of the Verified domain section. The Verify button also does not become enabled after entering my domain in the input box.

1. Go to the PrismaPixel Studios page in the Manage Publishers & Extensions area (https://marketplace.visualstudio.com/manage/publishers/prismapixel-studios)
2. Click on the Details tab.
3. Scroll down to Verified domain and enter https://prismapixel.studio in the Domain name input box.
4. Click Save at the top as the Verify button doesn't become enabled after entering the domain.
5. See the error banner at the top.

I would expect the Verify button to become enabled after entering my domain in the Domain name input box.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 105.0.1343.42
 
![image](https://user-images.githubusercontent.com/85934823/192658070-89db74d4-e6b9-49e3-87d5-aedbd92eacd3.png)

**Comment by SaiKanth007** [comment]
Before we save the domain for a publisher, we do a HEAD call to the domain mentioned and check for a 200 response. In this case, I see that the HEAD calls give a 503 and not 200 response.

When I tried the same from postman or local server it perfectly works fine. Does the site expect any specific cookie or block calls from any specific hosts?

**Comment by pratikgawali-msft** [comment]
@PrismaPixelStudios please feel free to open the issue again if you are still facing the same issue.
