### ISSUE TITLE
Support new GitHub Actions badge SVG url format

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vsmarketplace#49]
From https://github.com/microsoft/vscode-vsce/issues/553:

> It seems that instead of `/workflows`, GitHub Action badge URLs now look like `/actions/> workflows`: https://github.com/microsoft/vscode-vsce/issues/552#issuecomment-814242903
> 
> We need to update the RegEx to:
> 
> ```
> /^https:\/\/github\.com\/[^/]+\/[^/]+\/(actions\/)?workflows\/.*badge\.svg/
> ```
> 
> Before we do this on VSCE, we need appropriate changes to the Marketplace service.

cc @prashantvc

**Comment by mayankmaheshwari18** [comment]
Thanks @joaomoreno for letting us know. 
Currently we use the following regex for validating github badges: ```^https:\\/\\/github\\.com\\/[^/]+\\/[^/]+\\/workflows\\/.*badge\\.svg```

Just to confirm, should we change this to ```/^https:\/\/github\.com\/[^/]+\/[^/]+\/(actions\/)?workflows\/.*badge\.svg/``` ?

**Comment by joaomoreno** [comment]
Correct

**Comment by mayankmaheshwari18** [comment]
Raised a PR https://dev.azure.com/mseng/AzureDevOps/_git/AzureDevOps/pullrequest/608587
Will let you know once we deploy this to PROD.

**Comment by mayankmaheshwari18** [comment]
@joaomoreno This is deployed to PROD.

**Comment by joaomoreno** [comment]
Thanks @mayankmaheshwari18!
