### ISSUE TITLE
Mannually adding extention

### ISSUE THREAD

**Issue by EvilDarkSoul** [microsoft/vsmarketplace#491]
Type: <b>Bug</b>

Find an extention to download (I Am trying to install PlatformIO IDE) have VSCode ask you to try and manually install the extention, Go to the download link (Press "Try Downloading manually") and download to downloads folder (MacOS (Big Sur)) once downloaded return to VSCode and press "Install from VSIX..." go into the downloads folder and select the .vsix file that you just downloaded. And press install. After this nothign happens it doesnt inform you that it succesfully or failed to install the extention

VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @EvilDarkSoul 
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by isidorn** [comment]
It shows up in the extensions view as installed. Though maybe we do not show the installed list of extensions once an extension is installed via vsix. We should. If we do not please open a new issue in the vscode repo.
Closing this for now.
