### ISSUE TITLE
Videos on extension pages should have a max width

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vsmarketplace#495]
## Bug
For a large video used on an extension page:

```
<video src="https://github.com/mjbvz/test-vscode-ext/raw/main/test.mp4"></video>
```

The marketplace currently does not appear to set a `max-width`. This results in the video overflowing in to the rest of the page:

![Screen Shot 2022-10-03 at 3 58 16 PM](https://user-images.githubusercontent.com/12821956/193700695-631a0833-66d6-49ef-93ba-201ecd5bfbef.png)

[This test extension](https://marketplace.visualstudio.com/items?itemName=bierner.test-test) demonstrates the issue. Images correctly set a max-width with the css:

```
.markdown img {
    max-width: 100%;
}
```

For https://github.com/microsoft/vscode/issues/134514

**Comment by isidorn** [comment]
@anupkmr03 the fix for this should be low hanging. Could we look into this one please?

**Comment by SaiKanth007** [comment]
@isidorn I am looking into this and will push the fix as part of our next deployment

**Comment by isidorn** [comment]
@anupkmr03 just informed me the fix for this issue has been pushed.
He will comment here once the fix has been deployed to production. Thanks
