### ISSUE TITLE
android emulator is closed because of an internal error gpu found id 10de device id 0x1f99

### ISSUE THREAD

**Issue by jijinshaji** [microsoft/vsmarketplace#497]
Type: <b>Bug</b>

open gls emulation failed to initalize . please consider the following troubleshooting steps

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by isidorn** [comment]
Please file the issue with reproducable steps. Until that is done I am going to go ahead and close this.
