### ISSUE TITLE
Unable to publish Jupyter extension to marketplace

### ISSUE THREAD

**Issue by xavierdecoster** [microsoft/vsmarketplace#5]
@DonJayamanne commented on [Thu Feb 18 2021](https://github.com/microsoft/vscode/issues/116888)

Steps to Reproduce:

1.Attempt to upload the vsix to the marketplace portal
2.We get an error indicating its failing, here's the issue:
![Screen Shot 2021-02-17 at 14 55 35](https://user-images.githubusercontent.com/1948812/108279355-59459280-7131-11eb-8f74-b9309c3d730c.png)
![Screen Shot 2021-02-17 at 15 04 22](https://user-images.githubusercontent.com/1948812/108279422-70848000-7131-11eb-86f3-71877ee06abc.png)

@sandy081 /cc

Does this issue occur when all extensions are disabled?: N/A

---

@sandy081 commented on [Thu Feb 18 2021](https://github.com/microsoft/vscode/issues/116888#issuecomment-781313392)

cc @prashantvc 

---

@prashantvc commented on [Thu Feb 18 2021](https://github.com/microsoft/vscode/issues/116888#issuecomment-781331494)

@DonJayamanne could you email to vsmarketplace@microsoft.com? 
Is this is the extensions? https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

---

@DonJayamanne commented on [Thu Feb 18 2021](https://github.com/microsoft/vscode/issues/116888#issuecomment-781553910)

We managed to solve this issue. A `.so` file was incldued into the extension accidentally (due to python package) & we believe thats what caused the package to get rejected. Would be good to get a more meaningful message.

Thanks, closing as we have resolved this.

---

@DonJayamanne commented on [Mon Feb 22 2021](https://github.com/microsoft/vscode/issues/116888#issuecomment-782550839)

Re-opening as we're running into this yet again, & it would be good to know what's wrong with the package.
I've excluded *.so files, and still failing.
I have attached the file here.
[ms-toolsai-jupyter-insiders.4.vsix.zip](https://github.com/microsoft/vscode/files/6014055/ms-toolsai-jupyter-insiders.4.vsix.zip)

> Is this is the extensions? marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
Yes

Will send the email as well.

---

@prashantvc commented on [Sat Feb 20 2021](https://github.com/microsoft/vscode/issues/116888#issuecomment-782555503)

@rheajain can you take a look at this please?

---

@DonJayamanne commented on [Mon Feb 22 2021](https://github.com/microsoft/vscode/issues/116888#issuecomment-783613631)

@prashantvc @rheajain Is there anyone we can email to try to expedite this? Thanks

---

@DonJayamanne commented on [Mon Feb 22 2021](https://github.com/microsoft/vscode/issues/116888#issuecomment-783628569)

@rchiodo @IanMatthewHuff @greazer /cc

---

@DonJayamanne commented on [Tue Feb 23 2021](https://github.com/microsoft/vscode/issues/116888#issuecomment-783767615)

@fiveisprime /cc

**Comment by xavierdecoster** [comment]
@DonJayamanne looks like this was caused by a duplicate entry in the VSIX.

Validation failed because the VSIX contains a duplicate entry for a file only differing by casing.

Unzipping locally using 7-Zip triggered an alert trying to overwrite a file that just got extracted as part of the same operation (note the difference in casing here):

* B**c**ryptGenRandom.exe
* B**C**ryptGenRandom.exe
 
Modifying the VSIX to exclude one of these seems to have fixed the validation error. 

The modified version was uploaded successfully to our test environment and could be installed in VS Code (requires v1.54.0 Insiders build though, as that’s what you’re targeting).

**Comment by DonJayamanne** [comment]
Thanks.

**Comment by DonJayamanne** [comment]
@xavierdecoster Thanks, creating a separate issue to that the marketplace returns a more meaningful message in the future so we don't end up in this same situation, else it takes too long to diagnose the error.
