### ISSUE TITLE
go live

### ISSUE THREAD

**Issue by hitesh781** [microsoft/vsmarketplace#500]
Type: <b>Bug</b>

when i use to click on go live after my html code it dose not show me How my website look but it open the folder where it stored and showing to download

VS Code version: Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:22:48.346Z)
OS version: Windows_NT x64 6.0.6002
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @hitesh781 
Please create your issue here https://github.com/microsoft/vscode/issues
