### ISSUE TITLE
Publishing VS Code extension fails with virus check

### ISSUE THREAD

**Issue by eamodio** [microsoft/vsmarketplace#501]
It seems like all(?) vscode extensions are getting rejected for a failed virus check. I've seen this on 2 extensions now (both are built from CI with no dependency changes since the last successful publish very early this AM). And other extension authors are seeing the same failures.

I've also downloaded the vsix, scanned it locally, and scanned the zipped files and it all comes up clean -- as expected.

**Comment by anupkmr03** [comment]
Hi @eamodio, Sorry for the inconvenience, due to an internal issue virus scan was failing. Can you please re-upload the package again. It should work now.

**Comment by eamodio** [comment]
Thanks. Yeah it seems to have resolved itself.
