### ISSUE TITLE
cannot install  python extension

### ISSUE THREAD

**Issue by omprakashvenkatesh** [microsoft/vsmarketplace#503]
Type: <b>Bug</b>

want to  python 

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19041
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues
