### ISSUE TITLE
Unable to file an extension on the marketplace

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vsmarketplace#509]
I'm a member of the VS Code team and am attempting to publish an extension to the marketplace `mstools-ai.jupyter-renderers`
For some reaason this is now failing in the marketplace with the following error message in the marketplace management page

`Extension failed Virus check. Please submit a valid extension.`

We're publishing the extension via the Azure Pipelines and there haven't been any errors there.
https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers

![Screen Shot 2022-10-28 at 03 59 25](https://user-images.githubusercontent.com/1948812/198352982-66f7b479-e522-471d-b04e-cc4f7c24a2be.png)

**Comment by prashantvc** [comment]
@anupkmr03 can you take a look at this please?

**Comment by DonJayamanne** [comment]
we managed to publish another version, it's all ok now

**Comment by prashantvc** [comment]
@DonJayamanne that's good to know :)
I am curious about how you fixed it

**Comment by DonJayamanne** [comment]
> am curious about how you fixed it

just published another version, and that worked
