### ISSUE TITLE
Remote-SSH Extension Wrong Configuration File Loading

### ISSUE THREAD

**Issue by naveedbasharat06** [microsoft/vsmarketplace#510]
Type: <b>Bug</b>

I din't know from where. But for one of my host is is loading wrong configuration file have "a" in configpath
its in Remote-SSH Connection 

VS Code version: Code 1.72.2 (Universal) (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:30.254Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @naveedbasharat06 if it is related to VS Code
Please create your issue here https://github.com/microsoft/vscode/issues

**Comment by naveedbasharat06** [comment]
Sure
