### ISSUE TITLE
not able to search extensions

### ISSUE THREAD

**Issue by vivek-consensys** [microsoft/vsmarketplace#512]
Type: <b>Bug</b>

error displayed:- "Error while fetching extensions.XHR failed"

Not able to download any extensions

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by kj0171** [comment]
@vivek-consensys 
Can you share more details like console log and also the network tab.
Are you using a VPN client or some local firewall? Can you turn these off and retry?

**Comment by kj0171** [comment]
A couple of other similar issues were reported but end up being transient and do not exist now. Hopefully, the issue was transient and is resolved now. Closing the ticket. In case the issue exists, please feel free to re-open the ticket. Thanks.
