### ISSUE TITLE
Downloading Process

### ISSUE THREAD

**Issue by Ismaelito86** [microsoft/vsmarketplace#514]
Type: <b>Feature Request</b>

Please, I would be better and so good, if when I'm installing a new extension, it would show a progress bar indication or a circular progress indicator. Please

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Ismaelito86 If the issue is related VS Code, please create your issue here https://github.com/microsoft/vscode/issues
