### ISSUE TITLE
VSCode Marketplace readme pages are not updated with latest readme

### ISSUE THREAD

**Issue by mohitsuman** [microsoft/vsmarketplace#516]
Once the extension is released on Marketplace (with an update version, readme, and gifs), the VS Marketplace landing page for the extension still uses the old readme/gifs.

Even though the Extensions section in VSCode is updated after the release. I see on other issues this is due to the Marketplace cache. And the team was supposed to triage and fix it. But the issue still persists with extensions.

VSCode extension: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-openshift-connector

Can this be fixed on priority?

**Comment by prashantvc** [comment]
This happens to delay in updating the cache, the right content will get updated after about 30mins. Let us know if it takes long for your extensions.

Please feel free to reopen the issue, if you continue to have this problem

**Comment by mohitsuman** [comment]
@prashantvc It still shows an outdated readme at the marketplace than what we have at the GitHub repo. The extension update was released a week before. Can you please open this issue and check for this extension https://marketplace.visualstudio.com/items?itemName=redhat.vscode-openshift-connector

**Comment by prashantvc** [comment]
reopening, it shouldn't take a week to update. We will prioritise the issue :)

**Comment by mohitsuman** [comment]
@prashantvc Its been more than 2 weeks but I don't see the Marketplace UI reflecting the changed readme. It does not look like the cache is getting replaced by the new content. Any update on this?

**Comment by prashantvc** [comment]
We are working in it, the fix will be available end of this month

**Comment by prashantvc** [comment]
This is fixed, could you verify please?

**Comment by prashantvc** [comment]
duplicate of #415
