### ISSUE TITLE
Extensions as something like "Watch movies Online"

### ISSUE THREAD

**Issue by fabiocarvalho-planet** [microsoft/vsmarketplace#520]
Type: <b>Bug</b>

Opened Extensions and search in the marketplace for "CUE" (needed a better .cue processing extension), then along the list it shows extensions to "watch movies online" with descriptions like "HIT the ROAD (2022) Completa ONLINE...", "Cuevana! Animales fantásticos: Los secretos..." and "Sonic} 2: La | vER ~Pelicula {2022}...".

Are these real VSCode extensions? 
There's no moderation on submitted extensions to the marketplace? If not, it is possible to have malicious extensions that stole information, inject malicious software, etc...

Regards.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

![image](https://user-images.githubusercontent.com/103422323/202469535-6e52f959-22c9-46cf-a2f2-68d3ea694220.png)

**Comment by nikhgup** [comment]
@fabiocarvalho-planet these extensions are removed from Marketplace. Thanks for bringing this to our notice.

**Comment by amit-kulkarni-in** [comment]
@fabiocarvalho-planet , Thanks for bringing to our notice. We do scan for malicious content whenever any publisher uploads their extensions. We continue to improve the moderation of such spam extensions in the ecosystem.
