### ISSUE TITLE
I'm experiencing the same problem https://marketplace.visualstudio.com/items?itemName=4006wayne.wconvert

### ISSUE THREAD

**Issue by wjdesign** [microsoft/vsmarketplace#522]
I'm experiencing the same problem I'm experiencing the same problem https://marketplace.visualstudio.com/items?itemName=4006wayne.wconvert

**Comment by nikhgup** [comment]
@wjdesign Can you please explain the issue you are facing? The link you mentioned is giving 404 error because publisher of this extension might have removed the extension.

**Comment by wjdesign** [comment]
I tried to make my own extension for my company, but there is a message
"Extension validation error" that I can't publish.
I don't know why because there is nothing suspicious in my extension.

[image: image.png]

It look like success when I use this command by searching:  "vsce show
4006wayne.wconvert", but it show "Extension validation error" on my
Marketplace manage page.
how can I validate this?


Nikhil Gupta ***@***.***> 於 2022年11月21日 週一 下午1:52寫道：

**Comment by wjdesign** [comment]
I can't successfully search for my extension either.

[image: image.png]

Nikhil Gupta ***@***.***> 於 2022年11月21日 週一 下午1:52寫道：

**Comment by nikhgup** [comment]
@wjdesign You can retry the upload, it should work now. This was because of some combination of words blocked to control spam extension on Marketplace.

**Comment by wjdesign** [comment]
It's work!!! Thanks so much!!

Nikhil Gupta ***@***.***> 於 2022年11月21日 週一 晚上8:04寫道：
