### ISSUE TITLE
Fix the Extension Mutation Zoo

### ISSUE THREAD

**Issue by amalic** [microsoft/vsmarketplace#525]
Every time I set up a new VSCode development environment I have to guess which extension is the original extension.

I think it would be good practice to encourage extension developers to contribute to existing code instead of cloning or forking them, and offering their own version with even the same name and logo stolen from the original extension. Issue with those hobby projects is that most of them get stale while they divert users from the original extension which is constantly being updated.

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, this issue was fixed. If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
