### ISSUE TITLE
TCL formatting break

### ISSUE THREAD

**Issue by ajainitbhu** [microsoft/vsmarketplace#526]
Type: <b>Bug</b>

TCL Formatting break if we use the below sentence,
puts $fileId "$id|$name|[regsub -all {\n} $class { }]"

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.3.18-22-default

**Comment by isidorn** [comment]
Please file in https://github.com/microsoft/vscode/issues
With clear reproducable steps. Thank you
