### ISSUE TITLE
Cannot verify publisher

### ISSUE THREAD

**Issue by rodrigomedeirosf** [microsoft/vsmarketplace#528]
**Describe the bug**
I'm trying to create a new publisher, and I've informed a valid url domain and received the error "The domain url provided cloud not be reached"

**To Reproduce**
1. Go to 'https://marketplace.visualstudio.com/manage/createpublish'
2. Type "https://stackspot.com" in "Domain name"
3. Type another required fields and click on "Create"
4. See error "The domain url provided cloud not be reached"

**Expected behavior**
The Verify button is enabled

**Screenshots**
![error](https://user-images.githubusercontent.com/1902202/205996576-2d0551b5-1f67-4f8a-9189-fbc278384565.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey version 12.5
 - Browser Google Chrome
 - Version 107.0.5304.110 (arm64)

**Comment by kj0171** [comment]
Before we save the domain for a publisher, we do a HEAD call to the domain mentioned and check for a 200 response. In this case, I see that the HEAD calls give a 403 and not 200 response.

When I tried the same from postman or local server it perfectly works fine. Does the site expect any specific cookie or block calls from any specific hosts?

**Comment by rodrigomedeirosf** [comment]
Thank you for fast response the question. We've created a temporary role in our WAF to force the match. I've resent the form with the domain information and worked.

Have a nice day.
