### ISSUE TITLE
Acqusition funnel 30 days and till date

### ISSUE THREAD

**Issue by RandomFractals** [microsoft/vsmarketplace#53]
**Describe the bug**
I am having a problem interpreting your acquisition funnel for newly published extension.

Should not those two numbers be the same?

Also, do you check for unique visitors for page views?

btw, that ext. is showing 29 installs on ext. page:  https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.snippets-viewer

What do your 30 days and Till Date represent then?

![vs-marketplace-acquisitions](https://user-images.githubusercontent.com/656833/114114404-661b7280-98a6-11eb-8de6-43d17be0aed3.png)

**Comment by isidorn** [comment]
@prashantvc would know the answers here

**Comment by Neelima10735584** [comment]
Closing this issue as we are tracking at https://github.com/microsoft/vsmarketplace/issues/353
