### ISSUE TITLE
MR

### ISSUE THREAD

**Issue by marks199** [microsoft/vsmarketplace#534]
Type: <b>Feature Request</b>

HELLO WORLD

VS Code version: Code - Insiders 1.75.0-insider (f076d553210e9ea65e7bccbfa2f7a786c10fcab2, 2022-12-09T09:11:59.691Z)
OS version: Windows_NT x64 10.0.25252
Modes: Restricted
Sandboxed: Yes
Connection to 'vscode-remote' could not be established  No remote extension installed to resolve codespaces.

**Comment by madhurivadaligithub** [comment]
@marks199 If the issue is related to VS Code, please file in https://github.com/microsoft/vscode/issues
