### ISSUE TITLE
Update SVG badge source

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vsmarketplace#537]
Related to https://github.com/microsoft/vscode-vsce/pull/798

Please replace `vsmarketplacebadge.apphb.com` with `vsmarketplacebadges.dev` in the allowed SVG domain list.

**Comment by anupkmr03** [comment]
I have updated the list on PPE environment, please verify and confirm. Accordingly, execute the same on PROD.

**Comment by anupkmr03** [comment]
@joaomoreno do we maintain the similar kind of list on client side as well? If yes is that list updated?

@amit-kulkarni-in / @prashantvc Please update the marketplace documentation for the same.

**Comment by isidorn** [comment]
@anupkmr03 no, we do not have the list on the VS Code client. We only have the list in `vsce`. And Joao just updated it via https://github.com/microsoft/vscode-vsce/pull/798/files
