### ISSUE TITLE
My extension host is terminated and I can't get to make use of them

### ISSUE THREAD

**Issue by vicok2003** [microsoft/vsmarketplace#538]
Type: <b>Bug</b>

Extension host terminated unexpectedly 3 times within the last 5 minutes

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.15063
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
@vicok2003 If the issue is related to VS Code, please file in https://github.com/microsoft/vscode/issues
