### ISSUE TITLE
[l10n-platform] Untranslated strings in Marketplace

### ISSUE THREAD

**Issue by deakjahn** [microsoft/vsmarketplace#539]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: irrelevant
- OS Version: irrelevant

Steps to Reproduce:

1. Publish an extension using `l10n` throughout the `package.json` file
2. Visit the Marketplace, Feature Contributions tab
3. Instead of the processed texts, all you see are the l10n keys extracted directly

**Comment by Neelima10735584** [comment]
Hi,

Thanks for reaching VS Marketplace Team, If the error is still persisting, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
