### ISSUE TITLE
XHR failed

### ISSUE THREAD

**Issue by izsal** [microsoft/vsmarketplace#540]
Type: <b>Bug</b>

2022-12-21 11:23:45.033 [error] RequestService#request (browser) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {}
2022-12-21 11:23:45.034 [error] Error: XHR failed
    at b.onerror (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:72:1428)

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 5.19.0-26-generic
Modes:
Sandboxed: No

**Comment by JatinSanghvi** [comment]
Hi @izsal 

Let us know if the issue still exists at your end. If so, we would require the below information to help us understand the nature of the problem. These are specifically requested by our CDN provider to start investigating.

First ensure that the problem still persists.

1. HTTP requests exported in HAR format. To do this,
    a. Ensure that the extension page is still not loading.
    b. In Visual Studio Code, open Developer Tools (Ctrl+Shift+I).
    c. Switch to the Network tab and enable the 'Disable Cache' option.
    d. Open the extension page again.
    e. Right click on any request and select Copy > Copy all as HAR.
    f. Save the copied text in a file and email it to us (VSMarketplace [at] microsoft [period] com).
    
2. Headers copied after opening page: http://wpc.2dcc.edgecastcdn.net/002DCC/n2/.
    Go to the page, expand 'Client Info', copy all rows underneath, save it in a file and email it to us.

3. Traceroute output

    * If on Windows:
        1. Go to [https://winmtr.en.uptodown.com/windows/download]() and download the ZIP file.
        2. Open WinMTR64.exe from inside the ZIP file. This should open the WinMTR application.
        3. Enter host as 'ms-vscode.gallerycdn.vsassets.io' and click 'Start'.
        4. Let it run for a minute and then click 'Stop'.
        5. Click 'Export HTML' button to export the text to a file.
        6. Email this file to us.
    * On Linux:
        1. Ensure that traceroute utility is installed: `sudo apt install traceroute`
        2. Run command: `traceroute ms-vscode.gallerycdn.vsassets.io`.
        3. Copy the text output and email it to us.

**Comment by JatinSanghvi** [comment]
Since the GitHub issue is more than a month old, I doubt that it is still present. We will wait until the end of this week for your response. Thanks.

**Comment by fawwazman** [comment]
> Since the GitHub issue is more than a month old, I doubt that it is still present. We will wait until the end of this week for your response. Thanks.

hello bro, can u please help me to fix the problem. i have a problem that is i cant download extension from vs code automatically. when i want to download it there is xhr failed and i gotta to download the extension manual from google

**Comment by JatinSanghvi** [comment]
> hello bro, can u please help me to fix the problem. i have a problem that is i cant download extension from vs code automatically. when i want to download it there is xhr failed and i gotta to download the extension manual from google

Hi @fawwazman, it would be easier to help you if you can collection the information as I requested in https://github.com/microsoft/vsmarketplace/issues/540#issuecomment-1411490797 and email them to us. You can set the email subject to 'XHR failed' so that we can find it out easily.

**Comment by JatinSanghvi** [comment]
We haven't received an update on this GitHub issue or over email. I will close this one. In case we receive an email with the requested information, I will follow up with the respective person over that email thread.
