### ISSUE TITLE
No way to fix a Visual Studio extension Overview without publishing a new version.

### ISSUE THREAD

**Issue by ycherkes** [microsoft/vsmarketplace#544]
Some time ago **it was possible** to correct a mistake in the **Overview** section of the Visual Studio extension without publishing a new version.

1. Go to **Manage** -> **...** -> **Edit**
2. Fix the Overview section
3. Scroll down to the end of page and click 'Save & Upload' button.

Expected result: the extension overview has been successfully updated.
Actual result: "Upload failed: The extension with version x.x.x.x already exists."

**Comment by madhurivadaligithub** [comment]
Hi @ycherkes 
“The extension with version already exists”, it was expected for VS extensions, meaning for any change to VS extension now needs the extension version to be bumped up. 
This change guarantees end users that the extension is immutable, description, license and any other metadata is mapped to an extension version. 
It's a minor inconvenience to publishers like you, but it's a first step in many trust and security features coming to the Marketplace

**Comment by ycherkes** [comment]
My opinion: if user downloads two different versions of vsix - they must be binary different (not version only). Otherwise it can cause a minor inconvenience to users. 
Do you mean that readme.md is now a part of the vsix package?

**Comment by prashantvc** [comment]
@ycherkes No, the readme file is not part of the vsix package yet; but that is our goal.
The extension overview is tied to the specific version of the package. Extension users and enterprise users do not trust when the overview or any metadata is changed without bumping the version
