### ISSUE TITLE
Cannot get publishing information

### ISSUE THREAD

**Issue by yannick-beot-sp** [microsoft/vsmarketplace#545]
I created publisher information after authenticated with my GitHub account. I successfully published an extension and updates:
https://marketplace.visualstudio.com/items?itemName=yannick-beot-sp.vscode-sailpoint-identitynow

However, now, when I'm connected with my GitHub account, I'm recognized as my personal email account and I do not have access anymore to the publishing information.

**To Reproduce**
1. Go to https://marketplace.visualstudio.com/items?itemName=yannick-beot-sp.vscode-sailpoint-identitynow
2. Click on 'Sign in'
3. Choose "Sign in with GitHub"
4. Fill in the username and password of the GitHub account
5. After being authenticated, click "continue"
6. To the question "Stay signed in?", click either Yes or No. Note: at this step, the identifier shown is my personal email address and not my github account.
7. I'm redirected to the marketplace page. At this moment, the identifier shown is my personal email address account.
8. Click on "Marketplace" in the top left or go to https://marketplace.visualstudio.com/
9. Click on [Publish extensions](https://marketplace.visualstudio.com/manage)

**Expected behavior**
After being authenticated, I shall be able to see my publisher info (yannick).

**Screenshots**
Here is the result of clicking "Publish extensions"
![2022-12-29 11_00_26-Clipboard](https://user-images.githubusercontent.com/82362286/209935526-bc85654b-9500-46ee-a706-dc8713767c86.png)

**Comment by madhurivadaligithub** [comment]
Hi @yannick-beot-sp Could you please redirect to your publisher manage page (https://marketplace.visualstudio.com/manage/publishers/yannick) and let us know if you are facing any issues?

**Comment by yannick-beot-sp** [comment]
Hi @madhurivadaligithub 
When I try to connect to https://marketplace.visualstudio.com/manage/publishers/yannick and authenticating using my GitHub account, I get the following error.
![image](https://user-images.githubusercontent.com/82362286/210112173-ebe4b3b6-f53c-48ec-bb91-36688a5ade39.png)

I tried using an in-private session.

**Comment by amit-kulkarni-in** [comment]
@yannick-beot-sp : Please reach out to us on VSMarketplace@microsoft.com so that we can get additional sensitive information needed to resolve the issue. Closing this issue so that sensitive information is not shared in this forum.
