### ISSUE TITLE
Terms of use: clarification needed

### ISSUE THREAD

**Issue by deemp** [microsoft/vsmarketplace#548]
Dear marketplace admins,

Recently, I decided to finalize the project [nix-vscode-marketplace](https://github.com/AmeerTaweel/nix-vscode-marketplace) and built a workflow [here](https://github.com/deemp/nix-vscode-extensions) that collects the info about VS Code extensions as Nix expressions. My only goal is to eventually let Nix users use a set of VS Code extensions on per-project basis.

To achieve this goal, I use the following workflow:

1) The extension list is fetched using the publicly available API `https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery/`.
2) [nvfetcher](https://github.com/berberman/nvfetcher) uses some publicly available API to generate from this list the Nix expressions of the following form:

```nix
dbaeumer-vscode-eslint = {
    pname = "dbaeumer-vscode-eslint";
    version = "2.3.0";
    src = fetchurl {
      url = "https://dbaeumer.gallery.vsassets.io/_apis/public/gallery/publisher/dbaeumer/extension/vscode-eslint/2.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-eslint-2.3.0.zip";
      sha256 = "sha256-fR/glHPANL1Jg7rN3Dfzw3+ISiTXb+pWvj0sqgpYGS0=";
    };
    name = "vscode-eslint";
    marketplacePublisher = "dbaeumer";
    marketplaceName = "vscode-eslint";
    publisher = "dbaeumer";
  };
```
3) These expressions are combined into a single file.

That said, I access the VS Code Marketplace API on steps `1)` and `2)`.

As it's stated in the [Terms of Use](https://cdn.vsassets.io/v/M190_20210811.1/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf):
```
You may not access, search, obtain or attempt to obtain any Offerings, materials, or
information through any means other than Microsoft’s publicly supported interfaces (including, without
limitation, through automated harvesting, ‘spidering’ or ‘scraping’ the Marketplace).
```

My current assumption is that I access the Marketplace via `Microsoft’s publicly supported interfaces` and no other means. 

Could you please confirm that my workflow indeed complies with Microsoft's policy regarding the access to VS Code extensions?

**Comment by prashantvc** [comment]
@deemp as a developer I am in support of your extension. But, let me consult with our legal team if your use can in violation of any terms of use, if they are, we can find a workaround or better a way

**Comment by deemp** [comment]
Hello, @prashantvc! Do you have any news?

**Comment by prashantvc** [comment]
Not yet unfortunately. I will have some details by end of the week

**Comment by prashantvc** [comment]
Can you email me privately at prchol@microsoft.com
