### ISSUE TITLE
Cannot connect to the marketplace

### ISSUE THREAD

**Issue by Chakicodes** [microsoft/vsmarketplace#55]
Issue Type: <b>Bug</b>

Hi there,

I cannot connect to the extensions marketplace for a while. When it will be possible?

VS Code version: Code 1.55.1 (08a217c4d27a02a5bcde898fd7981bda5b49391b, 2021-04-07T15:06:02.360Z)
OS version: Windows_NT x64 10.0.19042

**Comment by amit-kulkarni-in** [comment]
Please reopen the bug if you still see that you are unable to connect to marketplace.
