### ISSUE TITLE
Html is not support

### ISSUE THREAD

**Issue by shivsharanyadav9516** [microsoft/vsmarketplace#551]
Type: <b>Feature Request</b>

HTML coding is not work

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @shivsharanyadav9516  This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
