### ISSUE TITLE
Extension data not shown on home page 

### ISSUE THREAD

**Issue by skofman1** [microsoft/vsmarketplace#553]
**Describe the bug**
When clicking on an "ecosystem" tab on home page, and then clicking on a different tab, when you go back to the original tab, some extensions are not properly rendered. 

![image](https://user-images.githubusercontent.com/16807822/211424614-1d01ca8b-2769-4b7c-8a84-9c0a31b1df57.png)

**To Reproduce**
1. Go to https://marketplace.visualstudio.com (let's assume that 'Visual Studio' tab is presented) 
2. Click on  'VS Code' tab
3. Click on 'Visual Studio' tab
4. See that not all extensions are rendered (screenshot above)

**Expected behavior**
No white boxes...

// cc @munishgoyal1 , @prashantvc

**Comment by anupkmr03** [comment]
Looking into it.

**Comment by skofman1** [comment]
@anupkmr03 , could you share an update pls?

**Comment by lyndaidaii** [comment]
Fix will be deployed soon this week.

**Comment by skofman1** [comment]
[heart]         Svetlana Kofman reacted to your message:
________________________________
