### ISSUE TITLE
Python extensions are disabled sometimes

### ISSUE THREAD

**Issue by Cha-Minho** [microsoft/vsmarketplace#554]
Issue Type: <b>Bug</b>

I don't know the exact reproducing steps.
Sometimes when I turn on my vscode, extensions related to python such as pylance and python indent are disabled.
In extensions tab, the extensions are installed but the icons are faded.
I cannot re-enable them or disable them. The Only thing I can do is uninstall and re install them.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by madhurivadaligithub** [comment]
Hi @Cha-Minho This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
