### ISSUE TITLE
can not download extension

### ISSUE THREAD

**Issue by xelland042** [microsoft/vsmarketplace#559]
Type: <b>Bug</b>

Do not working marketplace, showing recommendation without image of extension

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by roytaishi** [comment]
Hey, can you provide some more details about this issue? Some screenshots can be helpful.

**Comment by madhurivadaligithub** [comment]
Hi @xelland042  Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
