### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by umutugurlu1** [microsoft/vsmarketplace#560]
Type: <b>Bug</b>

ı dont setup anything 
ıt say "Error while installing 'Language Support for Java(TM) by Red Hat' extension. Please check the log for more details."
ı dont get ıt

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @umutugurlu1 This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
