### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by yewentao256** [microsoft/vsmarketplace#561]
Type: <b>Bug</b>

In a cluster(offline), I try to install python extension by file.
So I download the extension file `ms-python.python-2023.1.10171013.vsix`, and then run `code --install-extension ms-python.python-2023.1.10171013.vsix`

It shows
 
```bash
Unable to install extension 'ms-python.python' as it is not compatible with VS Code '1.74.3'.
```

I tried several other versions of ms-python, none of them work.  

Thanks for helping!

VS Code version: Code 1.74.3 (Universal) (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T17:07:18.579Z)
OS version: Darwin x64 21.5.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-957.el7.x86_64
Connection to 'SSH: 1984' could not be established  The connection timed out
Remote OS version: Linux x64 5.10.124-linuxkit

**Comment by madhurivadaligithub** [comment]
Hi @yewentao256 This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues

**Comment by yewentao256** [comment]
okk, thank you all the same~
