### ISSUE TITLE
I can't install any extensions

### ISSUE THREAD

**Issue by Cocochalula** [microsoft/vsmarketplace#562]
![Screenshot_20230121_123109](https://user-images.githubusercontent.com/123266221/213882309-f3a7b4a7-ea6d-4483-ab08-20407e99d577.png)
Type: <b>Bug</b>

when I try to install any extension it just says "Error while installing 'C#' extension. Please check the log for more details." and I tried for hours to fix it and it would not work.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @Cocochalula This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues

**Comment by isidorn** [comment]
Maybe duplicate of https://github.com/microsoft/vscode/issues/172989
Please file an issue in GitHub repo as Madhuri suggests
