### ISSUE TITLE
create extension publisher

### ISSUE THREAD

**Issue by kenyonwang** [microsoft/vsmarketplace#563]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by roytaishi** [comment]
Hey, can you explain the issue you are facing? Some screenshots can be helpful.

**Comment by kenyonwang** [comment]
Hi Roytaishi, 
Thank you for your concern. Below is what I did. 
1. Click Create publisher
2. Filled the basic information. And keep all the others empty
3. Click Create.
4. Keep the below page and never go to the next step. 
![image](https://user-images.githubusercontent.com/40668277/216306168-45910d50-be3f-4eed-89b3-45c15e18fab8.png)

I also have the same issue when I upload extension to the marketplace. I am thinking this happens because I live in China.

**Comment by roytaishi** [comment]
Wasn't able to repro this issue on my side. But might be an intermittent issue so retry and refresh should work. Is this fixed for you or are you still facing this?

**Comment by madhurivadaligithub** [comment]
@kenyonwang Please let us know, are you still facing the issue?

**Comment by kenyonwang** [comment]
@madhurivadaligithub Thank you for your concern. I got better, but I have the same issue during step of "Save and Upload".

**Comment by kj0171** [comment]
Thank you for reporting this. 
We are not able to reproduce this at our end.  Can you refresh and try again?

**Comment by taoqf** [comment]
We Chinese are blocked to use google service. Is there another way to create publisher? like `vsce` ?

**Comment by madhurivadaligithub** [comment]
Please go through below doc for VSCE commands to create and publish extensions.
https://code.visualstudio.com/api/working-with-extensions/publishing-extension

**Comment by taoqf** [comment]
@madhurivadaligithub I mean I wish to use `vsce create` to create a new publisher.

**Comment by madhurivadaligithub** [comment]
Thanks @taoqf, every extension needs to include a publisher name in its package.json file. Once you have a Personal Access Token, you can create a new publisher using vsce:

vsce create-publisher (publisher name)

**Comment by taoqf** [comment]
@madhurivadaligithub Thank you. But I got this
```log
 ERROR  The 'create-publisher' command is no longer available. You can create a publisher directly in the Marketplace: https://aka.ms/vscode-create-publisher
```
when I run 
```sh
vsce --version
# 2.15.0
vsce create-publisher
# ERROR  The 'create-publisher' command is no longer available. You can create a publisher directly in the Marketplace: https://aka.ms/vscode-create-publisher
```

**Comment by madhurivadaligithub** [comment]
Hi @kenyonwang
Apologies for delay in response. Yes, this command is no longer available now, you can create a new publisher by navigating to "https://marketplace.visualstudio.com/manage/" 

Thanks,
VS Marketplace Team
