### ISSUE TITLE
o mudo esta podre

### ISSUE THREAD

**Issue by kimbom060** [microsoft/vsmarketplace#567]
![help](https://user-images.githubusercontent.com/119951614/214802174-6adbe21c-fea3-47af-8274-32120bfca0e4.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by roytaishi** [comment]
Hey, can you add some more details about this issue? Some screenshots can be helpful.

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
