### ISSUE TITLE
Error with dowloading extensions

### ISSUE THREAD

**Issue by KKundeKK** [microsoft/vsmarketplace#568]
Type: <b>Performance Issue</b>

I cannot download extensions. It says: Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is invalid state...

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @KKundeKK This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
