### ISSUE TITLE
Extension tags seem to be calculated incorrectly which blocks publishing

### ISSUE THREAD

**Issue by rgrunber** [microsoft/vsmarketplace#569]
I think this is a case of the VS Code Marketplace becoming more restrictive because up until today, there was no issue publishing with the following metadata. However, the metadata is generated by vsce.

Given an extension with the following keywords (clearly less than 10) : https://github.com/redhat-developer/vscode-quarkus/blob/ee500685a159eeed8605c2b8ffe794ec19670102/package.json#L27-L32

When publishing, I'll see :

`ERROR  You exceeded the number of allowed tags of 10.`
(as described at https://code.visualstudio.com/api/working-with-extensions/publishing-extension#i-get-a-you-exceeded-the-number-of-allowed-tags-of-10-error-when-i-try-to-publish-my-extension )

Looking into the `extension.vsixmanifest` that's packaged into the vsix, I see :

```xml
<Tags>java,quarkus,maven,starter,quarkus-properties,Quarkus properties,qute-html,Qute HTML,__ext_qutehtml,qute-json,Qute JSON,__ext_qutejson,qute-yaml,Qute YAML,__ext_quteyaml,qute-txt,Qute Text,__ext_qutetxt,microprofile-properties</Tags>
```
That's definitely more than 10. The `__ext_*` terms probably shouldn't be there, but there's keywords in there that come from other features like https://code.visualstudio.com/api/references/contribution-points#contributes.languages (`id`, `alias`). I compared with a previous vsix (prior to today) that did publish successfully and the same terms existed.

**Comment by isidorn** [comment]
Sorry about that. The marketplace team has introduced a tag limit, and we are working with them to lift this boundary - as there are internal tags that VS Code adds.
I expect this limit to be lifted tomorrow since today is a national holiday for the Marketplace team.

Thank you for your understanding.

**Comment by prashantvc** [comment]
Looks like the edge case is missed on this. Upload pipeline is counting automatic tags too.
I am extremely sorry you have to go through it

**Comment by prashantvc** [comment]
We turned off the tag validation for now. We apologies for breaking your workflow. 
Please note that we will enable this feature in few weeks again, I suggest you to keep `keywords`/`tags` under 10

**Comment by PEZ** [comment]
Thanks for removing the blocker for now, @prashantvc! ❤️ I could publish now, without editing the VSIX. 🚀 

> I suggest you to keep `keywords`/`tags` under 10

Can you make it so that you only restrict `keywords` (the `keywords:` entry in the extension manifest)? I don't see how we can control `tags` as extension developers

> under 10

Is the restriction max 10 or max 9?

**Comment by prashantvc** [comment]
Yup, we will restrict only keywords. 
> Is the restriction max 10 or max 9?

The restriction will be max 10, sorry for the confusion :)

**Comment by zimmski** [comment]
> Is the restriction max 10 or max 9?

We found that confusing as well. In the documentation it says `The Visual Studio Marketplace does not allow an extension package to have more than ten keywords...` but the error message says `You exceeded the number of allowed tags of 10.`

Another thing that concerns me about that new rule, is what happens to extensions with lots of ecosystem support? I get that it is bad to spam the tags, but we are adding more functionality (and languages) to our Symflower plugin every month. Any advice on how to tag in the future?

**Comment by Neelima10735584** [comment]
Hi,

Thank you for contacting the VS Marketplace Team. The issue has been resolved and removed the limit on tags. If the error persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
