### ISSUE TITLE
Extensions malfunction

### ISSUE THREAD

**Issue by ammar1204** [microsoft/vsmarketplace#570]
Type: <b>Performance Issue</b>

Extensions keep disappearing every time I startup the app.
When I download an extension then close the app, the extensions don't show again when I reopen the app. I have been having this issue for the past one month.

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.18362
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @ammar1204  This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
