### ISSUE TITLE
vs code problem

### ISSUE THREAD

**Issue by Sid2Sahab** [microsoft/vsmarketplace#571]
Type: <b>Bug</b>

not show any extentation and setting option

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @Sid2Sahab This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
