### ISSUE TITLE
Can't search for extensions

### ISSUE THREAD

**Issue by Carla-Fang** [microsoft/vsmarketplace#573]
Type: <b>Performance Issue</b>

My internet works fine, but I can't search for new extensions. 

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by isidorn** [comment]
Please file this in the VS Code repository https://github.com/microsoft/vscode/issues
Thank you
