### ISSUE TITLE
Falha na conexão ssh

### ISSUE THREAD

**Issue by EliseuRG** [microsoft/vsmarketplace#576]
Type: <b>Bug</b>

Toda vez que tento conexão ao host da empresa, me retorna um erro de permissão.

Porém, já retirei e dei as permissões a pasta ./ssh/config. Já desinstalei e instalei o Visual code 3 vezes, já gerei a chave e publiquei no servidor 5 vezes. Não sei mais o que pode ser.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Connection to 'SSH' could not be established

**Comment by madhurivadaligithub** [comment]
Hi @EliseuRG This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
