### ISSUE TITLE
Extensões excluidas assim que atualizou

### ISSUE THREAD

**Issue by LucasAraujo1997** [microsoft/vsmarketplace#578]
Type: <b>Bug</b>

As extensões que estavam instaladas antes da ultima atualização simplesmente foram excluidas e também não consigo instalar de novo.

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by nikhgup** [comment]
can you please create an issue here  https://github.com/microsoft/vscode/issues. This issue is related to vscode.
