### ISSUE TITLE
font awesome

### ISSUE THREAD

**Issue by OviCONsoft** [microsoft/vsmarketplace#579]
Type: <b>Bug</b>

Hi, once introduced the link rel from font awesome an putting it on my weg page it works, bur after working on CSS and adding some border to the icon it doesn't work anymore, it shows a square inaide my round button that noramlly is a cart on font awesome. 

HTML code: 
<head>
<link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    />
</head>
<body>
<div class="pro">
          <img src="img/colectiipmici/Full_Black_classic.png" alt="" />
          <div class="des">
            <span>apple</span>
            <h5>Apple Serie 1</h5>
            <div class="star">
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
              <i class="fas fa-star"></i>
            </div>
            <h4>$150</h4>
          </div>
          <a href="#"><i class="fal fa-shopping-cart cart"></i></a>
        </div>
</body 

and the CSS code: 

#product1 .pro .cart {
  width: 40px;
  height: 40px;
  line-height: 40px;
  border-radius: 50px;
  background-color: #e8f6ea;
  font-weight: 500;
  color: #088178;
  border-color: 1px solid #cce7d0;
  position: absolute;
  bottom: 20px;
  right: 10px;
}

![sswebpage](https://user-images.githubusercontent.com/124869970/217753463-0f2e8eb2-6a52-4d8a-a2ea-06f7a86ca965.png)

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by nikhgup** [comment]
@OviCONsoft can you please explain the issue in detail.

**Comment by OviCONsoft** [comment]
I found out what the issue was. The problem i had was that the font awesome text i had wrote it incorectly:
<a href="#" class="cart"><i class="fa fa-shopping-cart"></i></a> This is the correct one and i had it like this before 
<a href="#" class="cart"><i class="fab fa-shopping-cart"></i></a>  That b was causing me problems when displaying the icon

**Comment by madhurivadaligithub** [comment]
Closing for now. @OviCONsoft, please re-open if the issue persists.
