### ISSUE TITLE
"no extensions found" after installing an extension

### ISSUE THREAD

**Issue by seawinkle** [microsoft/vsmarketplace#581]
Suddenly my extensions in Vscode seem to have disappeared. I uninstalled Vscode and then reinstalled it and tried to install the extensions again. Although the extensions appear to be installed in **_.vscode/extensions_** folder, Vscode says "no extensions found" and i can't use any of the extensions. I have tried uninstalling and re-installing Vscode many times. I even did a system restore.  I deleted `extensions.json` and re-installed the extensions but it didn't work. 

**Screenshots:** 

![1](https://user-images.githubusercontent.com/124889377/217830263-a81e48df-f1d7-4265-bffb-b96a83d2130f.jpg)

_extensions folder:_

![2](https://user-images.githubusercontent.com/124889377/217830294-3b26cdb1-60d5-4d0b-9cd8-288e61669b6d.jpg)

**Comment by isidorn** [comment]
If you can still reproduce this issue I suggest to open a new issue in this repository https://github.com/microsoft/vscode/issues

This is a VS Code issue, and not a Marketplace bug.
