### ISSUE TITLE
No installed extensions found

### ISSUE THREAD

**Issue by iyigityilmaz** [microsoft/vsmarketplace#583]
Type: <b>Bug</b>

vs code does not see the installed extensions. when ı try reinstall th extensions same issue 

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @iyigityilmaz  This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
