### ISSUE TITLE
M1 Mac - CPU usage 300%+

### ISSUE THREAD

**Issue by abbas-25** [microsoft/vsmarketplace#584]
Type: <b>Bug</b>

Just now disabled the extension using extension bisect. 

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @abbas-25 This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
