### ISSUE TITLE
Error: TF400898: An Internal Error Occurred. Activity Id: 16319878-3098-4cfc-9e3a-c5d573ba38f3

### ISSUE THREAD

**Issue by noppej** [microsoft/vsmarketplace#585]
Hi,

I'm trying to publish my extension for the first time, and irrespective of using `@vscode/vsce publish --yarn` or trying to upload via the "Manage Extensions" portal, I always get the same error:

`TF400898: An Internal Error Occurred. Activity Id: 16319878-3098-4cfc-9e3a-c5d573ba38f3`

I've double- and triple-checked all the steps at https://code.visualstudio.com/api/working-with-extensions/publishing-extension, and am running out of things to try.

Any help will be much appreciated ... even if it is just a hint on seeing a log or more details about what caused the error :)

**Comment by kj0171** [comment]
Thank you for contacting to vscode-marketplace. There is issue with one of the tags.  Can you please try removing it or making it less than 50 characters and then try again creating the extension. 

If the issue still persists, please feel free to reach out. 
Thanks

**Comment by noppej** [comment]
@kj0171 Thank you, that solved it. I don't think it was any specific tag, but rather the length. Perhaps this requires a better error message, or maybe updated documentation?

**Comment by kj0171** [comment]
@noppej 
Thank you for the feedback. We are closing this ticket for now.
