### ISSUE TITLE
XHR Failed

### ISSUE THREAD

**Issue by marshubs** [microsoft/vsmarketplace#587]
Type: <b>Bug</b>

I can't install all extensions, only manual. As for the internet, I use it for other activities, the internet is normal.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by kj0171** [comment]
@marshubs 
Can you share more details like console log and also the network tab.
Are you using a VPN client or some local firewall? Can you turn these off and retry?

**Comment by JatinSanghvi** [comment]
Hi @marshubs, we need to report such issues to our CDN provider. They would require the below information to start investigating.

If the issue still persists, please provide:

1. HTTP requests exported in HAR format. To do this,
    a. Ensure that the extension page is still not loading.
    b. In Visual Studio Code, open Developer Tools (Ctrl+Shift+I).
    c. Switch to the Network tab and enable the 'Disable Cache' option.
    d. Open the extension page again.
    e. Right click on any request and select Copy > Copy all as HAR.
    f. Save the copied text in a file and email it to us (VSMarketplace [at] microsoft [period] com).
    
2. Headers copied after opening page: http://wpc.2dcc.edgecastcdn.net/002DCC/n2/.
    Go to the page, expand 'Client Info', copy all rows underneath, save it in a file and email it to us.

3. Traceroute output

    * If on Windows:
        1. Go to [https://winmtr.en.uptodown.com/windows/download]() and download the ZIP file.
        2. Open WinMTR64.exe from inside the ZIP file. This should open the WinMTR application.
        3. Enter host as 'ms-vscode.gallerycdn.vsassets.io' and click 'Start'.
        4. Let it run for a minute and then click 'Stop'.
        5. Click 'Export HTML' button to export the text to a file.
        6. Email this file to us.
    * On Linux:
        1. Ensure that traceroute utility is installed: `sudo apt install traceroute`
        2. Run command: `traceroute ms-vscode.gallerycdn.vsassets.io`.
        3. Copy the text output and email it to us.

**Comment by JatinSanghvi** [comment]
We will be closing the issue since we haven't received any further updates on the information we requested.
