### ISSUE TITLE
Bug Discord Rich Presence by Crawl

### ISSUE THREAD

**Issue by makayasa** [microsoft/vsmarketplace#59]
Issue Type: <b>Bug</b>

The Rich Presence wont change the detail when i move to another File. The file name still remain as the first File I open, and wont change when i move to another file. 

But, when i change the folder with my other project, it works just fine. When I change to another file, the Rich Presence showing the new File I'm on it.

is there any problem with my main project folder ?

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
Not a marketplace issue. Closing
