### ISSUE TITLE
The Extentions Don't Work

### ISSUE THREAD

**Issue by xjoe93** [microsoft/vsmarketplace#591]
Type: <b>Bug</b>

When i open an Extention It dosen't Show Any Thing And It Give Me This Message " The Editor Could Not Be Opened Due To An unexpected Erro: XHR Failed"

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by kj0171** [comment]
Thank you for contacting vscode marketplace. Can you paste the network tab to debug the issue. Thanks

**Comment by kj0171** [comment]
Hoping this got resolved, closing this ticket. If the issue persists, please raise a new ticket. Thanks :)
