### ISSUE TITLE
vscord代码提示失效问题

### ISSUE THREAD

**Issue by wangkangle8** [microsoft/vsmarketplace#593]
Type: <b>Bug</b>

上午安装了v3、ts的插件，卸载之后，原本的代码提示不好使了，怎么也解决不了。

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @wangkangle8 This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
