### ISSUE TITLE
Update VS Marketplace Page "Issues" link to "Report an Issue"

### ISSUE THREAD

**Issue by iamcjwilliams** [microsoft/vsmarketplace#596]
Link to VS Marketplace [Page](https://marketplace.visualstudio.com/items?itemName=GitHub.copilot)

![Screenshot 2023-02-23 at 12 18 50 PM](https://user-images.githubusercontent.com/40559511/220999108-75b9ba94-9b83-4998-9786-ae12cf2533b3.png)

cc: @isidorn

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
