### ISSUE TITLE
Extension not being recognized by python

### ISSUE THREAD

**Issue by tyson-1966** [microsoft/vsmarketplace#597]
Type: <b>Bug</b>

From 1 month,I'm facing the extenxsion issue.Python cannot recgnize the packages,hence solve my issue as fast as possible.

VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in  https://github.com/microsoft/vscode/issues
