### ISSUE TITLE
意外终止

### ISSUE THREAD

**Issue by sangqihang** [microsoft/vsmarketplace#604]
Type: <b>Bug</b>

什么都没操作，自己就意外终止好多次

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.17763
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in  https://github.com/microsoft/vscode/issues
