### ISSUE TITLE
not excute any program

### ISSUE THREAD

**Issue by Fathi123-max** [microsoft/vsmarketplace#605]
Type: <b>Bug</b>

not excute any program 

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:25:16.105Z)
OS version: Linux x64 5.19.0-35-generic
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in  https://github.com/microsoft/vscode/issues
