### ISSUE TITLE
Transfer Publisher ID

### ISSUE THREAD

**Issue by matjp** [microsoft/vsmarketplace#607]
I recently discovered that I have lost access to my VS Code Marketplace Publisher ID (matjp) and published extension due to the fact that I closed my Microsoft Online account some time ago. I also changed my Github account to use a personal email account rather than a Microsoft account.

I now have a new VS Code Extension I'd like to publish under the same Publisher ID (matjp). Is there any way I can get the Publisher ID transfered to my Github account (https://github.com/matjp)?

**Comment by madhurivadaligithub** [comment]
@matjp  Please reach out to us on [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) so that we can get additional sensitive information needed to resolve the issue. Closing this issue so that sensitive information is not shared in this forum.

**Comment by matjp** [comment]
I did already send email to VSMarketplace@microsoft.com twice in the past week but I have had no response, that is why had to raise this issue.

How long can I expect to wait for a response.
