### ISSUE TITLE
No option to update a vscode extension

### ISSUE THREAD

**Issue by kstenerud** [microsoft/vsmarketplace#608]
**Describe the bug**

There's no option to update an extension on https://marketplace.visualstudio.com/manage/publishers/xyz

**To Reproduce**
1. Go to your publisher page (for example https://marketplace.visualstudio.com/manage/publishers/kstenerud)
2. Click on your extension (for example https://marketplace.visualstudio.com/manage/publishers/kstenerud/extensions/dogma-v1/hub?_a=acquisition)
3. Look for a button or link or something for updating the extension

**Expected behavior**

There should be something on the page that lets you upload an update to the extension.

**Desktop (please complete the following information):**
 - OS: Debian Bullseye
 - Browser: Firefox
 - Version 102.8.0esr

**Comment by SaiKanth007** [comment]
Hi @kstenerud 

To update an extension, please click on the three dots right after the extension name and you will see an option to update the extension. Below is the screenshot for reference.

<img width="140" alt="image" src="https://user-images.githubusercontent.com/17098988/223603525-7c005ccb-a5ff-4920-8137-1ccbce4a3a31.png">

**Comment by kstenerud** [comment]
That worked beautifully! Thanks!
