### ISSUE TITLE
Java Runtime config

### ISSUE THREAD

**Issue by SUMIT0733** [microsoft/vsmarketplace#61]
Issue Type: <b>Bug</b>

I have installed spring-boot-tool extension, it require JDK 11. I have already set java.home and java-runtime-config to use JDK 11, but I have set my env vaiable JAVA_HOME to JDK 1.8 and every time vs code is picking JAVA_HOME instead of java.home.

"java.home": "C:\\softs\\java\\jdk-11",
  "java.configuration.runtimes": [
    {
      "name": "JavaSE-11",
      "path": "C:\\softs\\java\\jdk-11"
    }
  ],
( This is my user-setting.json )

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

**Comment by isidorn** [comment]
File against JAVA extension please
