### ISSUE TITLE
Extension host terminated

### ISSUE THREAD

**Issue by boyprakasa** [microsoft/vsmarketplace#611]
Type: <b>Bug</b>

Extension host terminated unexpectedly 3 times within the last 5 minutes.

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.25309
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in  https://github.com/microsoft/vscode/issues
