### ISSUE TITLE
extensions auto deletion

### ISSUE THREAD

**Issue by aayyaan** [microsoft/vsmarketplace#613]
Type: <b>Performance Issue</b>

My extensions remove after some days and I have to install them again. Kindly fix my problem

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
