### ISSUE TITLE
me aparece cada 5 minutos

### ISSUE THREAD

**Issue by mounkey** [microsoft/vsmarketplace#614]
Type: <b>Bug</b>

Cada 5 minutos me aparece

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:06.752Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
