### ISSUE TITLE
can't install extensions

### ISSUE THREAD

**Issue by hansal000** [microsoft/vsmarketplace#615]
Type: <b>Performance Issue</b>

I can't install any vs code extensions

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by SaiKanth007** [comment]
Can you add more details please?

**Comment by VortexPh123** [comment]
![Screenshot (200)](https://user-images.githubusercontent.com/119449033/226108304-9a53c730-046f-4640-afe3-0614c653d77f.png)

I also can't install any extensions automatically, extension icons are not even loading. Please help me fix it.

**Comment by ab2a17** [comment]
Unable to install any of the extensions. After clicking the install button or manually installing the extension. In both scenario the extension is not getting install and only showing "installing" status only.
<img width="959" alt="image" src="https://user-images.githubusercontent.com/128807145/227510905-b5f35355-1e1f-46eb-8d05-540325e0ac3e.png">

**Comment by madhurivadaligithub** [comment]
Hi @hansal000 
 If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command:  Developer: Open Logs Folder).

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested.
