### ISSUE TITLE
The extension host terminated unexpectedly 3 times in the last 5 minutes. Extension Host

### ISSUE THREAD

**Issue by mrtgdev** [microsoft/vsmarketplace#616]
Type: <b>Bug</b>

It closes the extensions automatically when I write something, a few days ago this did not happen to me and I have not changed anything in my configuration. 
I think it looks like it's from Github Copilot

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by SaiKanth007** [comment]
This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
