### ISSUE TITLE
扩展宿主自动关闭

### ISSUE THREAD

**Issue by againstthewind7** [microsoft/vsmarketplace#618]
Type: <b>Bug</b>

总是提醒我扩展宿主在五分钟内重启三次，然后扩展宿主还是关闭了，什么代码提示，还有所有插件都用不了了

VS Code version: Code 1.76.1 (5e805b79fcb6ba4c2d23712967df89a089da575b, 2023-03-08T16:32:00.131Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
