### ISSUE TITLE
VS Live Share

### ISSUE THREAD

**Issue by ch3ckth3b4ck** [microsoft/vsmarketplace#62]
Issue Type: <b>Performance Issue</b>

Hello,

while using Live Share I receive this message but I can't solve the problem. 
"Starting collaboration session: Signing In"

I have uninstalled, restarte, installed the extension several times and I have also logged out and logged into my MS account several times but I can't use live share.

Best regards

Karim

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

**Comment by isidorn** [comment]
Please file against live share
