### ISSUE TITLE
Error downloading python extension in VSCode

### ISSUE THREAD

**Issue by dionisio35** [microsoft/vsmarketplace#620]
Type: <b>Bug</b>

I have a problem installing the Python extension in VSCode, when I try to install it I get the following error: [error] end of central directory record signature not found: CorruptZip: end of central directory record signature not found. And when I try to install it manually I get the following error: Corrupt ZIP: end of central directory record signature not found.

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
