### ISSUE TITLE
Visual Studio code helper screen issue

### ISSUE THREAD

**Issue by BilginAlkan** [microsoft/vsmarketplace#621]
Type: <b>Feature Request</b>

When I want to add different utilities to the Visual Studio Code application, some utilities list on the left of the screen does not appear when it first opens.
How can I restore this screen?

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in https://github.com/microsoft/vscode/issues
