### ISSUE TITLE
package.json bugs->URL field ... can it be any URL?

### ISSUE THREAD

**Issue by christianshay** [microsoft/vsmarketplace#622]
I have a question about a field in a VS Code extension manifest:

VS Code extension manifest formats are documented here: 

https://code.visualstudio.com/api/references/extension-manifest

On that page you will see an example that includes these fields:

"bugs": {
    "url": "https://github.com/microsoft/vscode-wordcount/issues",
    "email": "sean@xxxxxxx.com"

This is part of the npm package.json spec.

https://docs.npmjs.com/cli/v7/configuring-npm/package-json

This field causes the VS Code Marketplace reviews tab to add a "Report Issue" button which takes the user to that URL.

My question is:

Can we use any URL in the bugs->URL field (and get the Report Issue button pointing at that URL)? Or does it have to be github.com? Do you know of any extension that is using a non-github URL here (I cannot find one)

I see no way to test this aside from publishing an extension. Every extension I have checked is using a github issues url. We want to use our own website URL for bugs instead.

**Comment by amit-kulkarni-in** [comment]
@christianshay: Yes we can use any URL in the bugs and the URL in the bugs will be used in the "Report Issue" button .
