### ISSUE TITLE
Couldn't connect to extension marketplace 

### ISSUE THREAD

**Issue by Aditya-Dhodade** [microsoft/vsmarketplace#63]
Issue Type: <b>Bug</b>

when i had searched for An Extension , it showed me "We cannot connect to extension marketplace at this time. Please try again later".

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.18363

**Comment by isidorn** [comment]
Duplicate. Configure your proxies.
