### ISSUE TITLE
Error when trying to install Azure Resource Manager (ARM) Tools

### ISSUE THREAD

**Issue by Iyad-Abusneineh** [microsoft/vsmarketplace#632]
Type: <b>Bug</b>

I get this error when trying to install extension "Azure Resource Manager (ARM) Tools":

2023-03-23 09:28:58.331 [error] PackageIntegrityCheckFailed: Signature: PackageIntegrityCheckFailed

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by kevin-guertin** [comment]
This seems to have been resolved today.

**Comment by madhurivadaligithub** [comment]
@Iyad-Abusneineh   Are you still facing the issue?

**Comment by Iyad-Abusneineh** [comment]
No, the problem is solved. Thank you.
________________________________
Från: madhurivadaligithub ***@***.***>
Skickat: den 27 mars 2023 15:06
Till: microsoft/vsmarketplace ***@***.***>
Kopia: Iyad-Abusneineh ***@***.***>; Mention ***@***.***>
Ämne: Re: [microsoft/vsmarketplace] Error when trying to install Azure Resource Manager (ARM) Tools (Issue #632)


@Iyad-Abusneineh<https://github.com/Iyad-Abusneineh> Are you still facing the issue?
