### ISSUE TITLE
Published a extension with wrong vscode version, but could not unpublish it

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/vsmarketplace#633]
I published this extension https://marketplace.visualstudio.com/items?itemName=node-projects.vscode-designer-addon, but I accidently forgot the correct vscode version. So now people with older Vscode could install it, but it will not work.

How could I remove only the V1.0.0 from the marketplace?

**Comment by madhurivadaligithub** [comment]
Hi @jogibear9988  We will resolve this, could you please reach out to us through VSMarketplace@microsoft.com
