### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ab2a17** [microsoft/vsmarketplace#634]
Type: <b>Bug</b>

Unable to install any of the extensions. After clicking the install button or manually installing the extension. In both scenario the extension is not getting install and only showing "installing" status only

VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
<img width="959" alt="image" src="https://user-images.githubusercontent.com/128807145/227511434-b0a3a496-e10f-4b9a-b4c2-abd54d1a4335.png">

**Comment by seaniyer** [comment]
@ab2a17 

This seems to be an issue best addressed by VS Code team. You can reach out to them by opening an issue at 
https://github.com/microsoft/vscode/issues
