### ISSUE TITLE
python

### ISSUE THREAD

**Issue by TataJ7** [microsoft/vsmarketplace#635]
Type: <b>Bug</b>

python had been deleted by it self and it won't reinstall again

VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment]
@TataJ7  Could you please share more details screenshot or error messages to understand better?

**Comment by majcram** [comment]
Check your environment variables. You can find more information on the VS Code website. Here is the link. https://code.visualstudio.com/docs/python/environments

**Comment by skofman1** [comment]
Closing for now. @TataJ7 , please re-open if the issue persists.
