### ISSUE TITLE
Emails to vsmarketplace@microsoft.com from GMail are rejected

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vsmarketplace#639]
**Describe the bug**

Sending a e-mail to vsmarketplace@microsoft.com from GMail is rejected with the following message:

> The group `vsmarketplace-idc` only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

**To Reproduce**
1. Go to https://marketplace.visualstudio.com/, go to any extension page. 
2. On right side of page, Click on `Report Abuse`
3. Send a email

**Expected behavior**

Mails from GMail are accepted.

**Comment by lyndaidaii** [comment]
@tamuratak, Thanks for your feedback, could you share the screenshot? I was able to send email via Gmail

**Comment by lyndaidaii** [comment]
@tamuratak, it should work now. Please retry and let us know if you have any other problems.

**Comment by tamuratak** [comment]
I don't get error messages. It seems to work.

Thank you.
