### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by HeisenbergK** [microsoft/vsmarketplace#640]
Type: <b>Bug</b>

Trying to install any extension (I am trying to install Node.js Extension Pack by Wade Anderson), I get the error `end of central directory record signature not found`. I have tried both manual and marketplace installation.

VS Code version: Code 1.77.0 (Universal) (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T09:57:11.797Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

**Comment by skofman1** [comment]
//cc @isidorn , @dtivel

**Comment by dtivel** [comment]
@HeisenbergK, did this happen with the latest version (0.1.9) of Node.js Extension Pack?  If you try installing a different version, does it succeed or fail similarly?

**Comment by dtivel** [comment]
I can't repro this on VS Code 1.77.0 on Windows or macOS using Node.js Extension Pack version 0.1.9.

@HeisenbergK, when you download the file from VS Marketplace manually and installation fails, can you give me details about the file (size and/or hash)?  If you rename the file to have a .zip extension can macOS extract all files?

@sandy081, do you have ideas on how to debug this further?

**Comment by sandy081** [comment]
> I even downloaded manually the VSIX, but still the issue persists.

Seems MP is returning the invalid VSIX then?

CC @isidorn
