### ISSUE TITLE
styled-components

### ISSUE THREAD

**Issue by Milltiades** [microsoft/vsmarketplace#641]
Type: <b>Bug</b>

auto suggestion doesnt work on 1.77 update

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in  https://github.com/microsoft/vscode/issues
