### ISSUE TITLE
error while fetching extensions xhr failed

### ISSUE THREAD

**Issue by SixteenAngels** [microsoft/vsmarketplace#643]
Type: <b>Bug</b>

tried solving but no avail

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @SixteenAngels 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command:  Developer: Open Logs Folder)?

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.
