### ISSUE TITLE
XHR failed

### ISSUE THREAD

**Issue by greec-d** [microsoft/vsmarketplace#644]

**Comment by madhurivadaligithub** [comment]
Hi @greec-d  Thanks for reaching us, could you please share more details about the issue.

**Comment by itsdhairya** [comment]
I am facing the same error as this one 

![image](https://user-images.githubusercontent.com/99156657/230497668-15aa38bd-4061-4c86-9e91-9979ca1c5a66.png)


let me know if any one finds a solution, I am unable to access extensions from my marketplace as well as unable to install frameworks from terminal

**Comment by itsdhairya** [comment]
https://github.com/microsoft/vscode/issues/178841

**Comment by seaniyer** [comment]
@itsdhairya 

Thank you for opening the issue. Sorry to hear you seem to be experiencing install errors. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
