### ISSUE TITLE
My active subscription is not detected

### ISSUE THREAD

**Issue by rippler7** [microsoft/vsmarketplace#645]
[Type:]([url](url)) <b>Bug</b>

I've recently subscribed for the $5 monthly. But my VSCode extension does not recognize it! How should I go around this?

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in  https://github.com/microsoft/vscode/issues
