### ISSUE TITLE
Go live server is not working

### ISSUE THREAD

**Issue by jay190kumar** [microsoft/vsmarketplace#646]
Type: <b>Performance Issue</b>

Hey there this is Jay  and i'm facing one problem i.e., my go live server is not working. Please help me to get out from this issue.

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by seaniyer** [comment]
@jay190kumar  

I couldn't locate go live server, however, I was able to install Live Server v5.7.9. This might have been a transient issue. I suggest giving it a try again.
