### ISSUE TITLE
Live Server

### ISSUE THREAD

**Issue by Triz93** [microsoft/vsmarketplace#647]
Issue Type: <b>Feature Request</b>

Liver Server 5 is not seen in Extension marketplace. Unknowingly I uninstall the Live Server & now I am not able to install it again.

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:48.474Z)
OS version: Windows_NT ia32 6.1.7601
Restricted Mode: No

**Comment by seaniyer** [comment]
@Triz93 

Thanks for reaching out. Just to clarify, Which specific extension are you referring to? Perhaps this one https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer?
