### ISSUE TITLE
Publisher management no longer associated with Microsoft account

### ISSUE THREAD

**Issue by alexravenna** [microsoft/vsmarketplace#648]
**Describe the bug**
I published an [extension](https://marketplace.visualstudio.com/items?itemName=alexravenna.monokai-dimmed-vibrant) a long time ago and recently decided to release a new version. However, it appears that the publisher `alexravenna` is no longer associated with my Microsoft account (or never was? I think back then an Azure DevOps PAT wasn't required).

**Expected behavior**
When I click on "Publish extensions" in the marketplace I expect to be able to manage my previously published extension and also be able to publish further extensions under the same publisher name `alexravenna`.

**Additional context**
I changed the default e-mail address associated with my Microsoft account a couple months ago, if that could somehow be related to the issue.

**Comment by seaniyer** [comment]
@alexravenna 

Thank you for reaching out. Please contact VS Marketplace support team at vsmarketplace@microsoft.com. We look forward to helping with your account.
