### ISSUE TITLE
Unable to access Marketplace extensions/uanble to install frameworks

### ISSUE THREAD

**Issue by itsdhairya** [microsoft/vsmarketplace#649]
Type: <b>Bug</b>

Hi there,

I am having this problem and it has been a while, 
(https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md) I had already issued this one before on github and I got a reply which was not accurate. 

please help me fix this

![image](https://user-images.githubusercontent.com/99156657/230496282-35d6cd55-e410-44e2-8182-a549dce40ce8.png)

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.434Z)
OS version: Windows_NT ia32 10.0.22621
Modes:
Sandboxed: No

**Comment by itsdhairya** [comment]
https://github.com/microsoft/vscode/issues/178841

**Comment by seaniyer** [comment]
@itsdhairya 

Thank you for opening the issue. Sorry to hear you are experiencing VS Code install issues. The issue appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.
 
-	VS Marketplace Team
