### ISSUE TITLE
i can not install extension in the wsl2

### ISSUE THREAD

**Issue by skiponmyhands** [microsoft/vsmarketplace#65]
Issue Type: <b>Bug</b>

i can not install extension in the wsl2

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

**Comment by isidorn** [comment]
File against vscode. Though this should just work
