### ISSUE TITLE
Seeing two items for Ruby extension in Extensions view

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vsmarketplace#650]
**Describe the bug**
Seeing two items for Ruby extension in Extensions view

**To Reproduce**
1. Open Extensions view
2. Search for "ruby"

**Expected behavior**
Only one entry for the Ruby extension https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

**Screenshots**
![image](https://user-images.githubusercontent.com/12818376/230519889-d4002bb6-8350-4110-b70c-4c514d80e412.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - VS Code: 1.78 Insiders 
 
**Additional context**
Does not repro for VS Code 1.77.1 Stable
@isidorn for tracking

**Comment by isidorn** [comment]
fyi @xavierdecoster

**Comment by isidorn** [comment]
As @sandy081  says
"This seems to be an issue in MP - API returning the same extension twice"

![image](https://user-images.githubusercontent.com/1926584/231205896-d41369f8-676d-4ad6-b714-3d46af2d6f8c.png)

**Comment by joelverhagen** [comment]
I too was able to repro it.
![image](https://user-images.githubusercontent.com/94054/232601850-d2abc441-ae56-4430-8078-47ceb5f31f42.png)

For my future reference, I have these response headers:

```
cache-control: no-cache, no-store, must-revalidate
content-type: application/json; charset=utf-8
access-control-allow-methods: GET,POST,OPTIONS,HEAD
access-control-allow-origin: *
access-control-expose-headers: ActivityId,Request-Context
access-control-max-age: 3600
request-context: appId=cid-v1:7b764c19-6350-43b9-bde0-fcac881f8cd8
strict-transport-security: max-age=2592000
x-content-type-options: nosniff
activityid: 78de4664-c7ec-4e44-b6cf-d9d809a5def2
x-powered-by: ASP.NET
region: EUS2
x-cache: CONFIG_NOCACHE
x-geo: VSCodeSearchQueryGlobal_ExtensionQuery
x-msedge-ref: Ref A: 0CE9916C54D24D02B5F47734FAC135A2 Ref B: CHGEDGE1312 Ref C: 2023-04-17T20:15:55Z
date: Mon, 17 Apr 2023 20:15:55 GMT
```

**Comment by joelverhagen** [comment]
Okay, so this appears to be related to the `/searchrelevancy/` path, which IIRC is special to VS Code insiders:
<pre>
https://marketplace.visualstudio.com/_apis/public/gallery<b>/searchrelevancy/</b>extensionquery
</pre>

The issue does not repro on the default (non-insiders) URL:
```
https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery
```

**Comment by isidorn** [comment]
@joelverhagen yes, this is only for insiders. I shared this with Xavier, sorry for not commenting here.

**Comment by joelverhagen** [comment]
We determined that the search index that is serving this request actually has a duplicate document for the Ruby extension. This is due to a change in index schema and (it appears) a different casing of "Ruby" vs. "ruby". We'll work on either doing a data fix or rolling back to the baseline search index. No change should be needed on the client (VS Code) side at this time.

**Comment by isidorn** [comment]
Thanks for the update!

**Comment by joelverhagen** [comment]
@gregvanl, we have mitigated the problem. The VS Code and VS Code Insiders behavior should now be exactly the same.

**Comment by gregvanl** [comment]
@joelverhagen Thanks, just tried the Extensions view and looks good
