### ISSUE TITLE
Postgresql

### ISSUE THREAD

**Issue by vikram-ai** [microsoft/vsmarketplace#652]
Type: <b>Bug</b>

Postgresql not working. It's in broken stage

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

**Comment by madhurivadaligithub** [comment]
This issue is related to VS Code, please file it in  https://github.com/microsoft/vscode/issues
