### ISSUE TITLE
xhr failed

### ISSUE THREAD

**Issue by 01Shiv10** [microsoft/vsmarketplace#653]
Type: <b>Feature Request</b>

whenever i try to search for an extension it keeps showing error while fetching extensions .xhr failed i have tried proxy setting,dns setting but it's still not working please solve this issue

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by seaniyer** [comment]
@[username]

Thank you for opening the issue. Sorry to hear you are experiencing an issue with searching. It appears to be specific to VS Code editor and tools if I'm understanding correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
