### ISSUE TITLE
xhr falied

### ISSUE THREAD

**Issue by Metheprogrammer08** [microsoft/vsmarketplace#654]
Type: <b>Bug</b>

I can't fix xhr failed when loading extensions

VS Code version: Code 1.77.1 (b7886d7461186a5eac768481578c1d7ca80e2d21, 2023-04-04T23:21:11.906Z)
OS version: Windows_NT x64 10.0.17763
Modes:
Sandboxed: No

**Comment by seaniyer** [comment]
@Metheprogrammer08 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command:  Developer: Open Logs Folder)?

**Comment by madhurivadaligithub** [comment]
@Metheprogrammer08 Closing the issue since there has been no updates on the information requested.
