### ISSUE TITLE
Wrong image path after parsing markdown

### ISSUE THREAD

**Issue by yubaoquan** [microsoft/vsmarketplace#655]
**Describe the bug**
I have some relative image paths in readme.md. After I upgrade my extension version and republish it, the absolute path in marketplace is wrong. It point to file in master branch, but my repo's default branch is main.

**To Reproduce**

**Expected behavior**
The images' url point to main branch.

**Additional context**

### in markdown

```markdown
![feature select](images/feature-select.min.gif)
```

### in marketplace

```html
<img src="https://github.com/yubaoquan/reg-visualizer/raw/master/images/feature-select.min.gif" alt="feature select">
```

**Comment by madhurivadaligithub** [comment]
Hi @yubaoquan Are you still facing the issue?

Regards,
VS Marketplace Team

**Comment by yubaoquan** [comment]
I end up adding a master branch and copy files to it.
