### ISSUE TITLE
Seeing two items for Ruby extension in Extensions view

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vsmarketplace#657]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.78 Insiders 
- OS Version: Windows 11

Steps to Reproduce:

1. Open Extensions view
2. Search for "ruby"

![image](https://user-images.githubusercontent.com/12818376/230198755-b9dfb7a3-59b7-4df9-93c9-293c5f7587e1.png)

Clicking on either extension items brings up the same Extensions detail page.

Does not repo on 1.77.1 Stable

**Comment by sandy081** [comment]
This seems to be an issue in MP - API returning the same extension twice

![image](https://user-images.githubusercontent.com/10746682/231108184-52002d9d-f2fc-4c56-a6a6-f9f490f67dc9.png)


CC @isidorn
