### ISSUE TITLE
extension can not access 

### ISSUE THREAD

**Issue by LoveLonelyBoy** [microsoft/vsmarketplace#658]
Type: <b>Bug</b>

in windows 7 system, my vs code version is 1.70.2,but I can acess  extension market,the network error content is  net::ERR_CERT_AUTHORITY_INVALID

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 6.1.7601
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @LoveLonelyBoy 
Thank you for opening the issue. Sorry to hear you are experiencing [insert customer issue]. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues. 

-VS Marketplace Team
