### ISSUE TITLE
Cannot use Extension Marketplace

### ISSUE THREAD

**Issue by cmoncada07** [microsoft/vsmarketplace#659]
Type: <b>Performance Issue</b>

The error is always net:ERR_TIMED_OUT.

I am sure there is a network, I already installed python and Visual studio code but I can't install any in the marketplace extension.
I also tried to download the latest version.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing an issue with searching. It appears to be specific to VS Code editor and tools if I'm understanding correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
