### ISSUE TITLE
Install Extensions Stuck at Installing

### ISSUE THREAD

**Issue by Ghanim2715** [microsoft/vsmarketplace#660]
Type: <b>Bug</b>

Im installing extensions, but always stuck at installing. My network speed is very good, why this???

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

**Comment by Mechanike** [comment]
How did you solve it? I had a similar issue.
