### ISSUE TITLE
live server

### ISSUE THREAD

**Issue by prabhatsuman7250** [microsoft/vsmarketplace#661]
Type: <b>Bug</b>

Live server is not working 
 i am click on "Go Live " but not run 

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment]
Hi @prabhatsuman7250 This issue appears to be a support question specific to the extension which is best addressed by the extension owner.  I recommend visiting the extension page on https://marketplace.visualstudio.com/ and posting a question there. Let me know if I can help you with anything else.
