### ISSUE TITLE
Erroe. XHR failed

### ISSUE THREAD

**Issue by ashishbr** [microsoft/vsmarketplace#663]
Type: <b>Bug</b>

Yesterday i opened the vs code as usual, it took a while, usually loads up in 5 seconds.
Then when i tried to install a new extension (code runner). It shows "Error while fetching extensions. XHR failed".
i tried deleting all cache files, and also tried reinstalling, but it aint working.
Please help

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22624
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
@ashishbr Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command:  Developer: Open Logs Folder).

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.
