### ISSUE TITLE
XHR failed

### ISSUE THREAD

**Issue by Lechufane** [microsoft/vsmarketplace#664]
Type: <b>Bug</b>

XHR is not letting me install extensions, I have read every blog, done everything with proxy settings, disable avast, I have reinstalled twice in 2 different drives, I'm out of ideas and I need to install some extensions.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @Lechufane 
Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

**Comment by seaniyer** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.
