### ISSUE TITLE
Pylance

### ISSUE THREAD

**Issue by Helder-Velez** [microsoft/vsmarketplace#665]
Type: <b>Feature Request</b>

Não consigo usar bibliotecas que instalo porque o pylance não deixa, não consigo resolver

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by seaniyer** [comment]
@Helder-Velez 

It appears that this issue might be best addressed by Pylance owners. You can open an issue here to engage with that team https://github.com/microsoft/pylance-release/issues
