### ISSUE TITLE
Can't login to old publisher with same email

### ISSUE THREAD

**Issue by oreporan** [microsoft/vsmarketplace#666]
**Describe the bug**
Exactly the same as - https://github.com/microsoft/vsmarketplace/issues/356

My Extension - https://marketplace.visualstudio.com/items?itemName=orepor.color-tabs-vscode-ext
My Email - oreporan@gmail.com
When I go to my extensions, its says its empty (see image)

I noticed the publisher names are not the same, 
In the extension I'm called `orepor`, and when I login I'm called `OrePoran`

I guess a change has been done at some point in time, and the migration didn't work

Please help 

**Screenshots**
![image](https://user-images.githubusercontent.com/2146999/233940152-08b2ef9a-6c24-41ff-8956-8015c011bdb0.png)

**Comment by madhurivadaligithub** [comment]
Hi @oreporan 
Thanks for reaching out, we are looking into the issue and will get back to you.

**Comment by seaniyer** [comment]
@oreporan 

Thanks for engaging with our customer support team via email. Closing this issue as we are already working through it there.
