### ISSUE TITLE
ERROR  Part URI is not valid per rules defined in the Open Packaging Conventions specification

### ISSUE THREAD

**Issue by Gruntfuggly** [microsoft/vsmarketplace#667]
I can no longer publish my extension - I'm getting the error:

```
ERROR  Part URI is not valid per rules defined in the Open Packaging Conventions specification
```

I thought it was because of something I've recently added, but I've just tried publishing a new version with nothing changed but the version number.

Is there any way to find out what this error is relating too?

It was last successfully published on 12th of April 2023 (a week ago). I have also updated to the lastest version of vsce (2.15.0).

**Comment by madhurivadaligithub** [comment]
Hi @Gruntfuggly Thanks for reaching out, could you please share the publisher and extension details to investigate.

**Comment by Gruntfuggly** [comment]
I am the publisher (zaonce.com) - the extension is here: https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

**Comment by madhurivadaligithub** [comment]
It might be related to the space issue, could you please remove all spaces and dashes in the filename.
And let us know if you are still facing this issue.

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists please reach out to us.
