### ISSUE TITLE
I cannot click Create  when creating a publisher

### ISSUE THREAD

**Issue by karlupo** [microsoft/vsmarketplace#668]
Type: <b>Bug</b>

When I click create on https://marketplace.visualstudio.com/manage/createpublisher, when I want to create a publisher, it won't work. All the essential information is filled out.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @karlupo Thanks for reaching out, could you please share screenshot and error message to investigate better.

**Comment by karlupo** [comment]
> Hi @karlupo Thanks for reaching out, could you please share screenshot and error message to investigate better.

Unfortunately there is no error. Here is a screenshot of my data:
![grafik](https://user-images.githubusercontent.com/73790544/234345189-923b2762-55c1-43e2-b166-c2366c1ae0a3.png)

**Comment by madhurivadaligithub** [comment]
We are not able to repro the issue, this could have been an intermittent issue.

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested.
