### ISSUE TITLE
xhr failure

### ISSUE THREAD

**Issue by AndreSteph** [microsoft/vsmarketplace#670]
Type: <b>Performance Issue</b>

my vs code cannot install any extensions. it keeps saying xhr failure

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.16299
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @AndreSteph Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).
