### ISSUE TITLE
s: is displaying in the system.out.print line

### ISSUE THREAD

**Issue by prajwal262300** [microsoft/vsmarketplace#671]
Type: <b>Performance Issue</b>

I am beginner in java. I'm facing a small issue while running a code. 
It shows s: in the print line of the code, thought the output is printed in correct format.

VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by seaniyer** [comment]
Thanks for reaching out VS Marketplace team. The issue seems to be specific to Java. this may be best addressed by consulting with programming guides.
