### ISSUE TITLE
marketplace.visualstudio.com网站能否提供一个收藏功能

### ISSUE THREAD

**Issue by hanlilong** [microsoft/vsmarketplace#673]
现在出来好多比较好的插件，但是过一阵子会忘掉，
能否提供一个收藏功能，类似于github的star

**Comment by madhurivadaligithub** [comment]
Hi @hanlilong  can you provide some more details about this query?

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested Details.
