### ISSUE TITLE
my numpy extension didn't work

### ISSUE THREAD

**Issue by SkayKer** [microsoft/vsmarketplace#678]
Type: <b>Bug</b>

i don't know why but even if i already install numpy it didn't work

VS Code version: Code 1.78.0 (252e5463d60e63238250799aef7375787f68b4ee, 2023-05-03T20:09:00.748Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment]
Hi @SkayKer 
Thank you for opening the issue. Sorry to hear you are experiencing [insert customer issue]. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues. 

-VS Marketplace Team
