### ISSUE TITLE
Erro ao buscar as extensões. XHR failed

### ISSUE THREAD

**Issue by HamiltonVS** [microsoft/vsmarketplace#679]
Issue Type: <b>Feature Request</b>

Está apaecendo a seguinte falha ao tentar buscar as extensões para as linguagem: "Erro ao buscar as extensões. XHR failed". Isso de certo modo impede de adicionar extensões as linguagens, impedido de fazer a Depuração e até mesmo de buscar novas extensões. Esse erro está acontecendo para todas as linguagens de programação 

VS Code version: Code 1.63.1 (fe719cd3e5825bf14e14182fddeb88ee8daf044f, 2021-12-14T02:15:48.242Z)
OS version: Windows_NT ia32 6.1.7600
Restricted Mode: No

**Comment by madhurivadaligithub** [comment]
Hi @HamiltonVS 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).
