### ISSUE TITLE
Search results for specific language debugger are very unspecific

### ISSUE THREAD

**Issue by digitarald** [microsoft/vsmarketplace#68]
Follow up from https://github.com/microsoft/vscode/issues/119110, reviewing this with Java the search results are confusing.

Debugging a java file triggers the search for `tag:debuggers @sort:installs Java`:

<img width=200 src=https://user-images.githubusercontent.com/8599/115935410-f5e52300-a447-11eb-99f2-223b1ce60890.png>

_😢 Java Pack, the recommended extension for `java` files, the important one is all the way down._

Even the `ext:java` search triggered by the language switcher isn't putting Java ext pack very high:

<img width=200 src=https://user-images.githubusercontent.com/8599/115935661-8885c200-a448-11eb-858d-9249808bab39.png>

Trying different searches like `tag:debuggers ext:java` – doesn't seem to be a `or` search, as it shows Python first.

Potential solutions:

- Directly point users to a single extension if the current file type has an important recommendation
- Fix search to be smarter with combo searches like `tag:debuggers ext:java`

cc @fiveisprime

**Comment by connor4312** [comment]
I was just about to open this issue when verifying that issue. Ruby fares no better:

![](https://memes.peet.io/img/21-04-9382a7a7-b06c-4482-9976-9a6a810c043e.png)

It seems like `tag:debuggers` is just ignored. Prettier doesn't have a `debug` tag or any mentioned of debugging at all, yet somehow it's the first result.

**Comment by connor4312** [comment]
Oh, yea, in fact if I remove `tag:debuggers` I get the identical set of search results.

**Comment by connor4312** [comment]
Oh, it looks like we should actually use `@category:"debuggers"` to do the filtering. Then it works.

**Comment by digitarald** [comment]
Sana in the linked issue pointed out that `tag:debuggers Ruby` does it, just removing the install sorting.

**Comment by RandomFractals** [comment]
it's the same across the board, no matter what you search for and really needs to be prioratized and fixed so we can find extension in vs marketplace. Currently with over 20K extensions, unless you know exact ext. name it's almost impossible. See my other comment on that here: https://github.com/microsoft/vsmarketplace/issues/71#issuecomment-858550391

**Comment by mayankmaheshwari18** [comment]
@digitarald , The issue with search text as `tag:debuggers @sort:installs Java` works fine now. *Debugger for Java* comes on the top. We have fixed the issue where tags were not being considered as part of search. 
We will look for the ext filter issue.

**Comment by isidorn** [comment]
@roblourens Since the `tag` issue is fixed maybe we should know search for `tag` [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L604) now. We were searching for categories as a workaround.
What do you think?

**Comment by roblourens** [comment]
What is the difference between categories and tags anyway, why would one give better results? Where are tags defined, I don't see them in package.json.

**Comment by isidorn** [comment]
@roblourens good question, and I do not know the exact answer.
I can guess that tags are derived from `contributes` fields. @sandy081 might know better
As for why one would give better results, @mayankmaheshwari18 can explain better.

**Comment by sandy081** [comment]
Tags are computed from Keywords from `package.json`. I think `vsce` also adds additional tags based on contributions. Categories are for grouping extensions.

**Comment by prashantvc** [comment]
Closing this issue, we have fixed the issue where tags were not being considered as part of search.
Filtering is different issue, that we will address separately
