### ISSUE TITLE
Sale error al intentar instalar extensiones

### ISSUE THREAD

**Issue by Jose17-11** [microsoft/vsmarketplace#680]
Type: <b>Bug</b>

Siempre que intento instalar extensiones me sale el siguiente mensaje:
Error al instalar la extensión "Live Server". Consulte el [registro] (command:workbench.action.showWindowLog) para obtener más detalles.

VS Code version: Code 1.78.1 (6a995c4f4cc2ced6e3237749973982e751cb0bf9, 2023-05-04T09:46:23.602Z)
OS version: Linux x64 5.15.0-71-generic
Modes:
Sandboxed: Yes

**Comment by madhurivadaligithub** [comment]
Hi @Jose17-11 
Thank you for opening the issue. Sorry to hear you are experiencing installation issues. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.
