### ISSUE TITLE
Azure Logic App Standard Extension 2.80

### ISSUE THREAD

**Issue by bickhamr** [microsoft/vsmarketplace#681]
Type: <b>Bug</b>

This extension does not work correctly. In a workflow actions like "List Folders" which should connect to sharepoint and show folders in a Library do not work. The concurrency Cpntrol for the "For Each" loop action simply does not show up even if you have it in the json code. I don't know how many other actions are effected but the ones I mentioned above, I am certain do not work. I even tried the "Use Azure Connectors' option and it changed nothing.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @bickhamr 
This issue appears to be a support question specific to the extension which is best addressed by the extension owner.  I recommend visiting the extension page on https://marketplace.visualstudio.com/ and posting a question there. Let me know if I can help you with anything else.
