### ISSUE TITLE
I can't upload my extension. "Your extension has suspicious content."

### ISSUE THREAD

**Issue by cronofear-dev** [microsoft/vsmarketplace#682]
Hi, I wanted to publish my VSCode extension (I'm a new publisher), and I got the following message:

>Your extension has suspicious content. Please fix your extension metadata, or reach contact support if you need assistance.

I've tried a few things to solve the problem, but I'm unable to upload my extension.

My publisher url is: https://marketplace.visualstudio.com/publishers/cubylabgames
The repo with the issue is: https://github.com/cronofear-dev/VerseReferenceExplorer

I've tried removing the tiddlymap file (tiddlymap\output.html), removing any url, etc. Without any detail I'm not sure what I'm supposed to do. Any help will be welcomed. Thanks!

**Comment by madhurivadaligithub** [comment]
Hi @cronofear-dev 

Thank you for reaching out to us. This appears to be a support request for which we recommend contacting VS Marketplace support team by visiting https://marketplace.visualstudio.com/manage and accessing ‘Contact Microsoft’ at the top right. We look forward to helping you. 

-VS Marketplace Team
