### ISSUE TITLE
CREATE PUBLISHER - UNINTUITIVE RESULTS - REMOVES CURRENT PUBLISHERS / EXTENSIONS PUBLISHED

### ISSUE THREAD

**Issue by cole-st-john** [microsoft/vsmarketplace#687]
I have published an extension that is active in the marketplace.  

Item 1: No publishers are listed to the left of the page - though an extension is shown to the right with a publisher listed inside of it. However, a create publisher button is present on the left side of the page.  This gives the impression that one must somehow go through an additional step to make a "publisher" more official by clicking on the create publisher button on the left
Item 2: When I click on create publisher , it gives the exact same form as what was already filled out in my previously published extension.  I fill it out and click save. Suddenly my previous extension is gone from this page and only this new publisher is visible on the right - but still no overview of publishers is visible to the left side of the page as shown in all of the tutorials for VS Code Extension publishing.

**Expected behavior**
A list of available publishers that i have created should be shown on the left side of the page.
A list of published extensions under a selected publisher should be shown on the right 
Clicking on create publisher should add a new item in the list on the left but should not replace anything

**Screenshots**
![image](https://github.com/microsoft/vsmarketplace/assets/91350898/bc92361c-2d3d-411e-b162-5983822854ab)

**Desktop (please complete the following information):**
WINDOWS 10

**Comment by cole-st-john** [comment]
Just to add a detail:  the current bogus publisher name was just an artifact of a quick repeat of create publisher with a bogus string to see if this behaviour was reproducible.

**Comment by lyndaidaii** [comment]
@cole-st-john, we are having trouble in reproducing this issue, would you mind sending us information about your user id, and publisher name your created. thanks. <[VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com)

**Comment by seaniyer** [comment]
Closing. if there is still an outstanding issue please follow up at with customer support @ [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com)
