### ISSUE TITLE
C/C++, C#, F#, Julia extensions

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vsmarketplace#688]
Type: <b>Bug</b>

I managed to make Golang and Rust work on VS Code.  But at this present moment - these languages are not executing - C/C++ (MinGW tools installed), C# and F# (VS 2022 IDE installed), Julia (for some stupid reason).  It is getting on my nerves.  Maybe what Microsoft should do is stop using Typescript to develop VS Code.  Rather move to a compiled language such as C# which is very popular among developers.

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by Donkey-T** [comment]
list subfiles of file with 7 elements {a,b,c,d,e,,f,g}

**Comment by madhurivadaligithub** [comment]
Hi @AGoh2019 
Thank you for opening the issue. Sorry to hear you are experiencing the issue, It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues. 

 -VS Marketplace Team
