### ISSUE TITLE
"The domain url provided could not be reached" when creating a publisher - https://buttonwood.com.au

### ISSUE THREAD

**Issue by davidbairdala** [microsoft/vsmarketplace#690]
![image](https://github.com/microsoft/vsmarketplace/assets/6147079/c5cf4ace-0475-4cd8-aa14-f12cdf0f680f)

I have confirmed that a HEAD request returns 200 using both Postman and curl:

Curl
-----
`$ curl -X HEAD -I --max-redirs 0 https://buttonwood.com.au
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/2 200
server: nginx
date: Wed, 24 May 2023 00:03:02 GMT
content-type: text/html; charset=UTF-8
x-sucuri-id: 18040
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
content-security-policy: upgrade-insecure-requests;
surrogate-key: front post-2 post-user-1 single
link: <https://buttonwood.com.au/wp-json/>; rel="https://api.w.org/", <https://buttonwood.com.au/>; rel=shortlink
x-sucuri-cache: HIT
`

Postman
----------
![image](https://github.com/microsoft/vsmarketplace/assets/6147079/eadd6583-4a8b-474f-ba86-919fbd0d56a3)

But I am still unable to save a new publisher. Could there be anything else that is causing this error?

**Comment by Chizaruu** [comment]
One day, this issue will be solved. (I am suffering the same issue)

**Comment by advay26** [comment]
@davidbairdala Hi David, our apologies for taking so long to get back to you. 

It looks like the servers backing 'https://buttonwood.com.au' return an HTTP 403 Forbidden error for HEAD requests in some cases. When I tried to repro the issue using 'curl' and 'Postman', I saw that the servers return a 200 OK response either when there is no 'User-Agent' specified in the headers, or when the 'Accept' or 'Accept-Encoding' headers are included with it. 

Our system sends this HEAD request with a 'User-Agent' header included ("User-Agent: VSMarketplace/1.0"), but no 'Accept' or 'Accept-Encoding' headers. When I tried to mimic this using curl and Postman, it returns a 403. You can see this too with:
`curl -X HEAD -I --max-redirs 0 https://buttonwood.com.au -H "Accept:" -H "Accept-Encoding:" -H "User-Agent: VSMarketplace/1.0"`. It looks like there might be an access/permissions issue with this domain. Can you please let me know if this might be the issue?

**Comment by advay26** [comment]
@Chizaruu Can you please let me know the domain you are facing this issue with? It might be a similar problem for your domain as well. I can try to look into it for you.

**Comment by Chizaruu** [comment]
> @Chizaruu Can you please let me know the domain you are facing this issue with? It might be a similar problem for your domain as well. I can try to look into it for you.

https://www.koalahollow.com/
https://koalahollow.com/

**Comment by advay26** [comment]
@Chizaruu I tried sending HEAD requests to these domains, but I get a 500 Internal Server Error when I try that. You can see this with:
`curl -X HEAD -I https://www.koalahollow.com`
or 
`curl -X HEAD -I https://www.koalahollow.com -H "Accept:" -H "Accept-Encoding:" -H "User-Agent: VSMarketplace/1.0"`

This usually means there's a problem with the domain servers, permissions-related or otherwise. Without a more specific 5xx error code, it's difficult to diagnose where this error is coming from. Do you get 500 errors when you try sending a HEAD request to these domains too?

**Comment by davidbairdala** [comment]
Thanks @advay26 I can reproduce the 403 error from our domain when attempting a HEAD request with no "Accept" header. This server is hosted by a third party, but I will see what can be done about allowing these requests through.

**Comment by davidbairdala** [comment]
Just as an aside @advay26, is there any particular reason why the Accept header is omitted from the domain verification request? I understand that the Accept header is not mandatory, but it seems to be that at least some admins configure a 403 rule in their web servers for missing Accept headers in an attempt to block non-compliant crawlers and bots. (See https://serverfault.com/questions/795249/nginx-config-should-i-deny-requests-that-are-missing-the-accept-header). 

So on the one hand, yes, it's a HEAD request, and no response body is expected, but on the other hand, the HEAD request is supposed to simulate the GET request in all other respects, other than not returning a body, so it could be argued that it should have an Accept header. My two cents worth...

**Comment by advay26** [comment]
@davidbairdala Thanks for bringing that to our attention. I'm not sure if there was a conscious decision behind us not including an 'Accept' header, but I'll bring this to my team's attention, and we'll consider your suggestion. Thank you for your feedback!

I don't think we'll be able to address this anytime soon, so we'll need to find another workaround for your domain here for now. Please let us know if you're able to find a solution with your server host.

**Comment by davidbairdala** [comment]
Just for some additional context, the response to the HEAD request that returns the 403 error contains headers that indicate that our hosting provider is using Sucuri "Website firewall", which I guess is something similar to mod-security. The requests are being blocked by a "DDOS22" rule, the description of which can be found here: https://labs.sucuri.net/signatures/waf/ddos22-ddos-attempt-blocked/. I mention this only for posterity, and to add further weight to the idea that these HEAD requests should really include an Accept header.

As it turns out, we were not successful in convincing our hosting provider to relax these rules for the purposes of domain verification, so we worked around it by spinning up a temporary vanilla NGNIX instance that redirected everything other than HEAD requests to our production website and then pointed the DNS record for our domain to this server. The domain check has now passed and we have moved on to the next step in the process (awaiting manual approval, I think).

**Comment by advay26** [comment]
Thanks for the update and the additional context @davidbairdala. I took your recommendation to the team, and we agreed that we should be including an 'Accept' header in these HEAD requests and have now added that task to our backlog. I'm not sure exactly when we'll get to it, but this is something we intend to address soon. Thank you for providing valuable feedback!

**Comment by advay26** [comment]
I will go ahead and close this GitHub issue unless you have further questions. We have a tracking item for including an 'Accept' header with our HEAD requests, and I will try to provide an update here when we make progress on that item. Please feel free to reach out with any questions.
