### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by aryan-226** [microsoft/vsmarketplace#691]
Type: <b>Bug</b>

terminal  cant compile
![image](https://github.com/microsoft/vsmarketplace/assets/134290592/09d74de6-1a85-4330-8a1d-62f15da31461)

VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.4.0-1106-azure

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by madhurivadaligithub** [comment]
Hi @aryan-226 
Thank you for opening the issue. Sorry to hear you are experiencing the issue, It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
