### ISSUE TITLE
Error too many redirects - azure devops extension copy build steps

### ISSUE THREAD

**Issue by BastiDD** [microsoft/vsmarketplace#695]
I want to install the extension **copy build steps** into my Azure DevOps Server 2022 installation. Opening the details page of this extension results in an infinite loop of redirects.

**To Reproduce**
1. Open Chrome Browser
2. Go to https://marketplace.visualstudio.com/search?term=copy%20build%20step&target=AzureDevOps&category=All%20categories&sortBy=Relevance 
3. Open Developer Tools (F12) and navigate to Network Tab
4. Click on  Copy Build Steps Item in the Search Results
5. ERR_TOO_MANY_REDIRECTS appears in Browser window

**Expected behavior**
The Details Page of the Copy Build Steps Extension under https://marketplace.visualstudio.com/items?itemName=realdolmen.extensions-build-menu-copybuildsteps can be opened.

**Screenshots**
![image](https://github.com/microsoft/vsmarketplace/assets/3171067/cc657826-764c-444e-b313-ce3b6fb0bf0f)
![image](https://github.com/microsoft/vsmarketplace/assets/3171067/07d53452-72fa-4808-876d-a154317f60f9)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 21H2
 - Browser: Chrome
 - Version: 114.0.5735.91

**Additional context**
Also tried different Browsers on different maschines with the same result.

**Comment by AnitaToppo** [comment]
@BastiDD ,
Can you drop a mail with your queries to the group - [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) .

**Comment by BastiDD** [comment]
> @BastiDD , Can you drop a mail with your queries to the group - [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) .

I sent you an Email with the corresponding requests.

**Comment by AnitaToppo** [comment]
@BastiDD Thanks for informing, we will work on it.

Regards
Anita

**Comment by BastiDD** [comment]
@madhurivadaligithub the problem still exists. Why closing the issue without any comment?

**Comment by madhurivadaligithub** [comment]
Hi @BastiDD Since this appears to be a support request for which we recommend contacting VS Marketplace support team by visiting https://marketplace.visualstudio.com/manage and accessing ‘Contact Microsoft’ at the top right. 
Also we are tracking this from the CSR mails as we need some sensitive data from the customers.
