### ISSUE TITLE
extension are not shwing

### ISSUE THREAD

**Issue by Sainimmala02** [microsoft/vsmarketplace#698]
Type: <b>Feature Request</b>

how  to install extansion on vs code im new to it

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 6.1.7601
Modes:

**Comment by Sainimmala02** [comment]
i'm using in windows 7 .how to make access the extensions int vs code.it giving me as"error while fetching extensions .xhr failed.

**Comment by madhurivadaligithub** [comment]
Hi @Sainimmala02 
Could you please go through the document to install Marketplace extensions in VS Code https://code.visualstudio.com/docs/editor/extension-marketplace

Please let us know if you need any other details.

Thanks,
VS Marketplace Team
