### ISSUE TITLE
Folder Casing, (Github Desktop, Git Supercharged)

### ISSUE THREAD

**Issue by lnk3** [microsoft/vsmarketplace#70]
Issue Type: <b>Bug</b>

> This workspace was opened with a different casing than what exists on disk. Please re-open this workspace with the exact casing as it exists on disk, otherwise you may experience issues with certain Git features, such as missing blame or history.

Every time I open a folder it reads it as it was written with caps lock, which none of my folder are.
So it prints out this message.
- I recently moved to an insider preview in the dev channel
- Should I do `git config --global core.ignorecase true`?
Is this a big problem or negligible?

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.21370

**Comment by Neelima10735584** [comment]
Hi,

Thank you for reaching out to the VS Marketplace Team. To resolve this issue, you need to run git config --global core.ignorecase true to make Git ignore case differences. If the error persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
