### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by ToletiPraveenKumar** [microsoft/vsmarketplace#700]
Issue Type: <b>Feature Request</b>

Error while fetching extensions.XHR failed

VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

**Comment by madhurivadaligithub** [comment]
Hi @ToletiPraveenKumar 
Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.
