### ISSUE TITLE
error while instaling

### ISSUE THREAD

**Issue by daffa-art** [microsoft/vsmarketplace#706]
Type: <b>Bug</b>

Error while installing 'Debugger for Firefox' extension. Please check the log for more details.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @daffa-art 
Thank you for reporting your concern. We are following up to determine how best to address it, meanwhile could you please share Error screenshot and message to investigate better.

Thannks,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested data.
