### ISSUE TITLE
im not download extension

### ISSUE THREAD

**Issue by daffa-art** [microsoft/vsmarketplace#707]
Type: <b>Report bug</b>

Error while updating 'Error Lens' extension. Please check the [log](command:workbench.action.showWindowLog) for more details.

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @daffa-art
Thank you for reporting your concern. We are following up to determine how best to address it, in meanwhile could you please share error screenshot and log messages to investigate better.

Thanks,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested data.
