### ISSUE TITLE
why i can't install the extensions

### ISSUE THREAD

**Issue by TheSaintLuke** [microsoft/vsmarketplace#708]
Type: <b>Feature Request</b>

everytime i try to install the extensions (manim sideview) always error and will appear text "the editor could not be opened due to an unexpected error: XHR failed"

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @TheSaintLuke 
Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.
