### ISSUE TITLE
Icons not show up properly

### ISSUE THREAD

**Issue by DaiZack** [microsoft/vsmarketplace#711]
Type: <b>Bug</b>

After update insider June 22nd the Git lens and docker extension cannot show up on the left side bar. 

VS Code version: Code - Insiders 1.80.0-insider (Universal) (e8b22318bfab2e52d5dbceee767e8b4bfe9b5300, 2023-06-22T05:38:43.259Z)
OS version: Darwin arm64 22.5.0
Modes:
Remote OS version: Linux x64 5.19.0-1024-aws

<img width="115" alt="image" src="https://github.com/microsoft/vsmarketplace/assets/45176371/f27ef9c8-d44c-49c4-80f0-9b5dbbe33bb6">

**Comment by madhurivadaligithub** [comment]
Hi @DaiZack 
Thank you for opening the issue. Sorry to hear you are experiencing [insert customer issue]. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues. 

-VS Marketplace Team
