### ISSUE TITLE
c# (base lang support) extension won't install

### ISSUE THREAD

**Issue by r00tnpm** [microsoft/vsmarketplace#713]
Type: <b>Bug</b>

The C# extension by MS (latest v1.26.0) won't install on Windows 10 64bit, while other extensions don't have issue at all. The installation just hangs forever without completing. It has been an issue since Jan/Feb 2023, it still hasn't been fixed. Odd that MS's own stuff has this problem while 3rd party are fine. 

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @daffa-art
Thank you for reporting your concern. We are following up to determine how best to address it, in meanwhile could you please share error screenshot and log messages to investigate better.

Thanks,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for months. If the problem persists you can contact us with the requested details.

Thanks,
VS Marketplace Team
