### ISSUE TITLE
file link does not work  

### ISSUE THREAD

**Issue by nomi247** [microsoft/vsmarketplace#715]
Type: <b>Performance Issue</b>

i have add my picture link but the link is not opened ?

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @nomi247 Thank you for opening the issue. Sorry to hear you are experiencing [insert customer issue]. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
