### ISSUE TITLE
AZ AL Dev Tools/AL Code Outline

### ISSUE THREAD

**Issue by KhaledAhsoun** [microsoft/vsmarketplace#716]
Type: <b>Bug</b>

not working all functions

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @KhaledAhsoun 
Thank you for opening the issue. Sorry to hear you are experiencing [insert customer issue]. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
