### ISSUE TITLE
MongodB

### ISSUE THREAD

**Issue by pavan4113-coder** [microsoft/vsmarketplace#717]
Type: <b>Bug</b>

While i am installing MongoDb for VSCode ,I am not getting logo on the leftbar under the profile logo

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @pavan4113-coder 

Thank you for opening the issue. Sorry to hear you are experiencing [insert customer issue]. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
