### ISSUE TITLE
Dracula extension unavailable on marketplace

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vsmarketplace#720]
Originally reported in https://github.com/dracula/dracula-theme/issues/878

The official Dracula VS Code extension appears to have been unpublished from the marketplace and locked. cc @isidorn

**Comment by isidorn** [comment]
Fixed by @madhurivadaligithub 
The extension is again available. I will comment on the VS Code issue with more details since all the users are there. Thus closing this.
