### ISSUE TITLE
i am unable to download  java extension

### ISSUE THREAD

**Issue by 28sakshipatil** [microsoft/vsmarketplace#723]
Type: <b>Bug</b>

whenever i click on install button they show me "Error while downloading please check the log for details"

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @28sakshipatil  Thank you for opening the issue. Sorry to hear you are experiencing the issue, It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
