### ISSUE TITLE
/

### ISSUE THREAD

**Issue by Shubhamjadon05** [microsoft/vsmarketplace#725]
Type: <b>Bug</b>

/

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Shubhamjadon05 Thanks for reaching VS Marketplace Support Team, can you please share your concern with the Marketplace, we look forward to hearing from you. 

  -VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested data.
