### ISSUE TITLE
Unable to install Extensions in VSCode.

### ISSUE THREAD

**Issue by TaiDuc1001** [microsoft/vsmarketplace#727]
Type: <b>Bug</b>

I cannot install any extensions. It's just "INSTALLING"... for a very long time.
And i reinstalled VSCode but it doesn't work. It's still "INSTALLING".

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (2.50GB free)|
|Process Argv|--crash-reporter-id f1e4da94-89de-4380-a943-953f595c1cb6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
vsc-python-indent|Kev|1.18.0
cmake-tools|ms-|1.14.34
autodocstring|njp|0.6.1
intellicode-api-usage-examples|Vis|0.2.7
jinja|who|0.0.8
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30776702
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30766889
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30772539
pythonnoceb:30776495
cmakesidepanelv2:30779593

```

</details>

**Comment by msenol86** [comment]
the problem solved for me. I think Microsoft updated the Python package with a fix for this issue.

**Comment by madhurivadaligithub** [comment]
@TaiDuc1001 Thank you for opening the issue. sorry to hear you are experiencing the issue, are you still facing the extension installation issues? 
We look forward to hearing from you. 

 -VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.
