### ISSUE TITLE
Visual studio is connected to GitHub but does not generate any code 

### ISSUE THREAD

**Issue by bsingha123** [microsoft/vsmarketplace#730]
Type: <b>Bug</b>

It used to generate code but now it is not generating code. 
It is stuck.
I tested with simple things to generate names, or put data into a data frame in pandas.
The extension of co-pilot and copilot labs are there and I am logged to github 

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
