### ISSUE TITLE
download very long

### ISSUE THREAD

**Issue by redheet** [microsoft/vsmarketplace#731]
Type: <b>Bug</b>

my internet have a good signal, I have try install on market place visual studio it work, but in extensions on vscode not working

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19042
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @redheet 

Thank you for opening the issue. Sorry to hear you are experiencing the issue, It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
