### ISSUE TITLE
Server returned 503

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vsmarketplace#733]
```javascript
Error: Server returned 503
at a in src/vs/platform/request/common/request.ts:109:9
at e.$Po.B in out/vs/code/node/sharedProcess/sharedProcessMain.js:79:125835
at async e.$Po.z in src/vs/platform/extensionManagement/common/extensionGalleryService.ts:829:71
at async e.$Po.getExtensions in src/vs/platform/extensionManagement/common/extensionGalleryService.ts:663:26
at async D in src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts:429:32
at async e.$kp.G in out/vs/code/node/sharedProcess/sharedProcessMain.js:79:71278
at async e.$kp.C in src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts:217:48
at async in src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts:169:20
at async Promise.allSettled (index 0)
at async e.$kp.z in out/vs/code/node/sharedProcess/sharedProcessMain.js:79:64742
at async e.$kp.installGalleryExtensions in src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts:129:20
at async e.$kp.installFromGallery in src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts:97:20
```
[Go to Errors Site](https://errors.code.visualstudio.com/card?ch=74f6148eb9ea00507ec113ec51c489d6ffb4b771&bH=f3808ccb-9d0b-193f-1ee1-ff3565337a3b)

**Comment by joelverhagen** [comment]
@isidorn apologies on the delay. I haven't been able to look at this until now. I don't have access to the "Go to Errors Site" link in the original post above. Could I get an example HTTP request or repro steps for this? I don't remember the context to this at all, unfortunately.

**Comment by Tyriar** [comment]
@joelverhagen we don't record request info, this is our error telemetry which just sends stack traces of unhandled exceptions

**Comment by joelverhagen** [comment]
Okay, no worries. Do we have a time series of how often this exception is hit over time? I've done some querying against failures in Kusto specifically for gallery queries, but this seems to be exception telemetry.

**Comment by Tyriar** [comment]
Here's all the info we have on it for v1.81.0:

Stack
Error: Server returned 503
at c (out/vs/code/node/sharedProcess/sharedProcessMain.js:45:21680)
at ce.B (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:128527)
at async ce.z (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:125945)
at async ce.z (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:126885)
at async ce.getExtensions (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:122998)
at async M (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:73120)
at async H.I (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:73589)
at async H.F (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:68306)
at async (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:67129)
at async Promise.allSettled (index 0)
at async H.D (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:67076)
at async H.installGalleryExtensions (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:65540)
at async H.installFromGallery (out/vs/code/node/sharedProcess/sharedProcessMain.js:82:64861)


Deminified Stack
Error: Server returned 503
[at c in src/vs/platform/request/common/request.ts:109:9](https://vscode.dev/github/microsoft/vscode/blob/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/src/vs/platform/request/common/request.ts#L109:9)
at ce.B in out/vs/code/node/sharedProcess/sharedProcessMain.js:82:128527
[at async ce.z in src/vs/platform/extensionManagement/common/extensionGalleryService.ts:829:71](https://vscode.dev/github/microsoft/vscode/blob/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L829:71)
[at async ce.z in src/vs/platform/extensionManagement/common/extensionGalleryService.ts:882:27](https://vscode.dev/github/microsoft/vscode/blob/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L882:27)
[at async ce.getExtensions in src/vs/platform/extensionManagement/common/extensionGalleryService.ts:663:26](https://vscode.dev/github/microsoft/vscode/blob/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L663:26)
[at async M in src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts:468:32](https://vscode.dev/github/microsoft/vscode/blob/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts#L468:32)
at async H.I in out/vs/code/node/sharedProcess/sharedProcessMain.js:82:73589
[at async H.F in src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts:256:48](https://vscode.dev/github/microsoft/vscode/blob/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts#L256:48)
[at async in src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts:208:20](https://vscode.dev/github/microsoft/vscode/blob/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts#L208:20)
at async Promise.allSettled (index 0)
at async H.D in out/vs/code/node/sharedProcess/sharedProcessMain.js:82:67076
[at async H.installGalleryExtensions in src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts:134:20](https://vscode.dev/github/microsoft/vscode/blob/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts#L134:20)
[at async H.installFromGallery in src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts:102:20](https://vscode.dev/github/microsoft/vscode/blob/6445d93c81ebe42c4cbd7a60712e0b17d9463e97/src/vs/platform/extensionManagement/common/abstractExtensionManagementService.ts#L102:20)


Hits
469

Machines
450

Last Seen
yesterday

Versions
6445d93c81ebe42c4cbd7a60712e0b17d9463e97

---

It's happening here:

https://github.com/microsoft/vscode/blob/74f6148eb9ea00507ec113ec51c489d6ffb4b771/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L829

Some details about the url:

https://github.com/microsoft/vscode/blob/74f6148eb9ea00507ec113ec51c489d6ffb4b771/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L961

**Comment by Tyriar** [comment]
@joelverhagen all the info I have is in the issue so I'm handing this off to you to create an incident if you feel it's needed.

**Comment by josephplpriest** [comment]
Seeing this issue again for multiple team members at the moment.

**Comment by mariaghiondea** [comment]
It’s related to the ongoing azure issues - https://azure.status.microsoft/en-us/status

**Comment by isidorn** [comment]
fyi @joelverhagen
