### ISSUE TITLE
can not install extension

### ISSUE THREAD

**Issue by LaWass1864** [microsoft/vsmarketplace#735]
Type: <b>Bug</b>

Hello, 

I can't download extensions.
I have this message on the bottom right : 
Error while installing 'Prettier - Code formatter' extension. Please check the log for more details.

Thank's

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @LaWass1864 
Thanks for reaching out, we are unable to repro the issue, could you please share the log/error details to investigate better.

**Comment by madhurivadaligithub** [comment]
Closing the issue, If the problem still exists, feel free reopen the ticket or create a new one. 

Thanks,
VS Marketplace Support Team
