### ISSUE TITLE
vsix installtion proiblem

### ISSUE THREAD

**Issue by WillDoIt26** [microsoft/vsmarketplace#736]
Type: <b>Bug</b>

There is this problem in installing extensions from the in-built extension manager in vs code , so I downloaded vsix file from marketplace and tried installing through the vsix file but now it shows ' unterminated string in JSON at position 4096 '. This feels like a bug to me at this point please do something about it.

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:25.257Z)
OS version: Linux x64 5.19.0-46-generic snap
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
