### ISSUE TITLE
Extensions Not available 

### ISSUE THREAD

**Issue by Renukabodduluri12** [microsoft/vsmarketplace#737]
Type: <b>Bug</b>

Hi Team,
While searching for extension I'm getting the error msg like: XHR timeout: undefinedms. Can you please help me to fix this issue.

Thanks

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Renukabodduluri12 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.
