### ISSUE TITLE
XHR Failed

### ISSUE THREAD

**Issue by Degbola** [microsoft/vsmarketplace#739]
Type: <b>Performance Issue</b>

I have been trying to update and download new extensions but the only thing i  keep getting is XHR failed, and no i don't have a proxy 

VS Code version: Code 1.80.1 (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:22:07.651Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Degbola 
Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

**Comment by Degbola** [comment]
> 

The issue cleared by itself, I didn't have to do anything at all. Thanks you for the reply
