### ISSUE TITLE
eslint and sonarlint are not working

### ISSUE THREAD

**Issue by Shiva-Karthik** [microsoft/vsmarketplace#740]
Type: <b>Bug</b>

Install the extensions and check whether it is working or not

VS Code version: Code 1.80.2 (Universal) (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T21:05:41.366Z)
OS version: Darwin arm64 22.1.0
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Shiva-Karthik 
We are waiting to hear from you, please respond to our previous request for information within the next three business days if you still need your support request addressed.
