### ISSUE TITLE
Error while fetching extentions. XHR failed.

### ISSUE THREAD

**Issue by fatinanwar** [microsoft/vsmarketplace#741]
Type: <b>Bug</b>

I can't install extention after update my vscode.

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.22621
Modes:
![Untitled](https://github.com/microsoft/vsmarketplace/assets/61442453/8fb7f38e-424d-4bdb-a00d-9b3c33e57856)

**Comment by madhurivadaligithub** [comment]
Hi @fatinanwar  Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

**Comment by fatinanwar** [comment]
Disabled my ethernet and change to wireless network and it works. thanks
