### ISSUE TITLE
Extensions is automatically uninstalled

### ISSUE THREAD

**Issue by chengyue655** [microsoft/vsmarketplace#742]
Type: <b>Bug</b>

I use vscode-1.81.0 on Windows 10, and remote Linux server with Remote-SSH extension.

Extensions ISSUES:
1. The **MS-CEINTL.vscode-language-pack-zh-hans** is automatically uninstalled on vscode-Windows-1.81.0 and vscode-linux-server.
2. The **twxs.cmake** is automatically uninstalled on vscode-linux-server.

VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 3.10.0-862.3.3.el7.x86_64
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2
Remote OS version: Linux x64 3.10.0-862.3.3.el7.x86_64

**Comment by chengyue655** [comment]
I updated VS code 1.81.1 today, this problem has be resolved.

But I meet a new problem.

All extensions do not work on centos-7 vscode-server.

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing [insert customer issue]. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues. 

-VS Marketplace Team
