### ISSUE TITLE
Publish extension fails with error TF400898

### ISSUE THREAD

**Issue by danielvaughn** [microsoft/vsmarketplace#743]
**Describe the bug**
I've attempted to publish an extension to VSCode both from the cli and the web UI. It's been failing with a consistent error code. This is my first time attempting to publish this extension so I have no history of successful publishing attempts. As a test, I intentionally misconfigured the package to ensure that the `vsce package` command was properly failing in that scenario, and it failed as expected. So I can confirm that the package is correctly configured.

**To Reproduce**
Steps to reproduce in cli:
1. cd to a project directory
2. Compile the project: `vsce package`
3. Observe expected result: ` DONE  Packaged: /path/to/file/file-0.0.1.vsix (9 files, 4.4KB)`
4. Publish the package: `vsce publish`
5. Observe failure: ` ERROR  TF400898: An Internal Error Occurred. Activity Id: d72ecd2e-a897-44e6-ad8b-5a69a40b01a8`

Steps to reproduce in web UI:
1. Navigate to https://marketplace.visualstudio.com/manage/publishers/my-package
2. Choose "New Extension" > "Visual Studio Code"
3. Select the compiled `.vsix` file to upload
4. Click "upload"
5. Observe failure message: `TF400898: An Internal Error Occurred. Activity Id: 37420aad-d2d3-425f-a575-61edc6a1da10`

**Expected behavior**
Any of the following behaviors:
1. If the package is valid, publish without failure to either the cli or web UI
2. If the package is not valid, produce an error that describes a remediation path
3. If the package is not valid, fail on `vsce package` with an error that describes a remediation path

**Screenshots**
None

**Desktop:**
 - OS: Mac Ventura 13.4.1
 - Browser: Chrome
 - Version: vsce 2.20.1

**Smartphone:**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
The package I'm attempting to publish is called Matry, and it's a simple language extension that only provides syntax highlighting. Link to repo: https://github.com/matry/vscode

**Comment by madhurivadaligithub** [comment]
Hi @danielvaughn 

Thank you for contacting Visual Studio Marketplace Support. We received your message, and we will get back to you with a response as quickly as possible.  
 

Primary support team business hours are 9AM - 5PM, weekdays Indian Standard Time. Have any additional details that can help us assist you? Feel free to send it by replying to this email.

**Comment by agr** [comment]
Hey, sorry for a very late response.

Looking at [package.json](https://github.com/matry/vscode/blob/main/package.json) in the repository you mentioned, it `displayName` property specified as an empty string. It is required to be non-empty. Could you please try specifying it and publishing again?

It absolutely should have been mentioned in the error, apologies for the confusion.

**Comment by danielvaughn** [comment]
This worked, thank you.

**Comment by agr** [comment]
Filed a work item to provide better error messages when validating extension metadata.

**Comment by danielvaughn** [comment]
Thank you @agr! Much appreciated.
