### ISSUE TITLE
Extension Menu Not Opening

### ISSUE THREAD

**Issue by Cargren18** [microsoft/vsmarketplace#746]
![VSCode Extension Bug](https://github.com/microsoft/vsmarketplace/assets/97390393/f4445b9a-01ec-447d-b653-a2f7be0b2ec9)
Type: <b>Bug</b>

When I click on extension menu ,it does not show anything except extension at the top, no search bar, nothing pops up either.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by Cargren18** [comment]
I recently got this problem and installing extensions have become longer as compared to the previous experience.

**Comment by madhurivadaligithub** [comment]
Hi @Cargren18 
Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team

**Comment by Cargren18** [comment]
Ok thanks
