### ISSUE TITLE
extension is not starting 

### ISSUE THREAD

**Issue by kd1318** [microsoft/vsmarketplace#747]
Issue Type: <b>Bug</b>

extension marketplace has no extension shown, something is written <error while fetching . XHR failed >
pls help me to solve my issue

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:57.229Z)
OS version: Windows_NT ia32 6.1.7601
Restricted Mode: No

**Comment by madhurivadaligithub** [comment]
Hi @kd1318 
Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.
