### ISSUE TITLE
Cannot create a Visual Studio Marketplace publisher account

### ISSUE THREAD

**Issue by RiversJohn** [microsoft/vsmarketplace#748]
**Describe the bug**
Filling out the fields in the create publisher page and then clicking Create results 
in an error message shown above the create button instead of an account being created.

**To Reproduce**
1. Open https://marketplace.visualstudio.com/manage/createpublisher?managePageRedirect=true
2. Fill out the fields
3. Click Create
4. See error: TF400898: An Internal Error Occurred. Activity Id: a372f32b-2c68-4ded-8a0f-7cb026572dff

**Expected behavior**
A new publisher account is created successfully and the user is redirected to the correct page

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser: Microsoft Edge
 - Version: 116.0.1938.54
 - Also tried with Brave, same issue

**Additional context**
Obviously not everyone hits this obstacle as you would've noticed it rather quick.
Please give instructions on what additional information i can give you to get this resolved.

**Comment by madhurivadaligithub** [comment]
Hi @RiversJohn Thank you for reporting your concern. We are following up to determine how best to address it.

 -VS Marketplace Team

**Comment by RiversJohn** [comment]
Any additional information available or can i provide anything else you need? 

I'd like to publish my extension so i and any colleagues (or anyone else for that matter)
can easily install it from the marketplace.

**Comment by madhurivadaligithub** [comment]
Hi @RiversJohn 
Please try creating the publisher in a new browser/incognito or after clearing the cache.

Kindly let us know if you still facing the issue.

-VS Marketplace

**Comment by madhurivadaligithub** [comment]
Hi @RiversJohn 
Since we have not yet received the necessary information here, we hope this issue was resolved.
If the problem still exists, feel free to comment or open a new issue.

Thanks,
VS Marketplace Team

**Comment by RiversJohn** [comment]
Apologies i have been rather busy.

I just tried again, with Microsoft Edge cache cleared and incognito with fresh cache and the end result is the same with just a different activity Id:
`TF400898: An Internal Error Occurred. Activity Id: 4fc6e7c8-87a5-470d-81b5-5444dc5321b1`

Also tried Brave and Chrome, all three of course are chromium based but considering those cover super majority of users i doubt that's the cause.
