### ISSUE TITLE
Azure funtions

### ISSUE THREAD

**Issue by SwallowNest111** [microsoft/vsmarketplace#749]
Type: <b>Bug</b>

ECONNREFUSED error report when creating new Azure functions project
Language: C#
Runtime: .Net 6

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

```[tasklist]
### Tasks
```

**Comment by madhurivadaligithub** [comment]
Hi @SwallowNest111 
Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
