### ISSUE TITLE
cannot connect to extensions marketplace

### ISSUE THREAD

**Issue by brr012491** [microsoft/vsmarketplace#75]
Issue Type: <b>Bug</b>

I wrote some code and I pressed run and then it said cannot connect to the extensions marketplace at this time please try again later

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19042

**Comment by prashantvc** [comment]
Could you share more information? Steps to reproduce will really help
