### ISSUE TITLE
Domain verification is not processed after three months

### ISSUE THREAD

**Issue by abdul-alhasany** [microsoft/vsmarketplace#750]
**Describe the bug**
I have submitted my domain for verification around two months ago but it has not been processed and I have not received any feedback yet.

**To Reproduce**
N/A

**Expected behavior**
Domain to be verified or feedback to be sent if there are any issues.

**Screenshots**
![image](https://github.com/microsoft/vsmarketplace/assets/1753883/eac33256-eab4-4637-8bf9-9f72abe16958)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [116.0.5845.110]

**Additional context**
I have created a [topic in discussion ](https://github.com/microsoft/vsmarketplace/discussions/710) a couple of months ago but did not received any response.

- Publisher Name: [KalimahApps](https://marketplace.visualstudio.com/publishers/KalimahApps)

**Comment by madhurivadaligithub** [comment]
Hi @abdul-alhasany 
Thanks for reaching VS Marketplace Team, the status of your domain has been updated.

Can you please update company url in publisher profile

**Comment by abdul-alhasany** [comment]
Hi @madhurivadaligithub 
This still an issue. It was verified for a while and now it is not.
