### ISSUE TITLE
extension not install in vscode

### ISSUE THREAD

**Issue by ABHI981211** [microsoft/vsmarketplace#751]
Type: <b>Bug</b>

installation error in marketplace . i am install any extension it show try manually.please help and solve the problem.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @ABHI981211  Thanks for reaching VS Marketplace Team, could you please provide us more information about your issue so we can investigate it further?

**Comment by madhurivadaligithub** [comment]
@ABHI981211  Since we have not received any required data from you, hope this issue got resolved.
Please feel free to respond or create a new issue if you are still having trouble.
