### ISSUE TITLE
Download and installation of the extension fails due to CDN rate limiting

### ISSUE THREAD

**Issue by ceculbe** [microsoft/vsmarketplace#756]
Does this issue occur when all extensions are disabled?: Not Applicable - Related to Extension Installation

### Environment
Operating System: Windows x64
JDK version: 17.0.8
Visual Studio Code version: 1.81.1
Java extension version: 0.25.13

### Steps To Reproduce
> 1. search for extension in Marketplace
> 2. click 'install'
> 3. If given the option, proceed with manual download

Download and install will usually fail. Failure is intermittent, but >90% in our tests. 

### Current Result
Download of the extension package fails about 90% of the time. A popup appears with the option to download manually via browser. The manual download also fails 90% of the time with a browser error message indicating that "Request was blocked due to exceeding usage of resource . . . " (further details in attached screenshot.)
<img width="960" alt="262097126-1c7bf580-46ca-4920-aa06-11e588191451" src="https://github.com/microsoft/vscode/assets/10868522/1ed5317a-df46-4e3b-a8f0-69b8bcedb930">

### Expected Result
Once clicking 'install' on the extension page, download and installation proceeds without user involvement.

### Workaround
Navigating to the extension's Marketplace web page and downloading the extension from that page is successful. However, this requires manual install from the .vsix file and is difficult to manage in an education environment.

**Comment by madhurivadaligithub** [comment]
Hi @ceculbe Thank you for reporting your concern. We are following up to determine how best to address it. 

 -VS Marketplace Team

**Comment by drewgillies** [comment]
@ceculbe could you please try adding a parameter `redirect=true` to the URI your tests use? This may give you better performance as the API call will redirect to the CDN.

**Comment by ceculbe** [comment]
I can test adding redirect=true to the URI. The major issue, though, is that the download failures break the installation script when running the one-step Java Coding Pack installer executable (https://aka.ms/vscode-java-installer-win) as well as the "Extension Pack for Java" installation script. We use these extensively in our educational environment.

**Comment by drewgillies** [comment]
Thanks, @ceculbe. I'll be interested to know if the test alleviates the breaks. If not, we can investigate further.

**Comment by madhurivadaligithub** [comment]
Hi @ceculbe Since it has been ten days and we haven't received any response here, we are closing this issue. If the issue still persists, feel free to comment or open a new Github issue.

cc: @drewgillies

Thanks,
VS Marketplace Team
