### ISSUE TITLE
this does not look legit

### ISSUE THREAD

**Issue by nielslauritzen0** [microsoft/vsmarketplace#758]
Type: <b>Bug</b>

i entered a manifest file   'manifest.mf'
the marketplace search for extensions suggests:
"Meow Fuck" extension.  I did not load it.
I doubt it is legit.

VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

**Comment by madhurivadaligithub** [comment]
Hi @nielslauritzen0 
We are closing the issue since we have not received the necessary information over the past ten days.

If the issue still continues, could you kindly start a new issue or leave a comment here?
