### ISSUE TITLE
fail created javascripts

### ISSUE THREAD

**Issue by adminiondeveloping** [microsoft/vsmarketplace#76]
Issue Type: <b>Bug</b>

i want to create javascipts and i dont can

VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:35:57.887Z)
OS version: Windows_NT x64 10.0.19041

**Comment by adminiondeveloping** [comment]
please help me to create scripts on visual studio code to run the server!!!

**Comment by prashantvc** [comment]
Could you share more details please?
