### ISSUE TITLE
GNU Guile

### ISSUE THREAD

**Issue by AGoh2019** [microsoft/vsmarketplace#767]
Type: <b>Bug</b>

Have the latest version of VS Code. August edition. No GNU Guile extension found.

VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @AGoh2019 

Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

If you have any issues with any Marketplace specific extension, please share the extension details for investigation.

-VS Marketplace Team
