### ISSUE TITLE
debugging time issue

### ISSUE THREAD

**Issue by pratima369** [microsoft/vsmarketplace#77]
Issue Type: <b>Bug</b>

debugging issue not found html extention find in marketplace error msg show

even previously run very smooth without any issue

VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19041

**Comment by prashantvc** [comment]
Could you share more information please?
