### ISSUE TITLE
Unexpected search results when matching extension publisher

### ISSUE THREAD

**Issue by hbons** [microsoft/vsmarketplace#773]
On the extension details page,when you click on the publisher's name it does a fuzzy match on the name.

I’d expect this to only show extensions from that exact publisher.
Could be used to trick (new) users into installing something bad?

![image](https://github.com/microsoft/vsmarketplace/assets/103326/a50556f3-c0e6-4e63-bbc8-d321841385b1)

**Comment by hbons** [comment]
cc @isidorn (I'm not able to assign you)

**Comment by madhurivadaligithub** [comment]
Hi @hbons 

Thank you for raising the concern, we will get back to you with a response as quickly as possible.  

Primary support team business hours are 9AM - 5PM, weekdays Indian Standard Time. Have any additional details that can help us assist you? Feel free to send it by replying to this email. 

 Thanks, 
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @hbons 

Currently Visual Studio Marketplace does not support this publisher specific search, please search with github name in this case to get github related extensions.

Thanks,
VS Marketplace Team

**Comment by hbons** [comment]
Hi, the issue isn’t that I’m not able to search for the publisher, but that malicious extension writers can use this behaviour to insert themselves into official looking search results and trick users to install their extension.
