### ISSUE TITLE
Not being able to download extensions

### ISSUE THREAD

**Issue by tomatoprogrammer** [microsoft/vsmarketplace#774]
Type: <b>Bug</b>

I am not able to download extensions as when I click to install it,it tells me "error while installing 'Live Server' extension.Please check the log for more details" but doesnet help me..

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @tomatoprogrammer As we are unable to reproduce the issue, kindly send the error screenshot or logs so that we can investigate more thoroughly.

Thanks,
-VS Marketplace Team

**Comment by tomatoprogrammer** [comment]
the issue is now solved
