### ISSUE TITLE
Simple starter

### ISSUE THREAD

**Issue by yarikgames2013k** [microsoft/vsmarketplace#775]
Type: <b>Bug</b>

я не знаю как удалить дополнение: Simple starter

VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
