### ISSUE TITLE
Images not loading in extension description page 

### ISSUE THREAD

**Issue by TimeMachine777** [microsoft/vsmarketplace#778]
![VS code extensions bug](https://github.com/microsoft/vsmarketplace/assets/133058473/4e6f5a97-e7b6-4c85-bc50-97d2dc277f3d)
Type: <b>Bug</b>

Images do not load in the extension description page of any extension despite a very good internet connection, also everything else loads up except the images.

I even updated the application, restarted it and disabled then re-enabled the extensions, but nothing seems to work.

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @TimeMachine777 

Thank you for opening the issue. Sorry to hear you are experiencing, It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues. 

 -VS Marketplace Team
