### ISSUE TITLE
Webpage does not appear when rendered

### ISSUE THREAD

**Issue by byui-dev** [microsoft/vsmarketplace#780]
Type: <b>Performance Issue</b>

I have written code in HTML and CSS and installed the live server extension to allow me to view the webpage when it is opened with the live server but the webpage does not appear

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @byui-dev 

This issue appears to be a support question specific to the extension which is best addressed by the extension owner.  I recommend visiting the extension page on [https://marketplace.visualstudio.com/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmarketplace.visualstudio.com%2F&data=04%7C01%7Cv-vetha%40microsoft.com%7Cb1956b640d3a44eb898f08d91c482d31%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637571918734051307%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=NCEMCpDn6d4iWw3Pe8rcmtZEeHF9RaDwgAKWuFTP5L4%3D&reserved=0) and posting a question there. Let me know if I can help you with anything else.

Thanks,
VS Marketplace Team
