### ISSUE TITLE
Vscode cannot access extensions marketplace when http.proxy contains user credentials

### ISSUE THREAD

**Issue by digeomel** [microsoft/vsmarketplace#783]
Type: <b>Bug</b>

I have checked most previously reported issues related to the proxy and extensions (and there are quite a few and mostly a few years old), and although those have been closed/solved, mine is not.

I'm on Ubuntu 22.04.3 LTS.

First of all, there are two separate issues here:
1) How vscode accesses the extensions marketplace for updates/installs
2) How extensions access the Internet

My proxy-related settings are as follows:

```json
{
    "http.proxy": "http://user:password@10.20.30.40:5678/",
    "http.proxySupport": "on",
    "http.proxyAuthorization": null,
    "http.proxyStrictSSL": false,
}
```
With the settings above, vscode cannot access the extensions marketplace. If I remove the `user:password@` part, everything works fine.

**However**, and this is related to the 2nd issue, using this extension: https://marketplace.visualstudio.com/items?itemName=chrmarti.network-proxy-test which I assume tests if extensions can access the Internet, it is the other way around. Without the user credentials, it fails, with them it works.

The environment variables `http_proxy` and `https_proxy` are both set to `http://user:password@10.20.30.40:5678/`.

I realize that for the 2nd issue different extensions might use different ways to access the Internet, and some may not work with the proxy settings, but why can't vscode access the extensions marketplace when user credentials are present?

VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:11:49.843Z)
OS version: Linux x64 5.15.0-86-generic snap
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @digeomel 

Thank you for reaching VS Marketplace Support Team. We are following up to determine how best to address it.

 -VS Marketplace Team

**Comment by digeomel** [comment]
Thank you @madhurivadaligithub .
Please note that I also tried setting `http.proxyAuthorization` to a base64-encoded string of `user:password`, but that didn't work for both scenarios. In this case, I'm also not sure if special characters like `@` which normally have to be url-encoded, as `%40`, need to be encoded here before passed to base64, or there's no need for encoding at all. I think I tried both.

**Comment by lyndaidaii** [comment]
@digeomel, this is specific to vscode proxy setting.  We would suggest you create the GitHub issue on this repo: https://github.com/microsoft/vscode.

**Comment by digeomel** [comment]
@lyndaidaii ok, thank you, I will. Closing this.
