### ISSUE TITLE
I can't log into my account into the marketplace, either beta or public

### ISSUE THREAD

**Issue by FrankyFJQ** [microsoft/vsmarketplace#784]
I can't log into my account into the marketplace, either beta or public

Repro steps:
1. Go to "https://marketplace.visualstudio.com/" or "https://marketplace.vsallin.net/"
2. Click on 'sign in'
3. You will see "Bad Request - Request Too Long. HTTP Error 400. The size of the request headers is too long."
![image](https://github.com/microsoft/vsmarketplace/assets/129366604/4119a663-830d-487d-be59-60be58cba988)

**Comment by FrankyFJQ** [comment]
Anyone help with the problem? Currently I can't use marketplace to download and upload extensions.

**Comment by joelverhagen** [comment]
Hey @FrankyFJQ, does this problem reproduce on both on marketplace.visualstudio.com and marketplace.vsallin.net? In your screenshot I just see the PPE environment.

Second, could you try clearing your browser cookies and trying again?

**Comment by FrankyFJQ** [comment]
Yes, this problem reproduces on both on marketplace.visualstudio.com and marketplace.vsallin.net. I just only took a screenshot of them. I had searched the web and found your suggestion: clearing cookies, but it doesn't work. After I clear the cookies, I can see the not logged in screen, but when I click sign in, it goes back to that. There is a git and you can see the detail.
![mp error](https://github.com/microsoft/vsmarketplace/assets/129366604/586efcef-fea2-4f13-a91f-3e69ea4f2d7b)

**Comment by FrankyFJQ** [comment]
@joelverhagen Could you please start looking into this? Do you need any information from me? I still can't access marketplace today.

**Comment by joelverhagen** [comment]
Hey Franky, let's communicate internally over Teams and we can investigate the issue together.

**Comment by joelverhagen** [comment]
I have attempted a fix in PPE. Could you try there? I expect PROD to still have the problem.

**Comment by FrankyFJQ** [comment]
Yes, as you said, I can successfully sign in PPE, but public's marketplace still reports this error.

**Comment by joelverhagen** [comment]
Thanks for the confirmation. This will be automatically fixed in a subsequent deployment in PROD in the near future (M229 for reference). Could you use PPE in the meantime?

**Comment by FrankyFJQ** [comment]
OK thanks for the help, I don't know what is M229?

**Comment by FrankyFJQ** [comment]
Now both sites are working for me, I'll close this bug.
Thanks for your investigation and help.
