### ISSUE TITLE
cannot see or install any extentions

### ISSUE THREAD

**Issue by lud89** [microsoft/vsmarketplace#789]
Type: <b>Bug</b>

cannot see or install any extentions on my mac mini m2 
open vscode
search for extentions
error while fetching extensions. XHR timeour: undefinedms

VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 23.0.0
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @lud89 Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.

Thanks,
VS Marketplace Team
