### ISSUE TITLE
Cannot add new member to extension publisher

### ISSUE THREAD

**Issue by lhl2617** [microsoft/vsmarketplace#79]
> This issue is transferred from https://github.com/microsoft/vscode-vsce/issues/573

I am following the steps in this comment: 
https://github.com/microsoft/vscode/issues/21478#issuecomment-284889034

And I'm getting this error (TF14045) when trying to add another user:

![image](https://user-images.githubusercontent.com/33488131/118398921-92b76c80-b652-11eb-8bf4-7a65ea1d9745.png)

FWIW, I'm currently developing extension under a university org account, and will be leaving the university and would like it transferred. It seems like adding a personal account is the easier option (other than explicitly deprecating the extension and starting from a clean slate). I suspect that people outside the org cannot be reached and hence the error.

I was able to add another user in the same org (university).

It's been four years since extension transferral was requested--any updates on a better flow?

**Comment by ssbarnea** [comment]
Yep, it is broken beyond repair and nobody even bother to ack it. I tried adding another extension author while checking his email but it still does not allow adding new member.

**Comment by lhl2617** [comment]
Has this issue been flagged before? Any resolution/ACK at all?

**Comment by lhl2617** [comment]
Can we get an ACK on this?

cc @joaomoreno

**Comment by TalkIsCheap0** [comment]
i meet the same error !!!
![image](https://user-images.githubusercontent.com/49405187/123116162-a2a94400-d47b-11eb-97bd-586b0f46b982.png)

**Comment by amit-kulkarni-in** [comment]
Currently we are allowing User Id to add members to the publisher . The User Id can be found by hovering on the email id as shown below.  Please let us know if u are still facing issue.
![image](https://user-images.githubusercontent.com/104777722/211794659-f90a90b0-7aa8-4a10-a70c-6e962fa2b8ba.png)
