### ISSUE TITLE
Installed Extensions not updating or showing up in Extension tab.

### ISSUE THREAD

**Issue by Sammit81** [microsoft/vsmarketplace#790]
Type: <b>Performance Issue</b>

Whenvever I open the extension tab, the extensions which are already installed dont't show up in the extension tab. I even have them all enabled but they don't show up. Also earlier,  it was working fine, but the extensions installed are not updating for some reason, like it just shows that it's installing but it doesn't complete the update. I also tried installing the extensions through .VSIX ,  but it doesn't work.

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Sammit81 
Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
