### ISSUE TITLE
all extension is uncexpectedly 3 times within the last 5 minutes

### ISSUE THREAD

**Issue by adirasakhi** [microsoft/vsmarketplace#791]
Type: <b>Bug</b>

> Issue troubleshooting has identified that the issue is with Visual Studio Code. It is confirmed that the issue exists in Visual Studio Code Insiders

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:45:31.402Z)
OS version: Linux x64 5.15.0-86-generic snap
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @adirasakhi 

Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
