### ISSUE TITLE
Cannot install new extensions

### ISSUE THREAD

**Issue by vjtorres88** [microsoft/vsmarketplace#793]
Type: <b>Bug</b>

I and another co-worker are trying to install a new extension and cannot seem to be able to do it. Clicking on the Install button seems to just leave the extension stuck but never installs. Seems to have started when updating to latest version of VS code.

Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 3.10.0-1160.102.1.el7.x86_64

**Comment by madhurivadaligithub** [comment]
Hi @vjtorres88 
Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
