### ISSUE TITLE
Extension download Not working

### ISSUE THREAD

**Issue by asahelcode** [microsoft/vsmarketplace#794]
Type: <b>Bug</b>

Each time I try to download an extension I am being told to download manually, which also does not work

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @asahelcode 
Thanks for reaching VS Marketplace, please share error message or screenshot to investigate better. 

If you feel this issue is related to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @asahelcode 

Closing the issue since there has been no updates on the information requested.
