### ISSUE TITLE
"The domain url provided could not be reached" when verifying a publisher domain

### ISSUE THREAD

**Issue by sitingren** [microsoft/vsmarketplace#795]
When adding our website (https://www.vertica.com) to Domain name and click "Save", it returns "The domain url provided could not be reached" error.

![image](https://github.com/microsoft/vsmarketplace/assets/15162542/c3f18e7a-ade9-4311-a03d-263392041e01)

Inspect the url with `curl`, it returns 200 OK.
![image](https://github.com/microsoft/vsmarketplace/assets/15162542/b47dafeb-1933-4160-85f4-030f47c4b3c6)

We'd like to know how to get rid of this error and verify our url. Thanks.

**Comment by madhurivadaligithub** [comment]
Hi @sitingren 
Thank you for reaching VS Marketplace Support Team. We are following up to determine how best to address it.

 -VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @sitingren 
Are you still experiencing the issue? Please let us know if the problem persists or if there have been any changes.

Thanks,
VS Marketplace Team

**Comment by yangwooseong** [comment]
@madhurivadaligithub 

Same issue happens trying to add my team website (https://channel.io). Could you help?

**Comment by aminya** [comment]
@madhurivadaligithub  I am facing the same issue with abacus.ai. Getting the error: `The domain url provided could not be reached`

**Comment by madhurivadaligithub** [comment]
@aminya  Kindly contact us through our official support alias VSMarketplace@microsoft.com to help us address this issue promptly.
