### ISSUE TITLE
C# dev kit

### ISSUE THREAD

**Issue by andrea942303** [microsoft/vsmarketplace#796]
Issue Type: <b>Feature Request</b>

it does not want to install an extension c# dev kit and I just want to do that

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:49:10.067Z)
OS version: Windows_NT ia32 6.1.7600
Restricted Mode: No

still not working. I tried to install c# dev kit and its not working

**Comment by madhurivadaligithub** [comment]
Hi @andrea942303 
Thanks for reaching VS Marketplace Team, please provide additional details about your concern, it will help for investigation.

Thanks,
VS Marketplace Team
