### ISSUE TITLE
XHR

### ISSUE THREAD

**Issue by hajar-eddal** [microsoft/vsmarketplace#797]
Type: <b>Performance Issue</b>

i can't install any extention , and i get the XHR faild erroe 

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @hajar-eddal 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @hajar-eddal 
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.

Thanks,
VS Marketplace Team
