### ISSUE TITLE
XHR failed

### ISSUE THREAD

**Issue by A-Straight** [microsoft/vsmarketplace#798]
Type: <b>Bug</b>

Search for anything in the Extensions: Marketplace search bar, after loading it will not display any results only 'Error while fetching extensions. XHR failed'

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:57:32.750Z)
OS version: Darwin arm64 23.0.0
Modes:

![Screenshot 2023-10-24 at 8 26 00 PM](https://github.com/microsoft/vsmarketplace/assets/144737849/fe438bd6-b123-4c8b-a1a5-c7b64f08a560)

**Comment by madhurivadaligithub** [comment]
Hi @A-Straight 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @A-Straight 
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.

Thanks,
VS Marketplace Team
