### ISSUE TITLE
Extensions installation issues

### ISSUE THREAD

**Issue by Amine123-fd** [microsoft/vsmarketplace#799]
Type: <b>Performance Issue</b>

i can't install the extensions from the software itself or even the marketplace,
first when i try to install it from vs code it shows this message: Error While Installing Extension Please Check the Log.
and when i try to install it manually i get this message: Bad control character in string literal in JSON at position 7.
i hope you guys fix it or tell me how to fix it,

VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Amine123-fd 

Thank you for reaching VS Marketplace Support Team. We are following up to determine how best to address it.

 -VS Marketplace Team
