### ISSUE TITLE
Your extension has suspicious content. Please fix your extension metadata

### ISSUE THREAD

**Issue by ShejanMahamud** [microsoft/vsmarketplace#800]
I'm facing this error " Your extension has suspicious content. Please fix your extension metadata, or contact support if you need assistance. ".

Extension link: https://marketplace.visualstudio.com/items?itemName=ShejanMahamud.nightfall-glow

**Comment by jjeejj** [comment]
I have encountered the same problem, how can I solve it？ @ShejanMahamud

**Comment by ericbh22** [comment]
> I have encountered the same problem, how can I solve it？ [@ShejanMahamud](https://github.com/ShejanMahamud)

same did u figure it out

**Comment by bakhirev** [comment]
Faced with the same problem. I changed all the fields and the source code. The error does not disappear. The technical support team has not responded to the email for several days.
