### ISSUE TITLE
Manage Publishers & Extensions does not list owned publishers

### ISSUE THREAD

**Issue by zobo** [microsoft/vsmarketplace#802]
**Describe the bug**
The Manage Publishers & Extensions interface does not list any publishers. I can only get to them by entering the URL manually (https://marketplace.visualstudio.com/manage/publishers/PUBLISHER)

**To Reproduce**
1. Login to marketplace
2. Open https://marketplace.visualstudio.com/manage
3. On the left side there will be a "+ Create publisher" but no publishers listed

**Expected behavior**
A list of owned publishers should be visible.

**Screenshots**
![image](https://github.com/microsoft/vsmarketplace/assets/2456026/6c778ce4-821f-4bf7-b58d-c2a132bf22b9)
Note: I am added to 3 publishers as owner.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge, Chrome
 - Version 119.0.2151.44 64bit

**Additional context**
Tried two browsers, incognito/private mode too.

There is also a bunch of tracking link errors:
![image](https://github.com/microsoft/vsmarketplace/assets/2456026/2ebdf333-7b53-480f-9eab-896892a5bf15)

**Comment by madhurivadaligithub** [comment]
Hi @zobo 
Thanks for reaching VS Marketplace Team, we have investigated and added this issue to our backlog. 

We are currently not working on it because of other priorities, but we will keep you informed as soon as possible.

Yes, as you mentioned, the workaround would be to pass publisher id to url for managing extensions.

**Comment by oleg-shilo** [comment]
Thank you @zobo for reporting it. I admit I could not find time to do this even though the defect has been there for the last ~5 years.

The fundamental problem even not the fact that you cannot see the publisher easily but you cannot manage publishers at all. You can only add them (your screenshot). That's it.

**Comment by yueyinqiu** [comment]
Hello! Do we have any plans on this issue now? Accessing a publisher via a URL is possible, but what if I forget the publisher-id?

This issue has led me to create a new publisher with a different name (I forgot that the original publisher is also mine).
