### ISSUE TITLE
cannot access extensions mkts

### ISSUE THREAD

**Issue by xieyuanh** [microsoft/vsmarketplace#806]
Type: <b>Performance Issue</b>

It shows that error while fetching extensions, XHR timeout;undefinedms

VS Code version: Code 1.84.0 (d037ac076cee195194f93ce6fe2bdfe2969cc82d, 2023-11-01T11:29:04.398Z)
OS version: Windows_NT x64 10.0.17763
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @xieyuanh 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.

Thanks,
VS Marketplace Team
