### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by NxP-Reapper** [microsoft/vsmarketplace#808]
Type: <b>Bug</b>

eror while installing extension

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues. 

-VS Marketplace Team
