### ISSUE TITLE
C# Dev Kit not displaying Test Explorer on Ubuntu

### ISSUE THREAD

**Issue by wgrs** [microsoft/vsmarketplace#809]
Type: <b>Bug</b>

Brand new vscode installed 1.84
Create xunit test project
Create a test
Right click explorer 
Build Test Project
Expect Test Explorer to show tests
Nothing happens - no test explorer - no errors 

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:50:47.800Z)
OS version: Linux x64 6.5.0-10-generic snap
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for opening the issue. Sorry to hear you are experiencing the installation issue. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues. 

-VS Marketplace Team

**Comment by wgrs** [comment]
Vscode team says to contact dev kit team. Dev kit team says to contact the vscode tests team.
