### ISSUE TITLE
Details scrollbar

### ISSUE THREAD

**Issue by dwidge** [microsoft/vsmarketplace#815]
![move scrollbar](https://github.com/microsoft/vsmarketplace/assets/91388635/76c98dae-0f9a-4eb0-b8e7-e6aef163ead7)
Type: <b>Bug</b>

Cant view details easily, window mostly taken up by title which isn't scrollable. Can entire page be scrollable?

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @dwidge 
Thanks for reaching VS Marketplace Team, two scroll bars are available to view overview of the extension and categories, please check once and let us know if you still need any help here.

<img width="559" alt="image" src="https://github.com/microsoft/vsmarketplace/assets/81361084/bb9b0148-e171-42c5-ab11-7c6011a11244">

**Comment by dwidge** [comment]
Hello, I see there are 2 scroll bars. Thank you.
