### ISSUE TITLE
Unable to login using Personal Access Token

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/vsmarketplace#82]
I created a publisher named [zbr](https://marketplace.visualstudio.com/manage/publishers/zbr) and manually uploaded my extension to it but it seams impossible to setup the CLI vsce for publishing as one. Based on what I read on https://github.com/microsoft/vscode-vsce/issues/507 i believe I am not the only one confused by the weird authentication setup.

My account `sorin.sbarnea@gmail.com` is listed as owner of `zbr` publisher and I tried generating a PAT from `https://dev.azure.com/sorinsbarnea/_usersSettings/tokens` but it does not work when I try to use it to login using vsce, I always get Failed request: (401).

The page from https://marketplace.visualstudio.com/_apis/connectiondata does report something like:
```json
{
"authenticatedUser": {
"id": "51559800-adb9-4df8-b696-062e0700bccc",
"descriptor": "Microsoft.IdentityModel.Claims.ClaimsIdentity;0003BFFD86989D58@Live.com",
"subjectDescriptor": "msa.MmYwYTg5NWEtYjVkMi03MzVmLTg3ZjMtODEzNjI2ZTEyMjNj",
"providerDisplayName": "Sorin Sbarnea",
"isActive": true,
"properties": {
"Account": {
"$type": "System.String",
"$value": "sorin.sbarnea@gmail.com"
}
},
"resourceVersion": 2,
"metaTypeId": 255
},
"authorizedUser": {
"id": "51559800-adb9-4df8-b696-062e0700bccc",
"descriptor": "Microsoft.IdentityModel.Claims.ClaimsIdentity;0003BFFD86989D58@Live.com",
"subjectDescriptor": "msa.[CENSORED]",
"providerDisplayName": "Sorin Sbarnea",
"isActive": true,
"properties": {
"Account": {
"$type": "System.String",
"$value": "sorin.sbarnea@gmail.com"
}
},
"resourceVersion": 2,
"metaTypeId": 255
},
"instanceId": "2663b13f-50e3-a655-a159-22f6f4725fab",
"deploymentId": "2663b13f-50e3-a655-a159-22f6f4725fab",
"deploymentType": "hosted",
"locationServiceData": {
"serviceOwner": "00000029-0000-8888-8000-000000000000",
"defaultAccessMappingMoniker": "PublicAccessMapping",
"lastChangeId": 71900,
"lastChangeId64": 71900
}
}
```

## Update

After generating full access to all organizations on my PAT, the error message changed from 401 into:
```
 ERROR  Access Denied: Microsoft.IdentityModel.Claims.ClaimsIdentity;3c44d198-864f-4224-bf6d-da60d60fe01d\sorin.sbarnea@gmail.com needs the following permission(s) on the resource /zbr to perform this action: View user permissions on a resource
Time: 0h:00m:03s
```

I am not sure what this means, but somehow I feel that the dev.azure.com user is different than the one used by the marketplace. At the same time the system fails to give any hints regarding the the kind of magic required to authenticate on dev.azure.com using exactly the same user. 

If I try to access the directory switch option, I can see:
```
Switch to another directory

You are currently connected to the pycontribs Azure Active directory. Select a directory.
Current directory
pycontribs
pycontribs.onmicrosoft.com
3c44d198-864f-4224-bf6d-da60d60fe01d
Directories
Microsoft
19d5f71f-6c9a-4e7f-b629-2b0c38f2b167
Default Directory
9e952b40-c064-4d13-be06-e9490f7ff438
Microsoft Account
sorin.sbarnea@gmail.com
```

Still, this does not tell me which kind of directory I am support to use

**Comment by boyswan** [comment]
One of the worst and most frustrating journeys, I've been sitting on this issue for years. Still can't get into my VSCE and update my package...

**Comment by sjimenez77** [comment]
I can only publish from one computer. When I try to `vsce login` from another I always get a 401 error. Even if I try to login in the working one, when I am prompted if I want to overwrite the local PAT and I provide the token I get the same 401 error. I cannot understand what happens.
