### ISSUE TITLE
Im having trouble downloading the python extension on my computer

### ISSUE THREAD

**Issue by Davos15** [microsoft/vsmarketplace#820]
Type: <b>Bug</b>

EPERM: operation not permitted, mkdir 'c:\Users\minko\.vscode\extensions\.27f97fb4-dad5-4088-98fe-00d98e4ab901'

This is the error i get after trying to manually download the .vsix file

And this here after clicking the "Install" button: 
Error while installing 'Python' extension. Please check the [log](command:workbench.action.showWindowLog) for more details.

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for reaching VS Marketplace Support Team, this issue is specific to VS Code editor and tools, if we understanding correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

 -VS Marketplace Team
