### ISSUE TITLE
Can't read properties of undefined (reading 'search')

### ISSUE THREAD

**Issue by rk185416** [microsoft/vsmarketplace#822]
Type: <b>Bug</b>

Click on filter, select any of the filters. I get a popup on the bottom of my screen that says "Cannot read properties of undefined (reading 'serach')"

VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @rk185416 ,

Thank you for reaching VS Marketplace Support Team, this issue is specific to VS Code editor and tools, if we understand correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

 -VS Marketplace Team
