### ISSUE TITLE
I can't remove verified domain

### ISSUE THREAD

**Issue by madskristensen** [microsoft/vsmarketplace#823]
**Describe the bug**
Clicking the "Remove" button on my publisher profile, and then saving the changes doesn't do anything. I want to change my verified domain but can't.

**Comment by madhurivadaligithub** [comment]
Hi @madskristensen 
Thanks for reporting the issue, it is a known issue, we are working on a fix but it's going to be a while, and we'll update them when available.

Thanks,
VS Marketplace Support Team
