### ISSUE TITLE
Error while fetching extensions XHR failed

### ISSUE THREAD

**Issue by MHarena** [microsoft/vsmarketplace#824]
Type: <b>Performance Issue</b>

I can't download extensions.

VS Code version: Code 1.85.0 (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T22:27:05.695Z)
OS version: Linux x64 6.1.55-06876-gecce3ad0352d
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @MHarena 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.

Thanks,
VS Marketplace Team
