### ISSUE TITLE
Domain name still not validated since one month

### ISSUE THREAD

**Issue by sovetski** [microsoft/vsmarketplace#825]
Hi,

I added an extension on VS Code marketplace, I added also a domain name and validated it by DNS TXT.

Under the validation text, there is a not which says "it can sake up to 5 days", ok no problem, but I am waiting since 1 month and it still not validated, I don't have the validated icon on the marketplace.

Anyone else has the same problem?

Thanks
```[tasklist]
### Tasks
```

**Comment by joaomoreno** [comment]
cc @isidorn

**Comment by isidorn** [comment]
@sovetski is this still not done?

@seaniyer can you please help here?

**Comment by sovetski** [comment]
> @sovetski is this still not done?
> 
> 
> 
> @seaniyer can you please help here?

Hi, yes I still waiting, not verified yet. Thanks in advance!

**Comment by madhurivadaligithub** [comment]
Hi @sovetski  Thanks for reaching VS Marketplace Team, could you please reach out to VSMarketplace@microsoft.com with the publisher ID to verify from our end?

-Regards,
VS Marketplace Team

**Comment by sovetski** [comment]
> Hi @sovetski Thanks for reaching VS Marketplace Team, could you please reach out to [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) with the publisher ID to verify from our end?
> 
> -Regards, VS Marketplace Team

Hi, thank you, I sent an email the 23 December, I'm still waiting for a validation response.
I imagine they have other priorities before processing my request, I will keep you informed here when it is ok

**Comment by madhurivadaligithub** [comment]
Hi @sovetski 

Apologies for the delay, but we have not received any mail to process this request. Could you please share your publisher ID or resend your request to the VSMarketplace team VSMarketplace@microsoft.com.

Regards,
VS Marketplace Team

**Comment by sovetski** [comment]
> Hi @sovetski
> 
> Apologies for the delay, but we have not received any mail to process this request. Could you please share your publisher ID or resend your request to the VSMarketplace team [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com).
> 
> Regards, VS Marketplace Team

Hi, thank you for your time, I just resend the email, but if it is more quicker from there, the publisher ID is: NDNCI

Thanks!

**Comment by madhurivadaligithub** [comment]
Hi @sovetski  

Thanks for sharing the publisher ID, we have processed the request. Please feel free to reach out to us for any further queries.

Regards,
VS Marketplace Team

**Comment by sovetski** [comment]
Hi @madhurivadaligithub, I just checked my publisher page and I don't see any more the verified badge. What is the reason please? Because if it happens every time it will be difficult to open a new ticket and follow my publisher page to check if I lost the badge or not...

**Comment by madhurivadaligithub** [comment]
Hi @sovetski 

Unfortunately, your publisher has lost verified status as we are unable to validate your TXT record for [NDNCI](https://www.ndnci.com/), If you accidentally removed the TXT record, you can [[re-do the verification process](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2Fapi%2Fworking-with-extensions%2Fpublishing-extension%23verify-a-publisher&data=05%7C01%7Cv-mavadali%40microsoft.com%7Cde26accfd9ec4eb49b0008da3316f189%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637878471046971984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4rzt6M7bOkccvJBoQmdOnna0YGWamRFHgJAk4U9L%2BIM%3D&reserved=0)]

If you believe this is a mistake, you can reach out to us directly at VSMarketplace@microsoft.com.

**Comment by sovetski** [comment]
> Hi @sovetski
> 
> Unfortunately, your publisher has lost verified status as we are unable to validate your TXT record for [NDNCI](https://www.ndnci.com/), If you accidentally removed the TXT record, you can [[re-do the verification process](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcode.visualstudio.com%2Fapi%2Fworking-with-extensions%2Fpublishing-extension%23verify-a-publisher&data=05%7C01%7Cv-mavadali%40microsoft.com%7Cde26accfd9ec4eb49b0008da3316f189%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637878471046971984%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4rzt6M7bOkccvJBoQmdOnna0YGWamRFHgJAk4U9L%2BIM%3D&reserved=0)]
> 
> If you believe this is a mistake, you can reach out to us directly at [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com).

Thank you for the details, I removed the TXT record just after validated it, to keep my DNS configuration clean. Now I added it back, but it means I need to keep this TXT record forever even after being validated?

**Comment by madhurivadaligithub** [comment]
Hi @sovetski 

The domain was reverified for your publisher, if you do any changes to the publisher display name will revoke the verified badge.

Please refer this document for more information: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher
