### ISSUE TITLE
Your extension has suspicious content. Please fix your extension metadata, or contact support if you need assistance.

### ISSUE THREAD

**Issue by Matteonegridev** [microsoft/vsmarketplace#826]
Type: <b>Bug</b>

I was Publishing my theme but i get this error and I don't know what's wrong.
Can you help me?

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Matteonegridev 

Thanks for reaching VS Marketplace Team, could you please contact [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) with publisher and extension details.

-VS Marketplace Team

-Regards,
VS Marketplace Team
