### ISSUE TITLE
非推奨の拡張機能をインストールしたい

### ISSUE THREAD

**Issue by sirokuma1210** [microsoft/vsmarketplace#827]
Type: <b>Feature Request</b>

一度Rubyの拡張機能パックをダウンロードして、それに問題があったためRubyをアンインストールして個別に拡張機能を再度インストールしようとしたが、Rubyが非推奨の拡張機能と表示されてインストールできない。

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for reaching VS Marketplace Support Team, this issue is specific to VS Code editor and tools, if we understand correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

 -VS Marketplace Team
