### ISSUE TITLE
Platformio

### ISSUE THREAD

**Issue by LukasH463** [microsoft/vsmarketplace#828]
Type: <b>Bug</b>

When I open a file that has a platform.io file it is not recognized and I do not get the tools that should pop up on the status bar.

![platformio](https://github.com/microsoft/vsmarketplace/assets/152338170/d137912f-80d3-4e33-9fc4-d759bf294e34)

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for reaching VS Marketplace Support Team, this issue is specific to VS Code editor and tools, if we understand correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

 -VS Marketplace Team
