### ISSUE TITLE
Popular SASS Extension No Longer Supported

### ISSUE THREAD

**Issue by ChadNaps** [microsoft/vsmarketplace#83]
Issue Type: <b>Feature Request</b>

This extension has been [abandoned by its creator](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/486). Another user has [created an alternative](https://github.com/glenn2223/vscode-live-sass-compiler), but this original extension has too many downloads and is hurting the visibility of the updated extension. Please consider removing this extension from the marketplace.

VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T16:45:26.313Z)
OS version: Linux x64 5.11.0-17-generic

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vsmarketplace/issues/23
