### ISSUE TITLE
python extension

### ISSUE THREAD

**Issue by VENKATESWAR010604** [microsoft/vsmarketplace#830]
Type: <b>Performance Issue</b>

error while installing python extension please check the log more details

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @VENKATESWAR010604 
Thanks for reaching VS Marketplace Team, could you please share more information to investigate better, such as screenshots and error logs?

-VS Marketplace Team
