### ISSUE TITLE
what

### ISSUE THREAD

**Issue by fai8146767** [microsoft/vsmarketplace#831]
Type: <b>Performance Issue</b>

i dont know

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for reaching VS Marketplace Support Team, this issue is specific to VS Code editor and tools, if we understand correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

 -VS Marketplace Team
