### ISSUE TITLE
Annoying repeated show of recommended prompt to install

### ISSUE THREAD

**Issue by avinashmanohar** [microsoft/vsmarketplace#833]
Type: <b>Bug</b>

When we open visual studio code with our desired language, it always prompts us at startup to insall recommended extension which I don't want to install. It can be displayed first time, we should have a checkbox to not to recommend the extension next time.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:59.576Z)
OS version: Linux arm64 6.1.0-rpi7-rpi-2712
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @avinashmanohar 
Thank you for reaching VS Marketplace Support Team, this issue is specific to VS Code editor and tools, if we understand correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

 -VS Marketplace Team
