### ISSUE TITLE
i cant download extensions

### ISSUE THREAD

**Issue by mishuuusm** [microsoft/vsmarketplace#834]
Type: <b>Bug</b>

 Every time I try to download extensions this error appears  

Error while installing 'C/C++' extension. Please check the log for
more details. 

and if i try to downloaded manually this error appears

eperm: operation not permitted mkdir

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @mishuuusm 
Thanks for reaching out to the VS Marketplace Team. Are you facing this issue with other extensions as well? Here, we are unable to reproduce the problem. Could you please share more details, including any error messages or screenshots, for a better investigation?

If you think this is related to vscode, it is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

-VS Marketplace Team
