### ISSUE TITLE
C/C++ extension makes my memory full

### ISSUE THREAD

**Issue by Max490545149** [microsoft/vsmarketplace#835]
Type: <b>Performance Issue</b>

Every time when i open vs code.
the latest extension.
vs code 1.85.1

to see this problem:
1.install the extension.
2.open a workspace with a folder full of c++ files.
3.open one of the C++ file.
4.the problem is here.

Note:this problem often makes me angry because it often makes my computer stop working!
Computer:
8GB memory (your extension uses 3000MB+)
12 Core CPU
intel i5 2.60 GHz.

VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Max490545149 

Thank you for contacting the VS Marketplace Support Team. It seems that this issue is specific to the VS Code editor and its tools, if we understand correctly. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

 -VS Marketplace Team

**Comment by Max490545149** [comment]
Thanks a lot!
