### ISSUE TITLE
Please add clear links to release and pre-release extension in marketplace

### ISSUE THREAD

**Issue by rl-utility-man** [microsoft/vsmarketplace#838]
The "download extension" links in the marketplace for at least the  Python and Pylance extensions often point at pre-release versions.  When this happens, there's no obvious link to download the most recent release version.  Please add such a link and clearly label them when the latest version is a prerelease version.  

To compound this problem, VS Code does not offer an update button when an outdated prerelease extension is installed but the next full release is not out.  For example, installing prerelease Pylance v2023.11.13 via a script on VS Code 1.83.1.  It is not the latest pre release version but is newer than the most recent release version.  There is no update button letting me know that a newer release versiion is available and no "switch to release" version button either .

This is an issue for enterprises that block automatic updates and instead periodically write scripts to upgrade extensions.

**Comment by madhurivadaligithub** [comment]
Hi @rl-utility-man 
Thank you for contacting the VS Marketplace Team. Could you please try downloading extension versions from the 'Version History' tab?

If this does not meet your requirements, please let us know.

<img width="565" alt="image" src="https://github.com/microsoft/vsmarketplace/assets/81361084/8d70987d-2cee-4e38-b802-633979f43d5b">

**Comment by rl-utility-man** [comment]
Thanks @madhurivadaligithub!  No, the version history tab on Marketplace does not make what many users want to do clear or easy.

Pylance is a good example.  If I install the default version using the VS Code UI, I will get the latest "release version" -- which is also clearly marked on GitHub.  But the version history tab does not even convey the existence of a release version that's not the latest one.  The user has to do research some place outside of the marketplace to be able to use the marketplace correctly and the default download link on the marketplace is to a prerelease version while the default download link inside VS Code is to a release version.  That inconsistency is troubling.

I would like:
1)  the default download behavior to be the same on the main Marketplace download link as VS Code.  You can either point that link to a release version or add pre-release and release download links and
2)  pre-release and release versions to be clearly tagged as such in the version history tab.
(in general, I was astonished that Marketplace behaves differently from GitHub and VS Code)

Many thanks for a very useful resource.  I appreciate the huge amount of effort from a big team and vibrant community that went into it.

![pylance version history on marketplace](https://github.com/microsoft/vsmarketplace/assets/22990670/039bae0a-6eda-4957-adbc-c8b95c538e95)
![pylance release version installed by vs code](https://github.com/microsoft/vsmarketplace/assets/22990670/38e3f2fc-1f0f-47ba-be27-a2625b08147f)
![pylance version history on github](https://github.com/microsoft/vsmarketplace/assets/22990670/57d994d8-9df0-4963-bc5a-d09a038eff10)

**Comment by madhurivadaligithub** [comment]
Thanks @rl-utility-man for sharing the detailed information, we will investigate and get back to you with a response as quickly as possible.

Regards,
VS Marketplace Team
