### ISSUE TITLE
Clarity on VS Code Marketplace Plugin "Reports" data points

### ISSUE THREAD

**Issue by mike51r** [microsoft/vsmarketplace#839]
Howdy,

I need to get some clarity on the data points shown on the reports section of our VS Code plugin admin panel.

I see these data points on the browser rendered report:
Page Views
Install from VS Code
Download from Marketplace
![297185904-d4a2ccd0-9458-40c8-aec5-ff52e6f936bf](https://github.com/microsoft/vsmarketplace/assets/91695037/f199ce5f-9004-4d57-821a-f0000eed0b50)

However when I export I don't get the breakdown of Installed from VS Code vs. Marketplace.
![297185964-1310c125-feb3-4698-a677-acdb48488c43](https://github.com/microsoft/vsmarketplace/assets/91695037/2316e644-6164-454a-9042-55fe13e75b71)

I was wondering if we could get the full dataset as part of that download.

Additionally,
When we see "Install from VS Code", does this mean first time extension install only? 
Or when a user updates versions, does that add another 'tick' to the data?

Thanks,
Michael

**Comment by madhurivadaligithub** [comment]
Hi @mike51r Thank you for reporting your concern. We are following up to determine how best to address it. 

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @mike51r 
In general install is just install action (not including updates) from VS Code and Download count is from the VS Marketplace web site.

Regards,
VS Marketplace Team
