### ISSUE TITLE
create new php extenssion

### ISSUE THREAD

**Issue by AlexandroGonSan** [microsoft/vsmarketplace#84]
Issue Type: <b>Feature Request</b>

create new php extenssion to put on button to play/run file

VS Code version: Code - Insiders 1.57.0-insider (29c61570a5b9a669f777bb28b5acd5c37d99edbe, 2021-05-20T05:14:43.087Z)
OS version: Windows_NT x64 10.0.18362

**Comment by isidorn** [comment]
File against php debug
