### ISSUE TITLE
slow running

### ISSUE THREAD

**Issue by herekhan110** [microsoft/vsmarketplace#840]
Type: <b>Performance Issue</b>

as from today my VS code is executing code slowly it is taking my time about 20-30 seconds please fix this my issue

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Since we haven't heard back from you in a while, we assume the issue is resolved. Feel free to create a new ticket if you have any other issues.
