### ISSUE TITLE
python

### ISSUE THREAD

**Issue by syed1108** [microsoft/vsmarketplace#842]
Type: <b>Bug</b>

i was connected to internet and visual studio doesn t not have internet access 

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by Mahe716** [comment]
Uninstall and reinstall The software
And then try with ethernet...
