### ISSUE TITLE
Problem with Dart extension

### ISSUE THREAD

**Issue by AlexitoSnow** [microsoft/vsmarketplace#843]
Type: <b>Performance Issue</b>

Sometimes Dart Analysis Server continues to load for a long time and doesn't update the text editor, i.e.:
- Doesn't recognize mistakes
- Doesn't recognize packets
- when I hover over a word, like a class for example, it only comes up "Loading"
I've tried rebooting the Dart Analysis Server and sometimes it works but other times it just stays the same.

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by AlexitoSnow** [comment]
In this example, the App class is imported from the app_model package, but it is marked as undefined and the package is not being used.
![Captura de pantalla 2024-01-23 234423](https://github.com/microsoft/vsmarketplace/assets/116590887/f118bd43-a690-490a-9f6a-f4cd662e0a45)

Here it is evident that the Dart Analysis Server stays loading for a long time
![Captura de pantalla 2024-01-23 234443](https://github.com/microsoft/vsmarketplace/assets/116590887/dce630e2-bbef-40c6-aed5-8134c757690f)

**Comment by AlexitoSnow** [comment]
If this isn't the place where I should report this or it doesn't comply with any reporting format, I'm sorry, it's the first time I've posted something like this.

**Comment by madhurivadaligithub** [comment]
Hi @AlexitoSnow 

Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
