### ISSUE TITLE
Ability to see contribution types of extensions

### ISSUE THREAD

**Issue by snydergd** [microsoft/vsmarketplace#844]
## Scenario
I want to see if there's an Azure DevOps extension which would help to understand details of how Azure Pipelines templates are filled - e.g., what parameter values ended up being - tracing parameter source, and so forth.

I search the marketplace, but many of the results related to pipelines merely add tasks and clearly those are not going to help me.  Today it takes clicking into each extension and reading through to try and figure out what it provides - even in that case it's sometimes not clear.

## Research
I've searched through the issues on the github repo for "contribution" and "extensibility point", and not found any issues, even closed ones.

## Suggested Solution/Feature
I'd like to be able to either visually see, or else maybe apply a filter, so that I could quickly tell if an extension adds to the UI or if it only adds tasks.

I think it could be useful if the contributions of an extension were shown in the marketplace in some way - whether or not they are shown in the search results page - similar to how Artifact Hub allows you to view the templates of a Helm Chart, which I find immensely useful for picking a chart.

An even simpler option would be just being able to view the raw `vss-extensions.json` of an extension on the marketplace without downloading the vsix package first (which I have done - but not practical or efficient for narrowing search results).

**Comment by mishraris** [comment]
Hi,

to get all extension which add task to pipeline. you can go on pipeline and add a task where you find marketplace option which shows all extension which adds task on pipelines. The other way to get all same extension by using attached api and posting payload with it. Let us know if you need list as text file for all these extensions.

[PipelIneTaskExtension.txt](https://github.com/microsoft/vsmarketplace/files/14121523/PipelIneTaskExtension.txt)

Thanks

**Comment by madhurivadaligithub** [comment]
We are closing this since we haven't heard any response. If the issue still need assistance, please reactivate or create a new issue.

Regards,
VS Marketplace Team

**Comment by mishraris** [comment]
[heart]         Rishabh Mishra (MINDTREE LIMITED) reacted to your message:
________________________________

**Comment by mishraris** [comment]
[like]  Rishabh Mishra (MINDTREE LIMITED) reacted to your message:
________________________________

**Comment by snydergd** [comment]
@mishraris Thanks for the information!  What I'm looking for is actually the extensions which do not add tasks, so looking at tasks available on marketplace would not help me very much directly.  That API (and maybe others on that page you mentioned) seem promising, but I think maybe I need to customize the request a bit.  Is there documentation about this API and how to use it?  [This post ](https://www.reddit.com/r/vscode/comments/am1k1t/is_there_an_api_for_getting_list_of_all/) makes me not too hopeful, but wanted to know if you have any more info on this.

**Comment by mishraris** [comment]
@snydergd  To call API use method as post and add the payload data to body (JSON format) to send to API. You can use any scripting language or any REST UI application (like postman) to call API.
