### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by NickUsey** [microsoft/vsmarketplace#846]
Type: <b>Performance Issue</b>

When I attempt to add an extension, it will not install and then will ask me to install manually each time. 

VS Code version: Code 1.85.2 (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:10.514Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by NickUsey** [comment]
![Install Error](https://github.com/microsoft/vsmarketplace/assets/94800866/d4eb185e-af2d-46b3-8be1-c0650a6f8aca)

**Comment by madhurivadaligithub** [comment]
Hi @NickUsey ,

Are you still facing these issues ?

Regards,
VS Marketplace Team

**Comment by NickUsey** [comment]
No it’s all good now
