### ISSUE TITLE
net::ERR_PROXY_CONNECTION_FAILED

### ISSUE THREAD

**Issue by Sanhsok** [microsoft/vsmarketplace#847]
Type: <b>Bug</b>

net::ERR_PROXY_CONNECTION_FAILED

VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Sanhsok 

Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
