### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Qwerty1435287** [microsoft/vsmarketplace#849]
Type: <b>Performance Issue</b>

There's this issue that I can't solve even if I try few things from online it won't resolve the problem. This issue is that I can't install an extension since there's this "error while fetching extensions. XHR failed". Please resolve this. Thank you

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Qwerty1435287 ,

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
We are closing this since we haven't heard any response. If the issue still persists, please reactivate or create a new issue.

Regards,
VS Marketplace Team
