### ISSUE TITLE
unable to install extention

### ISSUE THREAD

**Issue by Gopika167** [microsoft/vsmarketplace#850]
Type: <b>Feature Request</b>

unable to install extentions from extention marketplace

VS Code version: Code 1.86.0 (05047486b6df5eb8d44b2ecd70ea3bdf775fd937, 2024-01-31T10:28:19.990Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Gopika167 ,

Thank you for reaching out to the VS Marketplace Team. Could you please provide more details about your concern, including reproducible steps and screenshots, to assist us in better investigating the issue.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
We are closing this since we haven't heard any response. If the issue still persists, please reactivate or create a new issue.

Regards,
VS Marketplace Team
