### ISSUE TITLE
Github copilot doesnt work

### ISSUE THREAD

**Issue by Arifhdyt11** [microsoft/vsmarketplace#855]
Type: <b>Bug</b>

bad request: missing Authorization header

VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:20.941Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Arifhdyt11 

Thanks for reaching VS Marketplace Team, Issue looks specific to the extension, could you please reach out to the extension publisher through QnA https://marketplace.visualstudio.com/itemsitemName=GitHub.copilot&ssr=false#qna

Thanks,
VS Marketplace Team
