### ISSUE TITLE
Can't load any extensions

### ISSUE THREAD

**Issue by NBishop69** [microsoft/vsmarketplace#857]
Type: <b>Performance Issue</b>

I had 10K things to commit on my toolbar, but no active projects so I clicked on discard all changes.  I must have messed up because i still have 10K issues but now have lost my github copilot and can't re install it.  Please help.
i have tried uninstalling vscode and reinstalling it but i still have all the changes and can't load any extensions period

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @NBishop69 

Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
