### ISSUE TITLE
Salesforce Extension Pack not installing

### ISSUE THREAD

**Issue by GeorgeP01** [microsoft/vsmarketplace#858]
Type: <b>Bug</b>

Since the 15th Feb 2024 the Salesforce extensions in my local vscode instance are just stuck on installing when i started VsCode.
I have tried uninstalling all of them (the SF ones), via 
code --list-extensions 
code --uninstall-extension ID
which worked to uninstall but then when I go to reinstall the Salesforce Extension Pack it just stays on 'Installing'.  
Non-SF extensions are fine. I am running SF CLI.

I am creating this via the help-> Issue Reporter from Vscode so don't know what info it collects but I am running Win10 with the following
Version: 1.86.2 (user setup)
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:40:56.878Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19044

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by GeorgeP01** [comment]
Here is a screenshot of what it stays on
![image](https://github.com/microsoft/vsmarketplace/assets/46985138/dde225c0-094a-4ba2-8628-138d7622104b)

**Comment by GeorgeP01** [comment]
![image](https://github.com/microsoft/vsmarketplace/assets/46985138/f913251e-8f64-4e16-bcf0-0cb5acf1a3f4)

**Comment by madhurivadaligithub** [comment]
Hi @GeorgeP01 

Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
