### ISSUE TITLE
Need to move an extension to a new Publisher

### ISSUE THREAD

**Issue by cesaref** [microsoft/vsmarketplace#861]
We have had a reorganisation, and want to move an extension which is currently published by one publisher to a new one which has been created. This is to reflect the real world, where the IP associated with this extension has moved to a new company.

The extension is soundstacks.cmajor, and we would want this moved to cmajorsoftware.cmajor

This does not appear to be possible through the web interface to the marketplace. Is this something that can be performed on our behalf?

**Comment by madhurivadaligithub** [comment]
Hi @cesaref 

Thanks for reaching VS Marketplace Team, currently we are not supporting extension transfers between publishers.

Please reach out to us VSMarketplace@microsoft.com for any other concerns.

Regards,
VS Marketplace Team
