### ISSUE TITLE
Intellisense can't find the type of my variables

### ISSUE THREAD

**Issue by Darkskimow** [microsoft/vsmarketplace#862]
Type: <b>Bug</b>

Hi, 

In my project (write in C++, using Unreal Engine 5.3 source code version), intellisense can't find the type of my variables insted i have this message : 
"[[__UNREAL_ENGINE_UPROPERTY__]]TMap<FString,double> Fcst_MapStringFloat::Map
TMapBase & TMapBase<KeyType, ValueType, SetAllocator, KeyFuncs>::TIterator::Map
const FScriptMapHelper & FScriptMapHelper::FIterator::Map
FString FURL::Map
UPackageMap * FNetDeltaSerializeInfo::Map
TMap<FObjectKey,FReplicationCacheData> FPhysScene_Chaos::FPrimitiveComponentReplicationCache::Map
TMap<KeyType,ValueType,SetAllocator> TMapBuilder<KeyType, ValueType, SetAllocator>::Map
llvm::DenseMap<FileID,FileNullability> clang::FileNullabilityMap::Map
MapT llvm::ValueMap<KeyT, ValueT, Config>::Map
ValueMapT * llvm::ValueMapCallbackVH<KeyT, ValueT, Config>::Map
const HeaderMap * clang::DirectoryLookup::__unnamed_union_1d27a_1::Map
MapType llvm::MapVector<KeyT, ValueT, MapType, VectorType>::Map
HRESULT(__stdcall * ID3D11DeviceContext1Vtbl::Map)(ID3D11DeviceContext1 *This,ID3D11Resource *pResource,UINT Subresource,D3D11_MAP MapType,UINT MapFlags,D3D11_MAPPED_SUBRESOURCE *pMappedResource)
HRESULT(__stdcall * IDXGISurface2Vtbl::Map)(IDXGISurface2 *This,DXGI_MAPPED_RECT *pLockedRect,UINT MapFlags)
HRESULT(__stdcall * ID3D11DeviceContextVtbl::Map)(ID3D11DeviceContext *This,ID3D11Resource *pResource,UINT Subresource,D3D11_MAP MapType,UINT MapFlags,D3D11_MAPPED_SUBRESOURCE *pMappedResource)
HRESULT(__stdcall * IDXGISurfaceVtbl::Map)(IDXGISurface *This,DXGI_MAPPED_RECT *pLockedRect,UINT MapFlags)
HRESULT(__stdcall * IDXGISurface1Vtbl::Map)(IDXGISurface1 *This,DXGI_MAPPED_RECT *pLockedRect,UINT MapFlags)
HRESULT(__stdcall * ID3D10BufferVtbl::Map)(ID3D10Buffer *This,D3D10_MAP MapType,UINT MapFlags, void **ppData)
HRESULT(__stdcall * ID3D10Texture1DVtbl::Map)(ID3D10Texture1D *This,UINT Subresource,D3D10_MAP MapType,UINT MapFlags, void **ppData)
HRESULT(__stdcall * ID3D10Texture2DVtbl::Map)(ID3D10Texture2D *This,UINT Subresource,D3D10_MAP MapType,UINT MapFlags,D3D10_MAPPED_TEXTURE2D *pMappedTex2D)
HRESULT(__stdcall * ID3D10Texture3DVtbl::Map)(ID3D10Texture3D *This,UINT Subresource,D3D10_MAP MapType,UINT MapFlags,D3D10_MAPPED_TEXTURE3D *pMappedTex3D)
TMap<FString,FCookedFileStatData> FCookedFileStatMap::Map
void * CrossCompiler::FKeywordToken::Map
TMap<FNavigationSimulationWidgetInfo::TPointerAsInt,FPaintGeometry> NavigationSimulationOverlay::FWidgetGeometryMap::Map
TMap<FNameEntryId,TUniquePtr<FNameRangeEntry>> NameReuse::FNameRangeCache::Map
T & TBucketMapLock<T>::Map
HRESULT(__stdcall * ID3D12ResourceVtbl::Map)(ID3D12Resource *This,UINT Subresource, const D3D12_RANGE *pReadRange, void **ppData)
HRESULT(__stdcall * ID3D12Resource1Vtbl::Map)(ID3D12Resource1 *This,UINT Subresource, const D3D12_RANGE *pReadRange, void **ppData)
HRESULT(__stdcall * ID3D12Resource2Vtbl::Map)(ID3D12Resource2 *This,UINT Subresource, const D3D12_RANGE *pReadRange, void **ppData)
TMap<FString,FString> FShaderFileCache::Map
TMap<const void*,TConstArrayView<FShaderParametersMetadata::FMember>> `anonymous-namespace'::FShaderParameterMemberLookup::Map
std::map<T,unsigned> llvm::UniqueVector<T>::Map
TMap<uint32,FMeshSectionInfo> FMeshSectionInfoMap::Map
FSoftObjectPath UAsyncEditorOpenMapAndFocusActor::Map
MMIAddrLabelMap * llvm::MMIAddrLabelMapCallbackPtr::Map
StringMap<std::pair<TimerGroup*,Name2TimerMap>> `anonymous-namespace'::Name2PairMap::Map
ValueToValueMapTy `anonymous-namespace'::LoopConstrainer::ClonedLoop::Map
TMap<FSoftObjectPath,TSet<FWeakObjectPtr>> FCachedSoftReference::Map
std::map<const IdentifierInfo*,struct Entry> `anonymous-namespace'::TypeStringCache::Map
ModuleMap & clang::ModuleMapParser::Map
MapType `anonymous-namespace'::InheritingConstructorInfo::Map
StringMap<int> `anonymous-namespace'::NameToIdxMap::Map
T `anonymous-namespace'::DenseMapTest<T>::Map
TMap<FGuid,FLevelSequenceLegacyObjectReference> FLevelSequenceObjectReferenceMap::Map
ValueToValueMap & llvm::SCEVParameterRewriter::Map
LoopToScevMapT & llvm::SCEVApplyRewriter::Map
const HashTable<ValueT,TraitsT>* llvm::pdb::HashTableIterator<ValueT, TraitsT>::Map
TMap<uint64,FLogMessageRecord> FLogMessageCache::Map
TMap<FString,FString> FEditorConfigTestSimpleMap::Map
TMap<FString,FEditorConfigTestKey> FEditorConfigTestSimpleKeyComplexValueMap::Map
TMap<FEditorConfigTestKey,FEditorConfigTestKey> FEditorConfigTestComplexMap::Map
MapTy llvm::ConstantUniqueMap<ConstantClass>::Map
TMap<int,int> FTestSparseClassDataStorage::Map
FSoftObjectPath FTemplateMapInfo::Map
TMap<FTopLevelAssetPath,FClassDigestData> UE::EditorDomain::FClassDigestMap::Map
Texmap * DatasmithMaxTexmapParser::FMapParameter::Map
FMapParameter DatasmithMaxTexmapParser::FCompositeTexmapParameters::FLayer::Map
Bitmap * FScopedBitMapPtr::Map
std::unordered_map<FPath::string_type,FileAttributes> unsync::FFileAttributeCache::Map
HRESULT(__stdcall * ID3D11DeviceContext2Vtbl::Map)(ID3D11DeviceContext2 *This,ID3D11Resource *pResource,UINT Subresource,D3D11_MAP MapType,UINT MapFlags,D3D11_MAPPED_SUBRESOURCE *pMappedResource)
FName FAutomationTestExcludelistEntry::Map
SizeType * LLMMap<TKey, TValue1, TValue2, SizeType>::StripeData::Map
TMap<FName,TUniquePtr<FPackage>> FPackageWriterRecords::Map
TMap<ECoreRedirectFlags,FRedirectNameMap*> FCoreRedirects::FRedirectTypeMap::Map
FMap FAnimNodeTracker::Map
HRESULT(__stdcall * ID3D11DeviceContext3Vtbl::Map)(ID3D11DeviceContext3 *This,ID3D11Resource *pResource,UINT Subresource,D3D11_MAP MapType,UINT MapFlags,D3D11_MAPPED_SUBRESOURCE *pMappedResource)
HRESULT(__stdcall * ID3D11DeviceContext4Vtbl::Map)(ID3D11DeviceContext4 *This,ID3D11Resource *pResource,UINT Subresource,D3D11_MAP MapType,UINT MapFlags,D3D11_MAPPED_SUBRESOURCE *pMappedResource)
FSoftObjectPath FTemplateMapInfoOverride::Map
TMap<FKeyType,FValueType> FManagedArrayCollection::Map
TMap<FGuid,TObjectPtr<ULandscapeInfo>> ULandscapeInfoMap::Map
TMap<FName,FAttributesSetEntry> FAttributesSetBase::Map
FString FVaRestURL::Map
TIFFRGBValue * _TIFFRGBAImage::Map
LoopToScevMapT & llvm::SCEVLoopAddRecRewriter::Map
ValueMap<const Value*,ValueEntry> llvm::DxilValueCache::WeakValueMap::Map
LiveOutMap llvm::LiveRangeCalc::Map
MapTy llvm::BlotMapVector<KeyT, ValueT>::Map
MapTy clang::ento::FunctionSummariesTy::Map"

I search and try lot of solution that i found on the internet, but nothing work. Even reset intellisense database change nothing, can you help me to fix this enoying problem please?

Thank you, Stephane

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Darkskimow 

Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
