### ISSUE TITLE
NATIVE CRASH ISSUE

### ISSUE THREAD

**Issue by Rafifern** [microsoft/vsmarketplace#863]
Type: <b>Performance Issue</b>

VS Code supports a --crash-reporter-directory <absolute-path> option that you can use to produce crash dumps into that folder. Please try this option first:

Close all instances of VSCode.
Run code --crash-reporter-directory <absolute-path> from the command line.
Run code-insiders instead of code if the issue is occurring on the Insiders version.
Take the steps that lead to the crash.
Check for a *.dmp file in that folder.
Send the *.dmp file back to us, either by email, or by creating a zip archive containing it and attaching the zip to the GitHub issue.
If you can reproduce the issue running out of sources, meaning compiled from source (code-oss), then you might be able to symbolicate the crash dump (.dmp file) as well. Otherwise, please wait for a maintainer to symbolicate your crash dump.

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Rafifern 

Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
