### ISSUE TITLE
Expired Certificate for visualstudiogallery.msdn.microsoft.com

### ISSUE THREAD

**Issue by rtresidd** [microsoft/vsmarketplace#864]
**Describe the bug**
visualstudiogallery.msdn.microsoft.com   has an expired certificate

**To Reproduce**
visit visualstudiogallery.msdn.microsoft.com

**Expected behavior**
Should have a valid certificate

**Desktop (please complete the following information):**
Any

**Comment by madhurivadaligithub** [comment]
Hi @rtresidd 
Thanks for reaching VS Marketplace Team, could you please elaborate on the issue by providing the error message or a screenshot? This will help us investigate more effectively.

Regards,
VS Marketplace Team

**Comment by rtresidd** [comment]
Looks like it got fixed over the weekend.. Or there's perhaps an instance that has a wrong cert on it.
This host [104.98.252.17]   visualstudiogallery.msdn.microsoft.com
Was previously supplying an expired certificate:
IssuerDN | C=US, O=Microsoft Corporation, CN=Microsoft Azure TLS Issuing CA 06
C=US, ST=WA, L=Redmond, O=Microsoft Corporation, CN=visualstudiogallery.msdn.microsoft.com
SN: visualstudiogallery.msdn.microsoft.com,*.visualstudiogallery.msdn.microsoft.com
TLS Certificate Validity: 13/07/2022 18:53:00 - 08/07/2023 18:53:00
Cheers
  RT
