### ISSUE TITLE
Transfer extension to another publisher

### ISSUE THREAD

**Issue by MermaidChart** [microsoft/vsmarketplace#865]
We are taking over the maintenance of a VSCode plugin:
https://marketplace.visualstudio.com/items?itemName=vstirbu.vscode-mermaid-preview

I have owner privileges on the originating org.

This is the publisher URL:
https://marketplace.visualstudio.com/manage/publishers/vstirbu?noPrompt=true

This is my UserID:
dca6f052-c47a-64b8-8de6-352bb9847bb8

Quote from #440
>  Hi @JounQin
>Usually, we do not allow transfer of VSCode extensions since it has following consequences:
>
>Users will not be able to install the older versions of your extensions that got published before the extension transfer from the VSCode.
If this extension is used as a dependency in other extensions by using publisherName.ExtensionName, that would not work.
You need to update all references to this extension with the new publisherName.
Please confirm if you are okay with the above consequences, then we can go ahead with the transfer extension request.

I do confirm there queries. This is the destination publisher:
https://marketplace.visualstudio.com/manage/publishers/mermaidchart

This query is similar to issue #440

**Comment by madhurivadaligithub** [comment]
Hi @MermaidChart 
Thanks for reaching VS Marketplace Team, currently we are not supporting transfer of the extension from one publisher to another.

Could you please reach out to us through VSMarketplace@microsoft.com support team for any other concerns.

Regards,
VS Marketplace Team

**Comment by mariaghiondea** [comment]
@MermaidChart please be aware that you shouldn't share your VSID publicly. That is a security risk. Can you please remove it?

**Comment by madhurivadaligithub** [comment]
Hi @MermaidChart 

Since we haven't received any response from you, we're closing the issue. Please feel free to reopen it or create a new one if needed.

Regards,
VS Marketplace Team
