### ISSUE TITLE
Typescript dont work with the same configuration of windows machine

### ISSUE THREAD

**Issue by emiesteban** [microsoft/vsmarketplace#867]
Type: <b>Bug</b>

Open a Typescript project on MAC, use the same libraries.

VS Code version: Code 1.87.1 (Universal) (1e790d77f81672c49be070e04474901747115651, 2024-03-06T00:23:16.418Z)
OS version: Darwin arm64 23.4.0
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @emiesteban 
Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
