### ISSUE TITLE
Live Server não funciona

### ISSUE THREAD

**Issue by devsouzamah** [microsoft/vsmarketplace#871]
Type: <b>Performance Issue</b>

Meu Live Server não abre... Já desinstalei o Live Server, desinstalei o Vs Code, instalei os dois novamente e mesmo assim o Live Server não abre.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by devsouzamah** [comment]
Meu Live Server não abre... Já desinstalei o Live Server, desinstalei o Vs Code, instalei os dois novamente e mesmo assim o Live Server não abre.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631

**Comment by madhurivadaligithub** [comment]
Hi @devsouzamah 

Thank you for contacting the VS Marketplace Support Team. It appears that the issue is related to the extension. Could you please reach out to the extension owner through QnA.

Please let us know if you need any other assistance here.

Regards,
VS Marketplace Team
