### ISSUE TITLE
pdf viewer losts connection overnight (latex workshop)

### ISSUE THREAD

**Issue by sylvain-bougnoux** [microsoft/vsmarketplace#872]
Type: <b>Bug</b>

I edit a latex document and have a side panel reading the resulting pdf file issued from the compilation. It works fine during the day, even with screen-locks. However, after a computer deep sleep (Win10), or a long time (the night), the pdf viewer does not react to any further compilation. I have to close it and reopen it to continue. It is not fundamental but still...

I use the last vs version, and the latex workshop extension.
Thanks.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @sylvain-bougnoux 

Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
