### ISSUE TITLE
It won't show up

### ISSUE THREAD

**Issue by JaffarsonJS** [microsoft/vsmarketplace#873]
Type: <b>Bug</b>

Can't uninstall and it won't show up in the extension section

VS Code version: Code 1.87.2 (Universal) (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:21:31.043Z)
OS version: Darwin arm64 23.4.0
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @JaffarsonJS 

Thanks for reaching out to the VS Marketplace Team. Could you please share more details about this issue, such as screenshots and error messages, to help us investigate better.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @JaffarsonJS 
We are closing this issue, If the issue still persists, please feel free to reactivate or create a new issue.

-VS Marketplace Team
