### ISSUE TITLE
Urgent

### ISSUE THREAD

**Issue by H3PTA-TECH** [microsoft/vsmarketplace#874]
Type: <b>Feature Request</b>

Its not showing any extension in the marketplace

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @H3PTA-TECH 

Thanks for reaching out to the VS Marketplace Team. Could you please share more details about this issue, such as screenshots and error messages, to help us investigate better.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @H3PTA-TECH 

We are closing this issue, if the issue still persists feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
