### ISSUE TITLE
Extension download issue

### ISSUE THREAD

**Issue by arijit-15** [microsoft/vsmarketplace#876]
Type: <b>Bug</b>

For the past many months, i am not able to download any sort of extensions on vs code. I had also uninstalled and installed again, tried downloading the extension manually but nothing works. Currently i am running vs code on windows 11 and vs code version 1.87.2. In the log file it shows Error: EPERM: operation not permitted, rename ..  . Pls anyone help me with this.

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @arijit-15 ,

Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
