### ISSUE TITLE
live server

### ISSUE THREAD

**Issue by Anjanadml** [microsoft/vsmarketplace#877]
Type: <b>Feature Request</b>

when i open my live server to o live my html page but its not working 

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Anjanadml ,

Thanks for reaching VS Marketplace Team, as this issue looks specific to extension, could you please reach out to the Extension owners through their github repo for further assistance.

Regards,
VS Marketplace Team
