### ISSUE TITLE
Can't research extension and update.

### ISSUE THREAD

**Issue by yhgzs-111** [microsoft/vsmarketplace#878]
Type: <b>Bug</b>

Can't research extension and update.
XHR Faild
![image](https://github.com/microsoft/vsmarketplace/assets/77568569/7b38abf2-9733-435d-a788-9944e3f884d2)
![image](https://github.com/microsoft/vsmarketplace/assets/77568569/9cc53d6a-90b4-448b-ad67-ea899f9c3e2d)

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @yhgzs-111 ,

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue as there have been no updates for a week. If the problem persists you can contact us with the requested network log.
