### ISSUE TITLE
EROR while fetching extensions .xhr

### ISSUE THREAD

**Issue by sola99a** [microsoft/vsmarketplace#881]
Type: <b>Feature Request</b>

eror while fetching extensions .xhr when i try o search exension

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @sola99a 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

-VS Marketplace Team
