### ISSUE TITLE
unable to install extension

### ISSUE THREAD

**Issue by rishisharma-web** [microsoft/vsmarketplace#882]
Type: <b>Bug</b>

I am unable to install some extensions like Language Support for Java(TM) by Red Hat and IntelliCode

VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @rishisharma-web 
Thanks for reaching VS Marketplace Support Team, could you please share error message or screenshot to investigate better.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
we have not heard any response, we are closing the issue. If the issue still persists, please recreate a new issue or reactivate the existing one.

Regards,
VS Marketplace Team
