### ISSUE TITLE
Extension Cannot be Published

### ISSUE THREAD

**Issue by Agnik7** [microsoft/vsmarketplace#884]
I am creating a VS Code code snippets extension. However, everytime I try to publish it, I am getting the error message "Your extension has suspicious content. Please fix your extension metadata, or contact support if you need assistance."

![Error](https://github.com/microsoft/vsmarketplace/assets/77234005/dfa102cc-0e7e-4ea9-9959-7a7cf4dee30a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by madhurivadaligithub** [comment]
Hi @Agnik7 ,

Thank you for contacting the VS Marketplace Team. Could you please reach out to our official support team at [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) to promptly address this issue.

Regards,
VS Marketplace Team
