### ISSUE TITLE
Salesforce Extension pack

### ISSUE THREAD

**Issue by navyamantripragada** [microsoft/vsmarketplace#886]
Type: <b>Bug</b>

Salesforce extension pack gets activated very slow and late. Even the latest version loads very slow.Almost take 15-20 mins to activate and display the commands. Please fix this as its effecting the productivity. 

VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @navyamantripragada,

Thank you for contacting the VS Marketplace Team. Could you please contact the extension publisher through the Q&A section for any queries related to extension functionality.

-VS Marketplace Team
