### ISSUE TITLE
can not get any extention 

### ISSUE THREAD

**Issue by Nabil-Nader** [microsoft/vsmarketplace#889]
Type: <b>Bug</b>

for example im trying to get some of popular extention that related to python , when i type python i get this error 'Error while fetching extenstions. canceled'  

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:42:52.765Z)
OS version: Darwin x64 22.6.0
Modes:

**Comment by Nabil-Nader** [comment]
it give me the python extension after some time but it really slow

**Comment by madhurivadaligithub** [comment]
Hi @Nabil-Nader 

Thanks for reaching out to the VS Marketplace Team. We were unable to reproduce the issue from our end. Could you please share more details to help us investigate better.

Regards,
VS Marketplace Team
