### ISSUE TITLE
StartUp file with an error

### ISSUE THREAD

**Issue by Mab72** [microsoft/vsmarketplace#890]
Type: <b>Bug</b>

STM32 VS CODEEXTENSION
Please check the automatically generated file(startup_stm32g041j6mx.s) when creating a new project. For microcontroller stm32g041j6m6. When you replace this file with a file(startup_stm32g041xx.s) from the library by ST Company, it all works. Thanks.

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Mab72 

Thanks for reaching VS Marketplace Team, as this issue looks specific to VS Code, could you please reach out to the VS Code Team https://github.com/microsoft/vscode/issues for further assistance.

Regards,
VS Marketplace Team
