### ISSUE TITLE
create vscode publisher 

### ISSUE THREAD

**Issue by 123456dengting** [microsoft/vsmarketplace#891]
create vscode publisher 
Enter only id and name 
click create   Web page not responsive
![image](https://github.com/microsoft/vsmarketplace/assets/28246564/c230c33c-a1f9-4646-9260-f114be800252)

**Comment by madhurivadaligithub** [comment]
Hi @123456dengting 

Thank you for reaching out to the VS Marketplace Team. Could you please try this scenario in private or incognito mode and let us know if you are still experiencing the issue?

VS Marketplace Team

**Comment by 123456dengting** [comment]
> Hi @123456dengting
> 
> Thank you for reaching out to the VS Marketplace Team. Could you please try this scenario in private or incognito mode and let us know if you are still experiencing the issue?
> 
> VS Marketplace Team

Same problem in stealth mode

**Comment by madhurivadaligithub** [comment]
Hi @123456dengting ,

We are unable to reproduce the issue. Could you please reach out to our official support team ([VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com)) with logs to address this issue promptly.

Regards,
VS Marketplace Team
