### ISSUE TITLE
live server extension

### ISSUE THREAD

**Issue by tomdangur15** [microsoft/vsmarketplace#892]
Type: <b>Bug</b>

i couldnot install live server it keeps failing again and again

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
we have not heard any response, we are closing the issue. If the issue still persists, please recreate a new issue or reactivate the existing one
