### ISSUE TITLE
Cannot install more than one extensions

### ISSUE THREAD

**Issue by Susith-n** [microsoft/vsmarketplace#893]
Type: <b>Bug</b>

Cannot install more than one entensions. Displays a popup "Error while installing '<Extension name>' extension. Please check the log for more details. " - button for Try Downloading Manually...

Error in log : [error] Cannot read properties of undefined (reading 'accessToken'):

Also i have tried couple of times with .vsix file. But didn't succeed. 

VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:41:02.734Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Susith-n 

Thank you for reaching out to the VS Marketplace Team. Could you please share more details, such as reproduction steps, to help us investigate the issue better.

-VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
@Susith-n  we have not heard any response, we are closing the issue. If the issue still persists, please recreate a new issue or reactivate the existing one

Regards,
VS Marketplace Team
