### ISSUE TITLE
Error while fetching extensions.XHR failed.

### ISSUE THREAD

**Issue by Keshabkjha** [microsoft/vsmarketplace#896]
Type: <b>Bug</b>

When click on Extensions (Ctrl+Shift+X) The extension is unable to load new extension 
It shows Error while fetching extensions.XHR failed.
i already updated my vs code. I already uninstalled and then installed vs code. I havetried everything. 

VS Code version: Code - Insiders 1.90.0-insider (816c6f7d7bc4da9796cd19ac6b122b6e26f50d7f, 2024-05-03T17:55:38.086Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Keshabkjha 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

-VS Marketplace Team

**Comment by Keshabkjha** [comment]
> Hi @Keshabkjha
> 
> Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).
> 
> -VS Marketplace Team

Any update

**Comment by madhurivadaligithub** [comment]
Thanks for the details @Keshabkjha , are you still encountering the problem?


Regards,
VS Marketplace Team

**Comment by Keshabkjha** [comment]
> Thanks for the details @Keshabkjha , are you still encountering the problem?
> 
> Regards, VS Marketplace Team

Yes, Please can you help to solve this problem? it's more than a month I am raising this problem.

**Comment by AkshatDew** [comment]
Type: Bug

When click on Extensions (Ctrl+Shift+X) The extension is unable to load new extension
It shows Error while fetching extensions.XHR failed.
and when i am updateing it then it shows (net::ERR_CERT_AUTHORITY_INVALID) this eror 

VS Code version: Code - Insiders https://code.visualstudio.com/updates/v1_67
OS version: Windows 7 supper lite x84(32 bit) 10.0.22631
@madhurivadaligithub plss help me , i will be  collage student in few months bca student so i have to practice html,css c, etc , and i have only this laptop plss help me resolve this problem

**Comment by madhurivadaligithub** [comment]
Hi @AkshatDew 

Thank you for the details. We are investigating the issue and will get back to you with an update promptly.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @AkshatDew 

Thanks for reaching out. If you're using a VPN client or local firewall, please adjust the firewall settings to allow these requests. If the error persists, sharing the network log (command: Developer: Open Logs Folder) would help us investigate further.

Could you please check and update with us.

Regards,
VS Marketplace Team

**Comment by Vilimzy** [comment]
Hey guy's 
I'm facing this same thing rn for over four days
