### ISSUE TITLE
Vue - Official

### ISSUE THREAD

**Issue by mfmanca2000** [microsoft/vsmarketplace#897]
Type: <b>Bug</b>

I can't install Vue - Official on VsCode 1.74.3 .
A message says vue.volar is incompatible with VSCode 1.74.3.
Any workaround ?
Without such plugin, I don't have any autocompletion at all in a Vue project

VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by madhurivadaligithub** [comment]
Hi @mfmanca2000 

Thanks for reaching VS Marketplace Team, we are currently looking into the issue and will provide you with an update as soon as possible.

Regards,
VS Marketplace Team

**Comment by mfmanca2000** [comment]
You can forget about this request. I've just uninstalled VSCode and reinstalled the latest version.
