### ISSUE TITLE
Cannot access to publisher after changing organization's directory 

### ISSUE THREAD

**Issue by PierreMarchand20** [microsoft/vsmarketplace#898]
I changed the directory of the (Azure devops) organization behind the extension [vscode-FreeFEM](https://marketplace.visualstudio.com/items?itemName=Pierre-Marchand.vscode-freefem) (from my previous employer to my Microsoft account), but I cannot access the publisher (id: Pierre-Marchand) anymore.

Is there a way to also transfer the publisher id from one directory to the other?

**Comment by madhurivadaligithub** [comment]
Hi @PierreMarchand20 

Thank you for contacting the VS Marketplace Team. Could you please reach out to our official support team at VSMarketplace@microsoft.com to promptly address this issue.

Regards,
VS Marketplace Team

**Comment by PierreMarchand20** [comment]
Yes thank you, they actually solved my issue 👍🏻
