### ISSUE TITLE
live server

### ISSUE THREAD

**Issue by yashvaland** [microsoft/vsmarketplace#904]
Type: <b>Performance Issue</b>

live server is not working

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace Team, could you please share more details about your concern to investigate better.

Regards,
VS Marketplace Team.

**Comment by madhurivadaligithub** [comment]
Since we have not received the required information, we are closing the issue. Please feel free to reopen or create a new issue if the problem still persists.

Regards,
VS Marketplace Team
