### ISSUE TITLE
blekit

### ISSUE THREAD

**Issue by Jabadaba00** [microsoft/vsmarketplace#910]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by madhurivadaligithub** [comment]
Hi @Jabadaba00 

Thanks for reaching VS Marketplace Team, the repro steps were not clear, could you please share more details like error message or screenshots to investigate further.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Since we have not received the required information, we are closing the issue. Please feel free to reopen or create a new issue if the problem still persists.

Regards,
VS Marketplace Team
