### ISSUE TITLE
Unable to find old versions in Visual Studio and on Marketplace

### ISSUE THREAD

**Issue by MichielOda** [microsoft/vsmarketplace#911]
**Describe the bug**
In VS Code it is possible to install other versions of the extensions. This functionality is not available for Visual Studio & the Marketplace.

**To Reproduce**
Using CodeMaid as an example.
1. Go to [CodeMaid VS2022](https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaidVS2022)
2. You find the download button to download the latest version
3. Nowhere something found for the older versions in the marketplace itself

In their readme/overview they put manually some links to older versions, but is not maintainable if you want a specific version and this is up to the good grace of the publishers. Not everyone does that.

Inside Visual Studio you have only the option to install, disable or uninstall an extension.

**Expected behavior**
Possibility to see the older versions and to be able to download them. VS Code has this functionality already.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Comment by madhurivadaligithub** [comment]
Hi @MichielOda 

Thanks for reaching VS Marketplace Team, we will check the details and provide updates as necessary.

-VS Marketplace Team

**Comment by MichielOda** [comment]
Any updates about this?

**Comment by seaniyer** [comment]
Hi @MichielOda 
You are right Visual Studio extensions are different in that way. Currently there is no plan to provide older version download for VS. I'd like to understand if there was a specific use case that prompted your suggestion.

**Comment by MichielOda** [comment]
Hi @seaniyer 

Our use case is for people that don't want to or can't (due to company policies) update their Visual Studio to VS22. Then they could still download the latest extension version for that VS version.

Another less important scenario would be that they don't want to have the newest changes in the extension but accidently auto-updated the extension. There is no easy way to go back a version.

Best regards

**Comment by seaniyer** [comment]
FYI @maiak

**Comment by MichielOda** [comment]
That's a bummer. I really hope that this would eventually be implemented.
