### ISSUE TITLE
Cannot connect to ubuntu or kali ,inux

### ISSUE THREAD

**Issue by Gook154** [microsoft/vsmarketplace#913]
Type: <b>Performance Issue</b>

Hello....i'm trying to connect my VS to the terminal but it cannot. I've applied the changes stated but still it cannot communicate with the terminal....please help.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching VS Marketplace Team. Sorry to hear you are experiencing connection issues. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues for quick action.

Thanks,
VS Marketplace Team
