### ISSUE TITLE
 net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by jtb3ats** [microsoft/vsmarketplace#915]
Type: <b>Bug</b>

I have tried everything on every website I could find I am not sure if it helped or made things worse but I cant open any extensions. It is also not showing me any of the photos that go along with them. I updated my laptop and restarted it and redownloaded it and tried every command within vscode that has to do with extensions and nothing fixed it. This is a school laptop so I am not sure if the school has something to do with it but it wasn't blocked before and it is now. It says XHR failure any time I try to open one. Please help me I have already spent hours trying to fix this!

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @jtb3ats ,

Since we have not received the required information, we are closing the issue. Please feel free to reopen or create a new issue if the problem still persists.

Regards,
VS Marketplace Team
