### ISSUE TITLE
The editor could not be opened due to an unexpected error: XHR failed

### ISSUE THREAD

**Issue by Damir324** [microsoft/vsmarketplace#916]
Type: <b>Bug</b>

Any time I open an extension or get close to installing one this error message pops up and I need to have it fixed so that I can countinue to compleate projects.

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @Damir324 ,

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

-VS Marketplace Team

**Comment by Damir324** [comment]
Hello, I am not using a VPN or client server. This is my personal computer.
Also, the command Developer Open Logs Folder response is the images
attached.

**Comment by madhurivadaligithub** [comment]
Thank you for the details. We are investigating the issue and will get back to you with an update promptly.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Tracking here https://github.com/microsoft/vsmarketplace/issues/896
