### ISSUE TITLE
vue

### ISSUE THREAD

**Issue by MarinaM79** [microsoft/vsmarketplace#917]
Type: <b>Bug</b>

faire un rapport

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.26217
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @MarinaM79 ,

Thank you for reaching out to the VS Marketplace Team. Could you please provide more details about your concerns so we can investigate further.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Since we have not received the required information, we are closing the issue. Please feel free to reopen or create a new issue if the problem still persists.

Regards,
VS Marketplace Team
