### ISSUE TITLE
try downloading manually tell that

### ISSUE THREAD

**Issue by ankitha200253** [microsoft/vsmarketplace#918]
Type: <b>Bug</b>

☑ Error while installing 'Live Server' extension. Please check the log for more details.
Try Downloading Manually...

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @ankitha200253 

Thank you for reaching VS Marketplace Team, we are investigating the issue and will get back to you with an update promptly.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @ankitha200253 ,

We are unable to reproduce the issue. Could you please try again and let us know if it still occurs for you?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue 

Regards,
VS Marketplace Team
