### ISSUE TITLE
Your extension has suspicious content. Please fix your extension metadata, or contact support if you need assistance.

### ISSUE THREAD

**Issue by AquaAsh07** [microsoft/vsmarketplace#919]
why i am getting this problem when i am uploading my extension
![Code_POuloqKRVN](https://github.com/microsoft/vsmarketplace/assets/143998850/636eb77f-9527-4841-8d87-418a49b3a9b1)

**Comment by madhurivadaligithub** [comment]
Hi @AquaAsh07 


Thanks for reaching VS Marketplace Team, could you please contact [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) with publisher and extension details.


Regards,
VS Marketplace Team
