### ISSUE TITLE
do not match the last updated date

### ISSUE THREAD

**Issue by sadobass** [microsoft/vsmarketplace#920]
Type: <b>Bug</b>

It do not match the last updated date between Marketplace site and vscode extensions
my case in "Flutter Riverpod Snippets"
Marketplace site : Last updated 2023. 3. 7. 오후 3:05:18
vscode extensions : Last updated 2024-02-20, 16:44:40

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:34:48.028Z)
OS version: Darwin arm64 23.5.0
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @sadobass 

Thank you for reaching VS Marketplace Team, we are investigating the issue and will get back to you with an update promptly.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
We can see the same dates in both the VS Code editor and the Marketplace UI. Could you please double-check and provide a screenshot to help us investigate this date mismatch further.

**From VS Code editor**
<img width="878" alt="image" src="https://github.com/microsoft/vsmarketplace/assets/81361084/c5f5da5b-dc2a-4d10-9666-82298bbddfbc">

**From Marketplace**

<img width="316" alt="image" src="https://github.com/microsoft/vsmarketplace/assets/81361084/9216b22d-170f-4889-a4c7-00751026a9c3">

Regards,
VS Marketplace Team

**Comment by sadobass** [comment]
Hi~

Attach an images captured today.

**From VS Code editor**
![스크린샷 2024-07-01 오후 5 38 04](https://github.com/microsoft/vsmarketplace/assets/5369741/a835814b-7775-49bd-b593-9c251b576149)


**From Marketplace**
<img width="1154" alt="스크린샷 2024-07-01 오후 5 37 52" src="https://github.com/microsoft/vsmarketplace/assets/5369741/1893e2b6-8482-48fd-b074-5ec13cc54946">

**Comment by madhurivadaligithub** [comment]
@sadobass  Are you still facing the issue?

**Comment by sadobass** [comment]
It will still look different.
The issue seems to be a difference in the labelling words

- web 
Version : 1.2.2	
Released on : 7 July 2020, 11:31:16 PM	
Last updated : 3. 7. 2023, 3:05:18 PM

- vscode
Published : 2020-07-07, 23:31:16
Last released : 2023-03-07, 15:05:18
Last updated : 2024-02-20, 16:44:40

|web| == |vscode|
|---|--|---|
|Released on| == |Published|
|Last updated| == |Last released|
|??| == |Last updated|

**Comment by madhurivadaligithub** [comment]
Thanks for the details, this is by design.
