### ISSUE TITLE
Beautifulsoup4

### ISSUE THREAD

**Issue by TurtleGam3s** [microsoft/vsmarketplace#921]
Type: <b>Bug</b>

Everytime I try to calculate my grade using the cengage mindtap extension I get an email saying that beautifulsoup4 does not have the right version installed because the right version is "None". After I hit calculate I'll also get a "Failed to calculate grade" popup

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 6.5.0-1021-azure

**Comment by TurtleGam3s** [comment]
This is the exact error I get.
Run pip install selenium
Defaulting to user installation because normal site-packages is not writeable
Collecting selenium
  Downloading selenium-4.21.0-py3-none-any.whl (9.[5](https://github.com/cengage-csp-students-prod-1/9780357423844_minnick-web-design-9e-fbc5e9d0-ba6d-40d7-b9ae-ef3377434640/actions/runs/9442575059/job/26004946968#step:2:6) MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 32.4 MB/s eta 0:00:00
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Collecting certifi>=2021.10.8
  Downloading certifi-2024.[6](https://github.com/cengage-csp-students-prod-1/9780357423844_minnick-web-design-9e-fbc5e9d0-ba6d-40d7-b9ae-ef3377434640/actions/runs/9442575059/job/26004946968#step:2:7).2-py3-none-any.whl (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.4/164.4 KB 42.4 MB/s eta 0:00:00
Collecting typing_extensions>=4.9.0
  Downloading typing_extensions-4.12.2-py3-none-any.whl (3[7](https://github.com/cengage-csp-students-prod-1/9780357423844_minnick-web-design-9e-fbc5e9d0-ba6d-40d7-b9ae-ef3377434640/actions/runs/9442575059/job/26004946968#step:2:8) kB)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/lib/python3/dist-packages (from selenium) (1.26.5)
Collecting trio~=0.17
  Downloading trio-0.25.1-py3-none-any.whl (467 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 467.7/467.7 KB 47.6 MB/s eta 0:00:00
Collecting exceptiongroup
  Downloading exceptiongroup-1.2.1-py3-none-any.whl (16 kB)
Collecting sniffio>=1.3.0
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting outcome
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting attrs>=23.2.0
  Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.[8](https://github.com/cengage-csp-students-prod-1/9780357423844_minnick-web-design-9e-fbc5e9d0-ba6d-40d7-b9ae-ef3377434640/actions/runs/9442575059/job/26004946968#step:2:9)/60.8 KB 19.4 MB/s eta 0:00:00
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from trio~=0.17->selenium) (3.3)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting PySocks!=1.5.7,<2.0,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting h11<1,>=0.[9](https://github.com/cengage-csp-students-prod-1/9780357423844_minnick-web-design-9e-fbc5e9d0-ba6d-40d7-b9ae-ef3377434640/actions/runs/9442575059/job/26004946968#step:2:10).0
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 KB 27.4 MB/s eta 0:00:00
Installing collected packages: sortedcontainers, typing_extensions, sniffio, PySocks, h[11](https://github.com/cengage-csp-students-prod-1/9780357423844_minnick-web-design-9e-fbc5e9d0-ba6d-40d7-b9ae-ef3377434640/actions/runs/9442575059/job/26004946968#step:2:12), exceptiongroup, certifi, attrs, wsproto, outcome, trio, trio-websocket, selenium
Successfully installed PySocks-1.7.1 attrs-23.2.0 certifi-2024.6.2 exceptiongroup-1.2.1 h11-0.14.0 outcome-1.3.0.post0 selenium-4.21.0 sniffio-1.3.1 sortedcontainers-2.4.0 trio-0.25.1 trio-websocket-0.11.1 typing_extensions-4.[12](https://github.com/cengage-csp-students-prod-1/9780357423844_minnick-web-design-9e-fbc5e9d0-ba6d-40d7-b9ae-ef3377434640/actions/runs/9442575059/job/26004946968#step:2:13).2 wsproto-1.2.0
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement beatifulsoup4 (from versions: none)
ERROR: No matching distribution found for beatifulsoup4
Error: Process completed with exit code 1.

**Comment by TurtleGam3s** [comment]
I've deleted beautfulsoup4 then ran the pip install bs4 command to reacquire it as well as flat out leaving it out completely before trying to submit my assignment again.

**Comment by madhurivadaligithub** [comment]
Hi @TurtleGam3s ,

Thanks for reaching VS Marketplace Team. Sorry to hear you are experiencing connection issues. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues for quick action.

Thanks,
VS Marketplace Team
