### ISSUE TITLE
suggestion fro cpp is disbaled

### ISSUE THREAD

**Issue by abhijayrawat** [microsoft/vsmarketplace#923]
Type: <b>Bug</b>

i tried everything but its not working

VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @abhijayrawat ,

Thank you for contacting the VS Marketplace Team. Could you please share more details about the issue you are facing? This will help us investigate the issue and provide you with an update promptly. 

Regards,
VS Marketplace Team
