### ISSUE TITLE
Move publisher to another directory

### ISSUE THREAD

**Issue by DifficultNick** [microsoft/vsmarketplace#924]
Can't find option on "Manage Publishers & Extensions" page to move publisher to another directory.

Our organization has moved to another tenant. I've moved organization to another directory in dev.azure (on "Microsoft Entra" tab), but the publisher in Marketplace is still in the old one, so it seems i cant publish my extension because of this mix (`vsce` says that my account on new tenant has not enough permissions, though I'm an owner of organization there).

How can I move publisher?
On the "Manage Publishers & Extensions" page I can see both directories with my publisher in the old one.

Thank you

**Comment by madhurivadaligithub** [comment]
Hi @DifficultNick 

Thank you for contacting the VS Marketplace Support Team. We kindly request that you to remove the personal or sensitive data (id's) from the details provided. For this request assistance, please reach out to us via [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) 

Regards,
VS Marketplace Team
