### ISSUE TITLE
Error while fetching extensions.XHR failed

### ISSUE THREAD

**Issue by irrolliey** [microsoft/vsmarketplace#927]
Type: <b>Performance Issue</b>

{
    "extensions.autoUpdate": "onlyEnabledExtensions",
    "http.proxyStrictSSL": false,
    "http.proxy": "",
    "http.proxyAuthorization": null,
}-this is the settings.json for proxy
my proxy is set to override i have tried on, off and fall back and still doesn't work,
my proxy in my device settings is automatic, i dont use any antivirus software, and my firewall settings for vs code is not disabled

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @irrolliey ,

Thanks for reaching out. If you're using a VPN client or some local firewall, please adjusting the firewall settings to allow these requests. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team
