### ISSUE TITLE
Cisco Terminal executing under wrong directory

### ISSUE THREAD

**Issue by mitracy** [microsoft/vsmarketplace#931]
Type: <b>Bug</b>

I have no idea how we got into this state or what to do to fix it.  Request for help using teams and email have gone unanswered.
IDE seems a bit confused. I had a remote ADS workspace which I removed (and removed it from Remote explorer via removed recent list) I then created a new workspace on the same machine. Opened the folder, but when I try to build an image via cisco terminal, it comes back with not being able to find the previously deleted workspace. I tried deleting and re-adding, reloading IDE, but seems like some sort of file is corrupted. The workspace is accessible from the normal explorer mode (i.e. I can see the source). Only the persistent terminal is messed up.
Also, a persistent terminal job refuses to terminate. It is even still there after I remove and re-add the workspace.
Workspace on ADS machine: 
sjc-ads-4231:/nobackup/mitracy/admin.tech.CSCwk11399.polaris_dev/
Directory that cisco terminal is trying to use:
/nobackup/mitracy/zbf.l2.CSCwc28751.v1712_throttle'
Command we are trying to execute
cd vob/ios && /auto/binos-tools/bin/mcp_ios_precommit -- SCM_REFPOINT=`date +%H%M%S`  c8kv_universalk9-image
${workspaceFolder}

VS Code version: Code 1.90.1 (611f9bfce64f25108829dd295f54a6894e87339d, 2024-06-11T21:01:24.262Z)
OS version: Windows_NT x64 10.0.22631
Modes:
Remote OS version: Linux x64 4.18.0-513.9.1.el8_9.x86_64

**Comment by madhurivadaligithub** [comment]
Hi @mitracy 
Thanks for reaching VS Marketplace Team. Sorry to hear you are experiencing connection issues. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues for quick action.

Thanks,
VS Marketplace Team
