### ISSUE TITLE
Dark / Light Mode picture image

### ISSUE THREAD

**Issue by juliankasimir** [microsoft/vsmarketplace#933]
**Describe the bug**
We have a picture element in Github where we display the dark and light mode images.
However, this is not displayed correctly in the [store](https://marketplace.visualstudio.com/items?itemName=jolution.todo-nukem-snippet-vscode).

I mean that SVG wasn't allowed either, who i could handle it with the prefers-color-scheme.

The readme is an image from GitHub where there is dark/light mode, so I wouldn't like to commit to just one.

Code:

```
<p align="center">
    <picture>
        <source media="(prefers-color-scheme: dark)" srcset="./images/todonukem-dark.png">
        <source media="(prefers-color-scheme: light)" srcset="./images/todonukem-light.png">
        <img alt="Shows the banner of TODO NUKEM, with its logo" src="./images/todonukem-dark.png" width="700">
    </picture>
</p>
```

**To Reproduce**
1. Go to the Readme.md
2. Copy the code above
3. See it in the store
4. Click the tabs and came bock to start
5. See error

**Expected behavior**
SVG and Picture Image support.

**Screenshots**
![darklightmode](https://github.com/microsoft/vscode-discussions/assets/120172350/2195c3c9-fb37-42b8-a1fd-cbaca5ee3825)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version latest

**Additional context**
Original post: https://github.com/microsoft/vscode-discussions/discussions/1237
A related request: https://github.com/microsoft/vsmarketplace/issues/281

**Comment by madhurivadaligithub** [comment]
Hi @juliankasimir ,

Thanks for reaching VS Marketplace Team and sharing the details, we will investigate and update you with details.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Similar issue to track https://github.com/microsoft/vsmarketplace/issues/281
