### ISSUE TITLE
Extensions Issue

### ISSUE THREAD

**Issue by hassaanmshaikh** [microsoft/vsmarketplace#934]
Type: <b>Bug</b>

Greetings,

Getting "Error while fetching extensions. XHR failed."

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @hassaanmshaikh 

Thanks for reaching out. If you're using a VPN client or some local firewall, please adjusting the firewall settings to allow these requests. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team

**Comment by hassaanmshaikh** [comment]
Can you elaborate on the local firewall settings. My vpn is not connected, and in regards to the firewall, I have visual studio in my allowed apps list.

**Comment by hassaanmshaikh** [comment]
I had tried everything online regarding the firewall and could not solve this issue. Finally was able to solve it with these steps:

- CMD → echo %http_proxy%
                %http_proxy% (no proxy).
                http:// local:3000 (there is a proxy).
- Removed any Proxy Server under System Environment Variables → Issue Resolved.

**Comment by madhurivadaligithub** [comment]
Thanks for the confirmation and sharing the details.
