### ISSUE TITLE
Manim

### ISSUE THREAD

**Issue by DIS1881** [microsoft/vsmarketplace#935]
Type: <b>Feature Request</b>

**I've installed manim sideview** but now I can't run manim because it has a problem. It show me "**Manim SV -press to discard**" red color. **Help me please :(**

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @DIS1881 ,

Thanks for reaching VS Marketplace Support Team, could you please share more details like screenshot and repro steps to investigate better and it appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues for quick action.

Thanks,
VS Marketplace Team
