### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by Daveid-maker** [microsoft/vsmarketplace#936]
Type: <b>Feature Request</b>

I cannot install extensions. It's showing me XHR failed

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi  @Daveid-maker ,

Thanks for reaching out. If you're using a VPN client or some local firewall, please adjusting the firewall settings to allow these requests. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team
