### ISSUE TITLE
i cant download any extensions 

### ISSUE THREAD

**Issue by karthikreddydwarampudi** [microsoft/vsmarketplace#938]
Type: <b>Performance Issue</b>

my network is good but i can't able to install the extensions it show an error please fix it as soon as possiable

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @karthikreddydwarampudi ,

Thanks for reaching out to the VS Marketplace Team. Could you please share the error message, a screenshot, and the repro steps to help us investigate better.


Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @karthikreddydwarampudi ,

Since we have not received any response from you, we are closing the issue. If the issue still persists, please reopen or create a new request.

Regards,
VS Marketplace Team
