### ISSUE TITLE
We have uninstalled 'vivo-ai-code.vivo-ai-code-vscode' which was reported to be problematic

### ISSUE THREAD

**Issue by godkun** [microsoft/vsmarketplace#939]
<img width="519" alt="image" src="https://github.com/microsoft/vsmarketplace/assets/26134303/4c291a03-ad29-4165-a338-28ebaae7dde6">

Hello official team, this morning we suddenly found that the vscode vivo-ai-code plugin was officially removed from the shelves. This plugin is only for internal employees of vivo and does not have any external services. We are very confused. We have not received any warnings or notifications about the removal, telling us what changes we need to make. We need the support of the official team to tell us the reason for the removal. We will make changes to meet the requirements for restoration. Our ultimate goal is to restore the shelf

**Comment by madhurivadaligithub** [comment]
Hi @godkun ,

Thank you for contacting the Visual Studio Marketplace Team. Due to confirmed reports of suspicious activities, we have unlisted this extension from the VS Code Marketplace. While we understand that this is intended for internal use, we take security and trust seriously, and it can affect other customers too. 

Regards,
VS Marketplace Team

**Comment by godkun** [comment]
Hi @madhurivadaligithub 

Can you tell me what the confirmed suspicious activity report is?  We can make corrections to ensure that it does not affect other customers.

**Comment by godkun** [comment]
This is the result of using extensiontotal analysis. It looks like there is no dangerous vulnerability. 

https://app.extensiontotal.com/report/vivo-ai-code.vivo-ai-code-vscode

Can you tell me what the suspicious reporting activity you mentioned is? This is very important to me.

**Comment by madhurivadaligithub** [comment]
Could you please out to us through our VS Marketplace Support (VSMarketplace@microsoft.com) alias for further clarifications.

Regards,
VS Marketplace Team
