### ISSUE TITLE
laravel blade snippets not working 

### ISSUE THREAD

**Issue by KHUNKIMHONG** [microsoft/vsmarketplace#940]
Type: <b>Bug</b>

laravel blade snippets not working 

VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

**Comment by madhurivadaligithub** [comment]
Hi @KHUNKIMHONG ,

Thanks for reaching VS Marketplace Team. Sorry to hear you are experiencing connection issues. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues for quick action.

Thanks,
VS Marketplace Team

**Comment by KHUNKIMHONG** [comment]
Thank you for your response.
