### ISSUE TITLE
Can't review extension on marketplace - Bug report

### ISSUE THREAD

**Issue by KevBeltrao** [microsoft/vsmarketplace#944]
I released an [extension](https://marketplace.visualstudio.com/items?itemName=KevinBeltrao.kevbeltrao-ouch-my-eyes) yesterday, and today, I received a report that when someone tried to add a review to my extension, it failed, and now he can't access the extension page on the marketplace because it returns a 404.

I asked my wife to try to add a review, and she was able to reproduce the error (failed to submit a review and can't access the extension's page anymore). Sorry if here it's not the appropriate place to post it, but I couldn't find any other place to report this issue.

- VS Code Version: Irrelevant
- OS Version: Irrelevant
I consider them irrelevant because the error is on the web page, and it happened in different OSs (the first one on Windows and my wife on Mac)

Steps to Reproduce:

1. Go to https://marketplace.visualstudio.com/items?itemName=KevinBeltrao.kevbeltrao-ouch-my-eyes
2. Try to rate it
3. You should now receive a 404 if you try to access it again

**Comment by v-sulagnapal** [comment]
Hi @KevBeltrao, 
Thanks for reaching VS Marketplace Team and sharing the details, we will investigate and update you with details.
Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @KevBeltrao ,

Please provide the screenshot or the specific error message of the 404 error to facilitate a more detailed investigation.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @KevBeltrao ,

Since we have not received any response from you, we are closing the issue. If the issue still persists, please reopen or create a new request.

Regards,
VS Marketplace Team
