### ISSUE TITLE
error while fetching extensions. XHR failed

### ISSUE THREAD

**Issue by vaishnaviprahlad** [microsoft/vsmarketplace#945]
Type: <b>Bug</b>

Unable to install an extension. error while fetching extensions. XHR failed

VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.153.1-microsoft-standard-WSL2

**Comment by Neelima10735584** [comment]
Hi @vaishnaviprahlad,

Thanks for reaching out. If you're using a VPN client or some local firewall, please adjusting the firewall settings to allow these requests. If the error is still persisting, it will help us to investigate, if you can share the network log ( command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @vaishnaviprahlad,

Since we have not received any response from you, we are closing the issue. If the issue still persists, please reopen or create a new request.

Regards,
VS Marketplace Team
