### ISSUE TITLE
not able to use prettier even after enabling all the necessary settings

### ISSUE THREAD

**Issue by 510kirti** [microsoft/vsmarketplace#946]
Type: <b>Bug</b>

i have downloaded the prettier exension but still unable to format my document after ctrl + s even i have done all the necessary settings

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by Neelima10735584** [comment]
Hi,
This issue appears to be a support question specific to the extension which is best addressed by the extension owner. We recommend visiting the extension page on https://marketplace.visualstudio.com/ and posting a question there. Let us know if we can help you with anything else. 

Regards,
VS Marketplace Team
