### ISSUE TITLE
Unpublishing an extension not uninstalling or stop functioning installed extension

### ISSUE THREAD

**Issue by Susanta120** [microsoft/vsmarketplace#947]
Hi there,
How can I uninstall or stop functioning my extension if I unpublish it from VS Code marketplace? Assume my extension installed on 10 users system.

**Comment by Neelima10735584** [comment]
Hi Susanta, 

Thank you for contacting the VS Marketplace Support Team. We suggest adding the ask to VS Code 

[Deprecated extensions](https://github.com/microsoft/vscode-discussions/discussions/1)   

and we’ll be happy to take care of the change. There you can also recommend an alternative extension to download in lieu of this one.

Regards,
VS Marketplace Team
