### ISSUE TITLE
在过去 5 分钟内，JS/TS 语言服务崩溃了 5 次。

### ISSUE THREAD

**Issue by Tatiana0914** [microsoft/vsmarketplace#948]
Type: <b>Performance Issue</b>

在过去 5 分钟内，JS/TS 语言服务崩溃了 5 次。

VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:34:26.404Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by Neelima10735584** [comment]
Hi,
Thanks for reaching VS Marketplace Team and sharing the details, we will investigate and update you with details.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @Tatiana0914 ,

Please provide the screenshot or the specific error message of the error to facilitate a more detailed investigation.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Hi @Tatiana0914 ,

Since we have not received any response from you, we are closing the issue. If the issue still persists, please reopen or create a new request.

Regards,
VS Marketplace Team

**Comment by Tatiana0914** [comment]
> Hi @Tatiana0914 ,
> 
> Since we have not received any response from you, we are closing the issue. If the issue still persists, please reopen or create a new request.
> 
> Regards, VS Marketplace Team

![image](https://github.com/user-attachments/assets/08955174-e79a-4e28-acbf-e3889f08ee27)
