### ISSUE TITLE
Trending category is disappeared

### ISSUE THREAD

**Issue by a-pota** [microsoft/vsmarketplace#950]
**Describe the bug**
The trending category is disappeared from the Visual Studio page.

**To Reproduce**
1. Go to 'https://marketplace.visualstudio.com/vs'
2. The Trending category is not shown on the page

**Expected behavior**
The category is show on the Visual Studio page

**Comment by madhurivadaligithub** [comment]
Hi @a-pota ,

Thank you for contacting the VS Marketplace Team. We will review your request and provide you with an update.

Regards,
VS Marketplace Team

**Comment by seaniyer** [comment]
@a-pota 
Thanks for reaching out about Trending. After carefully evaluating maintenance and performance impact vs. the value to user community, we have discontinued it.

**Comment by a-pota** [comment]
Unfortunately, in this case, newly created extensions or those with few downloads have lost the chance to attract the community's attention, as only extensions with a large number of downloads and discussions are displayed in the categories

**Comment by seaniyer** [comment]
@a-pota Thanks for your input. One avenue still available is the Features list. If you have a new extension that you'd like to present for community's attention, you can propose it here https://github.com/microsoft/vscode/issues/141472
