### ISSUE TITLE
python

### ISSUE THREAD

**Issue by akshay7549** [microsoft/vsmarketplace#952]
Type: <b>Performance Issue</b>

python extension is installed in VS code.

VS Code version: Code 1.91.0 (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:52:22.949Z)
OS version: Windows_NT x64 6.2.9200
Modes:

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
