### ISSUE TITLE
ektensions error

### ISSUE THREAD

**Issue by angga283** [microsoft/vsmarketplace#953]
Type: <b>Bug</b>

saya tidak bisa menginstall apapun di extensions marketplace studio visual code saya untuk windows 7

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 6.1.7600
Modes:

**Comment by Neelima10735584** [comment]
Hi @angga283,
Thank you for contacting the VS Marketplace Team. To assist you effectively, could you kindly provide additional details about your concern? This will help us investigate thoroughly.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue 

Regards,
VS Marketplace Team
