### ISSUE TITLE
Rating in VS market Place broken 

### ISSUE THREAD

**Issue by ErikEJ** [microsoft/vsmarketplace#954]
https://marketplace.visualstudio.com/search?term=ef%20core%20power%20tools&target=VS&category=All%20categories&vsVersion=&sortBy=Rating

vs

https://marketplace.visualstudio.com/search?term=ef%20core%20power%20tools&target=VS&category=All%20categories&vsVersion=vs2022&sortBy=Rating

As you can see, the very highly rated EF Core Power Tools is not listed in the second targeted search.

Could it be due to amd46 AND arm64 support - I have no idea, but something is broken!

**Comment by madhurivadaligithub** [comment]
Hi @ErikEJ ,

Thank you for reaching out to the VS Marketplace Team and providing the details. We will review and get back to you with an update accordingly.

Regards,
VS Marketplace Team

**Comment by Neelima10735584** [comment]
Hi @ErikEJ,
We had an identical query that we are tracking here #547.

Regards,
VS Marketplace Team

**Comment by ErikEJ** [comment]
@Neelima10735584 It is NOT identical, this concerns the search results, not the front page. Currently both front page and search results are broken, sadly. I really wish you could just fix these issues, it discourages my enthusiasm for creating great extensions if this is how badly promoted they are here...

**Comment by ErikEJ** [comment]
@madhurivadaligithub @Neelima10735584 @joelverhagen 

Even this search fails to list EF Core Power Tools:

https://marketplace.visualstudio.com/search?term=erikej&target=VS&category=All%20categories&cost=free&vsVersion=vs2022&sortBy=Relevance

Where this one does list it:

https://marketplace.visualstudio.com/search?term=erikej&target=VS&category=All%20categories&cost=free&vsVersion=&sortBy=Relevance

Looks like it is excluded from VS 2022 category for whatever reason - 😢

**Comment by ErikEJ** [comment]
@madskristensen FYI

**Comment by madskristensen** [comment]
@seaniyer @tinaschrepfer

**Comment by seaniyer** [comment]
@ErikEJ 
There is a bug in VS Marketplace web site which I believe is preventing the VS 2022 filter to not show if the min version is not 17.0.  I understand it is possible to work around by setting the min version to 17.0 if at all that is an option in this case.  May be not, but JFYI

```
    <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[17.5,18.0)">
      <ProductArchitecture>amd64</ProductArchitecture>
    </InstallationTarget>
```
    
cc: @sbanni

**Comment by ErikEJ** [comment]
@seaniyer Thanks for the update, that is an "interesting" bug. I will re-publish with a 17.0 target, and live with the hopefully small support burden until you fix this bug - hopefully not years from now! Now, if only you could also fix #547 😉 (reported 1.5 years ago)

**Comment by ErikEJ** [comment]
@madhurivadaligithub Is the bug fix already out??

**Comment by ErikEJ** [comment]
@madhurivadaligithub So I can bump up to 17.5 again and search will work as expected?

**Comment by madhurivadaligithub** [comment]
Thanks for updating the version, could you please let us know, after version update, are you still facing the issues?

**Comment by ErikEJ** [comment]
@madhurivadaligithub Not sure what you mean? Do you suggest I can try to bump to 17.5 again?

**Comment by madhurivadaligithub** [comment]
@ErikEJ  We would like to check if the workaround shared by Sean is helping you?

**Comment by ErikEJ** [comment]
Yes, the workaround works, as you can see on the site. But it does not seem like a proper fix  as my extension really does not work in 17.4 or older.
