### ISSUE TITLE
cannot download extensions even after reinstalling the vs code.It is showing error 

### ISSUE THREAD

**Issue by yugal19** [microsoft/vsmarketplace#956]
Type: <b>Feature Request</b>

Not able to download extensions on the vs code even after reinstalling it many times 

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Thank you for reaching VS Marketplace Support Team. Are you still facing the issue, If yes, are you using any VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team
