### ISSUE TITLE
está dando erro XHR Failed

### ISSUE THREAD

**Issue by adriolivdev** [microsoft/vsmarketplace#957]
Type: <b>Bug</b>

não está carregando extensões

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @adriolivdev ,

Thanks for reaching VS Marketplace Team. Are you still experiencing the issue?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists please feel free to reopen or create a new issue.

**Comment by adriolivdev** [comment]
ok dont problem
