### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by Devakumar2004** [microsoft/vsmarketplace#958]
Type: <b>Bug</b>

when i write anything on search bar its showing "error while fetching extensions. XHR failed". Hope you please solve my problem

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by elkhalifte** [comment]
this is not a VS Code issue, its an issue on their server for now https://marketplace.visualstudio.com/
they're working fixing it!

**Comment by Neelima10735584** [comment]
Hi @Devakumar2004 

Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).

Regards,
VS Marketplace Team

**Comment by Devakumar2004** [comment]
Thanks a lot my issue is resovled. Now im able to do coding. Once again thanks you   Sent from Mail for Windows From: NeelimaSent: 19 July 2024 11:26To: microsoft/vsmarketplaceCc: Devakumar2004; MentionSubject: Re: [microsoft/vsmarketplace] Unable to install extension (Issue #958) Hi @Devakumar2004Thanks for reaching out. If you're using a VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).Regards,VS Marketplace Team—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by madhurivadaligithub** [comment]
Thanks for the confirmation.
