### ISSUE TITLE
Say what caused verification to break or never end

### ISSUE THREAD

**Issue by sketchbuch** [microsoft/vsmarketplace#96]
A few times when uploading a new version of an extension the verification never ends. I tried to find the cause and contacted MS. Eventually someone looked at it and told me the build was broken but couldn't tell me any more. After a lot of trial and error and uploading dummy extensions I found it was due to not excluding enough files... the extension was massive (like 12OMB).

It would be great if verification breaks that you get told what happened or give us read access to the build history so we can look through the logs.

I now use .vscodeignore files so hopefully this will not happen again to me.

**Comment by isidorn** [comment]
Yeah `.vscodeignore` is the way to go. There are no plans for the marketplace to tackle this.
Maybe file a feature request against https://github.com/microsoft/vscode-vsce
