### ISSUE TITLE
XHR Failed

### ISSUE THREAD

**Issue by TheophileIssa** [microsoft/vsmarketplace#960]
Type: <b>Bug</b>

I can't access the extension market place 

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by elkhalifte** [comment]
this is not a VS Code issue, its an issue on their server for now https://marketplace.visualstudio.com/
they're working fixing it!

**Comment by Neelima10735584** [comment]
Hi @TheophileIssa,

Thank you for reaching VS Marketplace Support Team. Are you still facing the issue, If yes, are you using any VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).
 
Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
