### ISSUE TITLE
XHR failed when fetching extensions.

### ISSUE THREAD

**Issue by josephplpriest** [microsoft/vsmarketplace#963]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
1.91.1
f1e16e1e6214d7c44d078b1f0607b2388f29d729
x64

- OS Version: 
Description:	Ubuntu 24.04 LTS
Release:	24.04
Codename:	noble

Steps to Reproduce:
1. Open VS Code
2. Select extensions
3. When fetching popular extensions, get "Error while fetching extensions. XHR failed"

Netlog output:

[netlog.json](https://github.com/user-attachments/files/16290157/netlog.json)

**Comment by andylikescodes** [comment]
emmm... it is now working now again.

**Comment by loonglim** [comment]
Yeah, I already have same issue.
![Screenshot](https://github.com/user-attachments/assets/170498f1-303e-4c08-afb3-ba936bdbd5ac)

**Comment by tinudrc** [comment]
Is it resolved? I'm experiencing the same issue while installing Python

![image](https://github.com/user-attachments/assets/effa9b3a-176b-40e7-923d-32b5122289f5)

**Comment by madhurivadaligithub** [comment]
Closing the issue since the issue was resolved. If the issue still persists, please feel free to reopen or create a new issue.
