### ISSUE TITLE
Error while fetching extensions. XHR failed

### ISSUE THREAD

**Issue by sajeeldev** [microsoft/vsmarketplace#964]
Type: <b>Bug</b>

Whenever i try to install an extension. It gives me an error. I tried many possible ways to resolve this issue but it's still an issue and i request you to help me out to resolve this issue as quick as possible.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by Neelima10735584** [comment]
Hi @sajeeldev,

Thank you for reaching VS Marketplace Support Team. Are you still facing the issue, If yes, are you using any VPN client or some local firewall, please turn these off and retry. If the error is still persisting, it will help us to investigate, if you can share the network log (command: Developer: Open Logs Folder).
  
Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists please feel free to reopen or create a new issue.

Thanks,
VS Marketplace Team
