### ISSUE TITLE
Somebody else is on my

### ISSUE THREAD

**Issue by kevindelgado2467** [microsoft/vsmarketplace#966]
Type: <b>Feature Request</b>

Somebody else is on my account using my stuff

VS Code version: Code - Insiders 1.92.0-insider (89690b9d76a88fab676d26651134a1ffa4562732, 2024-07-19T05:03:57.939Z)
OS version:   
Modes:

**Comment by Neelima10735584** [comment]
Hi @kevindelgado2467,

Thank you for contacting the VS Marketplace Team. To assist you effectively, could you kindly provide additional details about your concern? This will help us investigate thoroughly.

Regards,
VS Marketplace Team

**Comment by kevindelgado2467** [comment]
Yes, somebody that wasn’t me went in and reported my code spaces. They went
in and changed everything. Somebody basically hacking into my account and
reported all the spaces and text messages. Then there were somehow able to
sync on my settings and change all of my hard drives and they somehow
logged into my iCloud from there. It was a completely different device. I
never turned on sync settings.

**Comment by Neelima10735584** [comment]
Hi @kevindelgado2467,

Thanks for sharing the details, could you please reach out to us through our support alias VSMarketplace@microsoft.com to address this issue promptly.
 
Regards
VS Marketplace Team
