### ISSUE TITLE
extension problem

### ISSUE THREAD

**Issue by Priyankagupta355** [microsoft/vsmarketplace#967]
Type: <b>Bug</b>

do not install extensions in vs code problem in this case some error are found this error is Scanning: Unexpected token '#', "#include<s"... is not valid JSON

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by Neelima10735584** [comment]
Hi @Priyankagupta355,

Thank you for contacting the VS Marketplace Team. To assist you effectively, could you kindly provide additional details about your concern? This will help us investigate thoroughly.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
