### ISSUE TITLE
github copilot sign in issue

### ISSUE THREAD

**Issue by HartmutChang** [microsoft/vsmarketplace#968]
Type: <b>Bug</b>

I CAN NOT sign is github on my mac. It will link me to github's web do not thing and than link me back, error shows auth bad credentials, but my internet are very stable and fast. wish github can fix this issue.

VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

**Comment by Neelima10735584** [comment]
Hi @HartmutChang,

Thank you for contacting the VS Marketplace Team. To assist you effectively, could you kindly provide additional details about your concern? This will help us investigate thoroughly.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue
