### ISSUE TITLE
Wallpaper

### ISSUE THREAD

**Issue by Lrvnjn** [microsoft/vsmarketplace#969]
Type: <b>Bug</b>

Cannot delete background or wallpaper

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes: Unsupported

**Comment by doctor4rat** [comment]
ok get over it
