### ISSUE TITLE
compiler does not work

### ISSUE THREAD

**Issue by winnt3r2** [microsoft/vsmarketplace#970]
Type: <b>Bug</b>

after writing the code the code is not working or compiling or giving the error every time i try to run code in terminal

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @winnt3r2 ,

Thank you for contacting the VS Marketplace Team. To assist you effectively, could you kindly provide additional details about your concern with error message/ screenshot, this will help us investigate thoroughly.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
