### ISSUE TITLE
Extension cannot open Excel file

### ISSUE THREAD

**Issue by BanLi-cat** [microsoft/vsmarketplace#971]
Type: <b>Bug</b>

When using VSCode to open Excel, the file is not displayed and is spinning around

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 6.1.7601
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @BanLi-cat 

Thank you for opening the issue. Sorry to hear you are experiencing an issue. It appears to be specific to VS Code editor and tools if we are understanding correctly. It is best to reach out VS Code team at  https://github.com/microsoft/vscode/issues

Regars,
VS Marketplace Team
