### ISSUE TITLE
Not able to download  as well as install  any extention in vs code like python and sqlite

### ISSUE THREAD

**Issue by PranaliDahake** [microsoft/vsmarketplace#972]
Type: <b>Bug</b>

Extention Python --> Click on Install

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:06:49.809Z)
OS version: Windows_NT x64 10.0.22631
Modes:

```[tasklist]
### Tasks
```

**Comment by madhurivadaligithub** [comment]
Thanks @PranaliDahake for reaching out to the VS Marketplace Team. Could you please elaborate on your issues so we can investigate further?

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
