### ISSUE TITLE
Cannot get extensions to load.

### ISSUE THREAD

**Issue by snowieoxs** [microsoft/vsmarketplace#975]
Type: <b>Bug</b>

```
Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
```

When I open vscode, rather than seeing externsions, I see "Drag a view here to display" I have been looking at possible solutions. and messing around with it for like a week and cant figure it out, my extensions do load in vscode indsiders, but that program is giving me other issues, so idk, this is the error 

log from developer tools:

```
log.ts:419  INFO Started local extension host with pid 5180.
log.ts:419  INFO [perf] Render performance baseline is 67ms
notificationsAlerts.ts:40 TypeError: Be.show is not a function
    at extensionsViewlet.ts:741:31
    at Array.map (<anonymous>)
    at we.ic (extensionsViewlet.ts:740:47)
    at we.refresh (extensionsViewlet.ts:681:8)
    at async Object.run (extensions.contribution.ts:1186:6)
    at async L.u (actions.ts:194:3)
    at async L.run (actions.ts:185:4)
    at async k.onClick (menuEntryActionViewItem.ts:207:4)
c @ notificationsAlerts.ts:40
```

I'm not really sure what to put for reproduce, because it heppens when i open the program, and haven't really used it because the extensions are not laoding, i have tried reinstalling the program, as well as deleteing folders and reinstalling, messing around with different suggestions i have found online.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @snowieoxs ,

Thank you for opening the issue. Sorry to hear you are experiencing the issues. It appears to be specific to VS Code editor and tools. It is best to reach out VS Code team at https://github.com/microsoft/vscode/issues.

Please reach out to us for any other queries.

Regards,
VS Marketplace Team
