### ISSUE TITLE
not showin extensions to download

### ISSUE THREAD

**Issue by inquisitive-anmol** [microsoft/vsmarketplace#976]
Type: <b>Performance Issue</b>

its not showing and searching any extension to download. Giving error that error in fetching extensions.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @inquisitive-anmol 

Thanks for reaching VS Marketplace Tea, could you please share repro steps and error screenshots to investigate further.

Regards,
VS Marketplace Team

**Comment by inquisitive-anmol** [comment]
I have fixed the issue.
