### ISSUE TITLE
Github Copilot chat is not working

### ISSUE THREAD

**Issue by Fariza21** [microsoft/vsmarketplace#977]
Type: <b>Bug</b>

When I'm typing my question to the github copilot chat, I'm not able to send it when I click the send button.

VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.18.0-513.24.1.el8_9.x86_64

**Comment by Neelima10735584** [comment]
Hi @Fariza21,

Thank you for reaching out to the VS Marketplace Team. Could you please share repro steps and error screenshots to investigate further so that we can take a look quickly.

Regards,
VS Marketplace Support Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
