### ISSUE TITLE
cannot search extension

### ISSUE THREAD

**Issue by skygajendra** [microsoft/vsmarketplace#978]
Type: <b>Bug</b>

when searching the extension i am getting failed to fetch extension

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by cast3** [comment]
Hi @Neelima10735584 
Same here.

Issue:

![imagen](https://github.com/user-attachments/assets/71262f1b-d9dc-46f5-a3ef-9d88ae437738)

**Comment by cast3** [comment]
> Hi @Neelima10735584 Same here.
> 
> Issue:
> 
> ![imagen](https://private-user-images.githubusercontent.com/62570607/357492193-71262f1b-d9dc-46f5-a3ef-9d88ae437738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NjMyMzQsIm5iZiI6MTcyMzY2MjkzNCwicGF0aCI6Ii82MjU3MDYwNy8zNTc0OTIxOTMtNzEyNjJmMWItZDlkYy00NmY1LWEzZWYtOWQ4OGFlNDM3NzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDE5MTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ODY1YjRjYmY0ZjBkZTg2MGNjNTIzYjU0YWMyNjEyZTA0ODcxMjJkZmI5Nzg0NzRjMjJmM2NmOWFkNTFmM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tr2RTGSxD3AtE4N8QYoH6CBcU6vRThYmt-UNqRAe34M)

Find out the cause but can't find how to solve it, should i just reinstall?

![imagen](https://github.com/user-attachments/assets/835e6d69-b6bb-45c8-818b-de7c43f31e26)

**Comment by Neelima10735584** [comment]
Hi @cast3,

Thanks for reaching out to the VS Marketplace Team. Sorry to hear you are experiencing the installation issue. We kindly suggest that you reinstall the application and attempt to search for the extension again. If the issue still persists, please reach out VS Code team at https://github.com/microsoft/vscode/issues.

Regards,
VS Marketplace Team
