### ISSUE TITLE
i am unable to download any extensions

### ISSUE THREAD

**Issue by aniketyadav04** [microsoft/vsmarketplace#982]
Type: <b>Bug</b>

i dont know what is the cause but i can't download any extensions

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by Neelima10735584** [comment]
Hi @aniketyadav04,

Thanks for reaching out to the VS Marketplace Team. Could you please share the error message, a screenshot, and the repro steps to help us investigate better.

Regards,
VS Marketplace Team

**Comment by aniketyadav04** [comment]
Yeah sure see this picture and also I am not able to download extensions
manually
Plz help me

**Comment by Neelima10735584** [comment]
Hi @aniketyadav04,

We are unable to find the picture, could you please reshare the error screenshot to help us investigate better.

Thanks
VS Marketplace Team

**Comment by aniketyadav04** [comment]
Sure see the screenshot below

**Comment by aniketyadav04** [comment]
Hii please help me about it I am in hurry

**Comment by aniketyadav04** [comment]
i am getting an error while installing any extensions or while opening the
settings plz tell me how can i fix that

**Comment by Neelima10735584** [comment]
Hi @aniketyadav04,

Thanks for sharing the details, still we are unable to view the shared details, could you please reach out to us through our support alias [VSMarketplace@microsoft.com](mailto:VSMarketplace@microsoft.com) to address this issue promptly.

Regards
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
