### ISSUE TITLE
Kaspersky Blocking Vscode Extensions Marketplace

### ISSUE THREAD

**Issue by MohamadHaydarMeg** [microsoft/vsmarketplace#985]
Type: <b>Bug</b>

Have kaspersky on your local machine.
Try to search for any new extension.

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by madhurivadaligithub** [comment]
Hi @MohamadHaydarMeg ,

Thanks for reaching out to the VS Marketplace Team. Could you please share the error message, a screenshot, and the repro steps to help us investigate better.

Regards,
VS Marketplace Team

**Comment by MohamadHaydarMeg** [comment]
Hello @madhurivadaligithub 
Thank you for responding.
It was an internal issue.

Sorry.
