### ISSUE TITLE
Error while fetching extensions. Failed to fetch

### ISSUE THREAD

**Issue by ShioriiCodes** [microsoft/vsmarketplace#987]
Type: <b>Bug</b>

Error while fetching extensions. Failed to fetch

VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching out to the VS Marketplace Team. Could you please share the error message, a screenshot, and the repro steps to help us investigate better.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists please feel free to reopen or create a new issue
