### ISSUE TITLE
vscode cannot see tailwind classes

### ISSUE THREAD

**Issue by ErgashevMaruf** [microsoft/vsmarketplace#992]
Type: <b>Bug</b>

vscode cannot see tailwind classes i installed Tailwind CSS IntelliSense

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by Neelima10735584** [comment]
Hi @ErgashevMaruf,

Thanks for reaching out to the VS Marketplace Team. Could you please share the error message, a screenshot, and the repro steps to help us investigate better.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
