### ISSUE TITLE
can't change live preview host id

### ISSUE THREAD

**Issue by unknown6464** [microsoft/vsmarketplace#993]
Type: <b>Bug</b>

when i open my website in browser it shows "not secure" 
and they also show me a warning while i want to open my website through live preview so where is the actual issue .. please help 

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching out to the VS Marketplace Team. Could you please share the error message, a screenshot, and the repro steps to help us investigate better.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.

Regards,
VS Marketplace Team
