### ISSUE TITLE
Cannot display sidebar for code hint completion class extension

### ISSUE THREAD

**Issue by 0zjn0123** [microsoft/vsmarketplace#994]
Type: <b>Bug</b>

To install the extension for the code completion class, open the sidebar for the extension

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Linux arm64 5.10.43
Modes:

**Comment by madhurivadaligithub** [comment]
Thanks for reaching out to the VS Marketplace Team. Could you please share the error message, a screenshot, and the repro steps to help us investigate better.

Regards,
VS Marketplace Team

**Comment by 0zjn0123** [comment]
> Thanks for reaching out to the VS Marketplace Team. Could you please share the error message, a screenshot, and the repro steps to help us investigate better.感谢您联系 VS Marketplace 团队。您能否分享错误消息、屏幕截图和重现步骤，以帮助我们更好地进行调查。
> 
> Regards, 问候 VS Marketplace Team VS Marketplace 团队

It seems that the webview in the sidebar cannot be used
