### ISSUE TITLE
Can't publish extension: Extension validation error

### ISSUE THREAD

**Issue by js8544** [microsoft/vsmarketplace#997]
Does this issue occur when all extensions are disabled?: Yes/No

When I publish a new version of my extension, vsce says publish successfully, but the management portal says: 
```
Extension validation error

Something went wrong, please retry after sometime.
```
![image](https://github.com/user-attachments/assets/e13b972e-f2a4-41e4-97b5-b701c53b95ed)

**Comment by madhurivadaligithub** [comment]
Thank you for contacting the VS Marketplace Support Team and informing us about the issue. We believe the underlying cause has now been resolved. Please give it a try again.

Regards, 
VS Marketplace Team.

**Comment by Banner-Keith** [comment]
> Thank you for contacting the VS Marketplace Support Team and informing us about the issue. We believe the underlying cause has now been resolved. Please give it a try again.
> 
> Regards, VS Marketplace Team.

Do you know if whatever your team did to resolve this would have fixed it for Azure DevOps Server as well? We are getting the same error there. We are one update behind so maybe your fix is in there, but there's nothing in the release notes for that.

**Comment by robertpiosik** [comment]
I'm facing this issue again on and off. Logs should be more detailed.
