### ISSUE TITLE
giving error while fetching extensions. failed to fetch

### ISSUE THREAD

**Issue by ayush-gupta456** [microsoft/vsmarketplace#998]
Type: <b>Bug</b>

giving error while fetching extensions. failed to fetch

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by ayush-gupta456** [comment]
rsolve this issue quickly

**Comment by madhurivadaligithub** [comment]
Thanks for reaching out to the VS Marketplace Team. Could you please share the error message, a screenshot, and the repro steps to help us investigate better.

Regards,
VS Marketplace Team

**Comment by madhurivadaligithub** [comment]
Closing the issue since there has been no updates on the information requested. If the issue still persists, please feel free to reopen or create a new issue.
